import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { getCart } from "@/src/modules/cart/server/repository";
export const dynamic = "force-dynamic";
const money = (value: number, currency: string) => new Intl.NumberFormat("en-NG", { style: "currency", currency }).format(value / 100);

export default async function CartPage({ searchParams }: { searchParams: Promise<{ added?: string; negotiated?: string; checkoutError?: string }> }) {
  const [user, query] = await Promise.all([getCurrentAppwriteUser(), searchParams]); if (!user) redirect("/login?returnTo=/cart");
  const { items } = await getCart(user.$id), groups = new Map<string, typeof items>();
  for (const item of items) groups.set(String(item.vendorId), [...(groups.get(String(item.vendorId)) ?? []), item]);
  const currencies = new Set(items.map(item => String(item.currency))), total = items.reduce((sum, item) => sum + Number(item.unitPriceMinor) * Number(item.quantity), 0), ready = items.length > 0 && currencies.size === 1;
  return <main className="marketplace-shell"><nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><Link href="/products">Continue shopping</Link></nav><header><p className="kicker">MULTI-VENDOR CART</p><h1>Your marketplace cart.</h1>{query.added && <p className="success-note">Item added.</p>}{query.negotiated && <p className="success-note">Accepted wholesale price added. The exact terms will be verified at checkout.</p>}{query.checkoutError && <p className="form-error">Checkout failed safely; your cart remains unchanged.</p>}</header><section className="cart-layout"><div>{items.length ? Array.from(groups).map(([vendorId, list]) => <section className="cart-vendor" key={vendorId}><h2>Seller {vendorId}</h2>{list.map(item => <article key={item.$id}><div><strong>{String(item.productName)}</strong><span>SKU {String(item.sellerSku)} · Qty {String(item.quantity)}{item.negotiationId ? " · Negotiated wholesale price" : ""}{item.purchaseType && item.purchaseType !== "standard" ? ` · ${String(item.purchaseType).replaceAll("_", " ")}` : ""}</span>{item.promisedDispatchAt && <small>Expected dispatch: {new Date(String(item.promisedDispatchAt)).toLocaleDateString("en-GB")}</small>}{item.brandingName && <small>Brand: {String(item.brandingName)} · Brief saved for manufacturer</small>}</div><strong>{money(Number(item.unitPriceMinor) * Number(item.quantity), String(item.currency))}</strong><form method="post" action={`/api/cart/items/${item.$id}/remove`}><button>Remove</button></form></article>)}</section>) : <p className="empty-market">Your cart is empty.</p>}</div><aside><span>ORDER SUMMARY</span><strong>{currencies.size === 1 ? money(total, [...currencies][0] ?? "NGN") : "Multiple currencies"}</strong><p>Prices, programme terms and capacity are revalidated atomically.</p>{ready ? <Link href="/checkout">Proceed to checkout</Link> : <button disabled>Proceed to checkout</button>}</aside></section></main>;
}
