import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { findVendorByOwner, getVendorBundle } from "@/src/modules/vendors/server/repository";
import { listVendorProgramOffers } from "@/src/modules/catalogue/server/product-programs";

export const dynamic = "force-dynamic";
const localDate = (value: unknown) => value ? new Date(String(value)).toISOString().slice(0, 16) : "";

export default async function SellerPrograms({ searchParams }: { searchParams: Promise<{ updated?: string; error?: string }> }) {
  const user = await getCurrentAppwriteUser(); if (!user) redirect("/login?returnTo=/seller/programs");
  const vendor = await findVendorByOwner(user.$id); if (!vendor || !["approved", "active"].includes(String(vendor.status))) redirect("/seller");
  const [{ compliance }, rows, query] = await Promise.all([getVendorBundle(vendor.$id), listVendorProgramOffers(vendor.$id), searchParams]);
  if (String(compliance?.vendorType) !== "manufacturer") redirect("/seller");
  return <main className="seller-shell program-shell"><nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><Link href="/seller">Seller Centre</Link></nav><header><div><p className="kicker">MANUFACTURER SALES PROGRAMMES</p><h1>Pre-order & white label</h1><p>Turn approved offers into scheduled pre-orders, branded production runs, or both. Buyers receive the terms before checkout.</p></div></header>
    {query.updated && <p className="success-note">Programme settings saved and published.</p>}{query.error && <p className="form-error">The settings were not saved. Check dates, capacity, minimum quantity and production terms.</p>}
    <section className="program-guidance"><article><span>01</span><h2>Pre-order</h2><p>Set an order window, total capacity and a realistic dispatch commitment. Payment follows the normal protected checkout.</p></article><article><span>02</span><h2>White label</h2><p>State the minimum run, production lead time and available branding or packaging options. The buyer supplies a written brief.</p></article></section>
    <section className="program-list">{rows.length ? rows.map(({ offer, product, program }) => <form action="/api/seller/programs" method="post" key={offer.$id}><input type="hidden" name="offerId" value={offer.$id}/><div className="program-product"><span>{String(offer.sellerSku)}</span><h2>{String(product?.name)}</h2><p>{String(offer.currency)} {(Number(offer.retailPriceMinor) / 100).toFixed(2)} · Standard MOQ {String(offer.minimumOrderQuantity)}</p></div><fieldset><legend>Pre-order settings</legend><label className="check"><input type="checkbox" name="preorderEnabled" defaultChecked={Boolean(program?.preorderEnabled)}/> Enable pre-order</label><label>Opens<input type="datetime-local" name="preorderOpensAt" defaultValue={localDate(program?.preorderOpensAt)}/></label><label>Closes<input type="datetime-local" name="preorderClosesAt" defaultValue={localDate(program?.preorderClosesAt)}/></label><label>Estimated dispatch<input type="datetime-local" name="estimatedDispatchAt" defaultValue={localDate(program?.estimatedDispatchAt)}/></label><label>Total capacity<input type="number" min="1" name="preorderCapacity" defaultValue={program?.preorderCapacity ? Number(program.preorderCapacity) : undefined}/></label><small>{Number(program?.preorderReserved ?? 0)} units already reserved; capacity cannot be bypassed at checkout.</small></fieldset><fieldset><legend>White-label settings</legend><label className="check"><input type="checkbox" name="whiteLabelEnabled" defaultChecked={Boolean(program?.whiteLabelEnabled)}/> Enable white label</label><label>Minimum branded quantity<input type="number" min="1" name="whiteLabelMinimumQuantity" defaultValue={program?.whiteLabelMinimumQuantity ? Number(program.whiteLabelMinimumQuantity) : undefined}/></label><label>Production lead time (days)<input type="number" min="1" max="365" name="whiteLabelLeadDays" defaultValue={program?.whiteLabelLeadDays ? Number(program.whiteLabelLeadDays) : undefined}/></label><label className="wide">Branding and packaging options<textarea name="whiteLabelOptions" maxLength={3000} defaultValue={String(program?.whiteLabelOptions ?? "")} placeholder="Logo printing, private carton, label languages, colour options…"/></label></fieldset><button>Save programme settings</button></form>) : <p className="empty-market">Publish an approved product offer before configuring a programme.</p>}</section>
  </main>;
}
