import "server-only";
import { ID, Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { publishAdminNotificationSafely } from "@/src/modules/admin-notifications/server/publisher";
const databaseId = () => env().APPWRITE_DATABASE_ID;
const db = () => createAppwriteDatabaseClient().databases;
export const listCustomerDisputes = (userId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "disputes", queries: [Query.equal("customerUserId", userId), Query.orderDesc("createdAt"), Query.limit(100)] });
export const listAdminDisputes = () => db().listDocuments({ databaseId: databaseId(), collectionId: "disputes", queries: [Query.orderDesc("updatedAt"), Query.limit(100)] });
export const listVendorDisputes = (vendorId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "disputes", queries: [Query.equal("vendorId", vendorId), Query.orderDesc("updatedAt"), Query.limit(100)] });
export async function createDispute(input: { userId: string; orderId: string; vendorOrderId: string; category: string; description: string }) { if (input.description.trim().length < 20) throw new Error("Description is too short"); const [order, vendorOrder] = await Promise.all([db().getDocument({ databaseId: databaseId(), collectionId: "orders", documentId: input.orderId }), db().getDocument({ databaseId: databaseId(), collectionId: "vendor_orders", documentId: input.vendorOrderId })]); if (String(order.customerUserId) !== input.userId || String(vendorOrder.orderId) !== input.orderId || String(order.status) === "pending_payment") throw new Error("Order not eligible"); const disputeId = ID.unique(), now = new Date().toISOString(); await db().createDocument({ databaseId: databaseId(), collectionId: "disputes", documentId: disputeId, permissions: [], data: { disputeNumber: `PAC-DSP-${new Date().getUTCFullYear()}-${disputeId.slice(-10).toUpperCase()}`, orderId: input.orderId, vendorOrderId: input.vendorOrderId, customerUserId: input.userId, vendorId: vendorOrder.vendorId, category: input.category, description: input.description.trim(), status: "open", createdAt: now, updatedAt: now } }); await db().createDocument({ databaseId: databaseId(), collectionId: "dispute_events", documentId: ID.unique(), permissions: [], data: { disputeId, actorUserId: input.userId, eventType: "opened", message: input.description.trim(), occurredAt: now } }); await publishAdminNotificationSafely({eventType:"dispute_opened",priority:"critical",title:"New customer complaint",body:`A ${input.category} dispute was opened for order ${input.orderId}.`,entityType:"dispute",entityId:disputeId,href:"/admin/disputes",roles:["support_officer"]}); }
export async function resolveDispute(input: { disputeId: string; actorUserId: string; status: "investigating" | "resolved" | "rejected"; resolution: string }) { const dispute = await db().getDocument({ databaseId: databaseId(), collectionId: "disputes", documentId: input.disputeId }); const now = new Date().toISOString(); await db().updateDocument({ databaseId: databaseId(), collectionId: "disputes", documentId: input.disputeId, data: { status: input.status, updatedAt: now, ...(input.resolution ? { resolution: input.resolution } : {}) } }); await db().createDocument({ databaseId: databaseId(), collectionId: "dispute_events", documentId: ID.unique(), permissions: [], data: { disputeId: input.disputeId, actorUserId: input.actorUserId, eventType: input.status, ...(input.resolution ? { message: input.resolution } : {}), occurredAt: now } }); await db().createDocument({ databaseId: databaseId(), collectionId: "audit_logs", documentId: ID.unique(), permissions: [], data: { actorUserId: input.actorUserId, action: `dispute.${input.status}`, entityType: "dispute", entityId: dispute.$id, metadata: JSON.stringify({ resolution: input.resolution }), occurredAt: now } }); }
