import "server-only";
import { ID, Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { decryptSupplierCredential, encryptSupplierCredential, maskSupplierCredential } from "../domain/credential-crypto";
import type { SupplierCredentials } from "../domain/connector";
import { safeSupplierSlug } from "../domain/supplier";
import { supplierConnector } from "../connectors/registry";

const databaseId = () => env().APPWRITE_DATABASE_ID;
const db = () => createAppwriteDatabaseClient().databases;
const encryptionKey = () => { const key = env().SUPPLIER_CREDENTIAL_ENCRYPTION_KEY; if (!key) throw new Error("Supplier credential encryption is not configured"); return key; };
export const listGlobalSuppliers = () => db().listDocuments({ databaseId: databaseId(), collectionId: "global_suppliers", queries: [Query.orderDesc("priority"), Query.limit(500)] });
export const listGlobalFeatureFlags = () => db().listDocuments({ databaseId: databaseId(), collectionId: "global_feature_flags", queries: [Query.limit(100)] });
export const listSupplierConnections = (supplierId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "supplier_connections", queries: [Query.equal("supplierId", supplierId), Query.orderDesc("testedAt"), Query.limit(20)] });

async function diplomatsOwnership() { const databases = db(), stores = await databases.listDocuments({ databaseId: databaseId(), collectionId: "stores", queries: [Query.equal("slug", "diplomats-stores"), Query.equal("status", "active"), Query.limit(1)] }), store = stores.documents[0]; if (!store) throw new Error("Active Diplomats Stores record is required"); const vendor = await databases.getDocument({ databaseId: databaseId(), collectionId: "vendors", documentId: String(store.vendorId) }); if (!["approved", "active"].includes(String(vendor.status))) throw new Error("Diplomats Stores vendor must be approved"); return { store, vendor }; }
export async function createGlobalSupplier(input: { name: string; slug: string; provider: string; apiKey: string; countryCode: string; defaultCurrency: string; actorUserId: string }) {
  const databases = db(), { store, vendor } = await diplomatsOwnership(), now = new Date().toISOString(), supplierId = ID.unique(), slug = safeSupplierSlug(input.slug), provider = input.provider.toLowerCase();
  if (provider !== "cj" || input.name.trim().length < 2 || !/^[A-Z]{2}$/.test(input.countryCode) || !/^[A-Z]{3}$/.test(input.defaultCurrency) || input.apiKey.trim().length < 12) throw new Error("Invalid supplier configuration");
  const credential: SupplierCredentials = { apiKey: input.apiKey.trim() }, transaction = await databases.createTransaction({ ttl: 120 });
  try { await databases.createDocument({ databaseId: databaseId(), collectionId: "global_suppliers", documentId: supplierId, permissions: [], transactionId: transaction.$id, data: { name: input.name.trim(), slug, provider, supplierType: "dropshipping", integrationType: "api", status: "draft", ownerVendorId: vendor.$id, ownerStoreId: store.$id, countryCode: input.countryCode, supportedCountries: [], defaultCurrency: input.defaultCurrency, fulfilmentModes: ["global_direct","global_wholesale","global_sourcing"], apiBaseUrl: "https://developers.cjdropshipping.com/api2.0/v1", connectionStatus: "not_configured", priority: 100, reliabilityScore: 0, createdBy: input.actorUserId, createdAt: now, updatedAt: now } }); await databases.createDocument({ databaseId: databaseId(), collectionId: "supplier_credentials", documentId: supplierId, permissions: [], transactionId: transaction.$id, data: { supplierId, encryptedValue: encryptSupplierCredential(credential, encryptionKey()), maskedValue: maskSupplierCredential(credential.apiKey), encryptionVersion: 1, updatedBy: input.actorUserId, updatedAt: now } }); await databases.createDocument({ databaseId: databaseId(), collectionId: "audit_logs", documentId: ID.unique(), permissions: [], transactionId: transaction.$id, data: { actorUserId: input.actorUserId, action: "global_supplier.create", entityType: "global_supplier", entityId: supplierId, metadata: JSON.stringify({ provider, slug, ownerVendorId: vendor.$id, ownerStoreId: store.$id }), occurredAt: now } }); await databases.updateTransaction({ transactionId: transaction.$id, commit: true }); return supplierId; }
  catch (error) { await databases.updateTransaction({ transactionId: transaction.$id, rollback: true }).catch(() => undefined); throw error; }
}
export async function testGlobalSupplierConnection(supplierId: string, actorUserId: string) {
  const databases = db(), supplier = await databases.getDocument({ databaseId: databaseId(), collectionId: "global_suppliers", documentId: supplierId }), credentialRecord = await databases.getDocument({ databaseId: databaseId(), collectionId: "supplier_credentials", documentId: supplierId }), testedAt = new Date().toISOString(), connector = supplierConnector(String(supplier.provider)), credentials = decryptSupplierCredential<SupplierCredentials>(String(credentialRecord.encryptedValue), encryptionKey());
  await databases.updateDocument({ databaseId: databaseId(), collectionId: "global_suppliers", documentId: supplierId, data: { connectionStatus: "testing", updatedAt: testedAt } });
  try { const tested = await connector.testConnection(credentials), expiresAt = tested.credentials.refreshTokenExpiresAt ?? tested.credentials.accessTokenExpiresAt; await databases.updateDocument({ databaseId: databaseId(), collectionId: "supplier_credentials", documentId: supplierId, data: { encryptedValue: encryptSupplierCredential(tested.credentials, encryptionKey()), maskedValue: maskSupplierCredential(tested.credentials.apiKey), encryptionVersion: 1, ...(expiresAt ? { expiresAt } : {}), updatedBy: actorUserId, updatedAt: testedAt } }); await databases.updateDocument({ databaseId: databaseId(), collectionId: "global_suppliers", documentId: supplierId, data: { status: "connected", connectionStatus: "connected", lastConnectionTestAt: testedAt, lastSuccessfulSyncAt: testedAt, reliabilityScore: 100, updatedAt: testedAt } }); await databases.createDocument({ databaseId: databaseId(), collectionId: "supplier_connections", documentId: ID.unique(), permissions: [], data: { supplierId, provider: connector.provider, status: "connected", ...(tested.result.externalAccountId ? { externalAccountId: tested.result.externalAccountId } : {}), message: tested.result.message, ...(tested.result.requestId ? { requestId: tested.result.requestId } : {}), ...(tested.result.tokenExpiresAt ? { tokenExpiresAt: tested.result.tokenExpiresAt } : {}), testedAt, testedBy: actorUserId } }); await databases.createDocument({ databaseId: databaseId(), collectionId: "audit_logs", documentId: ID.unique(), permissions: [], data: { actorUserId, action: "global_supplier.connection_verified", entityType: "global_supplier", entityId: supplierId, metadata: JSON.stringify({ provider: connector.provider, requestId: tested.result.requestId }), occurredAt: testedAt } }); return tested.result; }
  catch (error) { const message = error instanceof Error ? error.message.slice(0, 500) : "Supplier connection failed"; await databases.updateDocument({ databaseId: databaseId(), collectionId: "global_suppliers", documentId: supplierId, data: { connectionStatus: "error", lastConnectionTestAt: testedAt, lastFailedSyncAt: testedAt, reliabilityScore: 0, updatedAt: testedAt } }).catch(() => undefined); await databases.createDocument({ databaseId: databaseId(), collectionId: "supplier_connections", documentId: ID.unique(), permissions: [], data: { supplierId, provider: connector.provider, status: "error", message, testedAt, testedBy: actorUserId } }).catch(() => undefined); throw new Error(message); }
}
