import Link from "next/link";
import { redirect } from "next/navigation";
import { CountrySelect, PhoneFields } from "@/app/components/country-phone-fields";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { findOfftaker } from "@/src/modules/offtake/server/repository";
export const dynamic = "force-dynamic";
export default async function Page() {
  const user=await getCurrentAppwriteUser(); if(!user) redirect("/login?returnTo=/offtakers/register"); const existing=await findOfftaker(user.$id); if(existing) redirect("/offtakers");
  return <main className="marketplace-shell"><nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><Link href="/wholesale">Wholesale</Link></nav><header><p className="kicker">CORPORATE OFF-TAKER REGISTRATION</p><h1>Source African supply at scale.</h1></header><form className="vendor-form" action="/api/offtakers/register" method="post"><fieldset><legend>Company and KYB</legend><label>Legal name<input name="legalName" required/></label><label>Registration number<input name="registrationNumber" required/></label><label>Tax ID<input name="taxId"/></label><CountrySelect/><label>Industry<input name="industry" required/></label><label>Buyer type<select name="buyerType"><option>Manufacturer</option><option>Processor</option><option>Exporter</option><option>Retail chain</option><option>Institution</option><option>Commodity trader</option></select></label><label className="wide">Registered address<textarea name="address" required/></label></fieldset><fieldset><legend>Contact and demand</legend><label>Contact name<input name="contactName" defaultValue={user.name} required/></label><label>Email<input name="contactEmail" type="email" defaultValue={user.email} required/></label><PhoneFields phoneName="contactPhone" label="Contact phone"/><label>Product categories<textarea name="productCategories" required/></label><label>Expected volumes<textarea name="expectedVolume" required/></label><label>Buying frequency<input name="buyingFrequency" required/></label><label>Sourcing countries<input name="sourcingCountries"/></label><label>Currency<input name="currency" defaultValue="NGN" required/></label><label>Delivery locations<textarea name="deliveryLocations" required/></label><label>Payment terms<textarea name="paymentTerms" required/></label></fieldset><button>Submit for KYB review</button></form></main>;
}
