import Link from "next/link";
import { requireSuperAdmin } from "@/src/modules/authorization/server/require-super-admin";
import { listCommissionRules } from "@/src/modules/finance/server/commissions";
import { CommissionRuleForm } from "./commission-rule-form";
export const dynamic="force-dynamic";
const pct=(bps:unknown)=>(Number(bps)/100).toFixed(2);
export default async function CommissionRulesPage({searchParams}:{searchParams:Promise<{saved?:string;retired?:string;error?:string}>}){
  await requireSuperAdmin();
  const[rules,query]=await Promise.all([listCommissionRules(),searchParams]);
  return <main className="admin-detail"><header><div><p className="kicker">REVENUE GOVERNANCE</p><h1>Commission & revenue rules</h1><p>Versioned, prospective rules preserve the allocation used by every order item.</p>{query.saved&&<p className="success-note">Commission rule saved successfully.</p>}{query.retired&&<p className="success-note">Commission rule retired. Historical allocations remain unchanged.</p>}{query.error&&<p className="form-error">The rule could not be saved. Check its scope, percentage, effective date and administrative reason.</p>}</div><Link href="/admin/finance">Finance overview</Link></header><section className="catalogue-create"><h2>Create a rule</h2><CommissionRuleForm defaultEffectiveFrom=""/></section><section className="review-table"><div className="review-row review-head"><span>Rule</span><span>Allocation</span><span>Scope</span><span>Effective/status</span></div>{rules.documents.map(rule=><div className="review-row" key={rule.$id}><span><strong>{String(rule.name)}</strong><small>Version {String(rule.version??1)} · priority {String(rule.priority??0)}</small></span><span><strong>PAC-SM {pct(rule.rateBasisPoints)}%</strong><small>Vendor {(100-Number(rule.rateBasisPoints)/100).toFixed(2)}% · fee: {String(rule.feeBearer??"platform")}</small></span><span>{String(rule.scopeType??"global").replaceAll("_"," ")} {rule.scopeId?`· ${String(rule.scopeId)}`:""}<small>{String(rule.channel??"all").replaceAll("_"," ")}</small></span><span>{new Date(String(rule.effectiveFrom)).toLocaleString("en-GB")}<small>{String(rule.status)}</small>{String(rule.status)!=="retired"&&!['default-marketplace','pacsm-owned-products'].includes(rule.$id)&&<form action={`/api/admin/finance/commission-rules/${rule.$id}/retire`} method="post"><input name="reason" required minLength={10} placeholder="Retirement reason"/><button>Retire</button></form>}</span></div>)}</section><section className="admin-notice"><strong>Rule priority</strong><p>PAC-SM-owned inventory → product → vendor → category → channel → marketplace default. New orders snapshot the winning rule; later changes never rewrite prior sales.</p></section></main>;
}
