import Image from "next/image";
import Link from "next/link";
import { CommerceModuleHeader, CommerceModuleHero } from "@/app/components/commerce-module-header";
import { listActiveCarriers, listCarrierRates } from "@/src/modules/logistics/server/repository";
export const dynamic = "force-dynamic";

export default async function LogisticsMarketplace() {
  const [carriers, rates] = await Promise.all([listActiveCarriers(), listCarrierRates()]);
  return <main className="commerce-module"><CommerceModuleHeader current="logistics" utility={{ href: "/track", label: "Track shipment" }}/><CommerceModuleHero tone="blue" eyebrow="VERIFIED CONTINENTAL LOGISTICS" title="Move goods across Africa with confidence." description="Discover verified carriers, active trade corridors and transparent service rates for marketplace and cross-border delivery." metric={carriers.total} metricLabel="verified carriers in the PAC-SM network"><div className="module-status-line"><span>Road, air, sea & rail</span><span>Tracked fulfilment</span><span>Verified operators</span></div><Link className="module-action-link" href="/track">Track a shipment →</Link></CommerceModuleHero>
    <div className="module-body"><section className="module-feature-strip"><article><span>✓</span><div><strong>Verified carriers</strong><small>KYB and operating-document review</small></div></article><article><span>⌁</span><div><strong>Continental corridors</strong><small>Cross-border service coverage</small></div></article><article><span>▣</span><div><strong>Shipment events</strong><small>Operational tracking milestones</small></div></article><article><span>↺</span><div><strong>Delivery evidence</strong><small>Recipient and proof-of-delivery records</small></div></article></section>
      <section className="module-partner"><div><span>OFFICIAL LOGISTICS PARTNER</span><h2>Zenith Carex Express</h2><p>Supporting PAC-SM marketplace delivery and continental logistics operations.</p></div><Image src="/zenith-carex-express.png" width={376} height={180} alt="Zenith Carex Express"/></section>
      <section className="module-panel"><div className="module-panel-heading"><div><span>CARRIER DIRECTORY</span><h2>Verified logistics partners</h2><p>Compare coverage, transport modes and active routes.</p></div><Link className="module-action-link" href="/carriers/apply">Become a carrier →</Link></div>{carriers.total ? <div className="module-carrier-grid">{carriers.documents.map(carrier => { const carrierRates = rates.documents.filter(rate => rate.carrierId === carrier.$id); return <article className="module-carrier-card" key={carrier.$id}><span>{String(carrier.tradingName ?? carrier.legalName).slice(0,2).toUpperCase()}</span><span>{String(carrier.carrierNumber)} · {String(carrier.rating)} rating</span><h2>{String(carrier.tradingName ?? carrier.legalName)}</h2><p>{String(carrier.transportModes)} · {(carrier.serviceCountries as string[]).join(", ")}</p><strong>{carrierRates.length} active route{carrierRates.length === 1 ? "" : "s"}</strong>{carrierRates.slice(0,3).map(rate => <small key={rate.$id}>{String(rate.originCountryCode)} → {String(rate.destinationCountryCode)} · {String(rate.currency)} {(Number(rate.baseRateMinor)/100).toLocaleString()}</small>)}</article>; })}</div> : <div className="module-empty"><strong>No verified carriers listed yet</strong><span>Approved carrier profiles and service corridors will appear here.</span></div>}</section>
    </div></main>;
}
