import type { AcademyLessonContent } from "./lesson-content";
const lesson=(lessonId:string,introduction:string,objectives:readonly string[],sections:AcademyLessonContent["sections"],keyTakeaways:readonly string[],reflection:readonly string[]):AcademyLessonContent=>({lessonId,introduction,objectives,sections,keyTakeaways,reflection});

export const ACADEMY_CONTENT_8_10:readonly AcademyLessonContent[]=[
lesson("m08-l01","Incoterms are standard trade terms published by the International Chamber of Commerce. They allocate specified delivery tasks, costs and risks between seller and buyer, but they do not replace the complete sales contract.",["Explain what Incoterms cover.","Separate cost allocation from risk transfer.","Use a named place and applicable version."],[
 {heading:"Purpose and limits",paragraphs:["An Incoterm clarifies who arranges carriage, export or import formalities where allocated, who pays specified costs and where delivery and risk transfer occur. The rules help parties use shared language across countries and transport chains.","They do not by themselves set product quality, price, payment method, title ownership, breach remedies, sanctions or governing law. Those matters belong in the sales contract and related documents."]},
 {heading:"Cost and risk are different",paragraphs:["The party paying a transport cost does not necessarily carry risk throughout that transport. Under some terms, the seller pays main carriage even though risk transfers earlier. Ask two separate questions at every point: who pays this cost, and who bears loss or damage risk?", "Insurance responsibility also differs by term, and minimum prescribed cover may not meet the transaction's commercial needs. Both parties should understand gaps and claims procedures."],example:{title:"Route map",body:"Draw the route from seller's premises to buyer's final point. Mark delivery/risk transfer with one symbol and each cost responsibility with another."}},
 {heading:"Precise incorporation",paragraphs:["State the selected three-letter term, exact named place or port and rule version, for example 'FCA Seller's Facility, Aba, Nigeria, Incoterms 2020.' The named point can materially change loading, terminal and risk responsibilities.","Agree the term before quoting and ensure invoice, purchase order, logistics instructions and insurance arrangements are consistent."]}
],["Incoterms allocate defined delivery obligations, cost and risk.","Cost and risk can transfer at different points.","The term needs a precise named place and version."],["Which contract issue is not settled by an Incoterm?","Mark cost and risk on one proposed route."]),

lesson("m08-l02","Selecting a trade term requires matching transport mode, control and capability. A term that appears convenient can expose a small exporter to unfamiliar destination costs or procedures.",["Compare commonly used terms.","Match terms to transport and operational capability.","Avoid unsuitable or misunderstood responsibilities."],[
 {heading:"Terms for any mode",paragraphs:["EXW places limited delivery obligations on the seller but can be impractical where the buyer cannot manage export formalities or loading arrangements. FCA delivers to a buyer-nominated carrier at the named place and is often more workable for containerised or multimodal shipments.","CPT and CIP include seller-paid carriage to a named destination while risk transfers when goods are handed to the carrier; CIP includes specified insurance. DAP, DPU and DDP move delivery further toward destination, with DPU requiring unloading and DDP imposing extensive import-side responsibility on the seller."],points:["EXW","FCA","CPT and CIP","DAP","DPU","DDP"]},
 {heading:"Sea and inland-waterway terms",paragraphs:["FOB, CFR and CIF are intended for sea or inland-waterway transport where delivery occurs with goods on board the vessel. They may be unsuitable for container cargo handed to a terminal before vessel loading; FCA or another multimodal term may better reflect control.","Under CFR and CIF the seller pays carriage to the named destination port, while risk transfers on board at origin; CIF adds specified insurance. This illustrates why cost and risk must be mapped separately."]},
 {heading:"Selection discipline",paragraphs:["Consider transport mode, point of physical control, ability to complete export and import procedures, freight purchasing power, destination knowledge, tax or registration exposure, insurance and buyer preference.","Do not promise DDP without competent confirmation that the seller can lawfully and practically act on import obligations. Document assumptions and obtain logistics and legal advice where exposure is material."],example:{title:"Defensible choice",body:"State why the selected term matches the cargo handover point, customs capability, insurance plan and quotation—not merely that the buyer requested it."}}
],["Transport mode and handover point shape term selection.","Seller-paid freight does not always mean seller-held risk.","Destination-heavy terms demand capability and advice."],["Which term best reflects your actual carrier handover?","What responsibility should your business refuse until capability improves?"]),

lesson("m08-l03","Export price must recover every transaction cost, provide an appropriate margin and remain credible in the target market. Missing one logistics or finance item can convert a profitable domestic product into an export loss.",["Build an export cost sheet.","Calculate price by quantity and Incoterm.","Test margin against uncertainty."],[
 {heading:"Cost build-up",paragraphs:["Start with product cost based on real bill of materials, labour, overhead and expected yield. Add export packaging, labels, testing, inspection, documentation, certification where applicable, inland transport, handling, forwarding, terminal charges, main freight, insurance, bank or payment fees, commissions and finance cost according to the selected term.","Separate fixed transaction costs from per-unit costs and allocate them using realistic order quantity. State currency, quotation date, rate source and validity. Avoid double counting and clarify taxes or duties excluded from the seller's price."],points:["Production and yield","Export pack","Compliance and documents","Origin logistics","Main carriage and insurance","Finance and payment","Commission and contingency","Target profit"]},
 {heading:"Quotation and margin",paragraphs:["Price = total cost plus required profit, but the result must also be checked against customer value and comparable landed alternatives. If it is uncompetitive, redesign pack, quantity, route, term or process; do not simply omit costs.","Create quantity breaks only when scale genuinely changes cost. Define minimum order and payment assumptions. A lower unit price with a much larger order may require more working capital and create greater exposure."],example:{title:"Sensitivity",body:"Recalculate margin after a freight increase, currency movement, yield loss and payment delay. Set a quotation validity and approval rule for exceptions."}},
 {heading:"Commercial controls",paragraphs:["Use controlled cost-sheet versions, documented assumptions and authorised margin thresholds. Reprice when inputs, route, currency or specification changes materially.","The final quotation should clearly describe product, quantity, currency, unit and total price, Incoterm and named place, payment, lead time, validity and exclusions."]}
],["Export price is based on the selected responsibility scope.","Fixed costs and working capital change with order quantity.","Sensitivity testing protects margin."],["Which cost is most likely missing from your present price?","At what exchange or freight movement must you reprice?"]),

lesson("m08-l04","Shipment planning connects product readiness, documents, transport, intermediaries and milestones from origin to delivery. The best route balances time, cost, risk and product requirements.",["Select a suitable transport mode.","Distinguish FCL and LCL.","Create a controlled shipment plan."],[
 {heading:"Transport mode",paragraphs:["Road offers flexibility and regional reach; rail can move volume on available corridors; sea is efficient for large long-distance cargo but slower; air is fast and expensive, often suited to urgent, high-value or shelf-life-sensitive shipments. Multimodal routes combine modes.","Consider transit variability, frequency, handling, temperature, security, dimensions, dangerous-goods status, border requirements and the value of time—not freight price alone."]},
 {heading:"FCL, LCL and intermediaries",paragraphs:["FCL provides a full container allocation, though it may not be physically full. LCL consolidates shipments and can suit smaller volume but adds handling, consolidation timing and exposure to other cargo. Calculate utilisation and product compatibility.","A freight forwarder may coordinate booking, documents and movement; carriers transport cargo; customs brokers or other agents perform defined services. Verify competence, licences where applicable, insurance, references, charges and contractual responsibility."],example:{title:"Quote comparison",body:"Compare quotations on the same origin, destination, cargo, service, inclusions, free time, validity, transit estimate and liability conditions."}},
 {heading:"Milestone plan",paragraphs:["Plan order confirmation, production, inspection or tests, document cut-offs, booking, pickup, export clearance, departure, transhipment, arrival, import steps, delivery and proof of receipt. Assign an owner and escalation trigger to every milestone.","Build contingency for delay, missed sailing, document correction, damage and temperature excursion. Communicate using verified references and retain final transport evidence."]}
],["Mode selection balances time, cost, risk and product condition.","LCL adds consolidation and handling considerations.","Milestones need owners and escalation triggers."],["Which mode best protects the product's commercial value?","What is the earliest warning of a missed delivery?"]),

lesson("m09-l01","Financial records convert business activity into evidence for decisions, buyers and funders. A business plan connects market demand to operations, management, risk and cash requirements.",["Identify essential SME records.","Connect operations to financial statements.","Build an evidence-based business plan."],[
 {heading:"Core records",paragraphs:["Maintain sales invoices and receipts, purchases, expenses, inventory movement, payroll, receivables, payables, bank transactions, assets and liabilities. Reconcile cash and bank balances, control document numbering and retain supporting evidence.","Separate business and personal transactions. Timely records reveal margin, cash leakage, slow stock and overdue customers; reconstructed records created only for a loan application are less reliable."]},
 {heading:"Understand the financial story",paragraphs:["The income statement explains revenue, costs and profit over a period. The statement of financial position shows assets, liabilities and equity at a date. Cash flow explains why a profitable business may still lack money when inventory and receivables absorb cash.","Monitor gross margin, operating margin, stock days, receivable days, payable days and debt obligations. Compare actual results with budget and investigate significant differences."],points:["Revenue and cost","Profitability","Inventory","Receivables and payables","Cash movement","Debt and assets"]},
 {heading:"Business planning",paragraphs:["A credible plan defines product, customer problem, market evidence, competition, route to market, production and supply, management capability, financial assumptions, funding need, risks and milestones.","Ensure forecasts follow operational drivers such as customers, order size, capacity, price and yield. Use scenarios and state assumptions openly."],example:{title:"Evidence test",body:"For each major forecast assumption, cite a record, buyer evidence, quotation, capacity study or reasonable external source."}}
],["Good records support management before they support funding.","Profit and cash are not the same.","Plans should connect forecasts to operational evidence."],["Which missing record weakens your financing case?","What driver explains next year's proposed sales?"]),

lesson("m09-l02","Funding sources differ in repayment, ownership, restrictions, cost, timing and reporting. The right instrument fits the purpose and cash-generating profile of the need.",["Compare loans, grants, development finance, cooperative and equity-style funding.","Match funding tenor to use.","Recognise obligations beyond headline cost."],[
 {heading:"Loans and development finance",paragraphs:["Loans provide repayable capital with interest, fees, security or covenants. Short-term facilities may fund working capital; longer-term finance may fit equipment that produces benefits over years. Repayment must be supported by cash flow under realistic scenarios.","Development finance institutions may target sectors or policy outcomes and require detailed eligibility, safeguards and reporting. Verify current programmes directly; do not build a plan around an assumed approval."]},
 {heading:"Grants, cooperatives and investors",paragraphs:["Grants are usually competitive and restricted to defined activities, milestones and reporting. They are not free money without accountability. Cooperative finance can pool savings and knowledge but requires clear governance and member obligations.","Angel or equity-style investment exchanges capital for ownership or economic rights and may add expertise. Founders must understand valuation, control, information rights, dilution and exit expectations before agreement."],points:["Repayment or ownership effect","Total cost","Purpose restrictions","Security and guarantees","Decision time","Currency","Reporting and governance"]},
 {heading:"Match source to need",paragraphs:["Do not use a short, expensive loan to fund an asset whose returns emerge slowly, or permanent equity for a small self-liquidating order without considering alternatives. Combine sources only when obligations remain manageable.","Read term sheets and contracts with professional support. Stress-test sales delay, cost increase and currency movement."],example:{title:"Funding map",body:"For each need, state amount, date required, repayment source, cash generation timing, security and most suitable funding category."}}
],["Funding has obligations even when it is called support.","Tenor and repayment should match the financed use.","Verify programmes and understand contracts."],["Which source best fits your next need and why?","What downside scenario threatens repayment?"]),

lesson("m09-l03","A bankable proposal explains a credible opportunity, evidence, funding requirement, use of funds, repayment or return logic and risks. Working-capital analysis shows how much cash the transaction consumes before settlement.",["Prepare a funding case.","Calculate the cash conversion gap.","Present risks and mitigations honestly."],[
 {heading:"Proposal structure",paragraphs:["Describe legal business identity, management, product, customer and market evidence, historical performance, operating plan, funding amount, detailed use, financial projections, security where relevant and measurable milestones.","Show contribution from the business and why funding changes capacity or cash generation. Ensure numbers reconcile across narrative, budgets and statements. Unsupported guaranteed returns undermine credibility."]},
 {heading:"Working capital",paragraphs:["Cash is tied up from purchase of inputs through production, inventory, shipment and the buyer's payment period. Calculate inventory days plus receivable days minus payable days, then model the actual transaction timeline and peak deficit.","Growth can increase the deficit faster than profit. Deposits, supplier terms, staged production, invoice finance or another suitable instrument may reduce the gap, each with cost and risk."],example:{title:"Order finance",body:"Map every expected cash inflow and outflow by week. Finance the maximum cumulative shortfall plus justified contingency, not merely the invoice value."}},
 {heading:"Due diligence and risk",paragraphs:["Funders assess management, records, market, margins, repayment, compliance, security and downside resilience. Disclose material risks and show specific mitigations, insurance, contracts or controls.","Maintain a data room with authorised, current documents and protect sensitive information. Never alter records to satisfy an application."]}
],["Bankability rests on evidence and repayment logic.","Rapid growth can create a larger cash gap.","Transparent risks improve decision quality."],["What evidence supports your repayment source?","Calculate the peak cash deficit of one order."]),

lesson("m09-l04","Payment terms allocate financing and default risk between buyer and seller. The safest method is not always commercially acceptable, so parties combine verification, documents, banks, insurance and limits.",["Compare common payment methods.","Explain documentary compliance risk.","Design a proportionate payment structure."],[
 {heading:"Advance and open account",paragraphs:["Under advance payment, the buyer pays before shipment, reducing seller non-payment risk but increasing buyer exposure. Parties may use a deposit with balance at a defined milestone. Verify receipt irrevocably through the bank rather than relying on a screenshot.","Under open account, the seller ships before payment on agreed credit terms. This supports buyer cash flow but exposes the seller to default, delay and country or currency risk. Use only after due diligence, approved credit limits and appropriate controls."]},
 {heading:"Documentary methods",paragraphs:["Documentary collections route documents through banks under instructions, but banks generally do not guarantee payment. Letters of credit can provide a bank undertaking subject to their exact terms and compliant documents; they require careful review, cost and operational competence.","A commercial shipment can be satisfactory yet a payment presentation fail because documents contain discrepancies. Review terms before acceptance and prepare documents under four-eye control."],example:{title:"No method removes all risk",body:"Evaluate buyer, bank and country risk, document complexity, fraud, currency, cost and dispute exposure together."}},
 {heading:"Payment risk controls",paragraphs:["Verify buyer identity, ownership, address, trade history and references independently. Agree currency, due date, bank charges, late-payment consequences and dispute process. Consider credit insurance, guarantees, escrow or staged payment where suitable and lawful.","Watch unexplained fee requests, changed bank details and pressure to bypass verification. Confirm sensitive changes through a separate trusted channel."],points:["Buyer default","Bank or country risk","Currency movement","Document discrepancy","Fraud and account substitution","Delay and dispute"]}
],["Payment method shifts rather than eliminates risk.","Documentary methods demand exact compliance.","Independent verification protects payment instructions."],["Which method fits a new untested buyer?","How will you verify a bank-detail change?"]),

lesson("m10-l01","Market channels have different economics, service requirements and decision-makers. Sellers must adapt pack, price, evidence and fulfilment without losing product integrity.",["Compare supermarket, hospitality, distributor and digital channels.","Prepare channel-specific offers.","Evaluate margin and service obligations."],[
 {heading:"Retail and supermarkets",paragraphs:["Retail buyers may assess consumer demand, pack and case dimensions, barcode, label compliance, shelf life at delivery, margin, promotional support, supply reliability, returns and payment terms. Listing does not guarantee sell-through.","Calculate all deductions and working-capital effects. Start with a controlled store group when possible, monitor sales and replenishment, and do not accept volumes the operation cannot support."]},
 {heading:"Hospitality and distributors",paragraphs:["Hotels and restaurants often value consistent specification, food-service pack, dependable delivery and preparation performance. Samples should reflect the product that will actually be supplied.","Distributors provide relationships, warehousing or reach but require due diligence, territory and channel definitions, targets, reporting, inventory responsibility, credit limits and termination terms. Exclusivity should be earned and bounded."],example:{title:"Channel economics",body:"Compare net revenue after discounts, commission, promotions, delivery, returns, credit cost and channel-specific packaging—not only headline selling price."}},
 {heading:"Digital and institutional routes",paragraphs:["E-commerce expands visibility but adds catalogue accuracy, fulfilment, returns, ratings and platform fees. Institutional procurement may require formal specifications, eligibility documents, bid security, delivery schedules and auditability.","Choose the channel that matches customer behaviour and business capability. A multi-channel strategy needs inventory and price controls to prevent conflict."]}
],["Each channel changes cost, evidence and service.","Listing is not the same as sell-through.","Channel agreements require measurable responsibilities."],["Which channel best matches your pack and capacity?","What hidden deduction changes its net margin?"]),

lesson("m10-l02","Buyer acquisition is a disciplined pipeline from lead generation through verification, qualification and next action. Independent checks protect sellers from fraud and wasted effort.",["Build a buyer pipeline.","Verify identity and commercial credibility.","Recognise suspicious enquiries."],[
 {heading:"Finding and qualifying leads",paragraphs:["Sources include trade fairs, chambers, embassies, associations, referrals, professional networks, B2B platforms, procurement notices and direct research. Record source, organisation, contact, market, channel, need and permission to communicate.","Qualify fit, authority, need, quantity, timing, budget, specification and next step. A large list of unqualified contacts is not market access; focus on relevant decision-makers and respectful follow-up."],points:["Lead","Contacted","Qualified","Sample or proposal","Negotiation","Won, lost or nurture"]},
 {heading:"Independent verification",paragraphs:["Verify legal name and registration through appropriate official or credible sources, physical address, website and domain, contact role, ownership where relevant, trade history, references and commercial reputation. Cross-check bank-account beneficiary before payment.","Use a risk-based level of due diligence. Larger credit exposure, unfamiliar jurisdictions, unusual routes or high-risk products justify deeper review and professional support."],example:{title:"Verification record",body:"Save the source, date, result, reviewer and unresolved concern. Do not write 'verified' when only an email address was checked."}},
 {heading:"Fraud warning signs",paragraphs:["Warning signs include unexplained advance fees, urgency, refusal of video or independent checks, inconsistent company details, free-email impersonation, changed bank instructions, overpayment schemes and requests to misdescribe goods.","Pause, verify through a separate channel and escalate. Decline the opportunity when material risk remains; the fear of losing a sale should not override controls."]}
],["Acquisition is a managed pipeline, not random messaging.","Verification must be independent and recorded.","Suspicious urgency is a reason to pause."],["Which two sources produce your most credible leads?","What unresolved fact would stop you extending credit?"]),

lesson("m10-l03","A strong sales pitch is relevant, evidenced and followed by a clear next step. Negotiation then trades variables deliberately instead of reducing price without receiving value.",["Prepare a concise buyer pitch.","Set negotiation targets and limits.","Exchange concessions conditionally."],[
 {heading:"The export sales pitch",paragraphs:["State who you are, the customer problem, product and format, relevant benefit, credible evidence and proposed next step. Tailor language to the buyer's channel and avoid a long company history before addressing need.","Evidence can include specification, capacity, paid pilot, quality control, applicable certification, customer result or reliable lead time. Use only current truthful evidence and keep supporting documents ready."],example:{title:"Pitch structure",body:"For [buyer/need], we supply [specific offer] delivering [benefit]. We can support this with [evidence]. May we confirm specification and arrange [sample, call or quotation]?"}},
 {heading:"Prepare the negotiation",paragraphs:["Set an ideal outcome, target and walk-away point for price, quantity, specification, payment, delivery, packaging, Incoterm, lead time, territory and service. Calculate the cost and risk of every variable.","Understand interests behind positions. A demand for lower price may be addressed by larger quantity, simpler pack, deposit, longer lead time or different delivery scope rather than an unconditional discount."]},
 {heading:"Trade concessions",paragraphs:["Use conditional language: 'If you confirm the larger quantity and deposit by Friday, we can offer...' Record agreed points and unresolved items, then issue a complete written offer or counter-offer.","Never concede below approved margin, outside operational capacity or against compliance. Verify that the person negotiating has authority and that acceptance is captured through the platform or formal channel."]}
],["A pitch connects buyer need to credible evidence.","Every negotiation variable has cost and risk.","Concessions should be conditional and documented."],["Deliver your pitch in 90 seconds.","Which variable can you trade without damaging quality?"]),

lesson("m10-l04","Customer retention comes from accurate promises, consistent delivery, responsive problem resolution and disciplined account development. PAC-SM brings the seller's profile, products, negotiations, orders and operational records into one workflow.",["Plan reliable customer service.","Handle complaints with traceability and corrective action.","Use PAC-SM records to support repeat business."],[
 {heading:"Retention through performance",paragraphs:["Confirm specifications, quantities, dates and responsibilities before every order. Communicate milestones and risks early, deliver consistent product and documentation, and review performance after receipt. Reliability is often a stronger differentiator than promotional claims.","Track on-time-in-full delivery, rejection, complaint response, repeat orders, payment performance and account margin. Growth with an unprofitable or chronically late-paying customer is not healthy retention."]},
 {heading:"Complaints and recovery",paragraphs:["Acknowledge promptly, gather order and lot evidence, protect potentially affected product, investigate root cause, agree fair resolution and verify corrective action. Do not argue before facts are established or make an unsupported admission.","Use complaint trends to improve product, pack, communication or logistics. Traceability should identify other customers or stock potentially affected."],example:{title:"Service recovery",body:"State what is known, what is being investigated, immediate protection, responsible contact and next update time. Close only when action and customer communication are recorded."}},
 {heading:"PAC-SM workflow",paragraphs:["Maintain an accurate business and storefront profile, current product information, media, capacity, standards and certification evidence. Use wholesale negotiation and procurement records for offers, counter-offers and accepted terms; use order, payment, fulfilment and logistics records to follow execution.","The marketplace supports connection and accountability but does not replace seller responsibility. Update availability, respond through authorised accounts, protect credentials and retain transaction evidence. Build a 90-day account plan covering contacts, forecast, service actions, payment, next opportunity and review date."],points:["Accurate seller and product records","Verified communication","Recorded commercial terms","Order and payment milestones","Delivery evidence","Complaint and account history"]}
],["Retention is earned through repeatable performance.","Complaints should drive traceable corrective action.","PAC-SM records connect readiness, sale and fulfilment."],["Which service measure predicts repeat purchase?","Write the next three actions for one target account."])
] as const;
