export type AcademyReadingSection={
  heading:string;
  paragraphs:readonly string[];
  points?:readonly string[];
  example?:{title:string;body:string};
};

export type AcademyLessonContent={
  lessonId:string;
  introduction:string;
  objectives:readonly string[];
  sections:readonly AcademyReadingSection[];
  keyTakeaways:readonly string[];
  reflection:readonly string[];
};

const MODULE_ONE_CONTENT:readonly AcademyLessonContent[]=[
  {
    lessonId:"m01-l01",
    introduction:"Trade begins with an exchange of value, but cross-border trade adds more actors, controls and responsibilities than an ordinary local sale. This lesson builds the language you will use throughout the Academy and follows a transaction from the producer to the final customer.",
    objectives:[
      "Define trade, domestic trade, international trade, export and import.",
      "Explain why one transaction is an export to one party and an import to another.",
      "Distinguish exports of physical goods from exports of services.",
      "Identify the commercial elements required to complete a real export transaction."
    ],
    sections:[
      {heading:"What trade means",paragraphs:["Trade is the exchange of goods or services between parties for value. The value is commonly money, although a commercial arrangement may also include credit, agreed services or another lawful form of consideration. A transaction is not complete merely because a product changes location: the parties must know what is being supplied, the quantity and quality expected, the price, the time of delivery and how payment will be made.","Domestic trade takes place within one country. The buyer, seller and movement of the product remain within that national market. International or cross-border trade involves parties in different countries, so the transaction must also deal with borders, currencies, documentation, transport arrangements and the laws of the countries involved."],example:{title:"Simple comparison",body:"A processor in Kano sells cartons to a retailer in Lagos: domestic trade. The same processor sells cartons to a distributor in Accra: international trade."}},
      {heading:"Export and import are two views of the same transaction",paragraphs:["An export is a sale or supply of goods or services from one country to a buyer in another country. An import is the purchase or receipt of those goods or services into the buyer's country. The words describe the direction of the same transaction from different national perspectives.","Suppose a Nigerian company sells 2,000 cartons of processed food to a Ghanaian distributor. The Nigerian company is exporting and Nigeria records an export. The Ghanaian distributor is importing and Ghana records an import. Understanding this dual perspective matters because each side has different responsibilities, records and regulatory procedures."],points:["Seller's perspective: export.","Buyer's perspective: import.","Origin side: prepares the goods for lawful exit.","Destination side: prepares for lawful entry and local distribution."]},
      {heading:"Goods and services can both cross borders",paragraphs:["Goods are physical items such as cocoa, garments, cosmetics, machinery or packaged food. Their export normally requires packaging, physical transport, customs procedures and evidence that the product meets applicable requirements.","Services are non-physical commercial outputs. Examples include consulting, software, design, education, engineering support and other professional or digital services supplied to a customer in another country. Services may not pass through a seaport, but contracts, payment, tax, data, licensing and professional requirements may still apply."],example:{title:"Service export",body:"A Nigerian design company produces packaging artwork for a manufacturer in Kenya and is paid for the work. The company has exported a service even though no physical parcel crossed the border."}},
      {heading:"Exporting is a complete commercial system",paragraphs:["Exporting is not simply sending something abroad. A viable export needs an exportable product or service, a real buyer, agreed specifications, an acceptable price, clear delivery and payment terms, applicable compliance, accurate documents and workable logistics.","A weakness in any one element can stop the transaction. A willing buyer cannot compensate for prohibited labelling. Correct documents cannot compensate for inconsistent quality. A low selling price may still fail if freight and destination costs make the landed price uncompetitive. Exporters therefore manage a connected system rather than a single shipment."],points:["Product and quantity","Verified buyer","Price and currency","Quality specification","Compliance and documentation","Payment method","Delivery responsibilities","Transport and risk controls"]}
    ],
    keyTakeaways:["Export and import describe the same cross-border transaction from different perspectives.","Both goods and services can be exported.","An export is a commercial system involving product, buyer, terms, compliance, payment and logistics."],
    reflection:["Describe one transaction in your business that could become cross-border trade.","Which part of that transaction would change most if the customer were in another country?"]
  },
  {
    lessonId:"m01-l02",
    introduction:"Businesses export for growth, resilience and access to new customers, but a foreign enquiry is not automatically a profitable opportunity. This lesson helps you examine both the strategic reasons for exporting and the risks that must be priced and controlled.",
    objectives:["Explain the main commercial reasons businesses export.","Separate an observation or enquiry from an evidence-based opportunity.","Recognise common financial, operational and regulatory export risks.","Decide whether an export opportunity supports the business rather than distracting it."],
    sections:[
      {heading:"Market growth and revenue diversification",paragraphs:["A domestic market may limit the number of customers a business can reach. Exporting can open access to consumers, distributors, manufacturers, retailers, hospitality businesses and institutional buyers in other countries. This can increase sales and help a business make better use of equipment, staff and production capacity.","Exporting can also diversify revenue. When a business relies on one location, one major customer or one selling season, a local downturn can threaten the entire operation. Customers in multiple markets may reduce that concentration risk, provided the company does not expand faster than its working capital and production controls allow."]},
      {heading:"Foreign exchange, scale and brand development",paragraphs:["Cross-border sales may generate revenue in another currency. This can help a business pay for imported inputs or equipment, but it also creates exchange-rate exposure: the value received in the home currency can move between quotation, shipment and settlement.","Larger or repeat orders can improve production scale and encourage better systems, packaging and quality control. Export experience may strengthen a brand, but only if the exporter delivers consistently. A missed shipment or poor batch can damage credibility in a market where replacing trust is expensive."],points:["Larger addressable market","Multiple revenue sources","Foreign-currency earnings","Better use of capacity","Product and packaging improvement","Stronger commercial reputation"]},
      {heading:"The risks behind the opportunity",paragraphs:["Export orders often require more working capital because the exporter may buy inputs, produce, test, package and transport goods before receiving full payment. The payment cycle may be longer than in domestic trade. Delays at a border, port or inspection point can create storage charges, spoilage or missed delivery windows.","The exporter may face stricter product standards, stronger competitors, unfamiliar customer expectations and destination-country rules. Currency movements can reduce margin, and an unverified buyer can create fraud or non-payment risk. These are not reasons to avoid exporting; they are reasons to investigate, cost and allocate risk before accepting an order."],points:["Quality and specification failure","Long payment cycles","Foreign-exchange movement","Logistics delay or damage","Regulatory non-compliance","Stronger competition","Buyer fraud or default"]},
      {heading:"Observation, enquiry and viable opportunity",paragraphs:["An observation such as 'many Africans abroad want familiar food' may suggest a market, but it does not prove a viable opportunity. An enquiry shows interest, but the buyer, quantity, price and requirements must still be verified.","A viable opportunity has evidence of demand, an identifiable customer, purchasing power, a competitive offer, realistic landed cost, a route to market and a credible path to compliance and delivery. The right question is not simply 'Can I export this?' but 'Can my business supply this customer repeatedly, compliantly and profitably?'"],example:{title:"Opportunity test",body:"A buyer asks for 2,000 cartons. Before agreeing, confirm the buyer's identity, specification, destination requirements, acceptable price, delivery date, payment security, production capacity and full transaction cost."}}
    ],
    keyTakeaways:["Exporting may grow and diversify a business, but growth must be operationally and financially supportable.","An enquiry is not yet an order, and an observation is not yet market evidence.","Good exporters identify, allocate and price risk before committing."],
    reflection:["List three benefits exporting could create for your selected business.","List three risks that could remove the profit from the same opportunity."]
  },
  {
    lessonId:"m01-l03",
    introduction:"A market is more than a country name. It includes customers, channels, competitors, regulations, prices, culture and purchasing behaviour. This lesson explains how to identify realistic African opportunities and how value moves from inputs to the final customer.",
    objectives:["Identify relevant African and international customer segments.","Distinguish a large market from an accessible market.","Apply basic market-screening questions.","Map physical goods, information and money across an export value chain."],
    sections:[
      {heading:"Opportunities within Africa",paragraphs:["African businesses can supply neighbouring and non-neighbouring markets with processed foods, agricultural products, textiles, cosmetics, household products, light manufactures and services. Buyers may be consumers, wholesalers, distributors, retailers, hotels, restaurants, manufacturers, governments or other institutions.","Geographic closeness can reduce transit time and make market visits easier, but it does not guarantee access. Product standards, language, consumer preferences, payment systems, border procedures and distribution structures still differ. An exporter must verify what applies to the product and destination."],example:{title:"Start with a practical question",body:"Which African market can you reach reliably, which defined buyer segment needs your product, and what evidence shows that your offer is competitive there?"}},
      {heading:"Beyond Africa: size is not accessibility",paragraphs:["Markets outside Africa may offer large demand or diaspora customers, but a large market can also have strict standards, expensive logistics, sophisticated buyers and intense competition. Market size alone is therefore a weak selection method.","An accessible market is one where the business can identify buyers, meet requirements, deliver at a competitive landed cost and receive payment with manageable risk. A smaller reachable market may be a better first step than a famous market the business cannot serve consistently."],points:["Is there verified demand?","Which customer segment will buy?","Can the product meet required quality and labelling?","Is the landed cost competitive?","Can supply remain consistent?","Can buyers be found and verified?","Which regulations apply?"]},
      {heading:"Customer segments change the offer",paragraphs:["A consumer buys for personal use and responds to convenience, price, trust and presentation. A wholesaler buys volume for resale and focuses on margin, movement and supply. A distributor may require territory, marketing support and dependable replenishment. A retailer cares about shelf fit, barcode, packaging, margin and consumer demand. An institutional or business buyer may require specifications, tender documents, service levels and credit terms.","The same underlying product can therefore need different pack sizes, outer cartons, prices, labels and sales messages. Market research must identify the buyer and channel, not simply the destination country."],example:{title:"One product, different formats",body:"A household customer may prefer a 500 g retail pouch; a restaurant may prefer a 10 kg food-service pack; a distributor may require master cartons and pallet information."}},
      {heading:"The export value chain",paragraphs:["A typical physical chain may include the input supplier, producer or processor, exporter, warehouse, inland transporter, border or port, freight forwarder, carrier, importer, distributor or retailer and final customer. Some businesses perform several roles, but the responsibilities still exist.","Three flows move through this chain. Physical flow is the movement of inputs and products. Information flow includes specifications, orders, invoices, certificates, shipping instructions and tracking. Money flow includes deposits, finance, freight charges, duties, settlement and commissions. A failure in one flow affects the others: incorrect documents can stop the goods; delayed payment can stop production; poor quality can trigger rejection and financial loss."],points:["Map who owns or controls the goods at each stage.","Record what information must arrive before the goods.","Record who pays each cost and when.","Identify the points where delay, damage, rejection or fraud could occur."]}
    ],
    keyTakeaways:["A market consists of customers, channels, rules, competition, prices and behaviour—not only geography.","Accessible demand is more useful than impressive market size.","Export value chains carry goods, information and money, and all three flows must be controlled."],
    reflection:["Choose one product and name its most suitable customer segment in a specific African country.","Draw its chain from input supplier to final customer and mark the highest-risk point."]
  },
  {
    lessonId:"m01-l04",
    introduction:"Continental trade frameworks and digital marketplaces can lower some barriers, but they do not remove the exporter's duty to comply, verify and deliver. This lesson introduces AfCFTA concepts and shows how PAC-SM supports a business across the trade journey.",
    objectives:["Explain the purpose of AfCFTA in practical business language.","Recognise why preferential treatment is conditional rather than automatic.","Identify the support functions available across the PAC-SM ecosystem.","Understand why complete and accurate digital business records matter."],
    sections:[
      {heading:"What AfCFTA is intended to support",paragraphs:["The African Continental Free Trade Area is a framework intended to deepen African economic integration and facilitate trade among participating countries. Important concepts include tariff liberalisation, reduction of non-tariff barriers, rules of origin, market access and development of regional value chains.","For businesses, the opportunity is a larger connected trading area and the possibility of sourcing, processing and selling across African value chains. Real benefits depend on the applicable legal instruments, implementation arrangements and the facts of each transaction."],points:["Tariffs: charges applied to qualifying imported goods.","Non-tariff barriers: procedural or regulatory obstacles other than tariffs.","Rules of origin: tests used to establish where a product originates.","Market access: the conditions under which a product or service may enter a market."]},
      {heading:"The essential AfCFTA caution",paragraphs:["AfCFTA does not mean that any product can be shipped anywhere in Africa without restrictions. Preferential treatment may depend on product classification, applicable schedules, rules of origin and evidence that the product meets those rules.","The destination country can still apply legitimate product, safety, health, labelling, licensing and documentation requirements. Exporters must verify the current official position for their product and route rather than relying on assumptions, social-media advice or a previous shipment of a different product."],example:{title:"Practical safeguard",body:"Before pricing an expected tariff benefit, confirm the product classification, origin rule, supporting origin document, destination procedure and whether the relevant preference is operational for that trade route."}},
      {heading:"PAC-SM as a trade-enablement ecosystem",paragraphs:["PAC-SM is designed to connect education with commercial execution. The Academy develops knowledge, while the broader marketplace supports seller onboarding, product presentation, standards and certification records, wholesale negotiation, procurement opportunities, buyer connections, logistics, payments and operational administration.","A seller should use these functions as one connected readiness journey. Training identifies what must be improved; the seller account records the business and products; marketplace tools connect demand and supply; operational records support fulfilment and accountability."],points:["Export education and readiness","Product and storefront records","Packaging and quality expectations","Documentation and certification tracking","Retail, wholesale and procurement channels","Buyer and seller communication","Payment, order and logistics workflows"]},
      {heading:"Why an accurate digital profile matters",paragraphs:["Buyers, administrators and commercial partners make decisions using the information a business provides. Incomplete ownership details, inconsistent product descriptions, unsupported claims or expired documents reduce trust and slow verification.","A good digital business profile should use the same legal identity, contact information and product facts that appear in the business's formal records. Product images and descriptions should accurately represent what will be supplied. Certification claims should be supported by current evidence, and changes in capacity, price or availability should be updated promptly.","PAC-SM supports the transaction, but the seller remains responsible for truthful information, lawful products and reliable fulfilment. Digital visibility creates opportunity only when it is backed by operational readiness."],example:{title:"Your support diagnosis",body:"Identify the weakest stage in your current journey: product readiness, compliance, packaging, finance, buyer access, negotiation, payment or delivery. Then select the PAC-SM workflow that addresses it."}}
    ],
    keyTakeaways:["AfCFTA can facilitate continental trade, but preferences and market access remain conditional.","Exporters must verify classification, origin, standards and destination procedures.","PAC-SM connects learning, readiness, marketplace access and transaction workflows.","Accurate digital records build trust and reduce verification delays."],
    reflection:["Which AfCFTA assumption could create the greatest risk for an unprepared exporter?","Which PAC-SM capability should your business use first, and what evidence must you prepare?"]
  }
] as const;

import { ACADEMY_CONTENT_2_4 } from "./lesson-content-2-4.ts";
import { ACADEMY_CONTENT_5_7 } from "./lesson-content-5-7.ts";
import { ACADEMY_CONTENT_8_10 } from "./lesson-content-8-10.ts";

export const ACADEMY_LESSON_CONTENT:readonly AcademyLessonContent[]=[...MODULE_ONE_CONTENT,...ACADEMY_CONTENT_2_4,...ACADEMY_CONTENT_5_7,...ACADEMY_CONTENT_8_10];
export const findAcademyLessonContent=(lessonId:string)=>ACADEMY_LESSON_CONTENT.find(content=>content.lessonId===lessonId);
