import type { AcademyLessonContent } from "./lesson-content";
const lesson=(lessonId:string,introduction:string,objectives:readonly string[],sections:AcademyLessonContent["sections"],keyTakeaways:readonly string[],reflection:readonly string[]):AcademyLessonContent=>({lessonId,introduction,objectives,sections,keyTakeaways,reflection});

export const ACADEMY_CONTENT_5_7:readonly AcademyLessonContent[]=[
lesson("m05-l01","Export packaging must protect a product through longer, less predictable handling and distribution than many local journeys. Good packaging is a system of primary, secondary and transport components designed around the product and route.",["Explain packaging functions.","Assess route-specific hazards.","Specify primary, secondary and transport packaging."],[
 {heading:"Protection throughout the route",paragraphs:["Packaging protects against impact, vibration, compression, moisture, dust, contamination, light, oxygen, temperature and tampering as relevant. Map the route from production through storage, inland movement, border or port, carrier, importer and final channel, then identify hazards at every transfer.","Primary packaging touches or directly contains the product. Secondary packaging groups sale units. Tertiary or transport packaging supports handling and shipment. These layers must work together rather than look attractive in isolation."]},
 {heading:"Local and export conditions",paragraphs:["A local pack that survives a short delivery may fail after container stacking, humid storage or repeated handling. Export packs should be selected using measured product weight, fragility, shelf life, transport mode, stacking pattern and destination climate.","Optimisation matters: excessive packaging adds freight, waste and cost, while insufficient packaging creates damage and rejection. Confirm material suitability for the product, especially food-contact use."],example:{title:"Route audit",body:"Photograph each packaging layer, record dimensions and weight, simulate expected stacking and handling, and document every observed failure."}},
 {heading:"Specification and verification",paragraphs:["Write a packaging specification covering material, grade, dimensions, seal, closure, count, print, tolerances, carton strength and pallet arrangement where relevant. Approve suppliers against samples and incoming checks.","Use appropriate trials such as seal inspection, leakage check, drop or compression assessment and real distribution pilots. Formal testing should be performed by competent facilities where required."]}
],["Packaging is protection, information, handling and presentation.","The export route determines the hazard profile.","A written specification enables consistent purchasing and inspection."],["Which route hazard is most likely to damage your product?","What simple test can you run before a paid pilot?"]),

lesson("m05-l02","A label identifies the product, communicates safe and lawful use, supports traceability and helps the buyer manage it. Destination requirements must be verified before artwork is printed.",["Build a label-information checklist.","Treat nutrition and claims responsibly.","Explain barcode purpose and limits."],[
 {heading:"Core label information",paragraphs:["Depending on product and market, a label may require product name, net quantity, ingredients, allergen information, manufacturer or responsible business, country of origin, batch or lot, production and expiry or best-before dates, storage, instructions, warnings and language requirements.","The exact list is not universal. Check current official destination rules, product standards and buyer specifications. Mandatory information must remain legible, durable and correctly placed on the actual pack size."],points:["Identity","Quantity","Composition and allergens","Responsible party","Dates and storage","Lot traceability","Instructions and warnings","Origin and required language"]},
 {heading:"Nutrition and commercial claims",paragraphs:["Nutrition information should use the required format and a defensible data source, such as appropriate analysis or permitted calculation. Serving sizes, units and rounding must follow applicable rules.","Claims such as organic, natural, fortified, medicinal, sugar-free or environmentally friendly can trigger evidence and regulatory requirements. Marketing language must never overstate certification, health effect or origin."],example:{title:"Artwork control",body:"Create a legal-content checklist first, then design. Have technical and commercial reviewers approve the final print proof and retain the signed version."}},
 {heading:"Barcodes",paragraphs:["A barcode supports product identification, scanning and inventory processes. It does not prove product quality, regulatory approval or authenticity by itself. Use authorised numbering arrangements and assign a distinct identifier when required by pack or product variation.","Test printed codes on production material for size, contrast, quiet zones, placement and scan reliability. Master cartons and logistics units may require different identification from retail units."]}
],["Label content is product-and-destination specific.","Claims require evidence and careful approval.","Barcodes identify items; they do not certify them."],["Which label field needs official confirmation?","Which current claim on your pack lacks evidence?"]),

lesson("m05-l03","Shelf life is the period during which a product remains safe and meets defined quality under stated storage conditions. It must be supported by evidence that reflects formulation, process, packaging and distribution.",["Explain factors affecting shelf life.","Plan shelf-life evidence.","Control storage and stock rotation."],[
 {heading:"What determines shelf life",paragraphs:["Product composition, water activity, acidity, processing, hygiene, packaging barrier, seal integrity, light, oxygen, temperature and handling can influence safety and quality. A date copied from another product is not evidence.","Define acceptance criteria such as microbiological safety, texture, colour, aroma, nutrient or chemical limits and packaging integrity. The relevant criteria depend on the product and applicable standard."],points:["Product formulation","Validated process","Hygienic control","Packaging and seal","Storage condition","Distribution stress","Defined acceptance limits"]},
 {heading:"Establishing and monitoring",paragraphs:["Develop a study with competent technical support. Use representative production batches and packaging, stated storage conditions, planned intervals and suitable tests. Accelerated studies can support development but may not replace real-time evidence where behaviour differs.","Record batch, sample, condition, date, method and result. Investigate trends and failures. Reassess when ingredients, process, pack, supplier or route changes materially."],example:{title:"Commercial reality",body:"The remaining shelf life on buyer receipt—not only total life from production—must satisfy transit, customs, warehousing, distribution and the buyer's minimum requirement."}},
 {heading:"Storage and dispatch",paragraphs:["State storage conditions clearly and maintain them. Use first-expiry-first-out where expiry is relevant, monitor temperatures where required and segregate damaged or suspect stock.","Include production scheduling and border contingency in the shipment decision. Do not send goods whose remaining life is commercially or safely inadequate."]}
],["Shelf life is evidence-based and condition-specific.","Changes to product or packaging can invalidate prior evidence.","Buyer receipt life is a key commercial measure."],["What quality characteristic will fail first?","How much shelf life remains after a realistic delayed journey?"]),

lesson("m05-l04","Branding communicates a credible promise to a defined buyer, while a packaging audit tests whether protection, information, presentation and cost support that promise.",["Position a product for a defined segment.","Audit packaging systematically.","Prioritise improvements using risk and value."],[
 {heading:"Brand position",paragraphs:["Define the customer, need, competitive frame, benefit and evidence. The name, visual identity, tone, pack format and claims should reinforce the same position. Cultural and language checks reduce misunderstanding in the destination market.","A brand promise must match delivery. Premium graphics cannot compensate for leaking seals, inconsistent colour or late supply. Trust grows through product integrity and responsive service."],example:{title:"Positioning statement",body:"For [segment] who needs [job], [brand/product] provides [benefit] because [credible evidence], unlike [alternative]."}},
 {heading:"Packaging audit",paragraphs:["Review product-pack compatibility, barrier and seal, handling strength, tamper evidence, legal information, traceability, barcode, readability, accessibility, shelf impact, outer-carton markings, sustainability and total cost.","Inspect real filled packs and transport units rather than only artwork files. Ask production, warehouse, logistics, buyer and customer representatives because each sees different failures."],points:["Critical safety or compliance failure","High damage or shelf-life risk","Buyer acceptance barrier","Efficiency or cost opportunity","Appearance improvement"]},
 {heading:"Improvement plan",paragraphs:["Rank actions by severity and feasibility. Prototype, test and approve before full print or production. Control obsolete artwork and materials so old and new versions are not mixed.","Measure damage rate, complaints, scan success, packing speed, freight utilisation and customer response after change. Improvement must be demonstrated, not assumed."]}
],["Brand is a delivered promise, not a logo alone.","Audit the complete pack system using real samples.","Test changes before scale and measure results."],["What does your present pack promise and does performance support it?","Which improvement removes the largest commercial risk?"]),

lesson("m06-l01","Value addition increases usefulness, convenience, quality, shelf life, presentation or marketability for a defined customer. Processing is worthwhile only when the added customer value exceeds its added cost and risk.",["Distinguish value addition from extra processing.","Quantify customer and business value.","Screen commercially viable opportunities."],[
 {heading:"Customer value first",paragraphs:["Cleaning, grading, cutting, milling, drying, blending, cooking, portioning, fortifying, preserving or packaging may create value. The correct choice depends on what the customer is willing to pay for: convenience, consistency, safety, reduced waste, faster preparation or better storage.","Processing that customers do not value can increase equipment, energy, labour, compliance and packaging cost without improving price or demand. Define the job being solved before selecting technology."]},
 {heading:"Commercial value equation",paragraphs:["Estimate yield, input cost, conversion cost, packaging, losses, quality control, distribution and achievable price. Compare contribution and cash cycle with the unprocessed alternative. Include use or disposal of by-products.","Value addition may open a new segment or extend seasonal availability, but it can also introduce new hazards, standards and skills. Evaluate both revenue and responsibility."],example:{title:"Decision question",body:"Will the chosen process create a benefit the target buyer recognises, at a quality and price the business can supply repeatedly and profitably?"}},
 {heading:"Opportunity screening",paragraphs:["Research buyer format, specification, order quantity, shelf life and certification needs. Produce a small controlled sample, gather structured feedback and calculate real yield rather than laboratory estimates alone.","Proceed only with a defined specification, process, market and financial case."]}
],["Value addition is defined by customer utility.","Conversion costs and yields determine commercial viability.","New processes introduce new controls."],["Which customer problem does your proposed process solve?","What yield or price assumption needs a trial?"]),

lesson("m06-l02","A process-flow map makes production visible from receipt of inputs to release of finished product. It identifies where specifications, hazards, losses and records must be controlled.",["Map the complete production flow.","Define inputs, outputs and controls at each step.","Locate quality checkpoints and rework rules."],[
 {heading:"Build the flow",paragraphs:["Observe the real operation and list receipt, inspection, storage, preparation, processing, cooling or drying, in-process checks, packaging, labelling, finished storage and dispatch. Include water, utilities, rework, waste and by-products.","Use arrows and decision points. Record movement of people and materials where cross-contamination or mix-up is possible. A desk procedure that differs from practice cannot control production."]},
 {heading:"Step specification",paragraphs:["For every step, state purpose, responsible role, equipment, input requirement, operating parameter, output, quality check, record and action when limits are missed. Parameters might include time, temperature, weight, moisture, particle size or seal condition.","Define lot identity through the flow so finished units can be linked to inputs and records."],example:{title:"Checkpoint",body:"At receiving: verify supplier, lot, quantity, condition and acceptance criteria; quarantine failed inputs and record the disposition."}},
 {heading:"Control losses and variation",paragraphs:["Measure yield at meaningful stages. Unexpected loss can indicate spillage, over-processing, inaccurate measurement, theft or unrecorded rework. Variation affects cost and customer consistency.","Review the map after changes in product, equipment, layout or volume, and train operators on the current approved version."]}
],["Map actual work, including waste and rework.","Every critical step needs parameters, records and corrective action.","Yield reveals operational and financial performance."],["Draw your flow and mark three decision points.","Where can lot identity or product integrity be lost?"]),

lesson("m06-l03","Equipment should be selected for the required process and volume, not for impressive capacity claims. Total ownership includes utilities, safety, maintenance, skills and support.",["Create a user requirement specification.","Compare equipment on lifetime factors.","Plan installation, safety and maintenance."],[
 {heading:"Start with requirements",paragraphs:["Define product properties, required output, batch or continuous operation, quality tolerance, food-contact material, cleaning method, available space, utilities and expected growth. State the normal capacity needed rather than only a future ambition.","Capacity must be evaluated at the actual product, operating conditions and quality target. Nameplate capacity may exclude loading, cleaning, changeover and downtime."]},
 {heading:"Evaluate total ownership",paragraphs:["Compare purchase, delivery, duty, installation, power, water, consumables, labour, yield, maintenance, calibration, spare parts and expected life. Check local technical support and references using similar products.","Assess guarding, emergency stops, heat, pressure, electrical protection, ergonomics, cleanability and contamination risks. Unsafe or uncleanable equipment is not a bargain."],points:["Fit to process and specification","Sustainable output","Utilities and environment","Operator competence","Cleaning and food-contact design","Safety","Maintenance and spare parts","Total cost"]},
 {heading:"Commission and maintain",paragraphs:["Agree acceptance tests, documentation, training, warranty and spares before purchase. Installation qualification should confirm utilities, layout and safety; operational trials should confirm controls; performance trials should confirm product and output.","Use preventive maintenance and calibration schedules. Record breakdowns and analyse recurring causes."],example:{title:"Comparison sheet",body:"Score two options against mandatory requirements first, then weighted commercial criteria. Reject any option that fails a safety or product-contact requirement."}}
],["A requirement specification comes before supplier selection.","Useful capacity differs from nameplate capacity.","Ownership cost and support matter throughout equipment life."],["Which mandatory requirement would disqualify equipment?","What hidden operating cost is currently unmeasured?"]),

lesson("m06-l04","Production planning converts an order into feasible inputs, batches, people, equipment, quality checks and delivery dates. It protects customer service without exhausting cash or capacity.",["Translate demand into a production plan.","Calculate material and capacity needs.","Build contingencies and release controls."],[
 {heading:"Plan from the delivery date backwards",paragraphs:["Confirm specification, quantity, pack, release tests and dispatch date. Schedule finished-product release, packaging, processing, preparation, input receipt and procurement backwards, including realistic queues and approval time.","Account for existing orders, maintenance, public holidays, supplier lead times and transport cut-offs. A promised date should come from the plan, not sales optimism."]},
 {heading:"Materials and capacity",paragraphs:["Use bill-of-material quantities adjusted for yield, process loss and safety stock. Verify shelf life and storage capacity before buying. Convert order quantity into batches and labour or machine hours using demonstrated rates.","Identify the bottleneck and level the schedule around it. Excess upstream production can create waiting, deterioration and work-in-progress rather than faster delivery."],example:{title:"Order calculation",body:"Required input = good finished quantity divided by expected yield, then adjusted for approved contingency. Review whether the cash and storage implications remain acceptable."}},
 {heading:"Execution and control",paragraphs:["Issue controlled batch instructions and materials, record actual output and losses, and hold product until required checks are accepted. Define who can release, reject or authorise rework.","Track plan versus actual daily. Use contingency for supplier delay, breakdown or failed test, communicate material risks early and update the buyer through the responsible channel."]}
],["Plan backwards from verified delivery requirements.","Yield and bottlenecks control material and capacity needs.","Only authorised, accepted product should be released."],["What is the bottleneck in your order plan?","Which delay needs a pre-agreed contingency?"]),

lesson("m07-l01","Food safety prevents unacceptable biological, chemical and physical hazards during intended use. Hygiene controls people, practices and facilities so hazards are not introduced or allowed to grow.",["Recognise three hazard categories.","Apply personal and facility hygiene controls.","Report illness and contamination risks."],[
 {heading:"Food hazards",paragraphs:["Biological hazards include harmful microorganisms and pests. Chemical hazards include cleaning residues, pesticides, allergens or toxins. Physical hazards include glass, metal, stones, hard plastic or other foreign material. The relevant hazards depend on product, process and consumer.","Risk considers likelihood and severity. Controls should be preventive and based on a product-specific assessment rather than a generic cleanliness claim."]},
 {heading:"Personal hygiene",paragraphs:["Control handwashing, protective clothing, hair restraint, jewellery, wounds, illness reporting, eating, drinking and visitor behaviour. Training must explain why the rules exist and supervisors must reinforce them consistently.","Food handlers should report symptoms or conditions that could contaminate food. Management needs a lawful, confidential process for restriction and return to work."],points:["Clean hands at required moments","Suitable protective clothing","Controlled personal items","Covered wounds","Illness reporting","Authorised movement and visitors"]},
 {heading:"Factory hygiene",paragraphs:["Design cleaning schedules stating what, how, chemical, concentration, contact time, frequency, responsible person, verification and record. Separate raw and ready areas where required and control water, waste, drainage, ventilation and pests.","Cleaning removes soil; disinfection reduces microorganisms when properly applied. Neither compensates for poor layout or uncontrolled cross-contamination."],example:{title:"Hazard walk",body:"Follow the product route and record every point where people, surfaces, air, water, chemicals or foreign objects can contaminate it."}}
],["Food safety addresses specific hazards, not appearance alone.","Personal hygiene requires systems and supervision.","Cleaning must be specified, recorded and verified."],["Name one hazard from each category in your process.","Which hygiene control is most frequently bypassed?"]),

lesson("m07-l02","Good Manufacturing Practices are the foundational conditions required for controlled production. They cover premises, people, equipment, materials, sanitation, pests, storage and records.",["Assess core GMP areas.","Control materials and process status.","Use records as evidence of consistent practice."],[
 {heading:"GMP foundation",paragraphs:["Premises should support hygienic flow, maintenance, lighting, ventilation, drainage and controlled access. Equipment should be suitable, cleanable, maintained and calibrated where measurement matters. People need competence, hygiene and defined responsibilities.","Supplier approval, receiving inspection and stock status prevent unsuitable materials from entering production. Identify accepted, quarantined, rejected and released items physically and in records."]},
 {heading:"Sanitation, pests and storage",paragraphs:["Sanitation programmes, waste removal and pest prevention must avoid contaminating product. Use competent pest control, inspect trends and close structural entry points rather than relying only on chemicals.","Storage protects identity, condition and traceability. Control temperature or humidity where needed, separate chemicals and allergens, prevent floor or wall contact as appropriate and rotate stock using FIFO or FEFO."],example:{title:"GMP evidence",body:"A clean room during an announced visit is not sufficient. Review completed records, trends, corrective actions and ordinary working practice."}},
 {heading:"Gap closure",paragraphs:["Use a checklist suited to the facility and product. Classify findings by food-safety significance, assign corrective action, owner and due date, and verify effectiveness after completion.","GMP is continuous operational discipline and normally precedes more advanced hazard-control systems."]}
],["GMP establishes controlled production conditions.","Material status and storage protect product integrity.","Corrective actions require effectiveness checks."],["Which GMP gap has the highest safety impact?","What record would demonstrate daily control?"]),

lesson("m07-l03","HACCP uses structured logic to identify significant hazards, establish controls, monitor them and respond when control is lost. This lesson is introductory and does not represent formal certification.",["Describe HACCP logic.","Distinguish hazard, control and critical limit.","Plan monitoring and corrective action."],[
 {heading:"Prepare the analysis",paragraphs:["Define the product, ingredients, process, packaging, storage, distribution, intended use and vulnerable consumers. Assemble people who understand production, maintenance, quality and the product. Verify the process flow on site.","At every step, identify reasonably expected biological, chemical and physical hazards, their cause, severity and likelihood, and existing preventive controls."]},
 {heading:"Control points and limits",paragraphs:["Determine which significant hazards require control at a critical point or through another prerequisite programme. A critical limit separates acceptable from unacceptable operation and should be measurable or observable using a valid basis.","Monitoring must state what is checked, method, frequency, person and record. It should detect loss of control in time to isolate affected product."],example:{title:"Do not guess",body:"Time, temperature, pH or other critical limits require a scientific, regulatory or validated basis appropriate to the product and process."}},
 {heading:"Deviation, verification and records",paragraphs:["Corrective action restores control, identifies and controls affected product, investigates cause and prevents recurrence. Product disposition must be authorised and evidence-based.","Verification confirms the system is followed and effective through record review, calibration, observation, testing or validation as appropriate. Keep clear records and reassess after significant change."]}
],["HACCP builds on functioning prerequisite programmes.","Critical limits need a valid basis.","Corrective action includes product control and root cause."],["Which step controls your most significant hazard?","How would you identify all product affected by a deviation?"]),

lesson("m07-l04","Storage and traceability preserve released product and make it possible to identify affected lots quickly. Effective systems trace one step back, through production and one step forward.",["Apply FIFO and FEFO correctly.","Design lot identification and trace records.","Conduct recall and corrective-action exercises."],[
 {heading:"Storage controls",paragraphs:["Set conditions for temperature, humidity, light, cleanliness, stacking, segregation and security based on product needs. Monitor required conditions with suitable devices and respond to excursions.","FIFO dispatches oldest receipt or production first; FEFO dispatches the earliest expiry first and is often more appropriate for dated foods. Damaged, returned, quarantined and recalled products require clear separation and status."],points:["Condition limits","Monitoring and review","Stock rotation","Pest and damage checks","Status segregation","Inventory accuracy"]},
 {heading:"Traceability system",paragraphs:["Assign meaningful lot codes and record suppliers and input lots, production date and line or batch, process and release records, packaging lots, finished quantities, customers, shipment references and dates.","The system should answer: which inputs made this finished lot, which other lots used the same input, where is stock now, and which customers received it?"],example:{title:"Mass balance",body:"Account for the quantity received, used, wasted, held and dispatched. Large unexplained differences weaken traceability."}},
 {heading:"Recall and learning",paragraphs:["Create a recall procedure with decision authority, contact lists, notification, product isolation, retrieval, reconciliation, investigation and closure. Test it with a mock recall and measure time and percentage traced.","Complaints, deviations and mock recalls should lead to root-cause analysis and corrective and preventive action. Verify that the action works rather than closing it when a form is signed."]}
],["FEFO manages expiry risk better where dates differ.","Traceability connects inputs, production and customers.","Mock recalls test whether records work under pressure."],["Can you trace one lot to every customer within four hours?","What mass-balance difference would trigger investigation?"])
] as const;
