import type { AcademyLessonContent } from "./lesson-content";

const lesson=(lessonId:string,introduction:string,objectives:readonly string[],sections:AcademyLessonContent["sections"],keyTakeaways:readonly string[],reflection:readonly string[]):AcademyLessonContent=>({lessonId,introduction,objectives,sections,keyTakeaways,reflection});

export const ACADEMY_CONTENT_2_4:readonly AcademyLessonContent[]=[
lesson("m02-l01","An attractive product is not automatically exportable. Exportability is the combined ability of the product and the business behind it to satisfy a defined foreign customer repeatedly, lawfully and profitably.",["Apply the seven exportability tests.","Separate product appeal from commercial readiness.","Identify evidence needed before selecting a product."],[
 {heading:"The seven tests",paragraphs:["Test demand first: identify who buys, why they buy, expected quantity and evidence that demand is more than an assumption. Test quality against the buyer's written specification rather than the producer's personal opinion. Test supply reliability by checking raw materials, production capacity, seasonality, lead time and contingency arrangements.","Then test price and landed competitiveness, packaging fitness, regulatory compliance and differentiation. A product can pass six tests and still fail commercially because the seventh is critical. For example, strong demand does not rescue a food product whose shelf life is shorter than its transport and distribution cycle."],points:["Demand","Quality and consistency","Supply reliability","Competitive landed price","Protective and informative packaging","Product-and-market compliance","Meaningful differentiation"]},
 {heading:"Evidence before enthusiasm",paragraphs:["Replace statements such as 'everyone likes it' with observable evidence: customer interviews, distributor enquiries, repeat domestic sales, competitor listings, test orders, current quotations and official requirements. Record the date and source because markets and regulations change.","A product should also fit the firm's resources. Exporting a complex chilled product may be less realistic than a stable processed format when the business lacks cold-chain control. Product selection is therefore a strategic choice about customer value and execution capability."],example:{title:"Exportability score",body:"Score every test from 1 to 5, cite evidence, and mark any mandatory failure. A high average must not override an unmet legal or safety requirement."}},
 {heading:"Decision and improvement",paragraphs:["Choose one of three decisions: proceed to market validation, improve before testing, or reject for now. For every weak area, specify an action, owner, cost and deadline. Reassess after improvements rather than treating the first score as permanent.","Do not confuse a prototype with a repeatable commercial product. Buyers evaluate whether the same specification, pack and quantity can arrive on time across multiple orders."]}
],["Exportability belongs to the product-business-market combination.","Mandatory compliance or safety failures cannot be averaged away.","Selection decisions should cite current evidence."],["Which test is weakest for your product and what evidence proves it?","What lower-risk product format could improve exportability?"]),

lesson("m02-l02","Product-market fit connects a specific offer to a specific customer's need in a specific market. Broad descriptions hide the decisions required for packaging, pricing, channel and promotion.",["Define a priority customer and need.","Write a testable product-market-fit statement.","Adapt the offer to buyer and channel requirements."],[
 {heading:"Define the customer precisely",paragraphs:["A country is not a customer. Identify whether the decision-maker is a consumer, retailer, wholesaler, distributor, manufacturer, hotel, restaurant or institution. Describe location, purchasing frequency, order size, quality expectations, price sensitivity and the problem being solved.","Different actors may influence the purchase. A distributor wants margin and dependable replenishment; a retailer also considers shelf dimensions, barcode and consumer demand; an institutional buyer may require tenders, service levels and credit terms."]},
 {heading:"Connect need, format and benefit",paragraphs:["State the product format, the customer, the relevant need and the credible benefit. A useful hypothesis is: 'For [customer] in [market] who needs [job], our [format] provides [benefit], supported by [evidence].' Avoid unsupported superlatives such as best, premium or healthiest.","Product-market fit can change pack size, formulation, labelling, minimum order and service. The best format for household retail may be uneconomic for food-service buyers. Fit is demonstrated when customers buy, use, reorder and accept the delivered value."],example:{title:"Testable statement",body:"For independent Ghanaian restaurants needing consistent preparation time, our sealed 10 kg processed ingredient pack provides measured portions and dependable weekly supply, supported by a paid pilot."}},
 {heading:"Validate rather than assume",paragraphs:["Interview real buyers, show the actual pack, test price and minimum quantities, and ask what would prevent purchase. A compliment is not validation; paid trials, written specifications and repeat orders are stronger signals.","Record objections without defending the product. Objections reveal whether to change the offer, target a different segment or discontinue the hypothesis."]}
],["Product-market fit is specific and testable.","Buyer type determines commercial and packaging requirements.","Paid behaviour is stronger evidence than praise."],["Write your one-sentence fit hypothesis.","What behaviour would prove or disprove it?"]),

lesson("m02-l03","Market research reduces uncertainty by separating facts, informed estimates and assumptions. Competitor analysis then shows what standard the exporter must meet and where a defensible advantage may exist.",["Plan primary and secondary research.","Compare competitors consistently.","Turn findings into commercial decisions."],[
 {heading:"Research questions and sources",paragraphs:["Research demand, customer segments, prices, competitors, routes to market, regulation, culture, seasonality and logistics. Start with a decision: for example, whether to test Ghana or Kenya first. Collect only information that improves that decision.","Secondary sources include official statistics, customs or trade data, regulator guidance, retailer listings, industry reports and marketplace observations. Primary research includes buyer interviews, store visits, distributor calls, trade events, samples and pilots. Verify important claims with more than one credible source."],points:["Question being decided","Source and publication date","Fact, estimate or assumption","Implication for the offer","Further evidence required"]},
 {heading:"Competitor comparison",paragraphs:["Compare like with like: product specification, pack size, retail or wholesale price, quality cues, certifications, availability, lead time, channel coverage, reviews and service. Convert prices to comparable units and note whether taxes and delivery are included.","Direct competitors solve the same need with a similar product; indirect competitors solve the need differently. An exporter who ignores substitutes may overestimate demand. The objective is not to copy competitors but to understand the customer's alternatives."],example:{title:"Comparison discipline",body:"Compare three named offers in the same channel using one date and currency. Photograph or save evidence where lawful and record anything that cannot be verified."}},
 {heading:"Insight to action",paragraphs:["Summarise what must change in product, pack, price, proof or channel. A useful insight connects evidence to action: 'Retail packs cluster below our landed cost; test food-service bulk packs with restaurants instead.'", "Research should end with a decision and a low-cost market test, not an impressive report with no owner or deadline."]}
],["Research begins with a decision question.","Competitors and substitutes define the real choice facing buyers.","Every important insight should change or validate an action."],["Which three sources will you use and why are they credible?","What advantage can competitors not easily copy?"]),

lesson("m02-l04","Market screening compares opportunities on the same criteria, while an entry plan turns the preferred market into a controlled experiment with customers, channels, costs and milestones.",["Rank markets objectively.","Choose an entry route appropriate to resources.","Build a measurable market-entry test."],[
 {heading:"Screen candidate markets",paragraphs:["Compare demand evidence, customer access, competition, regulation, cultural fit, logistics, landed cost, payment conditions and currency exposure. Apply weights based on the product: shelf life and transit reliability deserve more weight for perishable goods than for digital services.","Use both opportunity and feasibility. A high-demand market may rank poorly if certification takes too long or the landed price is uncompetitive. Record assumptions and conduct sensitivity checks for freight, exchange rate and volume."],points:["Demand and purchasing power","Buyer accessibility","Competitive intensity","Compliance effort","Logistics and shelf-life fit","Landed-cost margin","Payment and country risk"]},
 {heading:"Entry routes",paragraphs:["Possible routes include direct sales, distributor or agent relationships, retail supply, institutional procurement, e-commerce, partnership or a controlled pilot. Each route changes margin, market control, local support, inventory position and credit exposure.","Distributors can provide reach but require due diligence, clear territory, targets, reporting and termination arrangements. Direct selling offers control but demands stronger internal sales and fulfilment capability."]},
 {heading:"The entry plan",paragraphs:["Define the target segment, offer, evidence, entry route, initial geography, pilot quantity, pricing basis, budget, responsibilities and success measures. Include compliance and logistics tasks before promotional activity.","Set review points. A 90-day test might aim for ten verified buyer conversations, three samples, one paid order and a measured reorder decision. Stop, adjust or scale based on evidence."],example:{title:"Risk-limited entry",body:"Start with one city, one customer segment and one pack format. Use a small paid shipment to validate documents, transit, product integrity, landed cost and buyer acceptance."}}
],["Screen markets with consistent weighted evidence.","Entry route determines control, cost and risk.","Start with measurable tests before scaling."],["Rank three markets and explain your weighting.","What result would justify a larger second shipment?"]),

lesson("m03-l01","Export readiness is the ability to meet an opportunity's operational, commercial, financial, regulatory and market requirements. It begins with a business that can be identified, governed and trusted.",["Assess business identity and governance.","Calculate realistic capacity.","Identify evidence buyers may request."],[
 {heading:"Business readiness",paragraphs:["A ready business has a verifiable legal identity, ownership and contact details, defined responsibilities, basic contracts and dependable records. Buyers and finance providers need to know who can commit the company and whether information is consistent across applications, invoices and bank records.","Governance should cover approval of prices, credit, purchasing, quality release and payments. Even a small enterprise benefits from separation of duties and documented decisions because export transactions create larger exposures."]},
 {heading:"Production readiness",paragraphs:["Capacity is the repeatable output that meets specification within available time—not the highest quantity ever produced. Calculate usable equipment time, labour, yields, planned maintenance, quality losses and existing orders. Identify the bottleneck that limits the whole process.","Supply reliability includes approved inputs, alternative suppliers, production instructions, quality checkpoints, storage and contingency. A buyer's order is not the time to discover that a key input is seasonal or a machine has no local spare part."],example:{title:"Capacity evidence",body:"Show normal output per shift, yield, current committed capacity, maximum sustainable output and the lead time required for the proposed order."}},
 {heading:"Buyer-facing evidence",paragraphs:["Prepare a truthful business profile, product specification, photographs, capacity statement, lead time, pricing basis, quality records and applicable registrations or certifications. Never claim certification that is pending or outside its scope.","Readiness is opportunity-specific. The same business may be ready for a small regional trial and unready for a national supermarket contract."]}
],["Readiness is the ability to execute, not enthusiasm.","Capacity must be sustainable and specification-compliant.","Buyer evidence must be consistent and verifiable."],["What is your true production bottleneck?","Which business record would a buyer struggle to verify today?"]),

lesson("m03-l02","Financial and regulatory readiness determine whether a business can fund the transaction and lawfully place the product in the destination market.",["Calculate the transaction cash gap.","Identify product-and-destination regulatory checks.","Distinguish registration from transaction approval."],[
 {heading:"Working-capital readiness",paragraphs:["Map when cash leaves for inputs, labour, packaging, testing, inland transport, documents, freight and insurance, and when customer funds become usable. The maximum cumulative deficit is the working-capital need. Add contingency rather than assuming perfect timing.","A profitable quotation can still cause insolvency if the exporter pays all costs months before settlement. Test the effect of delayed payment, exchange-rate movement, rejected quantities and higher freight."],example:{title:"Cash-cycle test",body:"Prepare a weekly timeline from purchase of inputs through collection of payment. State which costs are covered by deposit, internal cash or finance."}},
 {heading:"Regulatory pathway",paragraphs:["Requirements depend on the product, origin, destination, use and channel. Identify the competent authorities and verify current official rules for business registration, exporter status, food or product controls, labelling, testing, permits and destination entry.","A company registration proves identity but does not by itself approve every product. A laboratory report may support one batch or specification but not a broad certification claim. Record scope, issuer, issue date and expiry."],points:["Product classification","Origin and destination","Required registrations or permits","Standards and tests","Label and language rules","Import-side responsibility","Evidence and validity period"]},
 {heading:"Readiness controls",paragraphs:["Create a compliance register with owner, source link, required evidence, status and renewal date. Obtain professional or official confirmation for high-risk requirements.","Do not price or promise a delivery date until the cost and lead time of mandatory steps are known."]}
],["Profit and cash timing are different.","Regulatory readiness is product-and-destination specific.","Evidence has scope and validity limits."],["What is the largest cash deficit in your transaction timeline?","Which requirement needs official verification before quotation?"]),

lesson("m03-l03","The five-pillar scorecard creates a disciplined view of business, product, finance, compliance and market readiness. Its purpose is action, not a flattering percentage.",["Score five readiness pillars with evidence.","Apply mandatory-failure logic.","Prioritise gaps by transaction risk."],[
 {heading:"Five pillars",paragraphs:["Business readiness covers identity, governance, people and records. Product and production readiness covers specification, quality, supply, capacity and packaging. Financial readiness covers costing, margin, cash flow and funding. Compliance readiness covers applicable requirements and evidence. Market readiness covers demand, buyers, channels, competition and entry planning.","Score each criterion using defined anchors such as 0 for absent, 1 for informal, 2 for documented but incomplete and 3 for verified and operational. Attach evidence so another reviewer can reach a similar result."]},
 {heading:"Mandatory gates and risk",paragraphs:["Some deficiencies must override the average. A missing legal permission, unsafe product, unknown shelf life or inability to meet the specification cannot be balanced by strong marketing. Mark these as gates and stop the transaction until resolved.","Rank gaps by severity, probability, time to close, cost and dependency. A low score in a nonessential branding detail may be less urgent than an uncertain raw-material supply despite similar numeric scores."],example:{title:"Evidence-based scoring",body:"Do not award points for 'we can obtain it.' Award points for current documents, tested processes, records or independently verifiable results."}},
 {heading:"Use the score commercially",paragraphs:["Connect the scorecard to the exact opportunity and refresh it when the product, market or order size changes. Share an honest summary with mentors or responsible staff, not confidential answer keys or unsupported claims.","The outcome should state ready for pilot, ready with conditions, improvement required, or unsuitable at present."]}
],["Five pillars prevent narrow readiness decisions.","Mandatory gates override averages.","Scores require evidence and an opportunity context."],["Which pillar is weakest and which gate is open?","What evidence would move one criterion up a level?"]),

lesson("m03-l04","A readiness assessment becomes valuable only when gaps are converted into owned, measurable work. The 30-day plan focuses limited resources on the changes required for the next commercial milestone.",["Write specific readiness actions.","Assign owners, evidence and deadlines.","Prepare a credible export business profile."],[
 {heading:"From gap to action",paragraphs:["Replace vague actions such as 'improve packaging' with measurable commitments: obtain two transport-pack samples, conduct a drop and moisture review, select one by a date, and save the specification and supplier quotation. Every action needs an owner and completion evidence.","Sequence dependencies. Product specifications may be needed before label design; verified destination rules may be needed before printing; costing may depend on the final pack dimensions."]},
 {heading:"Thirty-day rhythm",paragraphs:["Week one confirms requirements and baseline evidence. Week two develops or obtains solutions. Week three tests and corrects them. Week four verifies completion, updates records and decides whether the business is ready for the next pilot.","Hold short weekly reviews using red, amber and green status. Escalate blocked mandatory items immediately rather than waiting until day thirty."],points:["Gap and associated risk","Action and responsible owner","Budget or resource","Due date","Completion evidence","Dependency and status"]},
 {heading:"Export business profile",paragraphs:["Build a concise profile containing legal identity, leadership, product and customer, capacity, quality controls, applicable evidence, target market, commercial terms and contact information. Keep claims factual and consistent with uploaded records.","End the plan with a decision meeting: proceed, proceed conditionally, extend remediation or stop. Document why."],example:{title:"Useful completion evidence",body:"A signed specification, verified regulator guidance, test result, approved costing sheet or completed buyer interview is evidence; 'discussed with the team' is not."}}
],["Actions must be specific, owned, dated and evidenced.","Dependencies determine the correct order of improvement.","The final decision should be explicit and recorded."],["Write the highest-priority action in measurable form.","What evidence will prove the business is ready for a pilot?"]),

lesson("m04-l01","Documentation begins with a consistent business identity and a verified regulatory pathway. Requirements must be checked against the current product, origin, destination and transaction.",["Maintain consistent legal and tax identity.","Build a product-specific document pathway.","Verify issuing authorities and validity."],[
 {heading:"Identity records",paragraphs:["Business registration, tax identification, bank details and exporter records establish who is trading. Names, addresses and registration numbers should match across profiles, contracts and invoices. Variations can delay banking, customs or buyer checks.","Know who is authorised to sign and which records must remain private. Share documents through controlled channels and redact unnecessary personal data where appropriate."]},
 {heading:"Agency and product requirements",paragraphs:["Identify origin-side and destination-side authorities. Requirements may involve export registration, product registration, sanitary or phytosanitary controls, conformity assessment, testing, inspection, licences or permits.","Use official current sources and record the precise product scope. Do not assume a permit for one product, facility, market or year covers another."],points:["Requirement","Authority and official source","Applicant or responsible party","Lead time and cost","Document produced","Validity and renewal"]},
 {heading:"Compliance checklist",paragraphs:["Create the checklist before quotation so costs and timing are known. Assign every document to a responsible party and identify originals, copies, translations or endorsements required.","Recheck before shipment because regulations, schedules and buyer instructions can change."]}
],["Consistent identity prevents avoidable verification failures.","Document requirements are transaction-specific.","Current official sources are essential."],["Which identity field is inconsistent across your records?","Who confirms the destination import requirement?"]),

lesson("m04-l02","Invoices and packing lists describe the commercial deal and the physical shipment. Their information must agree because customs, banks, carriers and buyers use them for different but connected decisions.",["Distinguish proforma and commercial invoices.","Prepare a complete packing list.","Audit cross-document consistency."],[
 {heading:"Proforma invoice",paragraphs:["A proforma invoice is a preliminary statement of proposed terms. It commonly identifies seller and buyer, products, quantities, unit and total price, currency, delivery term and named place, payment terms, validity and expected lead time.","It supports negotiation, approvals or payment arrangements but should be clearly labelled and controlled by version. Changes accepted by the parties must flow into the final documents."]},
 {heading:"Commercial invoice",paragraphs:["The commercial invoice records the actual sale and supports customs valuation, payment and buyer accounting. It should reflect the shipped quantity and agreed terms, include a unique date and number, and use an adequate product description and codes where required.","Avoid ambiguous descriptions, mathematical errors, inconsistent currency, unexplained discounts or an Incoterm without the named place and version where applicable."],example:{title:"Term precision",body:"Write 'FCA Seller's Warehouse, Kaduna, Incoterms 2020' rather than only 'FCA'. The named place determines where delivery and risk transfer occur."}},
 {heading:"Packing list",paragraphs:["The packing list explains how goods are arranged: package numbers, type, contents, quantities, net and gross weights, dimensions and marks. It normally focuses on physical information rather than price.","Totals must reconcile with the invoice, transport booking and actual packages. Warehouse staff should produce or verify it from the packed shipment, not from an old template."]}
],["Proforma terms precede the final transaction; the commercial invoice records it.","Packing lists describe physical arrangement.","All documents must reconcile with reality and each other."],["Which fields must match across invoice and packing list?","Audit one sample for quantity, weight, currency and terms."]),

lesson("m04-l03","Origin and transport documents provide evidence about where goods originate and how they are carried. Their legal effect and issuer must be understood rather than guessed from the title.",["Explain certificates of origin.","Distinguish bills of lading and air waybills.","Identify issuer, holder and operational use."],[
 {heading:"Certificate of origin",paragraphs:["A certificate of origin supports a statement about the origin of goods for relevant customs or trade purposes. Preferential origin is governed by applicable rules and requires evidence; the country of dispatch is not automatically the country of origin.","Confirm the competent issuing or certifying process, product classification, origin criterion and supporting records. False origin claims can cause denial of preference, penalties or seizure."]},
 {heading:"Bill of lading",paragraphs:["A bill of lading is used in sea transport and commonly functions as a receipt for cargo, evidence of the contract of carriage and, in some forms, a document controlling delivery. The exact legal effect depends on its form and governing rules.","Check shipper, consignee, notify party, vessel, ports, description, package count, weight, freight status and release method. Corrections after issue can be costly and delay cargo."]},
 {heading:"Air waybill",paragraphs:["An air waybill records air carriage and shipment information but is generally non-negotiable. It identifies the parties, airports, routing, cargo and charges or handling information.","The exporter must give accurate instructions to the carrier or forwarder and review the draft. Transport documents should agree with invoice and packing data."],example:{title:"Responsibility map",body:"For each document, record who supplies data, who issues it, who checks it, who receives it and what event depends on it."}}
],["Origin must be proven under applicable rules.","Sea and air documents have different functions.","Draft transport documents require prompt factual review."],["What evidence supports your proposed origin claim?","Which transport fields can stop delivery if incorrect?"]),

lesson("m04-l04","Document control prevents small inconsistencies from becoming border, payment or delivery failures. A controlled shipment file gives every authorised party the correct version at the correct time.",["Apply version and approval controls.","Review insurance and customs evidence.","Run a pre-shipment consistency check."],[
 {heading:"Insurance and customs records",paragraphs:["Insurance documentation should identify the insured interest, voyage or period, covered risks, value, exclusions, claims procedure and certificate or policy reference. Do not assume a trade term or carrier liability provides adequate cargo protection.","Customs records depend on the jurisdiction and procedure. Data may include declaration reference, classification, value, origin, procedure code, licences and supporting documents. The trader remains responsible for truthful information even when an intermediary submits it."]},
 {heading:"Version control",paragraphs:["Use unique document numbers, dates, status such as draft or final, controlled templates and an approval record. Restrict editing after approval and retain a change log. Do not distribute files named 'final-final-2'.", "Maintain a shipment index showing required documents, owner, due date, version, recipient and transmission evidence. Protect sensitive identity and payment information."]},
 {heading:"Consistency review",paragraphs:["Before shipment, compare seller and buyer names, product descriptions, classification, quantities, package count, weights, values, currency, origin, dates, ports, delivery terms and references across the complete set and the physical cargo.","Resolve discrepancies before originals are issued or declarations submitted. After shipment, archive the final set with communications, approvals and proof of delivery according to policy."],example:{title:"Four-eye control",body:"The preparer performs a checklist review; a second authorised person independently compares the documents to the order and packed goods."}}
],["Document control is an operational risk control.","Intermediaries do not remove the trader's responsibility for accuracy.","Cross-document consistency must be checked before submission."],["Design a naming convention for one shipment.","Which ten fields will your four-eye review compare?"])
] as const;
