"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { COOKIE_CONSENT_NAME, newCookieConsent, parseCookieConsent, serializeCookieConsent, type CookieConsent } from "@/src/modules/privacy/domain/cookie-consent";
type Choices={preferences:boolean;analytics:boolean;advertising:boolean};
const rejected:Choices={preferences:false,analytics:false,advertising:false},accepted:Choices={preferences:true,analytics:true,advertising:true};
export default function CookieConsentCentre({initialValue}:{initialValue?:string}){
  const initial=parseCookieConsent(initialValue),[consent,setConsent]=useState<CookieConsent|undefined>(initial),[open,setOpen]=useState(!initial);
  useEffect(()=>{document.documentElement.classList.toggle("cookie-consent-pending",open&&!consent);return()=>document.documentElement.classList.remove("cookie-consent-pending")},[open,consent]);
  function save(next:Choices){const value=newCookieConsent(next);document.cookie=`${COOKIE_CONSENT_NAME}=${serializeCookieConsent(value)}; Path=/; Max-Age=31536000; SameSite=Lax${location.protocol==="https:"?"; Secure":""}`;setConsent(value);setOpen(false);window.dispatchEvent(new CustomEvent("pacsm:cookie-consent",{detail:value}))}
  return <><button className="privacy-settings-trigger" type="button" onClick={()=>setOpen(true)}>Privacy settings</button>{open&&<div className="cookie-consent-backdrop" role="presentation"><section className="cookie-consent-dialog" role="dialog" aria-modal="true" aria-labelledby="cookie-consent-title" aria-describedby="cookie-consent-description"><header><div className="cookie-consent-mark">PAC<span>SM</span></div><div><span>YOUR PRIVACY CHOICES</span><h2 id="cookie-consent-title">Privacy &amp; cookie settings</h2></div></header><p id="cookie-consent-description">We use cookies and similar technologies to provide our Service, give you the best experience, improve and advertise the Service, keep it safe and secure, and measure advertising campaign effectiveness.</p><p>If you select <strong>Accept All</strong>, you agree to PAC-SM and the partners we work with storing cookies and similar technologies on your device for advertising purposes. You can reject all non-essential cookies or choose which types to accept below.</p>
  <details className="cookie-customise"><summary>Customise cookies</summary><form method="post" action="/api/privacy/consent" className="cookie-preference-form"><input type="hidden" name="mode" value="custom"/><div className="cookie-preference-list"><article><div><strong>Strictly necessary</strong><p>Required for sign-in, security, checkout, regional settings and core marketplace functions.</p></div><span className="always-on">Always on</span></article>{([["preferences","Preferences"],["analytics","Analytics"],["advertising","Advertising"]] as const).map(([key,label])=><article key={key}><label htmlFor={`cookie-${key}`}><strong>{label}</strong><p>{key==="preferences"?"Remembers optional display and experience choices.":key==="analytics"?"Helps us understand usage and improve marketplace performance.":"Supports relevant promotions and campaign measurement with approved partners."}</p></label><input id={`cookie-${key}`} name={key} type="checkbox" value="on" defaultChecked={Boolean(initial?.[key])}/></article>)}</div><button className="cookie-primary" type="submit">Save my choices</button></form></details>
  <div className="cookie-policy-line">Change your choices at any time using Privacy settings. For details, read our <Link href="/cookies-policy">Cookies and Similar Technologies Policy</Link>.</div><footer><form method="post" action="/api/privacy/consent"><input type="hidden" name="mode" value="reject"/><button className="cookie-secondary" type="submit" onClick={()=>save(rejected)}>Reject all</button></form><form method="post" action="/api/privacy/consent"><input type="hidden" name="mode" value="accept"/><button className="cookie-primary" type="submit" onClick={()=>save(accepted)}>Accept all</button></form></footer></section></div>}</>;
}
