import Link from "next/link";
import { redirect } from "next/navigation";
import { Query } from "node-appwrite";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { findVendorByOwner } from "@/src/modules/vendors/server/repository";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { listSettlements } from "@/src/modules/finance/server/settlements";
export const dynamic = "force-dynamic";
const money = (value: number, currency: string) => new Intl.NumberFormat("en-NG", { style: "currency", currency }).format(value / 100);
export default async function SellerFinancePage() { const user = await getCurrentAppwriteUser(); if (!user) redirect("/login?returnTo=/seller/finance"); const vendor = await findVendorByOwner(user.$id); if (!vendor) redirect("/vendor/register"); const [lines, settlements] = await Promise.all([createAppwriteDatabaseClient().databases.listDocuments({ databaseId: env().APPWRITE_DATABASE_ID, collectionId: "journal_lines", queries: [Query.equal("vendorId", vendor.$id), Query.orderDesc("$createdAt"), Query.limit(500)] }), listSettlements(vendor.$id)]); const balances = new Map<string, number>(); for (const line of lines.documents) balances.set(String(line.currency), (balances.get(String(line.currency)) ?? 0) + (line.direction === "credit" ? Number(line.amountMinor) : -Number(line.amountMinor))); return <main className="seller-shell"><nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><Link href="/seller">Seller Centre</Link></nav><header><div><p className="kicker">SELLER FINANCE</p><h1>Payable balance</h1><p>Delivered sales less commission, refunds and completed payouts.</p></div></header><section className="seller-grid">{balances.size ? Array.from(balances).map(([currency, balance]) => <article key={currency}><span>{currency} PAYABLE</span><strong>{money(balance, currency)}</strong><p>Available for the next admin-approved settlement.</p></article>) : <article><span>PAYABLE</span><strong>No balance yet</strong><p>Revenue is recognised after successful delivery.</p></article>}</section><section className="review-table"><div className="review-row review-head"><span>Settlement</span><span>Date</span><span>Amount</span><span>Status</span></div>{settlements.documents.length ? settlements.documents.map(item => <div className="review-row" key={item.$id}><span>{String(item.settlementNumber)}</span><span>{new Date(String(item.createdAt)).toLocaleDateString("en-GB")}</span><strong>{money(Number(item.amountMinor), String(item.currency))}</strong><span>{String(item.status)}</span></div>) : <p className="empty-state">No payouts processed yet.</p>}</section><section className="review-table"><div className="review-row review-head"><span>Account</span><span>Direction</span><span>Amount</span><span>Currency</span></div>{lines.documents.map(line => <div className="review-row" key={line.$id}><span>{String(line.accountCode).replaceAll("_", " ")}</span><strong>{String(line.direction)}</strong><span>{money(Number(line.amountMinor), String(line.currency))}</span><span>{String(line.currency)}</span></div>)}</section></main>; }
