import "server-only"; import { ID, Query } from "node-appwrite"; import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server"; import { env } from "@/src/shared/config/env"; import type { CertificationReviewAction } from "@/src/modules/standards/domain/compliance";
const databaseId=()=>env().APPWRITE_DATABASE_ID,db=()=>createAppwriteDatabaseClient().databases;
export async function listStandards(filters:{categoryId?:string;countryCode?:string}={}){const queries=[Query.equal("status","active"),Query.orderDesc("updatedAt"),Query.limit(500)];if(filters.categoryId)queries.push(Query.equal("categoryId",filters.categoryId));if(filters.countryCode)queries.push(Query.equal("countryCode",filters.countryCode.toUpperCase()));return db().listDocuments({databaseId:databaseId(),collectionId:"product_standards",queries})}
export async function listPackagingRequirements(filters:{categoryId?:string;countryCode?:string}={}){const queries=[Query.equal("status","active"),Query.limit(500)];if(filters.categoryId)queries.push(Query.equal("categoryId",filters.categoryId));if(filters.countryCode)queries.push(Query.equal("destinationCountryCode",filters.countryCode.toUpperCase()));return db().listDocuments({databaseId:databaseId(),collectionId:"packaging_requirements",queries})}
export async function listCertificationRequirements(filters:{categoryId?:string;countryCode?:string}={}){const queries=[Query.equal("status","active"),Query.limit(500)];if(filters.categoryId)queries.push(Query.equal("categoryId",filters.categoryId));if(filters.countryCode)queries.push(Query.equal("destinationCountryCode",filters.countryCode.toUpperCase()));return db().listDocuments({databaseId:databaseId(),collectionId:"certification_requirements",queries})}
export const listQualityCentres=(countryCode?:string)=>db().listDocuments({databaseId:databaseId(),collectionId:"quality_centres",queries:[Query.equal("status","verified"),...(countryCode?[Query.equal("countryCode",countryCode.toUpperCase())]:[]),Query.limit(500)]});
export const listCertificationApplications=(vendorId?:string)=>db().listDocuments({databaseId:databaseId(),collectionId:"certification_applications",queries:[...(vendorId?[Query.equal("vendorId",vendorId)]:[]),Query.orderDesc("submittedAt"),Query.limit(500)]});
export async function createStandard(data:Record<string,unknown>){return db().createDocument({databaseId:databaseId(),collectionId:"product_standards",documentId:ID.unique(),permissions:[],data:{...data,countryCode:String(data.countryCode).toUpperCase(),status:"active",effectiveAt:new Date(String(data.effectiveAt)).toISOString(),updatedAt:new Date().toISOString()}})}
export async function createPackagingRequirement(data:Record<string,unknown>){return db().createDocument({databaseId:databaseId(),collectionId:"packaging_requirements",documentId:ID.unique(),permissions:[],data:{...data,destinationCountryCode:String(data.destinationCountryCode).toUpperCase(),status:"active",updatedAt:new Date().toISOString()}})}
export async function createCertificationRequirement(data:Record<string,unknown>){return db().createDocument({databaseId:databaseId(),collectionId:"certification_requirements",documentId:ID.unique(),permissions:[],data:{...data,destinationCountryCode:String(data.destinationCountryCode).toUpperCase(),status:"active",updatedAt:new Date().toISOString()}})}
export async function createQualityCentre(data:Record<string,unknown>){return db().createDocument({databaseId:databaseId(),collectionId:"quality_centres",documentId:ID.unique(),permissions:[],data:{...data,countryCode:String(data.countryCode).toUpperCase(),status:"verified",verifiedAt:new Date().toISOString()}})}
export async function submitCertificationApplication(input:{vendorId:string;ownerUserId:string;productId:string;requirementId:string;qualityCentreId?:string;notes:string}){const database=db(),product=await database.getDocument({databaseId:databaseId(),collectionId:"products",documentId:input.productId});if(product.submittedByVendorId!==input.vendorId)throw new Error("Product not found");await database.getDocument({databaseId:databaseId(),collectionId:"certification_requirements",documentId:input.requirementId});const application=await database.createDocument({databaseId:databaseId(),collectionId:"certification_applications",documentId:ID.unique(),permissions:[],data:{applicationNumber:`PAC-CERT-${Date.now().toString(36).toUpperCase()}`,...input,status:"submitted",submittedAt:new Date().toISOString()}});await addEvent(application.$id,"submitted",input.ownerUserId,input.notes);return application}
export async function reviewCertificationApplication(applicationId:string,action:CertificationReviewAction,notes:string,actorUserId:string){const status=action==="approve"?"approved":action==="reject"?"rejected":action==="send_to_quality_centre"?"testing_required":"information_requested";await db().updateDocument({databaseId:databaseId(),collectionId:"certification_applications",documentId:applicationId,data:{status,reviewedAt:new Date().toISOString(),reviewedBy:actorUserId,...(notes?{reviewNotes:notes}:{})}});await addEvent(applicationId,action,actorUserId,notes);await db().createDocument({databaseId:databaseId(),collectionId:"audit_logs",documentId:ID.unique(),permissions:[],data:{actorUserId,action:`certification.${action}`,entityType:"certification_application",entityId:applicationId,metadata:JSON.stringify({status}),occurredAt:new Date().toISOString()}})}
async function addEvent(applicationId:string,eventType:string,actorUserId:string,notes=""){return db().createDocument({databaseId:databaseId(),collectionId:"certification_application_events",documentId:ID.unique(),permissions:[],data:{applicationId,eventType,actorUserId,...(notes?{notes}:{}),occurredAt:new Date().toISOString()}})}
