import Link from "next/link";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { requireTradeStaff } from "@/src/modules/authorization/server/require-trade-staff";
import { getVendorTradeBundle } from "@/src/modules/trade/server/repository";

export const dynamic = "force-dynamic";
export default async function TradeDossier({ params, searchParams }: { params: Promise<{ passportId: string }>; searchParams: Promise<{ reviewed?: string }> }) {
  await requireTradeStaff(); const [{ passportId }, query] = await Promise.all([params, searchParams]);
  const passport = await createAppwriteDatabaseClient().databases.getDocument({ databaseId: env().APPWRITE_DATABASE_ID, collectionId: "trade_passports", documentId: passportId });
  const bundle = await getVendorTradeBundle(String(passport.vendorId));
  return <main className="admin-detail"><header><div><p className="kicker">TRADE COMPLIANCE DOSSIER</p><h1>{String(passport.passportNumber)}</h1><p>Vendor {String(passport.vendorId)} · Readiness {String(passport.readinessScore)}%</p>{query.reviewed && <p className="success-note">Review decision recorded.</p>}</div><Link href="/admin/trade">Trade queue</Link></header><section className="vendor-record"><div><span>Status</span><strong>{String(passport.status).replaceAll("_", " ")}</strong></div><div><span>Exporter number</span><strong>{String(passport.exporterNumber ?? "Not supplied")}</strong></div><div><span>Target countries</span><strong>{Array.isArray(passport.targetCountries) ? passport.targetCountries.join(", ") : "—"}</strong></div><div><span>Product categories</span><strong>{Array.isArray(passport.productCategories) ? passport.productCategories.join(", ") : "—"}</strong></div><div><span>Incoterms</span><strong>{String(passport.incoterms)}</strong></div><div><span>Transport</span><strong>{String(passport.transportModes)}</strong></div></section><section className="review-table"><h2>Certifications and inspections</h2>{bundle.certifications.map(item => <div className="review-row" key={item.$id}><span>{String(item.certificationType)}</span><span>{String(item.certificateNumber)}</span><span>{String(item.issuingAuthority)}</span><strong>{String(item.status)}</strong></div>)}</section><section className="review-table"><h2>Private trade documents</h2>{bundle.documents.map(item => <div className="review-row" key={item.$id}><span>{String(item.documentType).replaceAll("_", " ")}</span><span>{String(item.referenceNumber || "—")}</span><span>{String(item.filename)}</span><strong>{String(item.status)}</strong></div>)}</section><section className="review-panel"><h2>Compliance decision</h2><form action={`/api/admin/trade/passports/${passportId}/review`} method="post"><label>Review notes<textarea name="notes" placeholder="Record evidence, conditions or required corrections" /></label><div className="review-actions"><button name="action" value="approve">Approve passport</button><button name="action" value="request_information">Request information</button><button className="danger" name="action" value="reject">Reject</button></div></form></section><section className="review-table"><h2>Audit timeline</h2>{bundle.events.map(event => <div className="review-row" key={event.$id}><span>{String(event.eventType).replaceAll("_", " ")}</span><span>{String(event.entityType).replaceAll("_", " ")}</span><span>{String(event.notes || "—")}</span><span>{new Date(String(event.occurredAt)).toLocaleString("en-GB")}</span></div>)}</section></main>;
}
