import "server-only";
import { ID, Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { listApprovedMediaForProducts } from "@/src/modules/catalogue/server/media";
const databaseId = () => env().APPWRITE_DATABASE_ID;
const db = () => createAppwriteDatabaseClient().databases;
async function withReadRetry<T>(operation: () => Promise<T>, attempts = 3): Promise<T> { let error: unknown; for (let attempt = 0; attempt < attempts; attempt++) { try { return await operation(); } catch (reason) { error = reason; if (attempt + 1 < attempts) await new Promise(resolve => setTimeout(resolve, 200 * (attempt + 1))); } } throw error; }
export const listCategories = () => withReadRetry(() => db().listDocuments({ databaseId: databaseId(), collectionId: "categories", queries: [Query.equal("status", "active"), Query.limit(100)] }));
export const listVendorProducts = (vendorId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "products", queries: [Query.equal("submittedByVendorId", vendorId), Query.orderDesc("submittedAt"), Query.limit(100)] });
export const listModerationProducts = () => db().listDocuments({ databaseId: databaseId(), collectionId: "products", queries: [Query.orderDesc("submittedAt"), Query.limit(100)] });
export async function listPublicProducts() {
  const databases = db();
  const products = await withReadRetry(() => databases.listDocuments({ databaseId: databaseId(), collectionId: "products", queries: [Query.equal("status", "approved"), Query.orderDesc("submittedAt"), Query.limit(100)] }));
  if (!products.documents.length) return [];
  const productIds = products.documents.map(product => product.$id);
  const mediaByProduct = await listApprovedMediaForProducts(productIds);
  const offers = await withReadRetry(() => databases.listDocuments({ databaseId: databaseId(), collectionId: "seller_offers", queries: [Query.equal("productId", productIds), Query.equal("status", "approved"), Query.limit(5000)] }));
  const cheapestOffers = new Map<string, (typeof offers.documents)[number]>();
  for (const offer of offers.documents) { const productId = String(offer.productId), current = cheapestOffers.get(productId); if (!current || Number(offer.retailPriceMinor) < Number(current.retailPriceMinor)) cheapestOffers.set(productId, offer); }
  const offerIds = [...cheapestOffers.values()].map(offer => offer.$id);
  const balances = offerIds.length ? await withReadRetry(() => databases.listDocuments({ databaseId: databaseId(), collectionId: "inventory_balances", queries: [Query.equal("offerId", offerIds), Query.limit(5000)] })) : null;
  const availability = new Map<string, number>();
  for (const balance of balances?.documents ?? []) { const offerId = String(balance.offerId); availability.set(offerId, (availability.get(offerId) ?? 0) + Number(balance.onHand) - Number(balance.reserved) - Number(balance.damaged)); }
  return products.documents.map(product => { const offer = cheapestOffers.get(product.$id); return offer ? { product, offer, available: availability.get(offer.$id) ?? 0, media: mediaByProduct.get(product.$id)?.[0] ?? null } : null; });
}
export async function listPublicProductsFiltered(filters: { q?: string; category?: string; market?: string; sort?: string; availability?: string }) { const rows = (await listPublicProducts()).filter((row): row is NonNullable<typeof row> => row !== null); const query = filters.q?.trim().toLowerCase(); const filtered = rows.filter(row => (!query || `${row.product.name} ${row.product.description} ${row.product.brandName ?? ""}`.toLowerCase().includes(query)) && (!filters.category || row.product.categoryId === filters.category) && (!filters.market || (filters.market === "wholesale" ? Number(row.offer.minimumOrderQuantity) > 1 : Number(row.offer.minimumOrderQuantity) === 1)) && (filters.availability !== "in_stock" || row.available > 0)); return filtered.sort((a, b) => filters.sort === "price_low" ? Number(a.offer.retailPriceMinor) - Number(b.offer.retailPriceMinor) : filters.sort === "price_high" ? Number(b.offer.retailPriceMinor) - Number(a.offer.retailPriceMinor) : filters.sort === "name" ? String(a.product.name).localeCompare(String(b.product.name)) : 0); }
export async function listPacsmProducts() { const rows = (await listPublicProducts()).filter(Boolean); return rows.filter(row => row && (String(row.product.brandName ?? "").toLowerCase().startsWith("pac-sm") || String(row.product.manufacturer ?? "").toLowerCase().startsWith("pac-sm"))); }
export async function getPublicProduct(slug: string) { const databases = db(); const products = await databases.listDocuments({ databaseId: databaseId(), collectionId: "products", queries: [Query.equal("slug", slug), Query.equal("status", "approved"), Query.limit(1)] }); const product = products.documents[0]; if (!product) return null; const [variants, offers, mediaByProduct] = await Promise.all([databases.listDocuments({ databaseId: databaseId(), collectionId: "product_variants", queries: [Query.equal("productId", product.$id)] }), databases.listDocuments({ databaseId: databaseId(), collectionId: "seller_offers", queries: [Query.equal("productId", product.$id), Query.equal("status", "approved"), Query.limit(100)] }), listApprovedMediaForProducts([product.$id])]); const enriched = await Promise.all(offers.documents.map(async (offer) => { const balances = await databases.listDocuments({ databaseId: databaseId(), collectionId: "inventory_balances", queries: [Query.equal("offerId", offer.$id), Query.limit(100)] }); const stores = await databases.listDocuments({ databaseId: databaseId(), collectionId: "stores", queries: [Query.equal("vendorId", offer.vendorId), Query.equal("status", "active"), Query.limit(1)] }); return { offer, store: stores.documents[0], available: balances.documents.reduce((sum, item) => sum + Number(item.onHand) - Number(item.reserved) - Number(item.damaged), 0) }; })); return { product, variants: variants.documents, offers: enriched.filter((item) => item.store), media: mediaByProduct.get(product.$id) ?? [] }; }
export async function getPublicStore(slug: string) { const databases = db(); const stores = await databases.listDocuments({ databaseId: databaseId(), collectionId: "stores", queries: [Query.equal("slug", slug), Query.equal("status", "active"), Query.limit(1)] }); const store = stores.documents[0]; if (!store) return null; const vendor = await databases.getDocument({ databaseId: databaseId(), collectionId: "vendors", documentId: String(store.vendorId) }); if (!["approved", "active"].includes(String(vendor.status))) return null; const offers = await databases.listDocuments({ databaseId: databaseId(), collectionId: "seller_offers", queries: [Query.equal("vendorId", store.vendorId), Query.equal("status", "approved"), Query.limit(100)] }); const products = (await Promise.all(offers.documents.map((offer) => databases.getDocument({ databaseId: databaseId(), collectionId: "products", documentId: String(offer.productId) })))).filter((product) => product.status === "approved"); const mediaByProduct = await listApprovedMediaForProducts(products.map(product => product.$id)); return { store, vendor, offers: offers.documents, products, mediaByProduct }; }
export async function reviewProduct(productId: string, action: "approve" | "restore" | "take_down" | "reject" | "request_changes", actorUserId: string, notes: string) {
  const databases = db(), transaction = await databases.createTransaction({ ttl: 120 }), id = databaseId(), now = new Date().toISOString();
  const status = action === "approve" || action === "restore" ? "approved" : action === "take_down" ? "suspended" : action === "reject" ? "rejected" : "changes_requested";
  try {
    await databases.updateDocument({ databaseId: id, collectionId: "products", documentId: productId, transactionId: transaction.$id, data: { status, reviewedBy: actorUserId, reviewedAt: now } });
    const offers = await databases.listDocuments({ databaseId: id, collectionId: "seller_offers", queries: [Query.equal("productId", productId)], transactionId: transaction.$id });
    for (const offer of offers.documents) await databases.updateDocument({ databaseId: id, collectionId: "seller_offers", documentId: offer.$id, transactionId: transaction.$id, data: { status } });
    await databases.createDocument({ databaseId: id, collectionId: "audit_logs", documentId: ID.unique(), permissions: [], transactionId: transaction.$id, data: { actorUserId, action: `product.${action}`, entityType: "product", entityId: productId, metadata: JSON.stringify({ notes, status }), occurredAt: now } });
    await databases.updateTransaction({ transactionId: transaction.$id, commit: true });
  } catch (error) { await databases.updateTransaction({ transactionId: transaction.$id, rollback: true }).catch(() => undefined); throw error; }
}
export async function submitProduct(input: { vendorId: string; actorUserId: string; name: string; slug: string; description: string; categoryId: string; brandName: string; manufacturer: string; countryOfOrigin: string; model: string; gtin: string; specifications: string; variantName: string; sku: string; variantAttributes: string; retailPriceMinor: number; wholesalePriceMinor?: number; currency: string; minimumOrderQuantity: number; fulfilmentMethod: string; processingDays: number }) {
  const databases = db(), transaction = await databases.createTransaction({ ttl: 120 }), productId = ID.unique(), variantId = ID.unique(), now = new Date().toISOString(), id = databaseId();
  try {
    await databases.createDocument({ databaseId: id, collectionId: "products", documentId: productId, permissions: [], transactionId: transaction.$id, data: { submittedByVendorId: input.vendorId, name: input.name, slug: input.slug, description: input.description, categoryId: input.categoryId, ...(input.brandName ? { brandName: input.brandName } : {}), ...(input.manufacturer ? { manufacturer: input.manufacturer } : {}), countryOfOrigin: input.countryOfOrigin, ...(input.model ? { model: input.model } : {}), ...(input.gtin ? { gtin: input.gtin } : {}), specifications: input.specifications, status: "approved", submittedAt: now, reviewedBy: input.actorUserId, reviewedAt: now } });
    await databases.createDocument({ databaseId: id, collectionId: "product_variants", documentId: variantId, permissions: [], transactionId: transaction.$id, data: { productId, name: input.variantName, sku: input.sku, attributes: input.variantAttributes, status: "approved" } });
    await databases.createDocument({ databaseId: id, collectionId: "seller_offers", documentId: ID.unique(), permissions: [], transactionId: transaction.$id, data: { vendorId: input.vendorId, productId, variantId, sellerSku: input.sku, retailPriceMinor: input.retailPriceMinor, ...(input.wholesalePriceMinor ? { wholesalePriceMinor: input.wholesalePriceMinor } : {}), currency: input.currency, minimumOrderQuantity: input.minimumOrderQuantity, fulfilmentMethod: input.fulfilmentMethod, processingDays: input.processingDays, status: "approved", submittedAt: now } });
    await databases.createDocument({ databaseId: id, collectionId: "audit_logs", documentId: ID.unique(), permissions: [], transactionId: transaction.$id, data: { actorUserId: input.actorUserId, action: "product.auto_publish", entityType: "product", entityId: productId, metadata: JSON.stringify({ vendorId: input.vendorId }), occurredAt: now } });
    await databases.updateTransaction({ transactionId: transaction.$id, commit: true });
    return productId;
  } catch (error) { await databases.updateTransaction({ transactionId: transaction.$id, rollback: true }).catch(() => undefined); throw error; }
}

export async function createAdminProduct(input: { name: string; description: string; categoryId: string; marketType: "retail" | "wholesale"; priceMinor: number; stock: number; actorUserId: string }) {
  if (input.name.trim().length < 3 || input.description.trim().length < 20 || input.priceMinor < 1 || input.stock < 0) throw new Error("Invalid product details");
  const databases = db(), transaction = await databases.createTransaction({ ttl: 120 }), productId = ID.unique(), variantId = ID.unique(), offerId = ID.unique(), suffix = productId.slice(-8), now = new Date().toISOString();
  try {
    await databases.createDocument({ databaseId: databaseId(), collectionId: "products", documentId: productId, permissions: [], transactionId: transaction.$id, data: { submittedByVendorId: "pacsm-demo-vendor", name: input.name.trim(), slug: `${input.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}-${suffix}`, description: input.description.trim(), categoryId: input.categoryId, brandName: "PAC-SM Admin Catalogue", manufacturer: "PAC-SM Demo Producer Network", countryOfOrigin: "NG", model: `ADMIN-${suffix}`, specifications: JSON.stringify({ demo: true, market: input.marketType }), status: "approved", submittedAt: now, reviewedBy: input.actorUserId, reviewedAt: now } });
    await databases.createDocument({ databaseId: databaseId(), collectionId: "product_variants", documentId: variantId, permissions: [], transactionId: transaction.$id, data: { productId, name: input.marketType === "wholesale" ? "Wholesale pack" : "Standard", sku: `PAC-ADMIN-${suffix}`, attributes: JSON.stringify({ market: input.marketType }), status: "approved" } });
    await databases.createDocument({ databaseId: databaseId(), collectionId: "seller_offers", documentId: offerId, permissions: [], transactionId: transaction.$id, data: { vendorId: "pacsm-demo-vendor", productId, variantId, sellerSku: `PAC-ADMIN-${suffix}`, retailPriceMinor: input.priceMinor, ...(input.marketType === "wholesale" ? { wholesalePriceMinor: input.priceMinor } : {}), currency: "NGN", minimumOrderQuantity: input.marketType === "wholesale" ? 10 : 1, fulfilmentMethod: "seller_fulfilled", processingDays: input.marketType === "wholesale" ? 5 : 2, status: "approved", submittedAt: now } });
    await databases.createDocument({ databaseId: databaseId(), collectionId: "inventory_balances", documentId: ID.unique(), permissions: [], transactionId: transaction.$id, data: { vendorId: "pacsm-demo-vendor", warehouseId: "pacsm-demo-warehouse", offerId, onHand: input.stock, reserved: 0, incoming: 0, damaged: 0, version: 1 } });
    await databases.createDocument({ databaseId: databaseId(), collectionId: "audit_logs", documentId: ID.unique(), permissions: [], transactionId: transaction.$id, data: { actorUserId: input.actorUserId, action: "product.admin_create", entityType: "product", entityId: productId, metadata: JSON.stringify({ marketType: input.marketType }), occurredAt: now } });
    await databases.updateTransaction({ transactionId: transaction.$id, commit: true });
  } catch (error) { await databases.updateTransaction({ transactionId: transaction.$id, rollback: true }).catch(() => undefined); throw error; }
}

export async function renameAdminProduct(productId: string, name: string, actorUserId: string) {
  if (name.trim().length < 3) throw new Error("Product name is too short");
  await db().updateDocument({ databaseId: databaseId(), collectionId: "products", documentId: productId, data: { name: name.trim() } });
  await db().createDocument({ databaseId: databaseId(), collectionId: "audit_logs", documentId: ID.unique(), permissions: [], data: { actorUserId, action: "product.rename", entityType: "product", entityId: productId, metadata: JSON.stringify({ name: name.trim() }), occurredAt: new Date().toISOString() } });
}

export async function deleteAdminProduct(productId: string, actorUserId: string) {
  const databases = db(), transaction = await databases.createTransaction({ ttl: 120 });
  try {
    const [offers, variants] = await Promise.all([databases.listDocuments({ databaseId: databaseId(), collectionId: "seller_offers", queries: [Query.equal("productId", productId), Query.limit(100)], transactionId: transaction.$id }), databases.listDocuments({ databaseId: databaseId(), collectionId: "product_variants", queries: [Query.equal("productId", productId), Query.limit(100)], transactionId: transaction.$id })]);
    for (const offer of offers.documents) { const balances = await databases.listDocuments({ databaseId: databaseId(), collectionId: "inventory_balances", queries: [Query.equal("offerId", offer.$id), Query.limit(100)], transactionId: transaction.$id }); for (const balance of balances.documents) await databases.deleteDocument({ databaseId: databaseId(), collectionId: "inventory_balances", documentId: balance.$id, transactionId: transaction.$id }); await databases.deleteDocument({ databaseId: databaseId(), collectionId: "seller_offers", documentId: offer.$id, transactionId: transaction.$id }); }
    for (const variant of variants.documents) await databases.deleteDocument({ databaseId: databaseId(), collectionId: "product_variants", documentId: variant.$id, transactionId: transaction.$id });
    await databases.deleteDocument({ databaseId: databaseId(), collectionId: "products", documentId: productId, transactionId: transaction.$id });
    await databases.createDocument({ databaseId: databaseId(), collectionId: "audit_logs", documentId: ID.unique(), permissions: [], transactionId: transaction.$id, data: { actorUserId, action: "product.delete", entityType: "product", entityId: productId, metadata: "{}", occurredAt: new Date().toISOString() } });
    await databases.updateTransaction({ transactionId: transaction.$id, commit: true });
  } catch (error) { await databases.updateTransaction({ transactionId: transaction.$id, rollback: true }).catch(() => undefined); throw error; }
}
