export const LANGUAGES = [
  { code: "en", name: "English" }, { code: "fr", name: "Français" }, { code: "ar", name: "العربية" },
  { code: "pt", name: "Português" }, { code: "sw", name: "Kiswahili" }, { code: "es", name: "Español" }
] as const;

export const CURRENCIES = [
  "DZD", "AOA", "BWP", "BIF", "CVE", "XAF", "KMF", "CDF", "DJF", "EGP", "ERN", "SZL", "ETB", "GMD", "GHS", "GNF", "KES", "LSL", "LRD", "LYD", "MGA", "MWK", "MRU", "MUR", "MAD", "MZN", "NAD", "NGN", "RWF", "STN", "SCR", "SLE", "SOS", "ZAR", "SSP", "SDG", "TZS", "TND", "UGX", "XOF", "ZMW", "ZWG", "USD",
  "EUR", "GBP", "CAD", "AUD", "CNY", "JPY", "INR", "AED", "SAR", "TRY", "BRL", "CHF", "SGD", "NZD", "HKD"
] as const;

export type LanguageCode = typeof LANGUAGES[number]["code"];
export type CurrencyCode = typeof CURRENCIES[number];
type Region = { name: string; currency: CurrencyCode; language: LanguageCode };

export const REGIONS: Record<string, Region> = {
  DZ:{name:"Algeria",currency:"DZD",language:"ar"},AO:{name:"Angola",currency:"AOA",language:"pt"},BJ:{name:"Benin",currency:"XOF",language:"fr"},BW:{name:"Botswana",currency:"BWP",language:"en"},BF:{name:"Burkina Faso",currency:"XOF",language:"fr"},BI:{name:"Burundi",currency:"BIF",language:"fr"},CV:{name:"Cabo Verde",currency:"CVE",language:"pt"},CM:{name:"Cameroon",currency:"XAF",language:"fr"},CF:{name:"Central African Republic",currency:"XAF",language:"fr"},TD:{name:"Chad",currency:"XAF",language:"fr"},KM:{name:"Comoros",currency:"KMF",language:"fr"},CD:{name:"Democratic Republic of the Congo",currency:"CDF",language:"fr"},CG:{name:"Republic of the Congo",currency:"XAF",language:"fr"},CI:{name:"Côte d’Ivoire",currency:"XOF",language:"fr"},DJ:{name:"Djibouti",currency:"DJF",language:"fr"},EG:{name:"Egypt",currency:"EGP",language:"ar"},GQ:{name:"Equatorial Guinea",currency:"XAF",language:"es"},ER:{name:"Eritrea",currency:"ERN",language:"en"},SZ:{name:"Eswatini",currency:"SZL",language:"en"},ET:{name:"Ethiopia",currency:"ETB",language:"en"},GA:{name:"Gabon",currency:"XAF",language:"fr"},GM:{name:"The Gambia",currency:"GMD",language:"en"},GH:{name:"Ghana",currency:"GHS",language:"en"},GN:{name:"Guinea",currency:"GNF",language:"fr"},GW:{name:"Guinea-Bissau",currency:"XOF",language:"pt"},KE:{name:"Kenya",currency:"KES",language:"sw"},LS:{name:"Lesotho",currency:"LSL",language:"en"},LR:{name:"Liberia",currency:"LRD",language:"en"},LY:{name:"Libya",currency:"LYD",language:"ar"},MG:{name:"Madagascar",currency:"MGA",language:"fr"},MW:{name:"Malawi",currency:"MWK",language:"en"},ML:{name:"Mali",currency:"XOF",language:"fr"},MR:{name:"Mauritania",currency:"MRU",language:"ar"},MU:{name:"Mauritius",currency:"MUR",language:"en"},MA:{name:"Morocco",currency:"MAD",language:"ar"},MZ:{name:"Mozambique",currency:"MZN",language:"pt"},NA:{name:"Namibia",currency:"NAD",language:"en"},NE:{name:"Niger",currency:"XOF",language:"fr"},NG:{name:"Nigeria",currency:"NGN",language:"en"},RW:{name:"Rwanda",currency:"RWF",language:"en"},ST:{name:"São Tomé and Príncipe",currency:"STN",language:"pt"},SN:{name:"Senegal",currency:"XOF",language:"fr"},SC:{name:"Seychelles",currency:"SCR",language:"en"},SL:{name:"Sierra Leone",currency:"SLE",language:"en"},SO:{name:"Somalia",currency:"SOS",language:"en"},ZA:{name:"South Africa",currency:"ZAR",language:"en"},SS:{name:"South Sudan",currency:"SSP",language:"en"},SD:{name:"Sudan",currency:"SDG",language:"ar"},TZ:{name:"Tanzania",currency:"TZS",language:"sw"},TG:{name:"Togo",currency:"XOF",language:"fr"},TN:{name:"Tunisia",currency:"TND",language:"ar"},UG:{name:"Uganda",currency:"UGX",language:"en"},ZM:{name:"Zambia",currency:"ZMW",language:"en"},ZW:{name:"Zimbabwe",currency:"ZWG",language:"en"},
  US:{name:"United States",currency:"USD",language:"en"},CA:{name:"Canada",currency:"CAD",language:"en"},GB:{name:"United Kingdom",currency:"GBP",language:"en"},FR:{name:"France",currency:"EUR",language:"fr"},PT:{name:"Portugal",currency:"EUR",language:"pt"},ES:{name:"Spain",currency:"EUR",language:"es"},AU:{name:"Australia",currency:"AUD",language:"en"},CN:{name:"China",currency:"CNY",language:"en"},JP:{name:"Japan",currency:"JPY",language:"en"},IN:{name:"India",currency:"INR",language:"en"},AE:{name:"United Arab Emirates",currency:"AED",language:"ar"},SA:{name:"Saudi Arabia",currency:"SAR",language:"ar"},BR:{name:"Brazil",currency:"BRL",language:"pt"},CH:{name:"Switzerland",currency:"CHF",language:"en"},SG:{name:"Singapore",currency:"SGD",language:"en"}
};

export const validCountry = (value: string) => /^[A-Z]{2}$/.test(value) && Boolean(REGIONS[value]);
export const flagForCountry = (countryCode: string) => countryCode.toUpperCase().replace(/[A-Z]/g, character => String.fromCodePoint(127397 + character.charCodeAt(0)));
export const languageName = (code: string) => LANGUAGES.find(language => language.code === code)?.name ?? "English";
export const isLanguage = (value: string): value is LanguageCode => LANGUAGES.some(language => language.code === value);
export const isCurrency = (value: string): value is CurrencyCode => (CURRENCIES as readonly string[]).includes(value);
