import Link from "next/link";
import { listPublicProgramProducts } from "@/src/modules/catalogue/server/product-programs";
import { preorderIsOpen } from "@/src/modules/catalogue/domain/product-program";
import { getCurrencyDisplay } from "@/src/modules/localization/server/currency";

export async function ProgramMarketplace({ kind }: { kind: "preorder" | "white_label" }) {
  const [rows, pricing] = await Promise.all([listPublicProgramProducts(kind), getCurrencyDisplay()]), preorder = kind === "preorder";
  return <main className="program-marketplace"><header><nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><div><Link href="/products">Marketplace</Link><Link href={preorder ? "/white-label" : "/pre-orders"}>{preorder ? "White label" : "Pre-orders"}</Link><Link href="/cart">Cart</Link></div></nav><div><p className="kicker">{preorder ? "RESERVE UPCOMING PRODUCTION" : "BUILD YOUR OWN BRAND"}</p><h1>{preorder ? "Pre-order marketplace" : "White-label marketplace"}</h1><p>{preorder ? "Secure upcoming products and production capacity through PAC-SM protected checkout." : "Source manufacturer-ready products, provide your branding brief and create a private-label product line."}</p></div></header><section className="program-assurance"><span>✓ Verified manufacturers</span><span>▣ Protected payment</span><span>◷ Clear production timelines</span><span>↗ Tracked fulfilment</span></section><section className="program-market-grid">{rows.length ? rows.map(({ program, offer, product }) => { const available = Math.max(0, Number(program.preorderCapacity ?? 0) - Number(program.preorderReserved ?? 0)); return <article key={offer.$id}><span>{preorder ? (preorderIsOpen(program) ? "OPEN FOR PRE-ORDER" : "WINDOW CLOSED") : "WHITE LABEL AVAILABLE"}</span><h2>{String(product.name)}</h2><p>{String(product.description).slice(0, 180)}</p><dl><div><dt>From</dt><dd>{pricing.format(Number(offer.retailPriceMinor), String(offer.currency))}</dd></div>{preorder ? <><div><dt>Capacity left</dt><dd>{available} units</dd></div><div><dt>Dispatch target</dt><dd>{new Date(String(program.estimatedDispatchAt)).toLocaleDateString("en-GB")}</dd></div></> : <><div><dt>Minimum run</dt><dd>{String(program.whiteLabelMinimumQuantity)} units</dd></div><div><dt>Lead time</dt><dd>{String(program.whiteLabelLeadDays)} days</dd></div></>}</dl>{!preorder && <small>{String(program.whiteLabelOptions)}</small>}<Link href={`/products/${String(product.slug)}`}>View terms and order →</Link></article>; }) : <div className="retail-empty"><h2>No programmes are published yet</h2><p>Verified manufacturers can activate eligible offers from Seller Centre.</p><Link href="/products">Browse the marketplace</Link></div>}</section></main>;
}
