import Link from "next/link";
import { redirect } from "next/navigation";
import { CommerceModuleHeader, CommerceModuleHero } from "@/app/components/commerce-module-header";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { findBusinessBuyer } from "@/src/modules/wholesale/server/repository";
import { listBuyerRfqs } from "@/src/modules/procurement/server/repository";
import { listCategories } from "@/src/modules/catalogue/server/repository";
export const dynamic = "force-dynamic";

export default async function ProcurementPage() {
  const user = await getCurrentAppwriteUser(); if (!user) redirect("/login?returnTo=/procurement");
  const [buyer, rfqs, categories] = await Promise.all([findBusinessBuyer(user.$id), listBuyerRfqs(user.$id), listCategories()]);
  return <main className="commerce-module"><CommerceModuleHeader current="procurement" utility={{ href: "/wholesale", label: "Business buyer" }}/><CommerceModuleHero tone="orange" eyebrow="STRUCTURED RFQ PROCUREMENT" title="Source at continental scale." description="Publish a clear commercial requirement, invite matched suppliers, compare quotations and convert the selected bid into a traceable purchase order." metric={rfqs.total} metricLabel="requests for quotation in your procurement workspace"><div className="module-status-line"><span>Structured requirements</span><span>Supplier comparison</span><span>PO conversion</span></div></CommerceModuleHero>
    <div className="module-body"><section className="module-feature-strip"><article><span>01</span><div><strong>Define demand</strong><small>Quantity, category and destination</small></div></article><article><span>02</span><div><strong>Receive quotations</strong><small>Comparable supplier proposals</small></div></article><article><span>03</span><div><strong>Select supplier</strong><small>Price, terms and lead time</small></div></article><article><span>04</span><div><strong>Create purchase order</strong><small>Preserved commercial audit trail</small></div></article></section>
      {buyer?.status === "approved" ? <section className="module-panel"><div className="module-panel-heading"><div><span>NEW PROCUREMENT REQUEST</span><h2>Create a request for quotation</h2><p>Give suppliers enough detail to return an accurate, comparable commercial offer.</p></div></div><form action="/api/procurement/rfqs" method="post"><label>RFQ title<input name="title" required minLength={5} placeholder="e.g. 20 tonnes of packaged maize flour"/></label><label>Category<select name="categoryId">{categories.documents.map(c => <option value={c.$id} key={c.$id}>{String(c.name)}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="1" required/></label><label>Unit<input name="unit" placeholder="units, cartons, tonnes" required/></label><label>Delivery country<input name="deliveryCountryCode" minLength={2} maxLength={2} placeholder="NG" required/></label><label>Currency<input name="currency" defaultValue="NGN" minLength={3} maxLength={3} required/></label><label>Quotation deadline<input name="quotationDeadline" type="datetime-local" required/></label><label style={{gridColumn:"span 2"}}>Detailed requirement<textarea name="description" required minLength={20} placeholder="Specifications, quality, packaging, certification and delivery expectations"/></label><button>Publish RFQ</button></form></section> : <section className="module-alert"><strong>Approved business buyer required</strong><p>Register your organization or monitor its approval in the <Link href="/wholesale">Wholesale Centre</Link>.</p></section>}
      <section className="module-panel"><div className="module-panel-heading"><div><span>PROCUREMENT WORKSPACE</span><h2>Your RFQ portfolio</h2><p>Monitor supplier response and open each request to compare quotations.</p></div></div>{rfqs.total ? <div className="module-table"><div className="module-table-row head"><span>Request</span><span>Status</span><span>Quantity</span><span>Action</span></div>{rfqs.documents.map(r => <div className="module-table-row" key={r.$id}><span><strong>{String(r.title)}</strong><br/><small>{String(r.rfqNumber)}</small></span><strong>{String(r.status).replaceAll("_"," ")}</strong><span>{String(r.quantity)} {String(r.unit)}</span><Link href={`/procurement/${r.$id}`}>Compare quotations →</Link></div>)}</div> : <div className="module-empty"><strong>No RFQs created yet</strong><span>Your published procurement requests will appear here.</span></div>}</section>
    </div></main>;
}
