import Link from "next/link";
import { redirect } from "next/navigation";
import { Query } from "node-appwrite";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { listCustomerDisputes } from "@/src/modules/disputes/server/repository";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
export const dynamic = "force-dynamic";
export default async function CustomerDisputesPage({ searchParams }: { searchParams: Promise<{ created?: string; error?: string }> }) { const user = await getCurrentAppwriteUser(); if (!user) redirect("/login?returnTo=/account/disputes"); const databases = createAppwriteDatabaseClient().databases, databaseId = env().APPWRITE_DATABASE_ID, [disputes, orders, query] = await Promise.all([listCustomerDisputes(user.$id), databases.listDocuments({ databaseId, collectionId: "orders", queries: [Query.equal("customerUserId", user.$id), Query.limit(100)] }), searchParams]); const vendorOrders = (await Promise.all(orders.documents.map(order => databases.listDocuments({ databaseId, collectionId: "vendor_orders", queries: [Query.equal("orderId", order.$id), Query.limit(100)] })))).flatMap(result => result.documents); return <main className="marketplace-shell"><nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><Link href="/account">Account</Link></nav><header><p className="kicker">BUYER PROTECTION</p><h1>Disputes</h1>{query.created && <p className="success-note">Dispute opened.</p>}{query.error && <p className="form-error">The dispute could not be opened.</p>}</header><section className="cart-vendor"><h2>Open a dispute</h2><form className="stack-form" action="/api/disputes" method="post"><label>Vendor order<select name="vendorOrderId" required>{vendorOrders.map(item => <option key={item.$id} value={item.$id}>{String(item.vendorOrderNumber)}</option>)}</select></label><label>Parent order<select name="orderId" required>{orders.documents.map(item => <option key={item.$id} value={item.$id}>{String(item.orderNumber)}</option>)}</select></label><label>Category<select name="category"><option value="item_not_received">Item not received</option><option value="not_as_described">Not as described</option><option value="damaged">Damaged</option><option value="other">Other</option></select></label><label>Details<textarea name="description" required minLength={20} maxLength={2000}/></label><button type="submit">Open dispute</button></form></section><section className="review-table">{disputes.documents.map(item => <div className="review-row" key={item.$id}><span>{String(item.disputeNumber)}</span><strong>{String(item.status)}</strong><span>{String(item.category).replaceAll("_", " ")}</span><span>{String(item.resolution ?? "Awaiting review")}</span></div>)}</section></main>; }
