import Link from "next/link";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { findBusinessBuyer, listBuyerPurchaseOrders, listPriceTiers, listWholesaleOffers } from "@/src/modules/wholesale/server/repository";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { getCurrencyDisplay } from "@/src/modules/localization/server/currency";
import { getNegotiationSettings } from "@/src/modules/wholesale/server/negotiations";

export const dynamic = "force-dynamic";

export default async function WholesalePage({ searchParams }: { searchParams: Promise<{ ordered?: string; orderError?: string; negotiationError?: string }> }) {
  const [user, offers, pricing, query] = await Promise.all([getCurrentAppwriteUser(), listWholesaleOffers(), getCurrencyDisplay(), searchParams]);
  const buyer = user ? await findBusinessBuyer(user.$id) : null;
  const db = createAppwriteDatabaseClient().databases;
  const databaseId = env().APPWRITE_DATABASE_ID;
  const products = await Promise.all(offers.documents.map(offer => db.getDocument({ databaseId, collectionId: "products", documentId: String(offer.productId) })));
  const tiers = await Promise.all(offers.documents.map(offer => listPriceTiers(offer.$id)));
  const negotiationSettings = await Promise.all(offers.documents.map(offer => getNegotiationSettings(offer.$id)));
  const orders = user ? await listBuyerPurchaseOrders(user.$id) : null;

  return <main className="marketplace-shell">
    <nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><Link href="/products">Retail marketplace</Link></nav>
    <header><p className="kicker">PAC-SM WHOLESALE</p><h1>Bulk sourcing for African businesses.</h1><p>Quantity pricing, purchase orders, seller-issued proforma invoices and auditable price negotiation. Offer prices are displayed in {pricing.currency}.</p><Link href="/wholesale/negotiations">My price negotiations →</Link></header>
    {query.ordered && <p className="success-note">Purchase order created successfully. It appears in your purchase-order history below.</p>}
    {query.orderError && <p className="form-error">The purchase order could not be created. Confirm your buyer approval, minimum quantity and offer availability.</p>}
    {query.negotiationError && <p className="form-error">The negotiation request could not be submitted. Confirm your buyer approval, quantity and proposed price.</p>}
    {!user ? <section className="cart-vendor"><Link href="/login?returnTo=/wholesale">Sign in to become a business buyer</Link></section> : !buyer ? <section className="cart-vendor"><h2>Register as a business buyer</h2><form className="stack-form" action="/api/wholesale/buyers" method="post"><label>Organization<input name="organizationName" required/></label><label>Registration number<input name="registrationNumber" required/></label><label>Country code<input name="countryCode" required minLength={2} maxLength={2}/></label><label>Buyer type<select name="buyerType"><option value="retailer">Retailer</option><option value="distributor">Distributor</option><option value="institution">Institution</option><option value="manufacturer">Manufacturer</option></select></label><button>Submit for approval</button></form></section> : <p className="admin-notice">Business buyer status: <strong>{String(buyer.status).replaceAll("_", " ")}</strong></p>}
    <section className="product-grid">{offers.documents.map((offer, index) => <article key={offer.$id}><div className="product-placeholder">{String(products[index].name).slice(0, 2).toUpperCase()}</div><span>MOQ {String(offer.minimumOrderQuantity)}</span><h2>{String(products[index].name)}</h2><strong>From {pricing.format(Number(offer.wholesalePriceMinor ?? offer.retailPriceMinor), String(offer.currency))}</strong>{tiers[index].documents.map(tier => <p key={tier.$id}>{String(tier.minimumQuantity)}+ units: {pricing.format(Number(tier.unitPriceMinor), String(tier.currency))}</p>)}{buyer?.status === "approved" && <form action="/api/wholesale/purchase-orders" method="post"><input type="hidden" name="offerId" value={offer.$id}/><input name="quantity" type="number" min={Number(offer.minimumOrderQuantity)} defaultValue={Number(offer.minimumOrderQuantity)} required/><button>Buy at listed wholesale price</button></form>}{buyer?.status === "approved" && negotiationSettings[index]?.enabled === "true" && <details><summary>Request a negotiated price</summary><p>Ask the seller for an additional discount. The seller may accept, reject or counter your proposal.</p><form className="stack-form" action="/api/wholesale/negotiations" method="post"><input type="hidden" name="offerId" value={offer.$id}/><label>Quantity<input name="quantity" type="number" min={Number(negotiationSettings[index]?.minimumQuantity ?? offer.minimumOrderQuantity)} defaultValue={Number(negotiationSettings[index]?.minimumQuantity ?? offer.minimumOrderQuantity)} required/></label><label>Requested unit price ({String(offer.currency)})<input name="unitPrice" type="number" min="0.01" step="0.01" required/></label><label>Delivery country code<input name="deliveryCountryCode" minLength={2} maxLength={2} required/></label><label>Required delivery date<input name="requestedDeliveryAt" type="date"/></label><label>Message<textarea name="message" maxLength={2000}/></label><button>Send price request to seller</button></form></details>}</article>)}</section>
    {orders && <section className="review-table" id="purchase-orders"><h2>Your purchase orders</h2><div className="review-row review-head"><span>Purchase order</span><span>Status</span><span>Total</span><span>Date</span></div>{orders.documents.length ? orders.documents.map(order => <div className="review-row" key={order.$id}><strong>{String(order.purchaseOrderNumber)}</strong><span>{String(order.status)}</span><span>{new Intl.NumberFormat("en", { style: "currency", currency: String(order.currency) }).format(Number(order.totalMinor) / 100)}</span><span>{new Date(String(order.createdAt)).toLocaleDateString("en-GB")}</span></div>) : <p className="empty-state">No purchase orders yet. Buy at the listed wholesale price or request a negotiated price above.</p>}</section>}
  </main>;
}
