import { ID } from "node-appwrite";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { assertSameOrigin } from "@/src/modules/auth/server/request-security";
import { findVendorByOwner } from "@/src/modules/vendors/server/repository";
import { productDraftRequestSchema } from "@/src/modules/catalogue/domain/product-ai-draft";
import { generateProductDraft } from "@/src/modules/catalogue/server/ai-product-draft";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
const attempts = new Map<string, number[]>();
function withinLimit(userId: string) { const now = Date.now(), recent = (attempts.get(userId) ?? []).filter(time => time > now - 600_000); if (recent.length >= 10) return false; recent.push(now); attempts.set(userId, recent); return true; }
export async function POST(request: Request) { try { assertSameOrigin(request); } catch { return Response.json({ error: "Forbidden" }, { status: 403 }); } const user = await getCurrentAppwriteUser(); if (!user) return Response.json({ error: "Sign in to use AI drafting." }, { status: 401 }); const vendor = await findVendorByOwner(user.$id); if (!vendor || !["approved", "active"].includes(String(vendor.status))) return Response.json({ error: "Seller approval is required." }, { status: 403 }); if (!withinLimit(user.$id)) return Response.json({ error: "AI drafting limit reached. Try again in ten minutes." }, { status: 429 }); const input = productDraftRequestSchema.safeParse(await request.json().catch(() => null)); if (!input.success) return Response.json({ error: "Enter a product name of at least three characters and check the optional facts." }, { status: 400 }); try { const result = await generateProductDraft(input.data); await createAppwriteDatabaseClient().databases.createDocument({ databaseId: env().APPWRITE_DATABASE_ID, collectionId: "audit_logs", documentId: ID.unique(), permissions: [], data: { actorUserId: user.$id, action: "product.ai_draft", entityType: "vendor", entityId: vendor.$id, metadata: JSON.stringify({ productName: input.data.name, model: result.model }), occurredAt: new Date().toISOString() } }); return Response.json({ draft: result.draft }); } catch (error) { console.error("AI product draft failed", error); const unavailable = error instanceof Error && error.message === "AI_NOT_CONFIGURED"; return Response.json({ error: unavailable ? "AI drafting is not configured yet. An administrator must add the server AI key." : "The AI draft could not be generated. Your form has not been changed; please try again." }, { status: unavailable ? 503 : 502 }); } }
