import Link from "next/link";
import type { Metadata } from "next";
import Image from "next/image";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { getCart } from "@/src/modules/cart/server/repository";
import { listCategories, listFeaturedPublicProducts, listPublicProducts } from "@/src/modules/catalogue/server/repository";
import { getCurrencyDisplay, type CurrencyDisplay } from "@/src/modules/localization/server/currency";
import { getTranslator } from "@/src/modules/localization/server/language";
import { ProductImage } from "@/src/modules/catalogue/ui/product-image";
import { accountGreeting } from "@/src/modules/auth/domain/display-name";
import { BRAND_CATALOGUES } from "@/src/modules/catalogue/domain/brand-catalogue";
import { selectFeaturedProducts } from "@/src/modules/catalogue/domain/featured-products";
import { PLATFORM_VERTICALS } from "@/src/content/platform-verticals";
import MarketplaceNavigation from "@/app/components/marketplace-navigation";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { alternates: { canonical: "/" } };

const categoryDesign: Record<string, { icon: string; color: string; tagline: string }> = {
  agriculture: { icon: "🌾", color: "sun", tagline: "Food, crops & ingredients" },
  electronics: { icon: "⚡", color: "sky", tagline: "Devices & power" },
  fashion: { icon: "✦", color: "rose", tagline: "Textiles & apparel" },
  home: { icon: "⌂", color: "mint", tagline: "Home & living" },
  industrial: { icon: "⚙", color: "gold", tagline: "Tools & machinery" },
  health: { icon: "✚", color: "lilac", tagline: "Beauty & wellness" }
};

type ProductRow = NonNullable<Awaited<ReturnType<typeof listPublicProducts>>[number]>;
function ProductCard({ item, index, pricing }: { item: ProductRow; index: number; pricing: CurrencyDisplay }) {
  const wholesale = Number(item.offer.minimumOrderQuantity) > 1;
  return <Link className="home-product" href={`/products/${String(item.product.slug)}`}>
    <ProductImage media={item.media} productName={String(item.product.name)} className={`home-product-art art-${index % 6}`} />
    <div className="home-product-body"><span className={`market-badge ${wholesale ? "bulk" : "retail"}`}>{wholesale ? `Wholesale · MOQ ${item.offer.minimumOrderQuantity}` : "Retail"}</span><h3>{String(item.product.name)}</h3><div className="rating">★★★★★ <span>Verified offer</span></div><strong>{pricing.format(Number(item.offer.retailPriceMinor), String(item.offer.currency))}</strong><p>{item.available > 0 ? `${item.available} available` : "Restocking soon"}</p></div>
  </Link>;
}

export default async function Home() {
  const [user, categories, rawProducts, rawFeaturedProducts, pricing, translator] = await Promise.all([getCurrentAppwriteUser(), listCategories(), listPublicProducts(), listFeaturedPublicProducts(), getCurrencyDisplay(), getTranslator()]);
  const { t } = translator;
  const products = rawProducts.filter((item): item is ProductRow => Boolean(item));
  const featuredRetail = rawFeaturedProducts.filter(item => Number(item.offer.minimumOrderQuantity) === 1);
  const retail = selectFeaturedProducts(featuredRetail, products.filter(item => Number(item.offer.minimumOrderQuantity) === 1));
  const wholesale = products.filter(item => Number(item.offer.minimumOrderQuantity) > 1).slice(0, 10);
  const cartCount = user ? (await getCart(user.$id)).items.reduce((sum, item) => sum + Number(item.quantity), 0) : 0;
  return <main className="commerce-home">
    <section className="seller-onboarding-banner" aria-labelledby="seller-onboarding-title"><div className="seller-onboarding-icon" aria-hidden="true">🏪</div><div className="seller-onboarding-copy"><span>SELL ACROSS AFRICA</span><h2 id="seller-onboarding-title">Turn your business into a PAC-SM storefront.</h2><p>Register as a seller, complete business verification and list retail or wholesale products for buyers across the continent.</p></div><ul aria-label="Seller benefits"><li>Verified storefront</li><li>Product and inventory tools</li><li>Continental buyer access</li></ul><Link href="/vendor/register">Register as a seller <b>→</b></Link></section>
    <div className="top-strip"><span>🌍 Delivering opportunity across Africa</span><div><Link href="/brands">Shop by Company</Link><Link href="/pre-orders">Pre-orders</Link><Link href="/white-label">White label</Link><Link href="/academy">Trade Academy</Link><Link href="/track">{t("Track shipment")}</Link><Link href="/faq">{t("FAQ")}</Link><Link href="/documentation">{t("Documentation")}</Link><Link href="/developers">{t("Developer API")}</Link><span>{t("Prices in")} {pricing.currency}</span></div></div>
    <header className="commerce-header"><div className="header-main"><Link className="brand commerce-brand" href="/"><span>PAC</span><b>SM</b></Link><form className="global-search" action="/products" method="get"><select name="market" aria-label="Market"><option value="">{t("All markets")}</option><option value="retail">{t("Retail")}</option><option value="wholesale">{t("Wholesale")}</option><option value="global">Global Stores</option></select><input name="q" aria-label="Search products" placeholder={t("Search products, brands and suppliers")} /><button aria-label="Search">⌕</button></form><nav className="account-actions"><Link href={user ? "/account" : "/login"}><small>{user ? accountGreeting(user.name, user.email) : "Hello, sign in"}</small><strong>{t("Account")}</strong></Link><Link href="/orders"><small>{t("Returns &")}</small><strong>{t("Orders")}</strong></Link><Link className="cart-action" href="/cart"><span>🛒</span><strong>{t("Cart")}</strong><i>{cartCount}</i></Link></nav></div><MarketplaceNavigation allCategories={t("All Categories")} sell={t("Sell on PAC-SM")}/></header>

    <section className="shopping-hero"><aside className="category-menu"><h2>{t("Shop categories")}</h2>{categories.documents.map(category => { const design = categoryDesign[String(category.$id)] ?? { icon: "◈", tagline: "Explore products" }; return <Link href={`/products?category=${category.$id}`} key={category.$id}><span>{design.icon}</span><div><strong>{String(category.name)}</strong><small>{design.tagline}</small></div><b>›</b></Link>; })}</aside><div className="hero-promo"><span className="promo-label">THE CONTINENTAL MARKET IS OPEN</span><h1>{t("Made in Africa.")}<br /><em>{t("Ready for the world.")}</em></h1><p>{t("Shop trusted products, source in bulk and move goods across borders—all in one marketplace.")}</p><div><Link className="hero-shop" href="/products">{t("Shop the marketplace")} →</Link><Link className="hero-wholesale" href="/wholesale">{t("Explore wholesale")}</Link></div><div className="hero-orbit"><span>AF</span></div></div><aside className="quick-services"><div className="welcome-card"><span>👋</span><h3>{user ? `Welcome, ${user.name.split(" ")[0]}` : t("Welcome to PAC-SM")}</h3><p>{t("Your gateway to verified African commerce.")}</p><Link href={user ? "/account" : "/register"}>{user ? "Open my account" : t("Join the marketplace")}</Link></div>{[{ icon: "📦", title: t("Track shipment"), href: "/track" }, { icon: "📋", title: "Request a quotation", href: "/procurement" }, { icon: "🚚", title: "Become a carrier", href: "/carriers/apply" }].map(service => <Link className="quick-link" href={service.href} key={service.title}><span>{service.icon}</span><strong>{service.title}</strong><b>›</b></Link>)}</aside></section>

    <section className="service-ribbon">{[{ icon: "✓", title: "Verified sellers", copy: "KYC and KYB reviewed" }, { icon: "♢", title: "Buyer protection", copy: "Returns and disputes" }, { icon: "⌖", title: "Tracked delivery", copy: "Live logistics timeline" }, { icon: "◎", title: "Trade ready", copy: "Compliance built in" }].map(item => <article key={item.title}><span>{item.icon}</span><div><strong>{item.title}</strong><small>{item.copy}</small></div></article>)}</section>

    <section className="vertical-discovery" aria-labelledby="vertical-discovery-title"><div className="vertical-discovery-heading"><div><span>ONE CONTINENTAL PLATFORM</span><h2 id="vertical-discovery-title">Explore more across Africa</h2><p>Discover the marketplace today and preview the specialist PAC-SM verticals being prepared.</p></div><form className="vertical-search" action="/products" method="get"><input name="q" aria-label="Search products, property, vehicles and opportunities across Africa" placeholder="Search products, property, vehicles and opportunities across Africa"/><button>Search</button></form></div><div className="vertical-grid">{PLATFORM_VERTICALS.map(vertical=><Link className="vertical-tile" href={vertical.href} key={vertical.slug} style={{"--tile-accent":vertical.accent} as React.CSSProperties}><span aria-hidden="true">{vertical.icon}</span><h3>{vertical.name}</h3><i>›</i><p>{vertical.summary}</p><b>{vertical.available?"Open now":"Coming soon"}</b></Link>)}</div></section>

    <section className="logistics-partner-strip" aria-labelledby="logistics-partner-title"><div><span>OFFICIAL LOGISTICS PARTNER</span><h2 id="logistics-partner-title">Continental delivery support by Zenith Carex Express.</h2><p>PAC-SM works with Zenith Carex Express to support dependable movement of marketplace goods.</p><Link href="/logistics">Explore logistics and tracking →</Link></div><div className="logistics-partner-logo"><Image src="/zenith-carex-express.png" width={376} height={180} alt="Zenith Carex Express" /></div></section>

    <section className="home-section category-section"><div className="section-title"><div><span>{t("Explore the market").toUpperCase()}</span><h2>{t("Shop by category")}</h2></div><Link href="/products">{t("View all categories")} →</Link></div><div className="category-tiles">{categories.documents.map(category => { const design = categoryDesign[String(category.$id)] ?? { icon: "◈", color: "mint", tagline: "Explore products" }; return <Link className={design.color} href={`/products?category=${category.$id}`} key={category.$id}><span>{design.icon}</span><h3>{String(category.name)}</h3><p>{design.tagline}</p><b>Shop now →</b></Link>; })}</div></section>

    <section className="home-section company-section"><div className="section-title"><div><span>SHOP TRUSTED NAMES</span><h2>Products by company</h2></div><Link href="/brands">View all companies →</Link></div><div className="company-tiles">{BRAND_CATALOGUES.map(brand => <Link href={`/brands/${brand.slug}`} key={brand.slug} style={{ "--company-accent": brand.accent } as React.CSSProperties}><strong>{brand.name}</strong><span>{brand.available ? "Shop products" : "Coming soon"}</span><b>Open collection →</b></Link>)}</div></section>

    <section className="home-section deals-section"><div className="section-title"><div><span>CURATED FOR YOU</span><h2>{t("Featured retail")}</h2></div><Link href="/products?market=retail">{t("See all retail")} →</Link></div><div className="home-product-grid">{retail.map((item, index) => <ProductCard item={item} index={index} pricing={pricing} key={item.product.$id} />)}</div></section>

    <section className="programme-home" aria-labelledby="programme-home-title"><div className="section-title"><div><span>MANUFACTURER OPPORTUNITIES</span><h2 id="programme-home-title">Order ahead or launch your own brand</h2></div><Link href="/seller/programs">Manufacturer programme setup →</Link></div><div className="programme-home-grid"><Link className="preorder-card" href="/pre-orders"><span>01 · RESERVE UPCOMING STOCK</span><div aria-hidden="true">◷</div><h3>Pre-order Marketplace</h3><p>Secure production capacity before release, with visible order windows and estimated dispatch dates.</p><b>Browse pre-orders →</b></Link><Link className="white-label-card" href="/white-label"><span>02 · YOUR BRAND, VERIFIED PRODUCTION</span><div aria-hidden="true">◆</div><h3>White-label Marketplace</h3><p>Find manufacturer-ready products, review minimum runs and submit your branding and packaging brief.</p><b>Explore white-label products →</b></Link></div></section>

    <section className="market-switcher"><Link href="/products?market=retail"><span>01 · EVERYDAY SHOPPING</span><h2>Retail</h2><p>Buy trusted African products in the quantities you need.</p><b>Shop retail →</b></Link><Link href="/wholesale"><span>02 · BUY MORE, SAVE MORE</span><h2>Wholesale</h2><p>Access commercial quantities, tier pricing and verified supply.</p><b>Source in bulk →</b></Link><Link href="/offtakers"><span>03 · RECURRING CORPORATE DEMAND</span><h2>Off-takers</h2><p>Register a company, publish supply requirements and award verified sellers.</p><b>Open Off-taker Centre →</b></Link></section>

    <section className="home-section wholesale-section"><div className="section-title"><div><span>BULK PRICE OPPORTUNITIES</span><h2>{t("Wholesale market")}</h2></div><Link href="/wholesale">{t("Explore wholesale")} →</Link></div><div className="home-product-grid">{wholesale.map((item, index) => <ProductCard item={item} index={index + 2} pricing={pricing} key={item.product.$id} />)}</div></section>

    <section className="continental-services"><div className="trade-callout"><span>TRADE BEYOND BORDERS</span><h2>Source. Verify.<br />Move. Grow.</h2><p>Trade Passports, customs records and verified logistics turn a marketplace order into continental opportunity.</p><div><Link href="/seller/trade">Trade infrastructure →</Link><Link href="/academy">Enter Trade Academy →</Link></div></div><div className="service-grid">{[{ icon: "🎓", title: "Trade & Export Academy", href: "/academy" }, { icon: "🌍", title: "Digital Trade Passport", href: "/seller/trade" }, { icon: "🚚", title: "Logistics Marketplace", href: "/logistics" }, { icon: "🏭", title: "Sell across Africa", href: "/vendor/register" }].map(item => <Link href={item.href} key={item.title}><span>{item.icon}</span><strong>{item.title}</strong><b>↗</b></Link>)}</div></section>

    <section className="newsletter"><div><span>THE CONTINENTAL EDIT</span><h2>Deals, suppliers and trade opportunities.</h2></div><form><input type="email" placeholder="Enter your email address" aria-label="Email address" /><button type="button">Subscribe</button></form></section>
    <footer className="commerce-footer"><div className="footer-brand"><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><p>Africa&apos;s market.<br />One connected continent.</p></div>{[{ title: "Buy", links: [["PAC-SM Products", "/pac-sm-products"], ["Marketplace", "/products"], ["Wholesale", "/wholesale"], ["Orders", "/orders"], ["Track shipment", "/track"]] }, { title: "Sell", links: [["Become a vendor", "/vendor/register"], ["Seller Centre", "/seller"], ["Carrier application", "/carriers/apply"], ["Carrier portal", "/carrier"]] }, { title: "Trade", links: [["Trade Academy", "/academy"], ["Off-taker Centre", "/offtakers"], ["Off-taker registration", "/offtakers/register"], ["Procurement", "/procurement"], ["Trade Passport", "/seller/trade"], ["Logistics", "/logistics"], ["Developer API", "/developers"]] }, { title: "Support", links: [["FAQ", "/faq"], ["Documentation", "/documentation"], ["My account", "/account"], ["Messages", "/account/messages"], ["Disputes", "/account/disputes"], ["Returns", "/orders"]] }].map(column => <div className="footer-column" key={column.title}><h3>{column.title}</h3>{column.links.map(([label, href]) => <Link href={href} key={label}>{label}</Link>)}</div>)}</footer><div className="footer-bottom"><span>© 2026 PAC-SM · Pan-African Continental Super Marketplace</span><span>English · {pricing.currency} · Nigeria</span></div>
    <nav className="mobile-dock"><Link href="/">⌂<span>Home</span></Link><Link href="/products">▦<span>Categories</span></Link><Link href="/cart">🛒<span>Cart</span></Link><Link href="/orders">□<span>Orders</span></Link><Link href="/account">○<span>Account</span></Link></nav>
  </main>;
}
