import Link from "next/link";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { getCart } from "@/src/modules/cart/server/repository";
import { listCategories, listPublicProducts } from "@/src/modules/catalogue/server/repository";
import { getCurrencyDisplay, type CurrencyDisplay } from "@/src/modules/localization/server/currency";
import { getTranslator } from "@/src/modules/localization/server/language";
import { ProductImage } from "@/src/modules/catalogue/ui/product-image";

export const dynamic = "force-dynamic";

const categoryDesign: Record<string, { icon: string; color: string; tagline: string }> = {
  agriculture: { icon: "🌾", color: "sun", tagline: "Food, crops & ingredients" },
  electronics: { icon: "⚡", color: "sky", tagline: "Devices & power" },
  fashion: { icon: "✦", color: "rose", tagline: "Textiles & apparel" },
  home: { icon: "⌂", color: "mint", tagline: "Home & living" },
  industrial: { icon: "⚙", color: "gold", tagline: "Tools & machinery" },
  health: { icon: "✚", color: "lilac", tagline: "Beauty & wellness" }
};

type ProductRow = NonNullable<Awaited<ReturnType<typeof listPublicProducts>>[number]>;
function ProductCard({ item, index, pricing }: { item: ProductRow; index: number; pricing: CurrencyDisplay }) {
  const wholesale = Number(item.offer.minimumOrderQuantity) > 1;
  return <Link className="home-product" href={`/products/${String(item.product.slug)}`}>
    <ProductImage media={item.media} productName={String(item.product.name)} className={`home-product-art art-${index % 6}`} />
    <div className="home-product-body"><span className={`market-badge ${wholesale ? "bulk" : "retail"}`}>{wholesale ? `Wholesale · MOQ ${item.offer.minimumOrderQuantity}` : "Retail"}</span><h3>{String(item.product.name)}</h3><div className="rating">★★★★★ <span>Verified offer</span></div><strong>{pricing.format(Number(item.offer.retailPriceMinor), String(item.offer.currency))}</strong><p>{item.available > 0 ? `${item.available} available` : "Restocking soon"}</p></div>
  </Link>;
}

export default async function Home() {
  const [user, categories, rawProducts, pricing, translator] = await Promise.all([getCurrentAppwriteUser(), listCategories(), listPublicProducts(), getCurrencyDisplay(), getTranslator()]);
  const { t } = translator;
  const products = rawProducts.filter((item): item is ProductRow => Boolean(item));
  const retail = products.filter(item => Number(item.offer.minimumOrderQuantity) === 1).slice(0, 10);
  const wholesale = products.filter(item => Number(item.offer.minimumOrderQuantity) > 1).slice(0, 10);
  const cartCount = user ? (await getCart(user.$id)).items.reduce((sum, item) => sum + Number(item.quantity), 0) : 0;
  return <main className="commerce-home">
    <section className="seller-onboarding-banner" aria-labelledby="seller-onboarding-title"><div className="seller-onboarding-icon" aria-hidden="true">🏪</div><div className="seller-onboarding-copy"><span>SELL ACROSS AFRICA</span><h2 id="seller-onboarding-title">Turn your business into a PAC-SM storefront.</h2><p>Register as a seller, complete business verification and list retail or wholesale products for buyers across the continent.</p></div><ul aria-label="Seller benefits"><li>Verified storefront</li><li>Product and inventory tools</li><li>Continental buyer access</li></ul><Link href="/vendor/register">Register as a seller <b>→</b></Link></section>
    <div className="top-strip"><span>🌍 Delivering opportunity across Africa</span><div><Link href="/track">{t("Track shipment")}</Link><Link href="/faq">{t("FAQ")}</Link><Link href="/documentation">{t("Documentation")}</Link><Link href="/developers">{t("Developer API")}</Link><span>{t("Prices in")} {pricing.currency}</span></div></div>
    <header className="commerce-header"><div className="header-main"><Link className="brand commerce-brand" href="/"><span>PAC</span><b>SM</b></Link><form className="global-search" action="/products" method="get"><select name="market" aria-label="Market"><option value="">{t("All markets")}</option><option value="retail">{t("Retail")}</option><option value="wholesale">{t("Wholesale")}</option></select><input name="q" aria-label="Search products" placeholder={t("Search products, brands and suppliers")} /><button aria-label="Search">⌕</button></form><nav className="account-actions"><Link href={user ? "/account" : "/login"}><small>{user ? "Welcome back" : "Hello, sign in"}</small><strong>{t("Account")}</strong></Link><Link href="/orders"><small>{t("Returns &")}</small><strong>{t("Orders")}</strong></Link><Link className="cart-action" href="/cart"><span>🛒</span><strong>{t("Cart")}</strong><i>{cartCount}</i></Link></nav></div><nav className="market-nav"><Link className="all-categories" href="/products">☰ {t("All Categories")}</Link><Link href="/pac-sm-products">{t("PAC-SM Products")}</Link><Link href="/products?market=retail">{t("Retail")}</Link><Link href="/wholesale">{t("Wholesale")}</Link><Link href="/offtakers">{t("Off-takers")}</Link><Link href="/procurement">{t("Procurement")}</Link><Link href="/seller/trade">{t("Trade")}</Link><Link href="/logistics">{t("Logistics")}</Link><Link href="/products">{t("Today's Deals")}</Link><Link className="sell-cta" href="/vendor/register">{t("Sell on PAC-SM")}</Link></nav></header>

    <section className="shopping-hero"><aside className="category-menu"><h2>{t("Shop categories")}</h2>{categories.documents.map(category => { const design = categoryDesign[String(category.$id)] ?? { icon: "◈", tagline: "Explore products" }; return <Link href={`/products?category=${category.$id}`} key={category.$id}><span>{design.icon}</span><div><strong>{String(category.name)}</strong><small>{design.tagline}</small></div><b>›</b></Link>; })}</aside><div className="hero-promo"><span className="promo-label">THE CONTINENTAL MARKET IS OPEN</span><h1>{t("Made in Africa.")}<br /><em>{t("Ready for the world.")}</em></h1><p>{t("Shop trusted products, source in bulk and move goods across borders—all in one marketplace.")}</p><div><Link className="hero-shop" href="/products">{t("Shop the marketplace")} →</Link><Link className="hero-wholesale" href="/wholesale">{t("Explore wholesale")}</Link></div><div className="hero-orbit"><span>AF</span></div></div><aside className="quick-services"><div className="welcome-card"><span>👋</span><h3>{user ? `Welcome, ${user.name.split(" ")[0]}` : t("Welcome to PAC-SM")}</h3><p>{t("Your gateway to verified African commerce.")}</p><Link href={user ? "/account" : "/register"}>{user ? "Open my account" : t("Join the marketplace")}</Link></div>{[{ icon: "📦", title: t("Track shipment"), href: "/track" }, { icon: "📋", title: "Request a quotation", href: "/procurement" }, { icon: "🚚", title: "Become a carrier", href: "/carriers/apply" }].map(service => <Link className="quick-link" href={service.href} key={service.title}><span>{service.icon}</span><strong>{service.title}</strong><b>›</b></Link>)}</aside></section>

    <section className="service-ribbon">{[{ icon: "✓", title: "Verified sellers", copy: "KYC and KYB reviewed" }, { icon: "♢", title: "Buyer protection", copy: "Returns and disputes" }, { icon: "⌖", title: "Tracked delivery", copy: "Live logistics timeline" }, { icon: "◎", title: "Trade ready", copy: "Compliance built in" }].map(item => <article key={item.title}><span>{item.icon}</span><div><strong>{item.title}</strong><small>{item.copy}</small></div></article>)}</section>

    <section className="home-section category-section"><div className="section-title"><div><span>{t("Explore the market").toUpperCase()}</span><h2>{t("Shop by category")}</h2></div><Link href="/products">{t("View all categories")} →</Link></div><div className="category-tiles">{categories.documents.map(category => { const design = categoryDesign[String(category.$id)] ?? { icon: "◈", color: "mint", tagline: "Explore products" }; return <Link className={design.color} href={`/products?category=${category.$id}`} key={category.$id}><span>{design.icon}</span><h3>{String(category.name)}</h3><p>{design.tagline}</p><b>Shop now →</b></Link>; })}</div></section>

    <section className="home-section deals-section"><div className="section-title"><div><span>CURATED FOR YOU</span><h2>{t("Featured retail")}</h2></div><Link href="/products?market=retail">{t("See all retail")} →</Link></div><div className="home-product-grid">{retail.map((item, index) => <ProductCard item={item} index={index} pricing={pricing} key={item.product.$id} />)}</div></section>

    <section className="market-switcher"><Link href="/products?market=retail"><span>01 · EVERYDAY SHOPPING</span><h2>Retail</h2><p>Buy trusted African products in the quantities you need.</p><b>Shop retail →</b></Link><Link href="/wholesale"><span>02 · BUY MORE, SAVE MORE</span><h2>Wholesale</h2><p>Access commercial quantities, tier pricing and verified supply.</p><b>Source in bulk →</b></Link><Link href="/offtakers"><span>03 · RECURRING CORPORATE DEMAND</span><h2>Off-takers</h2><p>Register a company, publish supply requirements and award verified sellers.</p><b>Open Off-taker Centre →</b></Link></section>

    <section className="home-section wholesale-section"><div className="section-title"><div><span>BULK PRICE OPPORTUNITIES</span><h2>{t("Wholesale market")}</h2></div><Link href="/wholesale">{t("Explore wholesale")} →</Link></div><div className="home-product-grid">{wholesale.map((item, index) => <ProductCard item={item} index={index + 2} pricing={pricing} key={item.product.$id} />)}</div></section>

    <section className="continental-services"><div className="trade-callout"><span>TRADE BEYOND BORDERS</span><h2>Source. Verify.<br />Move. Grow.</h2><p>Trade Passports, customs records and verified logistics turn a marketplace order into continental opportunity.</p><div><Link href="/seller/trade">Trade infrastructure →</Link><Link href="/logistics">Find a carrier →</Link></div></div><div className="service-grid">{[{ icon: "🌍", title: "Digital Trade Passport", href: "/seller/trade" }, { icon: "🚚", title: "Logistics Marketplace", href: "/logistics" }, { icon: "🏭", title: "Sell across Africa", href: "/vendor/register" }, { icon: "🤝", title: "Wholesale Buyer", href: "/wholesale" }].map(item => <Link href={item.href} key={item.title}><span>{item.icon}</span><strong>{item.title}</strong><b>↗</b></Link>)}</div></section>

    <section className="newsletter"><div><span>THE CONTINENTAL EDIT</span><h2>Deals, suppliers and trade opportunities.</h2></div><form><input type="email" placeholder="Enter your email address" aria-label="Email address" /><button type="button">Subscribe</button></form></section>
    <footer className="commerce-footer"><div className="footer-brand"><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><p>Africa&apos;s market.<br />One connected continent.</p></div>{[{ title: "Buy", links: [["PAC-SM Products", "/pac-sm-products"], ["Marketplace", "/products"], ["Wholesale", "/wholesale"], ["Orders", "/orders"], ["Track shipment", "/track"]] }, { title: "Sell", links: [["Become a vendor", "/vendor/register"], ["Seller Centre", "/seller"], ["Carrier application", "/carriers/apply"], ["Carrier portal", "/carrier"]] }, { title: "Trade", links: [["Off-taker Centre", "/offtakers"], ["Off-taker registration", "/offtakers/register"], ["Procurement", "/procurement"], ["Trade Passport", "/seller/trade"], ["Logistics", "/logistics"], ["Developer API", "/developers"]] }, { title: "Support", links: [["FAQ", "/faq"], ["Documentation", "/documentation"], ["My account", "/account"], ["Messages", "/account/messages"], ["Disputes", "/account/disputes"], ["Returns", "/orders"]] }].map(column => <div className="footer-column" key={column.title}><h3>{column.title}</h3>{column.links.map(([label, href]) => <Link href={href} key={label}>{label}</Link>)}</div>)}</footer><div className="footer-bottom"><span>© 2026 PAC-SM · Pan-African Continental Super Marketplace</span><span>English · {pricing.currency} · Nigeria</span></div>
    <nav className="mobile-dock"><Link href="/">⌂<span>Home</span></Link><Link href="/products">▦<span>Categories</span></Link><Link href="/cart">🛒<span>Cart</span></Link><Link href="/orders">□<span>Orders</span></Link><Link href="/account">○<span>Account</span></Link></nav>
  </main>;
}
