import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { findVendorByOwner, getVendorBundle } from "@/src/modules/vendors/server/repository";
import { getSellerWallet } from "@/src/modules/finance/server/withdrawals";

export const dynamic = "force-dynamic";
const money = (value: number, currency: string) => new Intl.NumberFormat("en-NG", { style: "currency", currency }).format(value / 100);
export default async function SellerWalletPage({ searchParams }: { searchParams: Promise<{ requested?: string; error?: string }> }) {
  const user = await getCurrentAppwriteUser(); if (!user) redirect("/login?returnTo=/seller/wallet"); const vendor = await findVendorByOwner(user.$id); if (!vendor) redirect("/vendor/register");
  const [{ balances, requests }, bundle, query] = await Promise.all([getSellerWallet(vendor.$id), getVendorBundle(vendor.$id), searchParams]);
  const account = bundle.compliance ? `${String(bundle.compliance.bankName)} · ${String(bundle.compliance.bankAccountName)} · ending ${String(bundle.compliance.bankAccountNumber).slice(-4)}` : "Verified settlement account";
  return <main className="seller-shell"><nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><Link href="/seller">Seller Centre</Link></nav><header><div><p className="kicker">SELLER WALLET</p><h1>Income and withdrawals</h1><p>Income becomes available after successful delivery. Pending claims are reserved until central finance reviews them.</p>{query.requested && <p className="success-note">Withdrawal request sent to central finance.</p>}{query.error && <p className="form-error">The request could not be created. Check the available balance and amount.</p>}</div></header><section className="wallet-grid">{balances.length ? balances.map(balance => <article key={balance.currency}><span>{balance.currency} WALLET</span><strong>{money(balance.availableMinor, balance.currency)}</strong><dl><div><dt>Ledger balance</dt><dd>{money(balance.ledgerBalanceMinor, balance.currency)}</dd></div><div><dt>Pending claims</dt><dd>{money(balance.pendingMinor, balance.currency)}</dd></div><div><dt>Available to claim</dt><dd>{money(balance.availableMinor, balance.currency)}</dd></div></dl>{balance.availableMinor > 0 && <form action="/api/seller/wallet/withdraw" method="post"><input type="hidden" name="currency" value={balance.currency}/><label>Amount to claim<input name="amount" type="number" min="0.01" max={(balance.availableMinor / 100).toFixed(2)} step="0.01" required/></label><label>Payment destination<input name="payoutAccount" value={account} readOnly/></label><label>Note (optional)<textarea name="sellerNote" maxLength={1000}/></label><button>Request withdrawal</button></form>}</article>) : <article><span>AVAILABLE BALANCE</span><strong>No income due yet</strong><p>Paid, delivered orders will appear here after marketplace commission and adjustments.</p></article>}</section><section className="review-table"><div className="review-row review-head"><span>Request</span><span>Amount</span><span>Requested</span><span>Status</span></div>{requests.length ? requests.map(item => <div className="review-row" key={item.$id}><span>{String(item.requestNumber)}</span><strong>{money(Number(item.amountMinor), String(item.currency))}</strong><span>{new Date(String(item.requestedAt)).toLocaleDateString("en-GB")}</span><span>{String(item.status)}</span></div>) : <p className="empty-state">No withdrawal claims yet.</p>}</section></main>;
}
