import Link from "next/link";
import { requireGlobalCommerceStaff } from "@/src/modules/authorization/server/require-global-commerce-staff";
import { listGlobalFeatureFlags, listGlobalSuppliers } from "@/src/modules/global-commerce/server/repository";

export const dynamic = "force-dynamic";
const setup = ["Create supplier","Add encrypted credential","Test connection","Configure webhook","Configure currencies","Configure pricing","Configure countries","Search products","Import test product","Test shipping","Run test checkout","Test supplier order","Verify tracking","Activate production"];
export default async function GlobalCommercePage({ searchParams }: { searchParams: Promise<{ created?: string; connected?: string; error?: string }> }) { const { canManageCredentials } = await requireGlobalCommerceStaff(); const [suppliers, flags, query] = await Promise.all([listGlobalSuppliers(), listGlobalFeatureFlags(), searchParams]); return <main className="admin-detail global-commerce-admin"><header><div><p className="kicker">GLOBAL SUPPLIER GATEWAY</p><h1>Global Commerce</h1><p>International supply connections controlled commercially by Diplomats Stores.</p></div><Link href="/admin">Admin overview</Link></header>{query.created && <p className="success-note">Supplier saved securely. Test its connection before activation.</p>}{query.connected && <p className="success-note">CJ API 2.0 connection verified and refreshed credentials stored securely.</p>}{query.error && <p className="form-error">The supplier action failed. Check the encryption key, supplier credential and application log.</p>}
  <section className="global-commerce-summary"><article><span>COMMERCIAL OWNER</span><strong>Diplomats Stores</strong><p>All current and future global products remain owned and accounted for through Diplomats Stores.</p></article><article><span>SUPPLIERS</span><strong>{suppliers.total}</strong><p>{suppliers.documents.filter(item => item.connectionStatus === "connected").length} securely connected</p></article><article><span>RELEASE MODE</span><strong>Limited pilot</strong><p>Supplier ordering remains manual until later acceptance gates pass.</p></article></section>
  <section className="global-future"><h2>Phase 6 · Global Checkout</h2><p>Review destination, supplier inventory, price and recent freight validations plus payment-ready fulfilment groups.</p><Link className="global-discovery-link" href="/admin/global-commerce/checkout">Open Checkout Assurance →</Link></section>
  <section className="global-future"><h2>Phase 7 · Order Automation</h2><p>Approve idempotent supplier-order mappings, create unpaid CJ orders and record controlled supplier payment confirmation.</p><Link className="global-discovery-link secondary" href="/admin/global-commerce/orders">Open Global Supplier Orders →</Link></section>
  <section className="global-commerce-layout"><div><section className="global-panel"><div className="global-panel-title"><div><span>SUPPLIER MANAGEMENT</span><h2>Connected supply sources</h2></div></div>{suppliers.documents.length ? suppliers.documents.map(supplier => <article className="supplier-row" key={supplier.$id}><div><strong>{String(supplier.name)}</strong><small>{String(supplier.provider).toUpperCase()} · {String(supplier.integrationType)} · {String(supplier.countryCode)}</small></div><b className={`connection-${String(supplier.connectionStatus)}`}>{String(supplier.connectionStatus).replaceAll("_", " ")}</b><span>Owner: Diplomats Stores</span>{canManageCredentials ? <form action={`/api/admin/global-commerce/suppliers/${supplier.$id}/test`} method="post"><button>Test connection</button></form> : <small>Connection tests require Super Admin.</small>}</article>) : <p className="empty-state">No global suppliers have been configured.</p>}</section>
    {canManageCredentials ? <section className="global-panel"><span>ADD FIRST CONNECTOR</span><h2>Connect CJdropshipping</h2><form className="global-supplier-form" action="/api/admin/global-commerce/suppliers" method="post"><label>Supplier name<input name="name" defaultValue="CJdropshipping" required/></label><label>Internal slug<input name="slug" defaultValue="cj-dropshipping" pattern="[a-z0-9][a-z0-9-]{2,99}" required/></label><label>Origin country<select name="countryCode" defaultValue="CN"><option value="CN">China</option><option value="US">United States</option><option value="DE">Germany</option><option value="GB">United Kingdom</option></select></label><label>Supplier currency<select name="defaultCurrency" defaultValue="USD"><option>USD</option><option>CNY</option><option>EUR</option><option>GBP</option></select></label><label className="credential-field">CJ API key<input name="apiKey" type="password" autoComplete="new-password" minLength={12} required/><small>Encrypted before Appwrite storage. It is never returned to this page.</small></label><button>Save CJ supplier securely</button></form></section> : <section className="global-panel"><span>SECURITY BOUNDARY</span><h2>Credential controls are restricted</h2><p>Your assigned role provides operational visibility. Only Super Admin can add supplier secrets or initiate authentication.</p></section>}</div>
    <aside><section className="global-panel"><span>FEATURE FLAGS</span><h2>Safe initial mode</h2>{flags.documents.map(flag => <div className="feature-flag" key={flag.$id}><strong>{String(flag.key)}</strong><span>{flag.enabled ? "Enabled" : "Disabled"}</span><small>{String(flag.mode)}</small></div>)}</section><section className="global-panel"><span>ACTIVATION CHECKLIST</span><ol>{setup.map((item, index) => <li className={index < 3 ? "current" : "future"} key={item}>{item}</li>)}</ol></section></aside></section>
  <section className="global-future"><h2>Phase 2 · Product Discovery</h2><p>Browse current supplier products, variants, images, stock and warehouse availability.</p><Link className="global-discovery-link" href="/admin/global-commerce/products">Open Global Product Discovery →</Link></section><section className="global-future"><h2>Phase 3 · Controlled Import</h2><p>Map selected CJ products and variants into the Diplomats Stores catalogue review queue without exposing unpriced products to customers.</p><Link className="global-discovery-link secondary" href="/admin/global-commerce/imported">Manage imported products →</Link></section><section className="global-future"><h2>Phase 4 · Landed-cost pricing</h2><p>Configure FX buffers, duties, taxes, freight assumptions, fees and protected PAC-SM margins, then calculate review-ready customer offers.</p><Link className="global-discovery-link" href="/admin/global-commerce/pricing">Open Global Pricing →</Link></section><section className="global-future"><h2>Phase 5 · Synchronization</h2><p>Reconcile supplier costs and buffered warehouse inventory, manage product-specific CJ subscriptions, webhook events and retry-safe runs.</p><Link className="global-discovery-link secondary" href="/admin/global-commerce/sync">Open Global Sync Centre →</Link></section><section className="global-future"><h2>Later modules remain gated</h2><p>Global Checkout, Supplier Orders and Tracking remain unavailable until their acceptance gates pass.</p></section></main>; }
