import "server-only";
import { randomUUID } from "node:crypto";
import { ID,Query } from "node-appwrite";
import { createAppwriteAuthClient,createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { ACADEMY_COURSE } from "@/src/modules/academy/domain/curriculum";
import { ACADEMY_PROJECT_SECTIONS,academyProjectMarks } from "@/src/modules/academy/domain/project";
import { getAcademyDashboard,getAcademyEnrollment } from "./repository";
const db=()=>createAppwriteDatabaseClient().databases;const databaseId=()=>env().APPWRITE_DATABASE_ID;
export async function getAcademyProject(userId:string){const enrollment=await getAcademyEnrollment(userId);if(!enrollment)return{enrollment:null,project:null,milestones:[],certificate:null};const [projects,certificates]=await Promise.all([db().listDocuments({databaseId:databaseId(),collectionId:"academy_projects",queries:[Query.equal("enrollmentId",enrollment.$id),Query.limit(1)]}),db().listDocuments({databaseId:databaseId(),collectionId:"academy_certificates",queries:[Query.equal("enrollmentId",enrollment.$id),Query.limit(1)]})]),project=projects.documents[0]??null,milestones=project?(await db().listDocuments({databaseId:databaseId(),collectionId:"academy_project_milestones",queries:[Query.equal("projectId",project.$id),Query.limit(50)]})).documents:[];return{enrollment,project,milestones,certificate:certificates.documents[0]??null}}
export async function saveAcademyProject(userId:string,input:{title:string;productName:string;originCountry:string;targetMarket:string;sections:ReadonlyMap<string,string>;submit:boolean}){const dashboard=await getAcademyDashboard(userId);if(!dashboard.enrollment||dashboard.passedModuleIds.size<10)throw new Error("Complete assessments first");const title=input.title.trim(),productName=input.productName.trim(),originCountry=input.originCountry.trim().toUpperCase(),targetMarket=input.targetMarket.trim().toUpperCase();if(!title||!productName||!/^[A-Z]{2}$/.test(originCountry)||!/^[A-Z]{2}$/.test(targetMarket))throw new Error("Project identity is incomplete");if(input.submit&&ACADEMY_PROJECT_SECTIONS.some(section=>(input.sections.get(section.code)??"").trim().length<100))throw new Error("Complete every project section");const existing=await getAcademyProject(userId);if(existing.project&&!["draft","changes_requested"].includes(String(existing.project.status)))throw new Error("Project is locked");const now=new Date().toISOString(),data={enrollmentId:dashboard.enrollment.$id,userId,title:title.slice(0,240),productName:productName.slice(0,240),originCountry,targetMarket,status:input.submit?"submitted":"draft",updatedAt:now,...(input.submit?{submittedAt:now}:{})},project=existing.project?await db().updateDocument({databaseId:databaseId(),collectionId:"academy_projects",documentId:existing.project.$id,data}):await db().createDocument({databaseId:databaseId(),collectionId:"academy_projects",documentId:ID.unique(),permissions:[],data:{...data,createdAt:now}});for(const [index,section] of ACADEMY_PROJECT_SECTIONS.entries()){const content=(input.sections.get(section.code)??"").trim();const row=existing.milestones.find(item=>item.milestoneCode===section.code),milestoneData={projectId:project.$id,milestoneCode:section.code,title:section.title,sequence:index+1,content,status:input.submit?"submitted":"draft",...(input.submit?{submittedAt:now}:{})};if(row)await db().updateDocument({databaseId:databaseId(),collectionId:"academy_project_milestones",documentId:row.$id,data:milestoneData});else await db().createDocument({databaseId:databaseId(),collectionId:"academy_project_milestones",documentId:ID.unique(),permissions:[],data:milestoneData})}return project}
export async function listSubmittedProjects(){return db().listDocuments({databaseId:databaseId(),collectionId:"academy_projects",queries:[Query.equal("status",["submitted","graded","changes_requested"]),Query.orderDesc("updatedAt"),Query.limit(200)]})}
export async function getProjectForReview(projectId:string){const project=await db().getDocument({databaseId:databaseId(),collectionId:"academy_projects",documentId:projectId}),milestones=await db().listDocuments({databaseId:databaseId(),collectionId:"academy_project_milestones",queries:[Query.equal("projectId",projectId),Query.orderAsc("sequence"),Query.limit(50)]});return{project,milestones:milestones.documents}}
export async function gradeAcademyProject(projectId:string,assessorId:string,scores:ReadonlyMap<string,number>,feedback:string){const {project,milestones}=await getProjectForReview(projectId);if(project.status!=="submitted")throw new Error("Project not awaiting review");let total=0;for(const section of ACADEMY_PROJECT_SECTIONS){const score=scores.get(section.code)??-1;if(score<0||score>section.marks)throw new Error("Invalid score");total+=score;const row=milestones.find(item=>item.milestoneCode===section.code);if(!row)throw new Error("Missing milestone");await db().updateDocument({databaseId:databaseId(),collectionId:"academy_project_milestones",documentId:row.$id,data:{status:"reviewed",score,feedback:feedback.slice(0,3000),reviewedAt:new Date().toISOString(),reviewedBy:assessorId}})}if(total>academyProjectMarks)throw new Error("Invalid total");const now=new Date().toISOString();await db().updateDocument({databaseId:databaseId(),collectionId:"academy_projects",documentId:projectId,data:{status:total>=ACADEMY_COURSE.passMark?"graded":"changes_requested",scorePercent:total,updatedAt:now}});if(total<ACADEMY_COURSE.passMark)return{score:total,certificate:null};const existing=await db().listDocuments({databaseId:databaseId(),collectionId:"academy_certificates",queries:[Query.equal("enrollmentId",String(project.enrollmentId)),Query.limit(1)]});let certificate=existing.documents[0];if(!certificate){const learner=await createAppwriteAuthClient().users.get({userId:String(project.userId)}),code=randomUUID().replaceAll("-","").slice(0,20).toUpperCase();certificate=await db().createDocument({databaseId:databaseId(),collectionId:"academy_certificates",documentId:ID.unique(),permissions:[],data:{certificateNumber:`PACSM-${new Date().getUTCFullYear()}-${code.slice(0,8)}`,enrollmentId:project.enrollmentId,userId:project.userId,courseId:ACADEMY_COURSE.id,courseVersion:ACADEMY_COURSE.version,learnerName:learner.name||learner.email,status:"active",verificationCode:code,issuedAt:now}})}await db().updateDocument({databaseId:databaseId(),collectionId:"academy_enrollments",documentId:String(project.enrollmentId),data:{status:"completed",completedAt:now,lastActivityAt:now}});return{score:total,certificate}}
export async function verifyAcademyCertificate(code:string){const rows=await db().listDocuments({databaseId:databaseId(),collectionId:"academy_certificates",queries:[Query.equal("verificationCode",code.toUpperCase()),Query.limit(1)]});return rows.documents[0]??null}
