import "server-only";
import { ID,Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { ACADEMY_COURSE,ACADEMY_MODULES,academyLessonCount } from "@/src/modules/academy/domain/curriculum";

const db=()=>createAppwriteDatabaseClient().databases;
const databaseId=()=>env().APPWRITE_DATABASE_ID;
export async function getAcademyEnrollment(userId:string){const rows=await db().listDocuments({databaseId:databaseId(),collectionId:"academy_enrollments",queries:[Query.equal("userId",userId),Query.equal("courseId",ACADEMY_COURSE.id),Query.limit(1)]});return rows.documents[0]??null}
export async function enrollInAcademy(userId:string){const existing=await getAcademyEnrollment(userId);if(existing)return existing;const now=new Date().toISOString();return db().createDocument({databaseId:databaseId(),collectionId:"academy_enrollments",documentId:ID.unique(),permissions:[],data:{userId,courseId:ACADEMY_COURSE.id,courseVersion:ACADEMY_COURSE.version,status:"active",progressPercent:0,enrolledAt:now,lastActivityAt:now}})}
export async function getAcademyDashboard(userId:string){const enrollment=await getAcademyEnrollment(userId);if(!enrollment)return{enrollment:null,completedLessonIds:new Set<string>(),passedModuleIds:new Set<string>(),completedCount:0,progressPercent:0};const [progress,attempts]=await Promise.all([db().listDocuments({databaseId:databaseId(),collectionId:"academy_lesson_progress",queries:[Query.equal("enrollmentId",enrollment.$id),Query.equal("status","completed"),Query.limit(500)]}),db().listDocuments({databaseId:databaseId(),collectionId:"academy_attempts",queries:[Query.equal("enrollmentId",enrollment.$id),Query.equal("status","graded"),Query.limit(100)]})]),completedLessonIds=new Set(progress.documents.map(item=>String(item.lessonId))),passedModuleIds=new Set(attempts.documents.filter(item=>Number(item.scorePercent)>=ACADEMY_COURSE.passMark).map(item=>String(item.assessmentId).replace("assessment-",""))),completedCount=completedLessonIds.size;return{enrollment,completedLessonIds,passedModuleIds,completedCount,progressPercent:Math.round(completedCount/academyLessonCount*100)}}
export function isAcademyModuleUnlocked(moduleId:string,completedLessonIds:ReadonlySet<string>,passedModuleIds:ReadonlySet<string>=new Set()){const index=ACADEMY_MODULES.findIndex(item=>item.id===moduleId);if(index<0)return false;return ACADEMY_MODULES.slice(0,index).every(item=>item.lessons.every(lesson=>completedLessonIds.has(lesson.id))&&passedModuleIds.has(item.id))}
export async function completeAcademyLesson(userId:string,moduleId:string,lessonId:string){const module=ACADEMY_MODULES.find(item=>item.id===moduleId),lesson=module?.lessons.find(item=>item.id===lessonId);if(!module||!lesson)throw new Error("Invalid lesson");const dashboard=await getAcademyDashboard(userId),enrollment=dashboard.enrollment;if(!enrollment||!["active","coursework_completed"].includes(String(enrollment.status)))throw new Error("Enrollment required");if(!isAcademyModuleUnlocked(moduleId,dashboard.completedLessonIds,dashboard.passedModuleIds))throw new Error("Module locked");const lessonIndex=module.lessons.findIndex(item=>item.id===lessonId);if(!module.lessons.slice(0,lessonIndex).every(item=>dashboard.completedLessonIds.has(item.id)))throw new Error("Complete lessons in sequence");const existing=await db().listDocuments({databaseId:databaseId(),collectionId:"academy_lesson_progress",queries:[Query.equal("enrollmentId",enrollment.$id),Query.equal("lessonId",lessonId),Query.limit(1)]}),now=new Date().toISOString();if(existing.documents[0])await db().updateDocument({databaseId:databaseId(),collectionId:"academy_lesson_progress",documentId:existing.documents[0].$id,data:{status:"completed",completedAt:now,lastViewedAt:now}});else await db().createDocument({databaseId:databaseId(),collectionId:"academy_lesson_progress",documentId:ID.unique(),permissions:[],data:{enrollmentId:enrollment.$id,userId,moduleId,lessonId,status:"completed",startedAt:now,lastViewedAt:now,completedAt:now}});const progress=await db().listDocuments({databaseId:databaseId(),collectionId:"academy_lesson_progress",queries:[Query.equal("enrollmentId",enrollment.$id),Query.equal("status","completed"),Query.limit(500)]}),percent=Math.round(progress.total/academyLessonCount*100);await db().updateDocument({databaseId:databaseId(),collectionId:"academy_enrollments",documentId:enrollment.$id,data:{progressPercent:percent,lastActivityAt:now,...(percent===100?{status:"coursework_completed",completedAt:now}:{})}})}
export async function getAcademyAdminSummary(){const [enrollments,progress,attempts,projects,certificates]=await Promise.all([db().listDocuments({databaseId:databaseId(),collectionId:"academy_enrollments",queries:[Query.orderDesc("enrolledAt"),Query.limit(200)]}),db().listDocuments({databaseId:databaseId(),collectionId:"academy_lesson_progress",queries:[Query.limit(5000)]}),db().listDocuments({databaseId:databaseId(),collectionId:"academy_attempts",queries:[Query.limit(5000)]}),db().listDocuments({databaseId:databaseId(),collectionId:"academy_projects",queries:[Query.limit(1000)]}),db().listDocuments({databaseId:databaseId(),collectionId:"academy_certificates",queries:[Query.limit(1000)]})]);return{enrollments:enrollments.documents,recentEnrollments:enrollments.documents.slice(0,20),completedLessons:progress.documents.filter(item=>item.status==="completed").length,submittedAttempts:attempts.documents.filter(item=>item.status==="submitted"||item.status==="graded").length,projectsAwaitingReview:projects.documents.filter(item=>item.status==="submitted").length,certificatesIssued:certificates.documents.filter(item=>item.status==="active").length}}
