import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CommerceModuleHeader, CommerceModuleHero } from "@/app/components/commerce-module-header";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { getBuyerRfq } from "@/src/modules/procurement/server/repository";
export const dynamic = "force-dynamic";
const money = (value:number,currency:string) => new Intl.NumberFormat("en-NG",{style:"currency",currency}).format(value/100);
export default async function RfqComparison({params}:{params:Promise<{rfqId:string}>}) { const user=await getCurrentAppwriteUser(); if(!user) redirect("/login"); const {rfqId}=await params; let data; try { data=await getBuyerRfq(user.$id,rfqId); } catch { notFound(); }
  return <main className="commerce-module"><CommerceModuleHeader current="procurement" utility={{href:"/procurement",label:"All RFQs"}}/><CommerceModuleHero tone="orange" eyebrow="QUOTATION COMPARISON" title={String(data.rfq.title)} description={`${String(data.rfq.quantity)} ${String(data.rfq.unit)} required for delivery to ${String(data.rfq.deliveryCountryCode)}.`} metric={data.quotes.length} metricLabel="supplier quotations received"/><div className="module-body"><section className="module-feature-strip"><article><span>✓</span><div><strong>Comparable bids</strong><small>Structured commercial submissions</small></div></article><article><span>₦</span><div><strong>Total pricing</strong><small>Currency-authoritative values</small></div></article><article><span>◷</span><div><strong>Lead times</strong><small>Supplier delivery commitment</small></div></article><article><span>PO</span><div><strong>One-step award</strong><small>Convert selection to purchase order</small></div></article></section><section className="module-panel"><div className="module-panel-heading"><div><span>SUPPLIER DECISION</span><h2>Compare submitted quotations</h2><p>Review total value, commercial terms and lead time before selecting a supplier.</p></div></div>{data.quotes.length ? <div className="module-data-list">{data.quotes.map(quote => <article className="module-data-card" key={quote.$id}><div><span>{String(quote.status)}</span><h3>{String(quote.quotationNumber)}</h3><p>{String(quote.terms)}</p><small>{String(quote.leadTimeDays)}-day lead time</small></div><div><strong>{money(Number(quote.totalMinor),String(quote.currency))}</strong>{data.rfq.status === "published" && quote.status === "submitted" ? <form action={`/api/procurement/rfqs/${rfqId}/accept`} method="post"><input type="hidden" name="quotationId" value={quote.$id}/><button>Accept and convert to PO</button></form> : <p>Status: {String(quote.status)}</p>}</div></article>)}</div> : <div className="module-empty"><strong>No supplier quotations yet</strong><span>Matched suppliers can submit bids until the quotation deadline.</span></div>}<Link className="module-action-link" href="/procurement">← Return to procurement</Link></section></div></main>;
}
