import "server-only";
import { ID, Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { forecastDemand, orderRiskScore } from "@/src/modules/intelligence/domain/forecast";
const databaseId = () => env().APPWRITE_DATABASE_ID; const db = () => createAppwriteDatabaseClient().databases;

export async function getIntelligenceDashboard() { const database = db(); const [signals, forecasts, recommendations, jobs, metrics] = await Promise.all([database.listDocuments({ databaseId: databaseId(), collectionId: "fraud_signals", queries: [Query.orderDesc("detectedAt"), Query.limit(100)] }), database.listDocuments({ databaseId: databaseId(), collectionId: "demand_forecasts", queries: [Query.orderDesc("generatedAt"), Query.limit(100)] }), database.listDocuments({ databaseId: databaseId(), collectionId: "product_recommendations", queries: [Query.orderDesc("score"), Query.limit(100)] }), database.listDocuments({ databaseId: databaseId(), collectionId: "background_jobs", queries: [Query.orderDesc("createdAt"), Query.limit(100)] }), database.listDocuments({ databaseId: databaseId(), collectionId: "system_metrics", queries: [Query.orderDesc("recordedAt"), Query.limit(100)] })]); return { signals, forecasts, recommendations, jobs, metrics }; }

export async function runIntelligenceRefresh(actorUserId: string) { const database = db(), now = new Date(), job = await database.createDocument({ databaseId: databaseId(), collectionId: "background_jobs", documentId: ID.unique(), permissions: [], data: { jobType: "intelligence_refresh", status: "running", payload: JSON.stringify({ actorUserId }), attempts: 1, maxAttempts: 3, createdAt: now.toISOString(), startedAt: now.toISOString() } }); try { const [products, items, orders, disputes] = await Promise.all([database.listDocuments({ databaseId: databaseId(), collectionId: "products", queries: [Query.equal("status", "approved"), Query.limit(5000)] }), database.listDocuments({ databaseId: databaseId(), collectionId: "order_items", queries: [Query.limit(5000)] }), database.listDocuments({ databaseId: databaseId(), collectionId: "orders", queries: [Query.limit(5000)] }), database.listDocuments({ databaseId: databaseId(), collectionId: "disputes", queries: [Query.limit(5000)] })]); const cutoff30 = Date.now() - 30 * 86400000, cutoff7 = Date.now() - 7 * 86400000, orderDates = new Map(orders.documents.map(order => [order.$id, new Date(String(order.createdAt)).getTime()])); for (const product of products.documents) { const rows = items.documents.filter(item => item.productId === product.$id), units30Days = rows.filter(item => (orderDates.get(String(item.orderId)) ?? 0) >= cutoff30).reduce((sum, item) => sum + Number(item.quantity), 0), recentUnits7Days = rows.filter(item => (orderDates.get(String(item.orderId)) ?? 0) >= cutoff7).reduce((sum, item) => sum + Number(item.quantity), 0), result = forecastDemand(units30Days, recentUnits7Days), vendorId = String(product.submittedByVendorId), documentId = `${product.$id}-${vendorId}`.slice(0, 36); await database.upsertDocument({ databaseId: databaseId(), collectionId: "demand_forecasts", documentId, permissions: [], data: { productId: product.$id, vendorId, units30Days, ...result, generatedAt: now.toISOString() } }); const peers = products.documents.filter(peer => peer.$id !== product.$id && peer.categoryId === product.categoryId).slice(0, 5); for (let index = 0; index < peers.length; index++) await database.upsertDocument({ databaseId: databaseId(), collectionId: "product_recommendations", documentId: `${product.$id}-${peers[index].$id}`.slice(0, 36), permissions: [], data: { productId: product.$id, recommendedProductId: peers[index].$id, strategy: "category_affinity", score: 100 - index * 10, generatedAt: now.toISOString() } }); }
    for (const order of orders.documents) { const orderItems = items.documents.filter(item => item.orderId === order.$id), customerDisputes = disputes.documents.filter(item => item.customerUserId === order.customerUserId).length, risk = orderRiskScore({ totalMinor: Number(order.totalMinor), disputes: customerDisputes, itemQuantity: orderItems.reduce((sum, item) => sum + Number(item.quantity), 0) }); if (risk.score >= 40) { const existing = await database.listDocuments({ databaseId: databaseId(), collectionId: "fraud_signals", queries: [Query.equal("entityType", "order"), Query.equal("entityId", order.$id), Query.limit(1)] }); if (!existing.total) await database.createDocument({ databaseId: databaseId(), collectionId: "fraud_signals", documentId: ID.unique(), permissions: [], data: { signalType: "order_risk", severity: risk.severity, entityType: "order", entityId: order.$id, userId: order.customerUserId, riskScore: risk.score, reasons: risk.reasons.join(","), status: "open", detectedAt: now.toISOString() } }); } }
    await database.createDocument({ databaseId: databaseId(), collectionId: "system_metrics", documentId: ID.unique(), permissions: [], data: { metricName: "intelligence_refresh_duration", value: Date.now() - now.getTime(), unit: "milliseconds", dimensions: JSON.stringify({ products: products.total, orders: orders.total }), recordedAt: new Date().toISOString() } }); await database.updateDocument({ databaseId: databaseId(), collectionId: "background_jobs", documentId: job.$id, data: { status: "completed", completedAt: new Date().toISOString() } }); return { products: products.total, orders: orders.total }; } catch (error) { await database.updateDocument({ databaseId: databaseId(), collectionId: "background_jobs", documentId: job.$id, data: { status: "failed", lastError: String(error).slice(0, 2000), nextAttemptAt: new Date(Date.now() + 300000).toISOString() } }); throw error; } }
