import "server-only";
import { ID, Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { canTransitionTracking, isTrackingStatus } from "@/src/modules/logistics/domain/tracking";
const databaseId = () => env().APPWRITE_DATABASE_ID; const db = () => createAppwriteDatabaseClient().databases;
export const findCarrierApplicationByOwner = async (ownerUserId: string) => (await db().listDocuments({ databaseId: databaseId(), collectionId: "carrier_applications", queries: [Query.equal("ownerUserId", ownerUserId), Query.limit(1)] })).documents[0] ?? null;
export const findCarrierByOwner = async (ownerUserId: string) => (await db().listDocuments({ databaseId: databaseId(), collectionId: "carriers", queries: [Query.equal("ownerUserId", ownerUserId), Query.limit(1)] })).documents[0] ?? null;
export const listCarrierApplications = () => db().listDocuments({ databaseId: databaseId(), collectionId: "carrier_applications", queries: [Query.orderDesc("submittedAt"), Query.limit(200)] });
export const listActiveCarriers = () => db().listDocuments({ databaseId: databaseId(), collectionId: "carriers", queries: [Query.equal("status", "active"), Query.limit(200)] });
export const listCarrierRates = (carrierId?: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "carrier_rates", queries: [...(carrierId ? [Query.equal("carrierId", carrierId)] : [Query.equal("status", "active")]), Query.limit(500)] });
export async function createCarrierApplication(input: Record<string, unknown> & { ownerUserId: string; serviceCountries: string[] }) { return db().createDocument({ databaseId: databaseId(), collectionId: "carrier_applications", documentId: ID.unique(), permissions: [], data: { ...input, serviceCountries: input.serviceCountries.map(code => code.toUpperCase()), status: "submitted", submittedAt: new Date().toISOString() } }); }
export const addCarrierDocument = (data: Record<string, unknown>) => db().createDocument({ databaseId: databaseId(), collectionId: "carrier_documents", documentId: ID.unique(), permissions: [], data });
export async function reviewCarrierApplication(applicationId: string, action: "approve" | "reject" | "request_information", notes: string, actorUserId: string) { const database = db(), application = await database.getDocument({ databaseId: databaseId(), collectionId: "carrier_applications", documentId: applicationId }), status = action === "approve" ? "approved" : action === "reject" ? "rejected" : "information_requested"; await database.updateDocument({ databaseId: databaseId(), collectionId: "carrier_applications", documentId: applicationId, data: { status, reviewedAt: new Date().toISOString(), reviewedBy: actorUserId, ...(notes ? { reviewNotes: notes } : {}) } }); if (action === "approve") await database.createDocument({ databaseId: databaseId(), collectionId: "carriers", documentId: ID.unique(), permissions: [], data: { applicationId, ownerUserId: application.ownerUserId, carrierNumber: `PAC-CAR-${new Date().getUTCFullYear()}-${applicationId.slice(-8).toUpperCase()}`, legalName: application.legalName, ...(application.tradingName ? { tradingName: application.tradingName } : {}), countryCode: application.countryCode, transportModes: application.transportModes, serviceCountries: application.serviceCountries, rating: "0.0", completedShipments: 0, status: "active", activatedAt: new Date().toISOString() } }); await database.createDocument({ databaseId: databaseId(), collectionId: "audit_logs", documentId: ID.unique(), permissions: [], data: { actorUserId, action: `carrier.${action}`, entityType: "carrier_application", entityId: applicationId, metadata: JSON.stringify({ status }), occurredAt: new Date().toISOString() } }); }
export async function addCarrierRate(input: { carrierId: string; serviceName: string; transportMode: string; originCountryCode: string; destinationCountryCode: string; baseRateMinor: number; perKgRateMinor: number; currency: string; estimatedDays: number }) { return db().createDocument({ databaseId: databaseId(), collectionId: "carrier_rates", documentId: ID.unique(), permissions: [], data: { ...input, originCountryCode: input.originCountryCode.toUpperCase(), destinationCountryCode: input.destinationCountryCode.toUpperCase(), currency: input.currency.toUpperCase(), status: "active", createdAt: new Date().toISOString() } }); }
export async function assignShipment(input: { shipmentId: string; carrierId: string; agreedRateMinor: number; currency: string; pickupAddress: string; deliveryAddress: string; actorUserId: string }) { const database = db(), carrier = await database.getDocument({ databaseId: databaseId(), collectionId: "carriers", documentId: input.carrierId }); if (carrier.status !== "active") throw new Error("Carrier unavailable"); const assignment = await database.createDocument({ databaseId: databaseId(), collectionId: "shipment_assignments", documentId: ID.unique(), permissions: [], data: { shipmentId: input.shipmentId, carrierId: input.carrierId, assignmentNumber: `PAC-ASG-${Date.now().toString(36).toUpperCase()}`, status: "assigned", agreedRateMinor: input.agreedRateMinor, currency: input.currency.toUpperCase(), pickupAddress: input.pickupAddress, deliveryAddress: input.deliveryAddress, assignedAt: new Date().toISOString() } }); await addTrackingEvent(input.shipmentId, assignment.$id, "assigned", "", "Shipment assigned to carrier", input.actorUserId); return assignment; }
export async function listCarrierAssignments(carrierId: string) { return db().listDocuments({ databaseId: databaseId(), collectionId: "shipment_assignments", queries: [Query.equal("carrierId", carrierId), Query.orderDesc("assignedAt"), Query.limit(200)] }); }
export async function trackShipment(trackingNumber: string) { const database = db(), shipments = await database.listDocuments({ databaseId: databaseId(), collectionId: "shipments", queries: [Query.equal("trackingNumber", trackingNumber), Query.limit(1)] }), shipment = shipments.documents[0]; if (!shipment) return null; const [assignments, events, pod] = await Promise.all([database.listDocuments({ databaseId: databaseId(), collectionId: "shipment_assignments", queries: [Query.equal("shipmentId", shipment.$id), Query.limit(1)] }), database.listDocuments({ databaseId: databaseId(), collectionId: "shipment_tracking_events", queries: [Query.equal("shipmentId", shipment.$id), Query.orderDesc("occurredAt"), Query.limit(100)] }), database.listDocuments({ databaseId: databaseId(), collectionId: "proofs_of_delivery", queries: [Query.equal("shipmentId", shipment.$id), Query.limit(1)] })]); return { shipment, assignment: assignments.documents[0] ?? null, events: events.documents, proof: pod.documents[0] ?? null }; }
export async function updateAssignmentTracking(input: { assignmentId: string; carrierId: string; status: string; location: string; message: string; actorUserId: string; recipientName?: string; deliveryCode?: string }) { if (!isTrackingStatus(input.status)) throw new Error("Invalid tracking status"); const database = db(), assignment = await database.getDocument({ databaseId: databaseId(), collectionId: "shipment_assignments", documentId: input.assignmentId }); if (assignment.carrierId !== input.carrierId) throw new Error("Assignment not found"); const current = String(assignment.status); if (!isTrackingStatus(current) || !canTransitionTracking(current, input.status)) throw new Error("Invalid tracking transition"); const now = new Date().toISOString(); await database.updateDocument({ databaseId: databaseId(), collectionId: "shipment_assignments", documentId: assignment.$id, data: { status: input.status, ...(input.status === "accepted" ? { acceptedAt: now } : {}), ...(input.status === "delivered" ? { completedAt: now } : {}) } }); await database.updateDocument({ databaseId: databaseId(), collectionId: "shipments", documentId: String(assignment.shipmentId), data: { status: input.status === "picked_up" ? "in_transit" : input.status, updatedAt: now, ...(input.status === "delivered" ? { deliveredAt: now } : {}) } }); await addTrackingEvent(String(assignment.shipmentId), assignment.$id, input.status, input.location, input.message, input.actorUserId); if (input.status === "delivered") { if (!input.recipientName) throw new Error("Recipient is required"); await database.createDocument({ databaseId: databaseId(), collectionId: "proofs_of_delivery", documentId: ID.unique(), permissions: [], data: { shipmentId: assignment.shipmentId, assignmentId: assignment.$id, recipientName: input.recipientName, ...(input.deliveryCode ? { deliveryCode: input.deliveryCode } : {}), deliveredAt: now, confirmedBy: input.actorUserId } }); await database.incrementDocumentAttribute({ databaseId: databaseId(), collectionId: "carriers", documentId: input.carrierId, attribute: "completedShipments", value: 1 }); } }
async function addTrackingEvent(shipmentId: string, assignmentId: string, status: string, location: string, message: string, actorUserId: string) { return db().createDocument({ databaseId: databaseId(), collectionId: "shipment_tracking_events", documentId: ID.unique(), permissions: [], data: { shipmentId, assignmentId, status, ...(location ? { location } : {}), message, actorUserId, occurredAt: new Date().toISOString() } }); }
