import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { findVendorByOwner } from "@/src/modules/vendors/server/repository";
import { listCategories, listVendorProducts } from "@/src/modules/catalogue/server/repository";
import { listVendorProductMedia } from "@/src/modules/catalogue/server/media";
import { ProductImage } from "@/src/modules/catalogue/ui/product-image";
import { AiProductDraft } from "./ai-product-draft";
import { BulkProductUpload } from "./bulk-product-upload";
import { CountrySelect } from "@/app/components/country-phone-fields";

export const dynamic = "force-dynamic";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ published?: string; error?: string; media?: string }> }) {
  const user = await getCurrentAppwriteUser();
  if (!user) redirect("/login?returnTo=/seller/products");
  const vendor = await findVendorByOwner(user.$id);
  if (!vendor) redirect("/vendor/register");
  if (!["approved", "active"].includes(String(vendor.status))) redirect("/seller");
  const [categories, products, media, query] = await Promise.all([listCategories(), listVendorProducts(vendor.$id), listVendorProductMedia(vendor.$id), searchParams]);
  const mediaByProduct = new Map<string, typeof media.documents>();
  for (const item of media.documents) { const key = String(item.productId), rows = mediaByProduct.get(key) ?? []; rows.push(item); mediaByProduct.set(key, rows); }

  return <main className="seller-shell"><nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><Link href="/seller">Seller Centre</Link></nav>
    <header><div><p className="kicker">CATALOGUE</p><h1>Products</h1><p>Approved sellers publish products and up to eight validated images immediately. PAC-SM may take down listings that do not meet marketplace standards.</p></div></header>
    {query.published && <p className="success-note">Product published. Add its product images below.</p>}{query.error && <p className="form-error">The product could not be published. Check every field.</p>}
    <BulkProductUpload categories={categories.documents.map(category => ({ id: category.$id, name: String(category.name) }))}/>
    <AiProductDraft />
    {query.media === "published" && <p className="success-note">Images published successfully.</p>}{query.media === "updated" && <p className="success-note">Product media updated.</p>}{query.media === "error" && <p className="form-error">The image operation failed. Use JPEG, PNG or WebP files up to 8 MB each, with no more than eight images per product.</p>}
    <form className="vendor-form product-form" action="/api/seller/products" method="post"><fieldset><legend>Product identity</legend><label>Name<input name="name" required /></label><label>URL slug<input name="slug" pattern="[a-z0-9-]+" required /></label><label>Category<select name="categoryId" required>{categories.documents.map(category => <option key={category.$id} value={category.$id}>{String(category.name)}</option>)}</select></label><label>Brand<input name="brandName" /></label><label>Manufacturer<input name="manufacturer" /></label><CountrySelect name="countryOfOrigin" label="Country of origin" /><label>Model<input name="model" /></label><label>GTIN / barcode<input name="gtin" /></label><label className="wide">Description<textarea name="description" required /></label><label className="wide">Specifications (one item per line)<textarea name="specifications" required /></label></fieldset><fieldset><legend>Variant and offer</legend><label>Variant name<input name="variantName" placeholder="Standard" required /></label><label>Seller SKU<input name="sku" required /></label><label className="wide">Variant attributes<input name="variantAttributes" placeholder="Colour: Black; Size: Large" required /></label><label>Retail price<input name="retailPrice" type="number" min="0.01" step="0.01" required /></label><label>Wholesale price<input name="wholesalePrice" type="number" min="0.01" step="0.01" /></label><label>Currency<input name="currency" defaultValue="NGN" minLength={3} maxLength={3} required /></label><label>Minimum order quantity<input name="minimumOrderQuantity" type="number" min="1" defaultValue="1" required /></label><label>Fulfilment<select name="fulfilmentMethod"><option value="vendor">Fulfilled by vendor</option><option value="pacsm_logistics">PAC-SM logistics</option></select></label><label>Processing days<input name="processingDays" type="number" min="0" max="90" defaultValue="2" required /></label></fieldset><button>Publish product</button></form>
    <section className="seller-media-list"><h2>Your published products and images</h2>{products.documents.length ? products.documents.map(product => { const productMedia = mediaByProduct.get(product.$id) ?? []; const primary = productMedia.find(item => String(item.isPrimary) === "true") ?? productMedia[0]; return <article className="seller-media-product" key={product.$id}><div className="seller-media-summary"><ProductImage media={primary} productName={String(product.name)} className="seller-media-cover"/><div><strong>{String(product.name)}</strong><p>{String(product.status).replaceAll("_", " ")} · {productMedia.length}/8 images</p><small>Submitted {new Date(String(product.submittedAt)).toLocaleDateString("en-GB")}</small></div></div><form className="media-upload-form" action={`/api/seller/products/${product.$id}/media`} method="post" encType="multipart/form-data"><label>Accessible image description<input name="altText" required minLength={3} maxLength={180} placeholder={`${String(product.name)} product view`}/></label><label>Add images<input name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple required /></label><small>JPEG, PNG or WebP · 8 MB each · maximum eight per product</small><button type="submit">Publish images</button></form>{productMedia.length > 0 && <div className="seller-media-grid">{productMedia.map(item => <article key={item.$id}><ProductImage media={item} productName={String(product.name)} className="seller-media-thumb"/><div><strong>{String(item.status).replaceAll("_", " ")}{String(item.isPrimary) === "true" ? " · primary" : ""}</strong><small>{String(item.altText)}</small><form action={`/api/seller/products/media/${item.$id}`} method="post">{item.status === "approved" && String(item.isPrimary) !== "true" && <button name="action" value="primary">Make primary</button>}<button className="danger" name="action" value="delete">Delete</button></form></div></article>)}</div>}</article>; }) : <p>No products published yet.</p>}</section>
  </main>;
}
