export type FaqItem = { question: string; answer: string };
export type FaqGroup = { id: string; title: string; intro: string; items: FaqItem[] };

export const faqGroups: FaqGroup[] = [
  { id:"getting-started",title:"Getting started",intro:"Accounts, regional preferences and marketplace basics.",items:[
    {question:"What is PAC-SM?",answer:"PAC-SM is a Pan-African multi-vendor marketplace for retail shopping, wholesale purchasing, institutional procurement, logistics and cross-border trade support."},
    {question:"Do I need an account to browse?",answer:"No. You can browse products, categories, standards, carriers and public marketplace information without signing in. An account is required to place orders, save items, message participants or submit applications."},
    {question:"Can I register or sign in with Gmail?",answer:"Yes. Choose Register with Google or Continue with Google. Google handles the identity check and PAC-SM exchanges the one-time result for its own secure, HttpOnly Appwrite session. Gmail and managed Google Workspace accounts are supported when the Google provider is enabled in Appwrite."},
    {question:"How can I tell that I am signed in?",answer:"Before authentication, the homepage account control reads Hello, sign in. After password or Google sign-in, it immediately changes to Hello followed by the first name stored on the secure Appwrite account, such as Hello, Stephen or Hello, Priest, and opens the member's Account page."},
    {question:"How do I verify an email-and-password account?",answer:"After registration, PAC-SM sends a verification link to the registered inbox. Open the link and press Verify email. The button prevents automated email scanners from consuming the link. If the link opens without an active PAC-SM session, sign in when prompted and PAC-SM safely returns you to the same verification link. Expired links can be replaced from the Account page."},
    {question:"How does PAC-SM identify my country?",answer:"PAC-SM checks a saved regional preference, your registered profile country and trusted reverse-proxy country headers, in that order. If none is available, Nigeria is used as the safe default."},
    {question:"Can I change the detected language and currency?",answer:"Yes. Use the flag, language and currency controls at the top of every page. The currency list covers currencies used by all sovereign African countries plus selected major international currencies. Your selections are saved for one year."},
    {question:"Do product prices actually convert when I change currency?",answer:"Yes. Public product, offer and store prices are converted into the selected display currency using current server-fetched ExchangeRate-API rates. The selector submits and reloads the current page with converted prices. Orders, checkout, refunds and settlements retain the original transaction currency as the legally and financially authoritative amount."},
    {question:"How current are converted prices?",answer:"Exchange rates update daily and PAC-SM caches the rate table for up to 24 hours. A secondary ExchangeRate-API endpoint and the last successfully loaded rate table protect currency changes from temporary network failures. If no valid rate has ever been retrieved for a currency, PAC-SM safely displays the original offer currency rather than inventing a rate. Currency refreshes use batched catalogue reads and retry transient Appwrite read failures."},
    {question:"Which languages are currently selectable?",answer:"English, French, Arabic, Portuguese, Kiswahili and Spanish are available. Selecting a language reloads the current page with server-rendered translations for the global controls and primary customer marketplace. Arabic also activates right-to-left document direction. Seller-authored product names and descriptions remain in their submitted language to preserve catalogue accuracy."},
    {question:"Where can I find help and platform guidance?",answer:"Use FAQ or Documentation in the utility menu at the top of the marketplace homepage. Both resources are also available under Support in the homepage footer."}
    ,{question:"What is the official PAC-SM website?",answer:"The canonical production marketplace is https://africancontinentalmarketplace.store. PAC-SM redirects requests from other production hostnames before sign-in, and Google callbacks carry a short-lived signed state token so proxy or browser cookie behavior cannot lose the protected return context. Authentication, payment and email links return to this HTTPS hostname."}
    ,{question:"How do I return to the homepage from anywhere in PAC-SM?",answer:"Every page except the homepage displays a floating Back to home control. It stays visible while you browse customer, wholesale, account, checkout, seller, operations and administration pages. On mobile it sits above the bottom navigation so it does not cover marketplace controls."}
  ]},
  { id:"buying",title:"Buying and orders",intro:"Retail catalogue, cart, checkout and buyer protection.",items:[
    {question:"How do I find a product?",answer:"Use the global search bar, homepage category tiles or marketplace filters. You can filter by retail or wholesale market and by product category."},
    {question:"How does the retail marketplace help me shop?",answer:"The professionally designed retail catalogue provides a dedicated search bar, marketplace channels, category shortcuts, stock filtering, price and name sorting, verified-seller cues, buyer-protection information and responsive product cards. Select a product to compare active seller offers, stock, quantities and prices before adding the preferred offer to cart."},
    {question:"What are PAC-SM Products?",answer:"PAC-SM Products are house-brand agro, food and beverage goods sold through PAC-SM. Open PAC-SM Products from the homepage marketplace menu to browse approved products, available stock and retail or wholesale offers."},
    {question:"Where is the official PAC-SM logo used?",answer:"The official Pan-African Continental Super Marketplace logo appears in the shared brand space across marketplace, account, seller, administrator, help and authentication pages. Its shared display space is enlarged by 40 percent and uses contain sizing so the original proportions remain preserved on desktop and mobile."},
    {question:"Can one cart contain products from multiple sellers?",answer:"Yes. PAC-SM keeps one customer cart and splits checkout into vendor-specific orders while retaining a single parent order for the buyer."},
    {question:"How is product availability protected?",answer:"Availability is revalidated on the server during checkout and stock is reserved atomically. The platform prevents checkout when the required stock is no longer available."},
    {question:"What happens after I press Place order and pay?",answer:"PAC-SM validates the address, coupon, price and stock, creates the parent and vendor orders, and immediately starts the payment method selected on checkout. Demo capture completes inside PAC-SM; configured live providers redirect to their secure hosted payment page. If a provider is interrupted, the pending order remains available for payment retry."},
    {question:"Where can I see my orders?",answer:"Open Orders from the marketplace header or visit your account. Each order shows vendor-specific fulfilment, shipment and return information."},
    {question:"How do returns and disputes work?",answer:"Eligible delivered orders can enter the returns workflow. If a transaction problem cannot be resolved normally, the buyer can create a dispute with an auditable case history for administrative review."},
    {question:"Are product reviews verified?",answer:"Reviews are tied to eligible order items so PAC-SM can distinguish verified-purchase feedback from unauthenticated comments."}
  ]},
  { id:"wholesale",title:"Wholesale and procurement",intro:"Business buying, price tiers, purchase orders and RFQs.",items:[
    {question:"What makes a product wholesale?",answer:"Wholesale offers have a minimum order quantity greater than one and may include quantity-based price tiers."},
    {question:"How do I become a business buyer?",answer:"Submit the wholesale business-buyer application with your organization and registration details. Administrative approval unlocks controlled commercial purchasing workflows."},
    {question:"Can I negotiate a wholesale price below the listed tiers?",answer:"Yes. Negotiation is enabled by default for wholesale offers unless the seller disables it. An approved business buyer selects Request a negotiated price, proposes a quantity and unit price, and receives an instant in-app response. The seller may accept, reject or counter. An accepted offer is time-limited, locked to the agreed quantity and price, and can be used once at checkout."},
    {question:"What happens when I select a wholesale product?",answer:"The product opens on its own full-screen transaction page rather than expanding inside the catalogue grid. The page presents the product, approved images, supply details, quantity tiers, buyer status, published-price checkout and price-negotiation form without unrelated products competing for space."},
    {question:"What is the difference between buying at the listed wholesale price and requesting a negotiated price?",answer:"Buy at listed wholesale price calculates the applicable published quantity tier, creates a linked purchase order and sends the approved business buyer directly to delivery and payment. Request a negotiated price sends a proposed unit price to the seller for acceptance, rejection or counteroffer. Once accepted, PAC-SM creates the negotiation-sourced purchase order and opens checkout with the exact agreed quantity and price."},
    {question:"How does a wholesale purchase reach payment and fulfilment?",answer:"Both listed-price and accepted-negotiation paths create a server-authoritative purchase order and checkout item. Checkout revalidates buyer approval, source offer, quantity, unit price, currency, purchase order, negotiation where applicable and live stock before reserving inventory. The buyer selects a delivery address and payment method, completes payment, and the resulting marketplace and vendor orders retain the purchase-order reference for fulfilment, delivery, finance and audit history."},
    {question:"What happens if I need to add an address during wholesale checkout?",answer:"Select Add address and return to checkout. PAC-SM carries a protected internal checkout destination into the address form. After the address is saved successfully, you return directly to delivery and payment, where the new address is selected and the wholesale purchase order remains in your cart."},
    {question:"How do wholesale counteroffers work?",answer:"Only the party whose response is required can act. After a seller counteroffer, the buyer can accept, reject or counter; after a buyer counteroffer, the seller can accept, reject or counter. Every successful response updates the offer, status, timeline and notification together. The page clearly shows whose response is required and gives a specific explanation when an action is unavailable. Buyers may withdraw an open request, while expired or previously converted offers cannot be used."},
    {question:"How do sellers control negotiated discounts?",answer:"In Seller Centre → Wholesale, sellers enable negotiation per offer and set minimum negotiable quantity, a confidential price floor, maximum discount, expiry period and whether counteroffers are allowed. The confidential limits are enforced by the server and are never shown to buyers."},
    {question:"Where does Super Admin respond to a wholesale negotiation?",answer:"Open Super Admin Centre and select the highlighted Wholesale Negotiations link in the sidebar, the orange Review buyer negotiations banner, or the Wholesale Negotiations operations card. Select Review & respond beside a PAC-SM-owned or demo-product request, then accept, reject or counter. Independent-seller requests must be answered from that seller's Seller Centre."},
    {question:"Who responds to negotiations for PAC-SM demo products?",answer:"Super Admin can open Admin Centre → Wholesale Negotiations and select Review & respond for PAC-SM-owned or demo inventory. The administrator may accept, reject or counter while their real user ID is recorded in the audit timeline. Super Admin cannot respond for an independent seller."},
    {question:"What is an RFQ?",answer:"A Request for Quotation lets an approved business buyer publish a requirement, invite matching vendors, compare quotations and award the preferred supplier."},
    {question:"Can an RFQ become a purchase order?",answer:"Yes. An accepted quotation can be converted into a commercial purchase order and proforma invoice while preserving the procurement history."},
    {question:"Why do Off-takers, Procurement, Trade and Logistics now look consistent?",answer:"These continental commerce centres use PAC-SM's shared module design system. They have the same navigation, responsive hero structure, workflow guidance, professional forms, status metrics, data panels, empty states and mobile behavior, while each module retains a distinct color tone and its own operational functions."},
    {question:"Does PAC-SM support bulk pricing?",answer:"Yes. Sellers can define offer-level price tiers with minimum and optional maximum quantities. The most specific eligible tier is used."}
  ]},
  { id:"offtakers",title:"Off-takers and supply agreements",intro:"Verified institutional demand, supplier proposals and scheduled purchasing.",items:[
    {question:"Who can register as an off-taker?",answer:"Processors, exporters, retailers, hospitality groups, institutions and other companies seeking recurring or bulk supply can apply through Off-takers in the homepage menu or Off-taker registration in the Trade footer. PAC-SM reviews company and buying information before publishing access is enabled."},
    {question:"How does an approved off-taker source products?",answer:"The off-taker publishes a structured requirement with quantity, specification, packaging, certification, origin, delivery, deadline and payment terms. Matching sellers can submit supply proposals."},
    {question:"Can an off-taker appoint more than one supplier?",answer:"Yes. An off-taker may shortlist proposals and split an award among multiple suppliers. Each award receives its own scheduled purchase-order reference under the shared supply agreement."},
    {question:"How are delivery and payment controlled?",answer:"Authorized staff inspect scheduled deliveries and record accepted quantities. Payment milestones remain visible as due, processing, paid, settled or failed; production money movement requires the configured approved payment or banking connector."},
    {question:"What happens when there is a supply disagreement?",answer:"The off-taker can open a dispute against an agreement or scheduled purchase order. Authorized staff review the evidence and record the resolution in the operational history."}
  ]},
  { id:"selling",title:"Selling on PAC-SM",intro:"Vendor registration, products, inventory and operations.",items:[
    {question:"How do I register as a seller and open a storefront?",answer:"Choose Register as a seller in the prominent homepage banner or Sell on PAC-SM in the marketplace menu. Sign in or create an account, complete the vendor application, provide business and settlement details, choose a store name and upload the required KYC/KYB documents. PAC-SM activates Seller Centre and storefront capabilities after the application is approved."},
    {question:"Who can become a vendor?",answer:"Registered companies, partnerships, sole proprietors, cooperatives, manufacturers, farmers, wholesalers, distributors, exporters and other supported business types may apply."},
    {question:"What documents are required for vendor verification?",answer:"The onboarding workflow requires a business registration certificate, tax document and director or owner identity document. Additional information may be requested during KYC or KYB review."},
    {question:"Where are private verification documents stored?",answer:"Documents are stored in a private encrypted Appwrite bucket. They are retrieved through authorized server routes and are not exposed as public files."},
    {question:"Can sellers add products immediately?",answer:"Yes, after the seller account is approved. A valid product, variant and offer publish automatically to the marketplace without waiting in a pre-approval queue. Super Admin continuously moderates the live catalogue and may request changes, take down, reject, restore or permanently delete a listing that does not meet PAC-SM store standards."},
    {question:"Can AI help me complete the product upload form?",answer:"Yes. In Seller Centre → Products, enter the product name, select its category, add any known facts and choose Generate with AI. PAC-SM returns an editable description, slug, specifications, variant suggestions, search keywords and questions about missing facts. Choose Fill empty fields or Replace draft fields, verify every statement, complete factual fields such as origin and price yourself, then publish normally. AI never publishes automatically and must not be used as evidence of certification, ingredients, origin, performance or regulatory approval."},
    {question:"Where can I start uploading a new product?",answer:"The Upload new product button remains visible throughout PAC-SM. Approved sellers go directly to the product publishing form. Visitors must first sign in or create an account, registered users without a vendor profile continue to the complete seller application, and applicants who are still under review see their verification status. Product publishing unlocks only after PAC-SM approves or activates the vendor."},
    {question:"How do sellers add product images?",answer:"From Seller Centre → Products, open an owned product and upload JPEG, PNG or WebP images. Each file may be up to 8 MB and each product may have up to eight images. PAC-SM validates the declared type and image signature, then publishes valid images immediately for approved sellers. Super Admin may reject an unsuitable image or take down its product."},
    {question:"Can every seller personalise a storefront?",answer:"Yes. All seller stores use PAC-SM's shared professional storefront layout so navigation, product cards, mobile behaviour, checkout links and buyer-trust information remain consistent. From Seller Centre → My Store, the owner can choose primary and accent colours and upload a proportionally fitted JPEG, PNG or WebP logo up to 4 MB. PAC-SM Products uses the same storefront design."},
    {question:"Where can a seller see income and claim a payout?",answer:"Open Seller Centre → Wallet. The wallet derives income from PAC-SM's vendor-payable ledger after successful delivery, commission, refunds and prior settlements. It separately shows ledger balance, pending claims and the amount available to withdraw. Submit a claim to the verified settlement account; central finance can approve and mark it paid or reject it with an audited review."},
    {question:"Can a seller choose the main product image?",answer:"Yes. The first valid upload becomes primary automatically, and the seller can later select another published image as primary. Super Admin can also change or reject images during post-publication moderation."},
    {question:"Can PAC-SM staff create seller accounts for assisted onboarding?",answer:"Yes. A Super Admin can grant the Seller Onboarding Manager role to a registered staff email. That administrator can create a seller's Appwrite login, active vendor identity and store in one audited operation. The temporary password is handed to the seller through a secure channel and is never stored in marketplace records. The seller must change it from Account Security after first sign-in. Approved sellers receive automatic catalogue publishing subject to ongoing Super Admin enforcement, while banking, KYC/KYB and settlement compliance remain required for protected financial operations."},
    {question:"How do sellers manage inventory?",answer:"Sellers can create warehouses, receive stock and review balances. PAC-SM records inventory movements and reservations rather than silently replacing history."},
    {question:"How do I check whether a product is ready for a specific export market?",answer:"Open Seller Centre → ExportReady. Create a structured product profile, record or confirm its international six-digit HS classification, then choose a destination country. PAC-SM evaluates only published, effective, official-source rules for that origin, destination, product category and HS prefix. A high numerical score never overrides missing mandatory evidence, and domestic marketplace availability remains separate from export readiness."},
    {question:"Can sellers connect external systems?",answer:"Yes. Approved vendors can create scoped API credentials, read products, inventory and orders, update controlled inventory fields and register signed webhook endpoints."}
  ]},
  { id:"logistics",title:"Logistics and carriers",intro:"Carrier marketplace, dispatch and public tracking.",items:[
    {question:"Who is PAC-SM's official logistics partner?",answer:"Zenith Carex Express is presented as PAC-SM's official logistics partner. Its official logo appears on the marketplace homepage and Logistics page with its original aspect ratio preserved. Available shipment routes, prices, assignments and tracking remain governed by the applicable PAC-SM logistics records and service terms."},
    {question:"How can a logistics company join PAC-SM?",answer:"Create an account and submit the carrier application with company, fleet, coverage, insurance and private verification documents."},
    {question:"How are carriers verified?",answer:"Authorized logistics staff review registration, insurance and operational details before activating a carrier number and marketplace profile."},
    {question:"Can carriers publish rates?",answer:"Verified carriers can publish service routes with origin, destination, transport mode, base rate, per-kilogram rate, currency and estimated delivery time."},
    {question:"How do I track a shipment?",answer:"Open Track Shipment and enter the carrier tracking number. Public tracking shows the current state, location updates, event messages and delivery confirmation."},
    {question:"What is proof of delivery?",answer:"When a carrier records delivery, PAC-SM stores the recipient, delivery time and optional delivery code as a controlled proof-of-delivery record."},
    {question:"Can tracking statuses be changed backwards?",answer:"No. The logistics state machine allows controlled forward transitions. Exceptions can be recorded and recovered into valid in-transit states."}
  ]},
  { id:"trade",title:"Trade, standards and certification",intro:"Export readiness, documents and destination compliance.",items:[
    {question:"What is the Digital Trade Passport?",answer:"It is a reviewed vendor export-readiness profile containing target markets, product categories, exporter information, Incoterms, transport modes, certifications and supporting documents."},
    {question:"What does the readiness score mean?",answer:"The score summarizes completion of exporter details, markets, categories, Incoterms, transport modes, certifications and documents. It supports review but does not replace a regulator decision."},
    {question:"What is the Product Standards Hub?",answer:"The hub organizes product standards, packaging and labelling rules, certification requirements and verified quality centres by category and destination country."},
    {question:"Who enters product standards?",answer:"Authorized trade-compliance staff enter standards from authoritative government, standards-body or accreditation sources. PAC-SM does not invent regulatory rules."},
    {question:"How does a seller request certification?",answer:"From Seller Compliance, select an owned product, an applicable requirement and optionally a preferred quality centre, then submit the product and testing notes."},
    {question:"Does PAC-SM approval replace customs or regulatory approval?",answer:"No. PAC-SM records marketplace compliance reviews and supporting evidence. Government, customs, standards and accreditation authorities retain their legal powers."}
    ,{question:"Can AI make an HS classification legally final?",answer:"No. HS classifications progress through AI suggested, vendor confirmed, PAC-SM reviewed, customs-broker verified and customs-ruling verified states. PAC-SM stores confidence, reasoning, nomenclature version and review history, but the competent customs authority remains authoritative."}
    ,{question:"How do I request an AI HS6 suggestion?",answer:"First complete the structured export profile in Seller Centre → ExportReady. Then open AI HS6 from Seller Centre, select the profiled product and generate a suggestion. The assistant returns an HS2022 six-digit code, confidence, reasoning, alternatives, attributes used and questions when facts are missing. Review the result and confirm the correct classification manually; Trade Compliance can then record a PAC-SM review."}
    ,{question:"Can one compliance certificate cover several products?",answer:"Yes. Upload the private document once in Trade Passport, then open Seller Centre → Evidence Vault. Link it to a requirement code, issuer, validity dates, relevant HS codes and every owned product it covers. The evidence starts as verification required and cannot satisfy a mandatory rule until authorized review confirms it."}
  ]},
  { id:"finance",title:"Payments and finance",intro:"Payment status, ledgers, refunds and settlements.",items:[
    {question:"Which retail payment methods are available?",answer:"PAC-SM DemoPay, Paystack and PAPSS are selectable during checkout. Without live provider credentials, each option runs an explicitly labelled sandbox capture and charges no money. Adding the server-only Paystack key automatically changes Paystack to its secure hosted checkout. PAPSS remains simulated until certified merchant or participating-bank connector onboarding is complete."},
    {question:"How is a Paystack payment confirmed?",answer:"PAC-SM initializes the transaction on the server, sends the buyer to Paystack, and verifies the returned reference, successful status, order metadata, currency and exact minor-unit amount on the server before marking the order paid or releasing reserved stock. Browser claims alone are never accepted."},
    {question:"Can I safely retry an interrupted payment?",answer:"Yes. An unpaid order remains in pending-payment state with its inventory reservation, and the order page offers the payment methods again. Successful capture is idempotent, so a repeated callback does not sell stock twice or create a second payment."},
    {question:"How are seller earnings calculated?",answer:"Effective commission rules are applied and financial movements are posted to balanced journal entries. Seller wallet balances are projections of the ledger."},
    {question:"When does a vendor become eligible for settlement?",answer:"Settlement eligibility follows successful fulfilment and applicable return or dispute controls. Administrators can review settlement reports before processing."},
    {question:"Are refunds audited?",answer:"Yes. Return decisions, refund records, financial reversals and related journal entries remain connected to their originating order."}
    ,{question:"How do administrators manage paid orders and delivery?",answer:"The Super Admin opens Orders & Delivery to see the buyer's name, email, account phone, recipient phone, complete delivery address including both street lines, city, state or region, postal code and country, together with payment details, purchased products, quantities and vendor fulfilment stages. Unpaid orders remain locked. Paid orders can move into processing, warehouse picking and packing, dispatch with carrier tracking, and confirmed delivery."}
  ]},
  { id:"security",title:"Security and administration",intro:"Authentication, roles, private data and operational controls.",items:[
    {question:"How is Google sign-in protected?",answer:"PAC-SM uses Appwrite's OAuth token flow and a short-lived HMAC-signed state token containing a random nonce, issue time and safe internal return path. Signature verification uses constant-time comparison, rejects expiry or tampering and does not depend on a browser state cookie surviving cross-service redirects. Production signs with the server-only runtime credential; localhost uses an ephemeral cryptographic development secret. PAC-SM exchanges the one-time OAuth token through Appwrite's Account REST endpoint, extracts only the project-specific server session cookie and stores its decoded secret in the marketplace's secure HttpOnly cookie."},
    {question:"What must be configured before verification emails work?",answer:"PAC-SM uses Resend for email delivery. The self-hosted Appwrite service must use Resend SMTP so Appwrite can securely issue verification and recovery links. The PAC-SM application uses the server-only Resend API key for branded transactional messages. The sending domain must be verified, and no email credential may use a NEXT_PUBLIC prefix."},
    {question:"How are administrator permissions assigned?",answer:"From Super Admin Centre → Admin Team, the Super Administrator enters an existing registered email and selects one or several operational privileges in the same submission. Roles include warehouse, fulfilment, finance, support, catalogue, verification, trade, logistics and Off-taker responsibilities. Privileges are cumulative, recorded separately and can be revoked one at a time without removing the account's other responsibilities. PAC-SM stores readable role IDs in its audit database and automatically converts them to Appwrite-safe alphanumeric account labels. If Appwrite reports a permission error, the single Coolify APPWRITE_API_KEY must include users.read and users.write."},
    {question:"Where can an appointed administrator see assigned privileges?",answer:"The administrator signs in with the exact email that received the grant and opens My Account. An Administrative access section lists every active privilege and provides an Open operational centre link wherever that role already has a delegated workspace. Privileges whose operational pages remain reserved for Super Admin are still displayed as active without presenting an unauthorized link."},
    {question:"What is an Order Fulfilment Manager?",answer:"It is a restricted administrator appointed by the Super Admin through Admin Team. The manager signs in with their own PAC-SM account and uses the separate Fulfilment Admin Centre to see payment confirmation, purchased products, buyer delivery details and order stages, and to coordinate processing, dispatch, tracking and delivery. The role cannot open Super Admin configuration, team privileges or unrelated review centres."},
    {question:"Can operational administrators become Super Administrators?",answer:"No. The Super Administrator label cannot be granted or revoked through the normal team-management screen."},
    {question:"Where can the Super Admin see everyone who has created an account?",answer:"Open User & Seller Accounts from the Super Admin Centre. The unified directory combines Appwrite Authentication users with marketplace profiles, seller and store status, contact details, email verification, active or disabled state, registration dates and assigned administrative roles. It can be searched by name, email, phone, store or merchant ID and filtered by customer, seller, administrator or Super Admin."},
    {question:"Where does Super Admin manage seller products?",answer:"Open Super Admin Centre and select the highlighted Product Management card at the beginning of the operations grid. It opens /admin/catalogue, where Super Admin can approve legacy submitted listings, review automatically published seller products, moderate images, rename, request changes, take down, restore, reject or permanently delete products."},
    {question:"How are API keys stored?",answer:"Merchant API keys are shown once and stored only as SHA-256 hashes. Requests use constant-time verification, explicit scopes and per-credential rate limits."},
    {question:"How are webhooks secured?",answer:"Webhook bodies are signed with HMAC-SHA256. Receivers should verify the exact request body and deduplicate events using the event ID."},
    {question:"What backend does PAC-SM use?",answer:"Appwrite is the exclusive application backend for authentication, database records and private storage. Server-side code uses one limited-scope runtime key for the operations the marketplace needs. The full-scope provisioning key remains outside the application and is never used for ordinary marketplace requests."},
    {question:"How are product images protected?",answer:"Original product files are stored in the private Appwrite product-media bucket. PAC-SM validates file size, declared type and image signature, enforces seller ownership and only serves approved images publicly through its controlled media route. Pending or rejected images are visible only to the owning seller and Super Admin."},
    {question:"Why must the production APP_BASE_URL use the public domain?",answer:"Marketplace redirects and payment callback origins are deliberately built from APP_BASE_URL so a reverse proxy cannot send a user to an internal container address such as 0.0.0.0:3000. In Coolify, set APP_BASE_URL to the public HTTPS marketplace domain without a trailing path."}
  ]}
];

export const documentationSections = [
  {id:"resend-email-delivery",title:"Resend transactional email delivery",summary:"Resend delivers branded PAC-SM notifications and carries Appwrite-issued authentication messages without exposing credentials to the browser.",points:["Verify a dedicated sending domain or subdomain in Resend with its displayed SPF and DKIM records before production delivery.","The PAC-SM Coolify application uses server-only RESEND_API_KEY, RESEND_FROM_EMAIL and optional RESEND_REPLY_TO_EMAIL variables for transactional messages.","New registrations receive a branded welcome message through the Resend HTTPS API; failure to send this non-security message never rolls back a successfully created account.","Verification and password-recovery tokens remain generated and validated by Appwrite. Configure the separate self-hosted Appwrite service with Resend SMTP: host smtp.resend.com, port 587, TLS, username resend, password equal to the Resend API key, and a sender on the verified domain.","Keep RESEND_API_KEY and Appwrite _APP_SMTP_PASSWORD server-only, rotate exposed credentials immediately, and never prefix them with NEXT_PUBLIC_.","The email adapter uses a ten-second timeout, plain-text and HTML alternatives, escaped user content and an idempotency key to reduce duplicate registration messages.","Authentication responses retain account-enumeration protection, and PAC-SM never emails or stores a user's password."]},
  {id:"governed-hs-ai",title:"Governed AI HS6 and reusable evidence",summary:"AI accelerates classification research while human confirmation, regulatory review and reusable verified evidence control legal readiness.",points:["AI HS6 requires a completed structured export profile and is available only to approved sellers for their own products.","The structured response includes HS2022 chapter, heading, six-digit subheading, confidence, reasoning, alternatives, missing-fact questions and attributes used.","The assistant cannot return destination tariff extensions, tariffs, duties, regulatory requirements or legal eligibility.","A hierarchy guard requires HS6 to begin with its four-digit heading and two-digit chapter before storage.","Generated records start as AI_SUGGESTED; sellers can record VENDOR_CONFIRMED classifications, and Trade Compliance can approve as PACSM_REVIEWED or reject.","Sensitive pharmaceutical, chemical, medical, dual-use, machinery, animal and plant categories remain human-review-sensitive regardless of confidence.","Evidence Vault links one private Appwrite trade document to a requirement code and multiple owned products, including issuer, validity and HS coverage.","Evidence starts as verification_required; only verified, unexpired evidence can satisfy a mandatory rule.","AI generation and classification review events are written to Appwrite audit logs without treating model output as law."]},
  {id:"export-readiness-engine",title:"Product-level ExportReady engine",summary:"PAC-SM calculates market-specific readiness from governed classification, effective regulatory rules and verified evidence while keeping domestic selling independent.",points:["Approved sellers open Seller Centre → ExportReady and build a structured profile for an owned catalogue product, including manufacturing country, intended use, process, material origins, packaging, target countries and category-specific facts.","International HS6 is stored separately from origin and destination national tariff extensions; each classification retains HS nomenclature version, confidence, reasoning, attributes used and governance status.","Classification statuses are AI_SUGGESTED, VENDOR_CONFIRMED, PACSM_REVIEWED, CUSTOMS_BROKER_VERIFIED and CUSTOMS_RULING_VERIFIED; AI output is never silently treated as a legal determination.","The versioned rules engine filters published rules by origin, destination, HS prefix, product category and effective source version instead of hardcoding requirements in UI components.","Requirement taxonomy separates exporter, product, manufacturer, facility, shipment, customs, importer, origin, labelling, packaging, testing, certification, licensing, registration, SPS, environmental, safety and conformity obligations.","Legal status distinguishes mandatory, conditional, recommended, voluntary, buyer-specific and preference-required items.","Every regulatory rule must cite an authority, official URL, source hierarchy, jurisdiction, effective date, last verification, next review and version.","Assessment status is READY, CONDITIONALLY_READY, NOT_READY, REVIEW_REQUIRED, PROHIBITED or RESTRICTED for one product and destination; there is no unsupported global export-ready badge.","Verified evidence can satisfy matching requirement codes; expired or unverified evidence cannot satisfy a mandatory finding, and a mandatory failure overrides the numerical readiness score.","Existing Trade Passport, certification, private document and shipment workflows remain connected operational foundations; the new product matrix does not block otherwise valid domestic listings.","Trade Compliance staff and Super Admin use Regulatory Control Centre to publish source-backed rule versions and monitor classifications and assessments, with changes written to the audit log.","Initial authoritative references include the Nigeria Trade Portal tariff tools, NEPC export-document guidance and GOV.UK DCTS guidance; actual product conclusions require published rules and current source review."]},
  {id:"product-upload-entry",title:"Universal product-upload entry",summary:"A persistent marketplace action guides every user to the correct seller-onboarding or product-publishing stage without bypassing verification.",points:["Upload new product is visible from the homepage and every customer, seller, operational, help and administration page.","Visitors are sent to sign-in with /sell/upload retained as the safe internal return destination; they may register an account from the authentication journey.","Signed-in users without a vendor record continue to the full vendor registration, KYC/KYB, settlement and storefront application.","Existing applicants who are pending, rejected or otherwise inactive see their application status and cannot enter product publishing.","Only approved or active vendors are redirected to Seller Centre → Products, where normal product validation, automatic publication and post-publication moderation remain in force.","The persistent action supplements existing seller-registration and Seller Centre links rather than replacing them."]},
  {id:"ai-catalogue-drafting",title:"AI-assisted catalogue drafting",summary:"Approved sellers can generate structured, editable product-copy suggestions without delegating factual responsibility or publication control to AI.",points:["Enter a product name in Seller Centre → Products before requesting a draft; category and optional seller-supplied facts improve the suggestion.","The assistant proposes a URL slug, description, specifications, generic variant information, catalogue keywords and questions for missing facts.","Fill empty fields preserves work already entered; Replace draft fields is an explicit seller action and still does not submit the form.","Brand, manufacturer, origin, ingredients, dimensions, certifications, regulatory status, GTIN, stock and prices must come from verified seller records and are never intentionally invented by the assistant.","Only authenticated approved or active sellers may call the same-origin endpoint, with ten attempts per ten-minute application instance window.","Enable it with the locked server-only OPENAI_API_KEY Coolify secret; OPENAI_PRODUCT_DRAFT_MODEL selects the structured-output model and the key must never use a NEXT_PUBLIC prefix.","Requests disable provider storage, transmit only product drafting inputs, validate a strict response schema and record successful generation metadata—not generated copy—in Appwrite audit logs.","The seller remains responsible for reviewing accuracy and PAC-SM retains its normal post-publication moderation rights."]},
  {id:"brand-identity",title:"Shared PAC-SM brand identity",summary:"The official PAC-SM logo uses one proportionally scaled brand space throughout the application.",points:["The desktop logo space is increased from 112 × 64 pixels to 157 × 90 pixels, an exact 40 percent scale increase after whole-pixel rounding.","The mobile logo space is increased from 94 × 54 pixels to 132 × 76 pixels using the same 40 percent scale factor.","Contain sizing preserves the source logo aspect ratio without stretching or cropping.","Navigation containers expand to accommodate the larger mark without overlapping links, search, account or storefront controls."]},
  {id:"commerce-module-design",title:"Continental commerce module design standard",summary:"Off-takers, Procurement, Trade and Logistics use a shared production UI system that future operational modules should follow.",points:["CommerceModuleHeader provides one cross-module navigation for Off-takers, Procurement, Trade and Logistics plus marketplace and contextual account links.","CommerceModuleHero standardizes the eyebrow, title, explanation, workflow status, metric and responsive hero composition while supporting a restrained module-specific color tone.","Off-taker Centre uses structured demand publishing, supplier proposal cards, award controls and supply-agreement tables.","Procurement uses structured RFQ creation, portfolio monitoring and a dedicated quotation-comparison screen with purchase-order conversion.","Trade Passport uses consistent readiness metrics, compliance forms, private-document controls and trade-record tables.","Logistics uses carrier trust signals, official-partner presentation, carrier cards, route summaries and a matching shipment-tracking experience.","Shared module panels standardize headings, fields, buttons, alerts, success messages, tables, cards and empty states.","Desktop, tablet and mobile breakpoints are defined centrally in commerce-modules.css; future commerce pages should reuse these primitives instead of introducing isolated page styles.","All module pages retain the global country, language, currency and Back to home controls."]},
  {id:"retail-marketplace",title:"Professional retail marketplace",summary:"Retail discovery and product purchasing use a responsive, trust-led commerce experience.",points:["Open /products?market=retail for the dedicated retail catalogue.","The retail header keeps product search, account, wishlist, cart, marketplace channels, seller registration and order tracking accessible.","Category shortcuts and the filter panel support text search, category selection, buying format and in-stock filtering.","Results can be sorted by featured order, lowest price, highest price or product name; filtering and sorting remain server-authoritative.","Product cards present approved imagery, brand or seller context, retail or MOQ badges, stock urgency, display-currency pricing and a clear product action.","The product-detail page combines an approved media gallery, product origin and model, verified-review summary, buyer-protection cues and a sticky best-offer purchase panel.","All active seller offers remain comparable by store, buying format, available stock, price and quantity before cart submission.","The experience adapts to tablet and mobile layouts while preserving search, filters, two-column mobile product browsing and the global Back to home control."]},
  {id:"wholesale-experience",title:"Wholesale product and transaction experience",summary:"Wholesale discovery and transaction entry are separated to provide a focused, responsive buying experience.",points:["/wholesale is the discovery catalogue and shows concise product cards rather than embedded transaction forms.","Selecting an offer opens /wholesale/[offerId], a dedicated full-screen product workspace.","The workspace presents the approved product image, origin, description, fulfilment information, processing time, MOQ, maximum quantity and every published price tier.","Approved business buyers can choose Continue to secure checkout for the listed tier price or submit a structured negotiated-price request.","Negotiation inputs occupy their own responsive panel and include quantity, proposed price, delivery country, required date and commercial message.","Unauthenticated users retain the selected product as their post-login destination, while unregistered or pending business buyers receive a clear access explanation.","Validation failures return to the same selected product with a visible message instead of dropping the buyer back into the catalogue.","Customer-facing pages using the shared marketplace shell now use modern navigation, elevated responsive cards, consistent form controls and mobile spacing aligned with the homepage visual system."]},
  {id:"official-logistics-partner",title:"Official logistics partner",summary:"Zenith Carex Express is identified across PAC-SM as the official logistics partner.",points:["The Zenith Carex Express logo appears in the homepage logistics-partner strip and on /logistics.","The supplied logo is stored as a local application asset and rendered with contain sizing so its original proportions are preserved.","The partnership display directs users to the Logistics marketplace and shipment-tracking workflows.","Carrier availability, route coverage, service rates, shipment assignment and tracking statuses continue to use PAC-SM's verified logistics records and controlled workflows.","Other logistics companies may still apply through Become a carrier and enter the verification process."]},
  {id:"admin-wholesale-negotiations",title:"Super Admin wholesale negotiation access",summary:"Wholesale price requests are exposed as a priority operation in the Super Admin Centre.",points:["Use the highlighted Wholesale Negotiations sidebar link, the Review buyer negotiations banner near the top of the dashboard, or the Wholesale Negotiations operations card.","All three controls open /admin/wholesale-negotiations.","The queue displays the negotiation reference, product, status and available action.","Review & respond is available only for PAC-SM-owned and demo-product negotiations.","Super Admin can accept the buyer price, reject it or issue a counteroffer while preserving the administrator's identity in the audit timeline.","Independent-seller negotiations remain visible for oversight but must be answered by the owning seller from Seller Centre → Wholesale."]},
  {id:"checkout-address-return",title:"Checkout address handoff",summary:"A buyer who needs a delivery address can save it without losing the active retail or wholesale checkout.",points:["Checkout links to /account/addresses with a protected internal /checkout return destination.","The address form preserves that destination through its POST request.","After Appwrite confirms the address was created, PAC-SM returns the buyer directly to checkout using a 303 redirect.","Checkout reloads the active server-authoritative cart and address list, selects the first available address and enables Place order and pay.","External or protocol-relative return destinations are rejected; only internal PAC-SM paths are accepted.","Opening Saved addresses from the Account page without a checkout destination retains the normal Address saved confirmation page."]},
  {id:"wholesale-checkout",title:"Wholesale checkout and payment cycle",summary:"Published wholesale tiers and accepted negotiations both progress into secure delivery, payment and fulfilment.",points:["Only an approved business buyer can begin wholesale checkout.","For a listed offer, PAC-SM resolves the most specific eligible quantity tier, verifies stock and creates the purchase order and checkout item in one Appwrite transaction.","For an accepted negotiation, the purchase order preserves the negotiation as its source and locks the accepted quantity, unit price and currency.","Both paths redirect directly to /checkout, where the buyer selects a saved delivery address and DemoPay, Paystack or PAPSS according to configured availability.","Checkout independently revalidates the purchase order, its line item, buyer ownership, seller, offer, quantity, price, currency, product approval and available inventory.","Negotiated checkout additionally verifies that the acceptance is unexpired, unused and belongs to the signed-in buyer.","Successful order creation stores the purchase-order reference on each wholesale order item, marks the purchase order converted, reserves stock and starts payment immediately.","Successful payment continues through the standard vendor-order, warehouse, dispatch, delivery, finance, return and dispute controls."]},
  {id:"overview",title:"Platform overview",summary:"PAC-SM combines retail, wholesale, procurement, fulfilment, logistics and trade compliance in one Appwrite-backed marketplace.",points:["The official PAC-SM logo is served from the application asset directory and fitted proportionally into the shared brand space across desktop and mobile interfaces.","Open FAQ or Documentation from the homepage utility menu or the Support footer.","Retail and wholesale product discovery","Multi-vendor ordering and inventory reservation","Vendor, carrier and business-buyer verification","Procurement RFQs and quotations","Trade Passport, standards and certification","Scoped merchant APIs and signed webhooks"]},
  {id:"accounts",title:"Accounts, navigation and regional preferences",summary:"Account sessions are server-mediated, navigation remains consistent and regional settings appear across the entire application.",points:["The homepage account control reads Hello, sign in for visitors and switches to a server-rendered Hello, [first name] greeting immediately after a valid password or Google session is established.","The greeting uses the Appwrite account name, with a safely normalised email-name fallback, and never relies on browser-supplied identity text.","Every route below the root layout displays a fixed Back to home link except the homepage itself.","The global home link covers customer, authentication, account, checkout, wholesale, seller, staff and administrator interfaces without relying on page-specific menus.","The control is keyboard accessible, has a visible focus state and moves above the marketplace mobile dock on small screens.","Register with a normalized email and strong password, or use Register with Google after the Appwrite Google provider is enabled.","Google OAuth uses Appwrite's one-time token exchange and a ten-minute HMAC-signed state token with a random nonce, timestamp and safe internal return path; it does not rely on a transient browser state cookie.","Email-and-password registration sends a verification link after Appwrite SMTP is configured. The user explicitly submits the verification to avoid link-scanner consumption; a missing session returns through sign-in without losing the token.","Verification can be resent from Account, while already verified accounts are detected before another email is requested.","Country resolution covers all 54 sovereign African countries and uses saved preference, profile, trusted proxy header, then Nigeria fallback.","English, French, Arabic, Portuguese, Kiswahili and Spanish use server-rendered dictionaries with English phrase fallback; Arabic uses right-to-left layout direction.","Seller-authored catalogue content is not silently machine-translated.","The currency selector includes every currency used by African sovereign states and selected global trading currencies.","Public catalogue prices convert through a daily server-cached ExchangeRate-API rate table.","Checkout, orders, refunds and settlements retain the source transaction currency; display conversion is informational.","If a rate is unavailable, the original offer currency is shown without an estimated substitute."]},
  {id:"buyers",title:"Customer marketplace",summary:"Customers can search, compare, buy and manage marketplace activity.",points:["Open PAC-SM Products from the homepage menu for the dedicated house-brand agro, food and beverage storefront.","Search by name, description, brand, category and market type.","Add approved offers to a server-authoritative cart.","Checkout collects delivery address, optional coupon and payment method on one page.","Place order and pay reserves inventory, creates the parent and vendor orders, and immediately starts the selected payment.","If provider launch is interrupted, the order stays pending and can be paid from its order page.","Track fulfilment, payments and shipments from Orders.","Create eligible returns, disputes, verified reviews and order messages.","Use wishlist and notification centres for ongoing engagement."]},
  {id:"vendors",title:"Vendor onboarding and Seller Centre",summary:"Vendor access follows self-service or controlled assisted onboarding with strict ownership checks.",points:["The homepage prominently displays Register as a seller; it opens /vendor/register, and unauthenticated applicants return there automatically after sign-in.","Applicants provide contact, legal business, ownership, settlement, store and KYC/KYB document information before review.","A Super Admin can appoint Seller Onboarding Managers from Admin Team.","Authorized onboarding staff create the Appwrite login, active vendor identity and store; temporary passwords are not stored and must be changed at /account/security after first sign-in.","Only approved or active sellers can publish catalogue records; pending, rejected or suspended vendor accounts cannot use the seller publishing route.","Approved-seller product, variant and offer records are assigned live status immediately and the publication is written to the audit log.","Validated JPEG, PNG and WebP product images publish immediately for approved sellers; the first image becomes primary and original files remain in private Appwrite storage behind the controlled media route.","Post-publication moderation lets Super Admin request changes, take a product down, reject it, restore it or permanently delete it. Product and offer visibility change together, and every moderation decision records the responsible administrator, reason and timestamp.","A suspended, rejected or changes-requested product is excluded from public catalogue and checkout queries until restored.","Self-service applicants complete business, beneficial-owner, banking, store and trade fields and upload registration, tax and identity evidence privately.","Approved sellers manage products, inventory, orders, wallet, analytics, RFQs, wholesale, warehousing, compliance, trade and integrations.","Every store uses one responsive PAC-SM storefront template; Seller Centre → My Store lets the owner upload a proportionally fitted logo and select validated primary and accent colours without changing the shared customer experience.","PAC-SM Products uses the same storefront component and visual rules as independent seller stores.","Seller Centre → Wallet calculates ledger, pending-claim and available balances from posted vendor-payable journal lines. A withdrawal cannot exceed the unreserved available balance.","Withdrawal requests use the seller's verified settlement destination and remain reserved while pending. Super Admin reviews them at /admin/withdrawals; payment creates the settlement, withdrawal status and balanced journal entry in one Appwrite transaction.","Rejected claims release the reserved amount, while paid claims remain linked to their settlement and audit history.","All seller reads and mutations are scoped to the authenticated vendor."]},
  {id:"wholesale",title:"Wholesale and procurement",summary:"Approved business buyers and sellers use structured commercial workflows.",points:["Wholesale tiers support minimum and maximum quantities.","Buying at the listed wholesale price creates a purchase order immediately and displays a visible success or validation result.","Negotiation is enabled by default for wholesale offers, including PAC-SM demo offers without a separate settings record; sellers can disable it or configure minimum quantities, confidential price floors, maximum discounts, counteroffers and expiry per offer.","Approved buyers submit price requests from /wholesale and monitor them at /wholesale/negotiations; sellers respond from Seller Centre → Wholesale.","The negotiation state machine alternates seller and buyer turns: the receiving party may accept, reject or counter the latest proposal. The interface identifies the responsible party and preserves every proposal in an immutable timeline.","A response commits its current price, quantity, status, event and recipient notification atomically so a partial counteroffer cannot be displayed as a failed response.","Action failures use safe, specific guidance for expiry, turn ownership, disabled counteroffers, invalid values and seller pricing limits.","For PAC-SM-owned or demo inventory only, Super Admin may act as the platform seller at /admin/wholesale-negotiations. The actual administrator identity and proxy action are written to negotiation events and audit logs; independent seller negotiations cannot be proxied.","Accepted prices are single-use and bound to the buyer, seller offer, currency, exact quantity and expiry. Checkout revalidates all terms and stock inside the order transaction before recording the negotiation reference on the order item.","Super Admin monitors commercial activity at /admin/wholesale-negotiations. Financial commission, refunds and settlement calculations use the negotiated order amount actually paid.","Purchase orders preserve buyer, vendor, pricing and source information.","Proforma invoices are generated from commercial purchase orders.","RFQs support supplier invitations, quotations, negotiation history and award conversion."]},
  {id:"offtakers",title:"Off-taker ecosystem",summary:"Verified companies publish recurring demand and operate auditable multi-supplier supply agreements.",points:["Open Off-takers in the homepage marketplace menu or use Off-taker registration in the Trade footer.","Companies register at /offtakers/register with legal, contact, sourcing, delivery and commercial information for KYB review.","The Super Admin can appoint an Off-taker Verification Manager and authorized staff approve, reject or request more information at /admin/offtakers.","Approved off-takers publish product specifications, volumes, frequency, packaging, certification, origin, deadline, delivery and payment terms from /offtakers.","Verified sellers respond from /seller/offtake with quantity, unit price, lead time, certifications and negotiated terms.","Off-takers can shortlist, request revision, reject or award proposals and split demand among several suppliers.","Awards form one supply agreement per requirement and create supplier-specific PAC-PO scheduled purchase-order references.","Authorized staff record delivery inspection and accepted quantities before operational settlement.","Payment milestones track due, processing, paid, settled and failed states; a paid status is an operational record and does not replace an approved payment connector.","Agreement or scheduled-order disputes retain category, description, review state and resolution history."]},
  {id:"orders",title:"Orders, finance and trust",summary:"Order and finance state changes are controlled and auditable.",points:["Checkout revalidates price, approval and available stock, then creates one parent order with vendor-specific child orders.","Inventory reservations prevent overselling while the order awaits payment.","Buyers can retry an interrupted payment from the order page without recreating the order.","Demo capture exercises the complete Appwrite transaction, inventory, ledger and notification path.","Paystack is initialized only on the server and capture requires verified reference, status, order metadata, amount and currency.","PAPSS is a provider adapter awaiting certified merchant or participating-bank onboarding details; no unverified browser callback can release goods.","Provider secrets remain server-only. Successful capture is idempotent and atomically converts reservations into stock sales.","Commission, refunds and settlements use balanced journal records.","Returns, disputes and verified reviews provide buyer-protection controls."]},
  {id:"warehouse",title:"Fulfilled by PAC-SM",summary:"Warehouse teams manage inbound stock through dispatch.",points:["Inbound shipment notices and expected quantities.","Receiving reconciliation and shortage visibility.","Put-away into controlled warehouse bins.","Pick tasks, packing and fulfilment packages.","Role-separated receiving, picking, packing and management privileges."]},
  {id:"logistics",title:"Carrier and logistics marketplace",summary:"Verified third-party carriers publish coverage and fulfil assigned shipments.",points:["Carrier onboarding includes registration, insurance, fleet and private documents.","Logistics staff approve applications and activate carrier numbers.","Carriers publish route-level base and weight rates.","Dispatchers assign existing shipments to verified carriers.","Carrier tracking uses controlled state transitions and exception recovery.","Public tracking exposes safe timeline information and delivery confirmation."]},
  {id:"trade",title:"Trade Passport and cross-border operations",summary:"Trade records support export readiness without claiming regulatory authority.",points:["Vendors declare exporter details, target markets, product groups and Incoterms.","Readiness scoring reflects profile, certification and document completeness.","Trade officers approve, reject or request additional information.","Cross-border shipments record origin, destination, HS codes and customs status.","Trade documents remain private and every decision creates an audit event."]},
  {id:"standards",title:"Standards, packaging and certification",summary:"Destination rules are maintained as structured, source-backed registry records.",points:["Standards are filtered by product category and country.","Packaging rules cover materials, labels, handling and weight limits.","Certification rules identify authority, mandatory status and validity.","Verified quality centres publish services and accreditations.","Sellers apply against owned products; trade staff control review and testing status.","Registry administrators should use only authoritative sources."]},
  {id:"api",title:"Merchant API and webhooks",summary:"Approved vendors can integrate ERP, POS, warehouse and logistics systems.",points:["Create sandbox or live API credentials and copy the key once.","Available scopes: products read, inventory read/write, orders read and webhook management.","Version 1 endpoints live under /api/v1/merchant.","Credentials are hashed, rate-limited, vendor-scoped and revocable.","Webhook deliveries include HMAC signatures, event IDs, attempt state and response logs.","The Developer Portal contains endpoint and verification examples."]},
  {id:"admin",title:"Administration and intelligence",summary:"Administrative centres separate sensitive operational responsibilities.",points:["The first highlighted operations card in Super Admin Centre is Product Management; it opens /admin/catalogue for automatic-publication oversight, legacy approvals, image moderation, takedown, restoration and deletion.","User & Seller Accounts is the Super Admin-only unified directory for Appwrite users, contacts, account state, verification, seller/store status, registration dates and active administrative roles.","The directory supports search by name, email, phone, store or merchant ID and filtering by account type.","Admin Team lets the Super Admin select several privileges for one registered email in a single grant. Readable underscore role IDs remain in admin_members and audit records, while account authorization uses deterministic alphanumeric labels accepted by Appwrite 1.8.1.","Every delegated administrator sees an Administrative access section on /account. It lists all active roles and links only to operational centres that accept that role, preventing misleading links to Super-Admin-only pages.","Bulk assignment distinguishes missing accounts, protected Super Admin accounts, missing Appwrite users.read/users.write scopes and record-write failures instead of reporting every backend problem as an invalid email.","Each assigned privilege can be revoked separately without removing the administrator's other roles. Super Administrator access remains excluded from ordinary role management.","Order Fulfilment Managers use the separate /operations centre and cannot access Super Admin configuration or unrelated administration.","Orders & Delivery shows payment capture, complete buyer contact and shipping details, purchased products, quantities, identifiers and vendor-order progress in one operational view.","Delivery records include recipient and account phone numbers, both street lines, city, state or region, postal code, country and the stored address identifier.","Payment records include provider, status, amount, payment number, creation and capture time, and internal identifier.","Sensitive buyer and delivery details are restricted to authenticated Super Admins and appointed Order Fulfilment Managers.","Unpaid orders cannot enter fulfilment; paid orders move through processing, warehouse picking and packing, carrier dispatch and confirmed delivery.","Dispatch requires a carrier and tracking number and creates the customer-visible shipment timeline.","Vendor, carrier, business-buyer, catalogue and certification review.","Warehouse, logistics, finance, settlements, returns and disputes.","Analytics for orders, vendors, products, disputes and reviews.","Demand forecasts, recommendation read models, fraud signals and background jobs.","Redis and external search remain deferred until measured demand requires them."]},
  {id:"deployment",title:"Deployment and operations",summary:"PAC-SM is designed for Coolify and a self-hosted Appwrite installation.",points:["The canonical production origin is https://africancontinentalmarketplace.store; configure www and any former domain to redirect to this hostname before authentication begins.","Public catalogue enrichment uses batched Appwrite queries with bounded retry to prevent transient connection failures during regional refreshes.","Set APP_BASE_URL to https://africancontinentalmarketplace.store; application redirects, OAuth return URLs and payment callback origins use it instead of the container's internal 0.0.0.0 address.","PAC-SM deliberately uses a host-only secure session cookie. Leave SESSION_COOKIE_DOMAIN unset in Coolify so a stale www/apex value cannot cause a successful login to be discarded by the browser.","Set Appwrite endpoint, project, database and bucket identifiers as Coolify variables.","Use one limited APPWRITE_API_KEY runtime secret for authentication administration, documents and files. Google OAuth itself uses the public Account API and never exposes this key.","For Appwrite 1.8.1 the runtime scopes are sessions.write, users.read, users.write, databases.read, databases.write, documents.read, documents.write, files.read and files.write.","Keep the full-scope provisioning key outside the application runtime and use it only for schema and runtime-key provisioning.","On Coolify, supply APPWRITE_API_KEY as a locked runtime secret instead of a local key-file path.","In Appwrite Console, register africancontinentalmarketplace.store as a Web platform, enable Google under Auth → Settings, and copy Appwrite's displayed OAuth redirect URL into the Google Cloud OAuth client. Store the Google client ID and secret only in Appwrite.","For local OAuth testing, also register localhost as an Appwrite Web platform and add only the callback values shown by Appwrite to the Google development client.","Configure self-hosted Appwrite SMTP variables for host, port, secure mode, username, password and system sender address; recreate the Appwrite services and verify the mail worker before testing verification or password recovery.","Use a sender on the verified mail.africancontinentalmarketplace.store subdomain for Resend API and Appwrite SMTP delivery.","Set PAYSTACK_SECRET_KEY only on the Coolify server to activate Paystack; configure its callback/webhook against the canonical HTTPS domain before production acceptance tests.","Complete PAPSS onboarding and implement the issued connector specification before enabling PAPSS capture.","Use HTTPS in production and preserve trusted proxy country headers.","Run typecheck, lint, domain tests, production build and Appwrite provisioning before release."]}
] as const;
