export type FaqItem = { question: string; answer: string };
export type FaqGroup = { id: string; title: string; intro: string; items: FaqItem[] };

export const faqGroups: FaqGroup[] = [
  { id:"getting-started",title:"Getting started",intro:"Accounts, regional preferences and marketplace basics.",items:[
    {question:"What is PAC-SM?",answer:"PAC-SM is a Pan-African multi-vendor marketplace for retail shopping, wholesale purchasing, institutional procurement, logistics and cross-border trade support."},
    {question:"Do I need an account to browse?",answer:"No. You can browse products, categories, standards, carriers and public marketplace information without signing in. An account is required to place orders, save items, message participants or submit applications."},
    {question:"How does PAC-SM identify my country?",answer:"PAC-SM checks a saved regional preference, your registered profile country and trusted reverse-proxy country headers, in that order. If none is available, Nigeria is used as the safe default."},
    {question:"Can I change the detected language and currency?",answer:"Yes. Use the flag, language and currency controls at the top of every page. The currency list covers currencies used by all sovereign African countries plus selected major international currencies. Your selections are saved for one year."},
    {question:"Do product prices actually convert when I change currency?",answer:"Yes. Public product, offer and store prices are converted into the selected display currency using current server-fetched ExchangeRate-API rates. The selector submits and reloads the current page with converted prices. Orders, checkout, refunds and settlements retain the original transaction currency as the legally and financially authoritative amount."},
    {question:"How current are converted prices?",answer:"Exchange rates update daily and PAC-SM caches the rate table for up to 24 hours. A secondary ExchangeRate-API endpoint and the last successfully loaded rate table protect currency changes from temporary network failures. If no valid rate has ever been retrieved for a currency, PAC-SM safely displays the original offer currency rather than inventing a rate. Currency refreshes use batched catalogue reads and retry transient Appwrite read failures."},
    {question:"Which languages are currently selectable?",answer:"English, French, Arabic, Portuguese, Kiswahili and Spanish are available. Selecting a language reloads the current page with server-rendered translations for the global controls and primary customer marketplace. Arabic also activates right-to-left document direction. Seller-authored product names and descriptions remain in their submitted language to preserve catalogue accuracy."},
    {question:"Where can I find help and platform guidance?",answer:"Use FAQ or Documentation in the utility menu at the top of the marketplace homepage. Both resources are also available under Support in the homepage footer."}
  ]},
  { id:"buying",title:"Buying and orders",intro:"Retail catalogue, cart, checkout and buyer protection.",items:[
    {question:"How do I find a product?",answer:"Use the global search bar, homepage category tiles or marketplace filters. You can filter by retail or wholesale market and by product category."},
    {question:"What are PAC-SM Products?",answer:"PAC-SM Products are house-brand agro, food and beverage goods sold through PAC-SM. Open PAC-SM Products from the homepage marketplace menu to browse approved products, available stock and retail or wholesale offers."},
    {question:"Where is the official PAC-SM logo used?",answer:"The official Pan-African Continental Super Marketplace logo appears in the shared brand space across marketplace, account, seller, administrator, help and authentication pages. It is scaled with contain sizing so its original proportions are preserved on desktop and mobile."},
    {question:"Can one cart contain products from multiple sellers?",answer:"Yes. PAC-SM keeps one customer cart and splits checkout into vendor-specific orders while retaining a single parent order for the buyer."},
    {question:"How is product availability protected?",answer:"Availability is revalidated on the server during checkout and stock is reserved atomically. The platform prevents checkout when the required stock is no longer available."},
    {question:"What happens after I press Place order and pay?",answer:"PAC-SM validates the address, coupon, price and stock, creates the parent and vendor orders, and immediately starts the payment method selected on checkout. Demo capture completes inside PAC-SM; configured live providers redirect to their secure hosted payment page. If a provider is interrupted, the pending order remains available for payment retry."},
    {question:"Where can I see my orders?",answer:"Open Orders from the marketplace header or visit your account. Each order shows vendor-specific fulfilment, shipment and return information."},
    {question:"How do returns and disputes work?",answer:"Eligible delivered orders can enter the returns workflow. If a transaction problem cannot be resolved normally, the buyer can create a dispute with an auditable case history for administrative review."},
    {question:"Are product reviews verified?",answer:"Reviews are tied to eligible order items so PAC-SM can distinguish verified-purchase feedback from unauthenticated comments."}
  ]},
  { id:"wholesale",title:"Wholesale and procurement",intro:"Business buying, price tiers, purchase orders and RFQs.",items:[
    {question:"What makes a product wholesale?",answer:"Wholesale offers have a minimum order quantity greater than one and may include quantity-based price tiers."},
    {question:"How do I become a business buyer?",answer:"Submit the wholesale business-buyer application with your organization and registration details. Administrative approval unlocks controlled commercial purchasing workflows."},
    {question:"Can I negotiate a wholesale price below the listed tiers?",answer:"Yes. Negotiation is enabled by default for wholesale offers unless the seller disables it. An approved business buyer selects Request a negotiated price, proposes a quantity and unit price, and receives an instant in-app response. The seller may accept, reject or counter. An accepted offer is time-limited, locked to the agreed quantity and price, and can be used once at checkout."},
    {question:"What is the difference between buying at the listed wholesale price and requesting a negotiated price?",answer:"Buy at listed wholesale price immediately creates a purchase order using the published quantity tier. Request a negotiated price sends a proposed unit price to the seller for acceptance, rejection or counteroffer. Only an accepted negotiated offer can be moved into the cart at the agreed price."},
    {question:"How do wholesale counteroffers work?",answer:"Only the party whose response is required can act. Buyer and seller counteroffers are preserved in an immutable timeline. Either party can accept or reject the latest proposal; buyers may withdraw an open request. Expired or previously converted offers cannot be used."},
    {question:"How do sellers control negotiated discounts?",answer:"In Seller Centre → Wholesale, sellers enable negotiation per offer and set minimum negotiable quantity, a confidential price floor, maximum discount, expiry period and whether counteroffers are allowed. The confidential limits are enforced by the server and are never shown to buyers."},
    {question:"Who responds to negotiations for PAC-SM demo products?",answer:"Super Admin can open Admin Centre → Wholesale Negotiations and select Review & respond for PAC-SM-owned or demo inventory. The administrator may accept, reject or counter while their real user ID is recorded in the audit timeline. Super Admin cannot respond for an independent seller."},
    {question:"What is an RFQ?",answer:"A Request for Quotation lets an approved business buyer publish a requirement, invite matching vendors, compare quotations and award the preferred supplier."},
    {question:"Can an RFQ become a purchase order?",answer:"Yes. An accepted quotation can be converted into a commercial purchase order and proforma invoice while preserving the procurement history."},
    {question:"Does PAC-SM support bulk pricing?",answer:"Yes. Sellers can define offer-level price tiers with minimum and optional maximum quantities. The most specific eligible tier is used."}
  ]},
  { id:"offtakers",title:"Off-takers and supply agreements",intro:"Verified institutional demand, supplier proposals and scheduled purchasing.",items:[
    {question:"Who can register as an off-taker?",answer:"Processors, exporters, retailers, hospitality groups, institutions and other companies seeking recurring or bulk supply can apply through Off-takers in the homepage menu or Off-taker registration in the Trade footer. PAC-SM reviews company and buying information before publishing access is enabled."},
    {question:"How does an approved off-taker source products?",answer:"The off-taker publishes a structured requirement with quantity, specification, packaging, certification, origin, delivery, deadline and payment terms. Matching sellers can submit supply proposals."},
    {question:"Can an off-taker appoint more than one supplier?",answer:"Yes. An off-taker may shortlist proposals and split an award among multiple suppliers. Each award receives its own scheduled purchase-order reference under the shared supply agreement."},
    {question:"How are delivery and payment controlled?",answer:"Authorized staff inspect scheduled deliveries and record accepted quantities. Payment milestones remain visible as due, processing, paid, settled or failed; production money movement requires the configured approved payment or banking connector."},
    {question:"What happens when there is a supply disagreement?",answer:"The off-taker can open a dispute against an agreement or scheduled purchase order. Authorized staff review the evidence and record the resolution in the operational history."}
  ]},
  { id:"selling",title:"Selling on PAC-SM",intro:"Vendor registration, products, inventory and operations.",items:[
    {question:"Who can become a vendor?",answer:"Registered companies, partnerships, sole proprietors, cooperatives, manufacturers, farmers, wholesalers, distributors, exporters and other supported business types may apply."},
    {question:"What documents are required for vendor verification?",answer:"The onboarding workflow requires a business registration certificate, tax document and director or owner identity document. Additional information may be requested during KYC or KYB review."},
    {question:"Where are private verification documents stored?",answer:"Documents are stored in a private encrypted Appwrite bucket. They are retrieved through authorized server routes and are not exposed as public files."},
    {question:"Can sellers add products immediately?",answer:"Seller operations unlock after vendor approval. Submitted products and offers pass through catalogue moderation before becoming publicly purchasable."},
    {question:"Can PAC-SM staff create seller accounts for assisted onboarding?",answer:"Yes. A Super Admin can grant the Seller Onboarding Manager role to a registered staff email. That administrator can create a seller's Appwrite login, active vendor identity and store in one audited operation. The temporary password is handed to the seller through a secure channel and is never stored in marketplace records. The seller must change it from Account Security after first sign-in. Products still pass catalogue moderation, and banking, KYC/KYB and settlement compliance remain required for protected financial operations."},
    {question:"How do sellers manage inventory?",answer:"Sellers can create warehouses, receive stock and review balances. PAC-SM records inventory movements and reservations rather than silently replacing history."},
    {question:"Can sellers connect external systems?",answer:"Yes. Approved vendors can create scoped API credentials, read products, inventory and orders, update controlled inventory fields and register signed webhook endpoints."}
  ]},
  { id:"logistics",title:"Logistics and carriers",intro:"Carrier marketplace, dispatch and public tracking.",items:[
    {question:"How can a logistics company join PAC-SM?",answer:"Create an account and submit the carrier application with company, fleet, coverage, insurance and private verification documents."},
    {question:"How are carriers verified?",answer:"Authorized logistics staff review registration, insurance and operational details before activating a carrier number and marketplace profile."},
    {question:"Can carriers publish rates?",answer:"Verified carriers can publish service routes with origin, destination, transport mode, base rate, per-kilogram rate, currency and estimated delivery time."},
    {question:"How do I track a shipment?",answer:"Open Track Shipment and enter the carrier tracking number. Public tracking shows the current state, location updates, event messages and delivery confirmation."},
    {question:"What is proof of delivery?",answer:"When a carrier records delivery, PAC-SM stores the recipient, delivery time and optional delivery code as a controlled proof-of-delivery record."},
    {question:"Can tracking statuses be changed backwards?",answer:"No. The logistics state machine allows controlled forward transitions. Exceptions can be recorded and recovered into valid in-transit states."}
  ]},
  { id:"trade",title:"Trade, standards and certification",intro:"Export readiness, documents and destination compliance.",items:[
    {question:"What is the Digital Trade Passport?",answer:"It is a reviewed vendor export-readiness profile containing target markets, product categories, exporter information, Incoterms, transport modes, certifications and supporting documents."},
    {question:"What does the readiness score mean?",answer:"The score summarizes completion of exporter details, markets, categories, Incoterms, transport modes, certifications and documents. It supports review but does not replace a regulator decision."},
    {question:"What is the Product Standards Hub?",answer:"The hub organizes product standards, packaging and labelling rules, certification requirements and verified quality centres by category and destination country."},
    {question:"Who enters product standards?",answer:"Authorized trade-compliance staff enter standards from authoritative government, standards-body or accreditation sources. PAC-SM does not invent regulatory rules."},
    {question:"How does a seller request certification?",answer:"From Seller Compliance, select an owned product, an applicable requirement and optionally a preferred quality centre, then submit the product and testing notes."},
    {question:"Does PAC-SM approval replace customs or regulatory approval?",answer:"No. PAC-SM records marketplace compliance reviews and supporting evidence. Government, customs, standards and accreditation authorities retain their legal powers."}
  ]},
  { id:"finance",title:"Payments and finance",intro:"Payment status, ledgers, refunds and settlements.",items:[
    {question:"Which retail payment methods are available?",answer:"PAC-SM DemoPay, Paystack and PAPSS are selectable during checkout. Without live provider credentials, each option runs an explicitly labelled sandbox capture and charges no money. Adding the server-only Paystack key automatically changes Paystack to its secure hosted checkout. PAPSS remains simulated until certified merchant or participating-bank connector onboarding is complete."},
    {question:"How is a Paystack payment confirmed?",answer:"PAC-SM initializes the transaction on the server, sends the buyer to Paystack, and verifies the returned reference, successful status, order metadata, currency and exact minor-unit amount on the server before marking the order paid or releasing reserved stock. Browser claims alone are never accepted."},
    {question:"Can I safely retry an interrupted payment?",answer:"Yes. An unpaid order remains in pending-payment state with its inventory reservation, and the order page offers the payment methods again. Successful capture is idempotent, so a repeated callback does not sell stock twice or create a second payment."},
    {question:"How are seller earnings calculated?",answer:"Effective commission rules are applied and financial movements are posted to balanced journal entries. Seller wallet balances are projections of the ledger."},
    {question:"When does a vendor become eligible for settlement?",answer:"Settlement eligibility follows successful fulfilment and applicable return or dispute controls. Administrators can review settlement reports before processing."},
    {question:"Are refunds audited?",answer:"Yes. Return decisions, refund records, financial reversals and related journal entries remain connected to their originating order."}
    ,{question:"How do administrators manage paid orders and delivery?",answer:"The Super Admin opens Orders & Delivery to see the buyer's name, email, account phone, recipient phone, complete delivery address including both street lines, city, state or region, postal code and country, together with payment details, purchased products, quantities and vendor fulfilment stages. Unpaid orders remain locked. Paid orders can move into processing, warehouse picking and packing, dispatch with carrier tracking, and confirmed delivery."}
  ]},
  { id:"security",title:"Security and administration",intro:"Authentication, roles, private data and operational controls.",items:[
    {question:"How are administrator permissions assigned?",answer:"The Super Administrator grants a defined operational role to an existing registered email. Roles include warehouse, finance, support, catalogue, verification, trade, logistics and Off-taker Verification responsibilities."},
    {question:"What is an Order Fulfilment Manager?",answer:"It is a restricted administrator appointed by the Super Admin through Admin Team. The manager signs in with their own PAC-SM account and uses the separate Fulfilment Admin Centre to see payment confirmation, purchased products, buyer delivery details and order stages, and to coordinate processing, dispatch, tracking and delivery. The role cannot open Super Admin configuration, team privileges or unrelated review centres."},
    {question:"Can operational administrators become Super Administrators?",answer:"No. The Super Administrator label cannot be granted or revoked through the normal team-management screen."},
    {question:"Where can the Super Admin see everyone who has created an account?",answer:"Open User & Seller Accounts from the Super Admin Centre. The unified directory combines Appwrite Authentication users with marketplace profiles, seller and store status, contact details, email verification, active or disabled state, registration dates and assigned administrative roles. It can be searched by name, email, phone, store or merchant ID and filtered by customer, seller, administrator or Super Admin."},
    {question:"How are API keys stored?",answer:"Merchant API keys are shown once and stored only as SHA-256 hashes. Requests use constant-time verification, explicit scopes and per-credential rate limits."},
    {question:"How are webhooks secured?",answer:"Webhook bodies are signed with HMAC-SHA256. Receivers should verify the exact request body and deduplicate events using the event ID."},
    {question:"What backend does PAC-SM use?",answer:"Appwrite is the exclusive application backend for authentication, database records and private storage. Server-side code uses one limited-scope runtime key for the operations the marketplace needs. The full-scope provisioning key remains outside the application and is never used for ordinary marketplace requests."},
    {question:"Why must the production APP_BASE_URL use the public domain?",answer:"Marketplace redirects and payment callback origins are deliberately built from APP_BASE_URL so a reverse proxy cannot send a user to an internal container address such as 0.0.0.0:3000. In Coolify, set APP_BASE_URL to the public HTTPS marketplace domain without a trailing path."}
  ]}
];

export const documentationSections = [
  {id:"overview",title:"Platform overview",summary:"PAC-SM combines retail, wholesale, procurement, fulfilment, logistics and trade compliance in one Appwrite-backed marketplace.",points:["The official PAC-SM logo is served from the application asset directory and fitted proportionally into the shared brand space across desktop and mobile interfaces.","Open FAQ or Documentation from the homepage utility menu or the Support footer.","Retail and wholesale product discovery","Multi-vendor ordering and inventory reservation","Vendor, carrier and business-buyer verification","Procurement RFQs and quotations","Trade Passport, standards and certification","Scoped merchant APIs and signed webhooks"]},
  {id:"accounts",title:"Accounts and regional preferences",summary:"Account sessions are server-mediated and regional settings appear across the entire application.",points:["Register with a normalized email and strong password.","Verify email or request password recovery after SMTP is configured.","Country resolution covers all 54 sovereign African countries and uses saved preference, profile, trusted proxy header, then Nigeria fallback.","English, French, Arabic, Portuguese, Kiswahili and Spanish use server-rendered dictionaries with English phrase fallback; Arabic uses right-to-left layout direction.","Seller-authored catalogue content is not silently machine-translated.","The currency selector includes every currency used by African sovereign states and selected global trading currencies.","Public catalogue prices convert through a daily server-cached ExchangeRate-API rate table.","Checkout, orders, refunds and settlements retain the source transaction currency; display conversion is informational.","If a rate is unavailable, the original offer currency is shown without an estimated substitute."]},
  {id:"buyers",title:"Customer marketplace",summary:"Customers can search, compare, buy and manage marketplace activity.",points:["Open PAC-SM Products from the homepage menu for the dedicated house-brand agro, food and beverage storefront.","Search by name, description, brand, category and market type.","Add approved offers to a server-authoritative cart.","Checkout collects delivery address, optional coupon and payment method on one page.","Place order and pay reserves inventory, creates the parent and vendor orders, and immediately starts the selected payment.","If provider launch is interrupted, the order stays pending and can be paid from its order page.","Track fulfilment, payments and shipments from Orders.","Create eligible returns, disputes, verified reviews and order messages.","Use wishlist and notification centres for ongoing engagement."]},
  {id:"vendors",title:"Vendor onboarding and Seller Centre",summary:"Vendor access follows self-service or controlled assisted onboarding with strict ownership checks.",points:["A Super Admin can appoint Seller Onboarding Managers from Admin Team.","Authorized onboarding staff create the Appwrite login, active vendor identity and store; temporary passwords are not stored and must be changed at /account/security after first sign-in.","Assisted access enables immediate product submission but does not waive catalogue moderation, KYC/KYB, banking or settlement compliance.","Self-service applicants complete business, beneficial-owner, banking, store and trade fields and upload registration, tax and identity evidence privately.","Approved sellers manage products, inventory, orders, finance, analytics, RFQs, wholesale, warehousing, compliance, trade and integrations.","Catalogue submissions remain non-public until moderation approval.","All seller reads and mutations are scoped to the authenticated vendor."]},
  {id:"wholesale",title:"Wholesale and procurement",summary:"Approved business buyers and sellers use structured commercial workflows.",points:["Wholesale tiers support minimum and maximum quantities.","Buying at the listed wholesale price creates a purchase order immediately and displays a visible success or validation result.","Negotiation is enabled by default for wholesale offers; sellers can disable it or configure minimum quantities, confidential price floors, maximum discounts, counteroffers and expiry per offer.","Approved buyers submit price requests from /wholesale and monitor them at /wholesale/negotiations; sellers respond from Seller Centre → Wholesale.","The negotiation state machine permits only the party whose response is required to accept, reject or counter, while preserving every proposal in an immutable timeline.","For PAC-SM-owned or demo inventory only, Super Admin may act as the platform seller at /admin/wholesale-negotiations. The actual administrator identity and proxy action are written to negotiation events and audit logs; independent seller negotiations cannot be proxied.","Accepted prices are single-use and bound to the buyer, seller offer, currency, exact quantity and expiry. Checkout revalidates all terms and stock inside the order transaction before recording the negotiation reference on the order item.","Super Admin monitors commercial activity at /admin/wholesale-negotiations. Financial commission, refunds and settlement calculations use the negotiated order amount actually paid.","Purchase orders preserve buyer, vendor, pricing and source information.","Proforma invoices are generated from commercial purchase orders.","RFQs support supplier invitations, quotations, negotiation history and award conversion."]},
  {id:"offtakers",title:"Off-taker ecosystem",summary:"Verified companies publish recurring demand and operate auditable multi-supplier supply agreements.",points:["Open Off-takers in the homepage marketplace menu or use Off-taker registration in the Trade footer.","Companies register at /offtakers/register with legal, contact, sourcing, delivery and commercial information for KYB review.","The Super Admin can appoint an Off-taker Verification Manager and authorized staff approve, reject or request more information at /admin/offtakers.","Approved off-takers publish product specifications, volumes, frequency, packaging, certification, origin, deadline, delivery and payment terms from /offtakers.","Verified sellers respond from /seller/offtake with quantity, unit price, lead time, certifications and negotiated terms.","Off-takers can shortlist, request revision, reject or award proposals and split demand among several suppliers.","Awards form one supply agreement per requirement and create supplier-specific PAC-PO scheduled purchase-order references.","Authorized staff record delivery inspection and accepted quantities before operational settlement.","Payment milestones track due, processing, paid, settled and failed states; a paid status is an operational record and does not replace an approved payment connector.","Agreement or scheduled-order disputes retain category, description, review state and resolution history."]},
  {id:"orders",title:"Orders, finance and trust",summary:"Order and finance state changes are controlled and auditable.",points:["Checkout revalidates price, approval and available stock, then creates one parent order with vendor-specific child orders.","Inventory reservations prevent overselling while the order awaits payment.","Buyers can retry an interrupted payment from the order page without recreating the order.","Demo capture exercises the complete Appwrite transaction, inventory, ledger and notification path.","Paystack is initialized only on the server and capture requires verified reference, status, order metadata, amount and currency.","PAPSS is a provider adapter awaiting certified merchant or participating-bank onboarding details; no unverified browser callback can release goods.","Provider secrets remain server-only. Successful capture is idempotent and atomically converts reservations into stock sales.","Commission, refunds and settlements use balanced journal records.","Returns, disputes and verified reviews provide buyer-protection controls."]},
  {id:"warehouse",title:"Fulfilled by PAC-SM",summary:"Warehouse teams manage inbound stock through dispatch.",points:["Inbound shipment notices and expected quantities.","Receiving reconciliation and shortage visibility.","Put-away into controlled warehouse bins.","Pick tasks, packing and fulfilment packages.","Role-separated receiving, picking, packing and management privileges."]},
  {id:"logistics",title:"Carrier and logistics marketplace",summary:"Verified third-party carriers publish coverage and fulfil assigned shipments.",points:["Carrier onboarding includes registration, insurance, fleet and private documents.","Logistics staff approve applications and activate carrier numbers.","Carriers publish route-level base and weight rates.","Dispatchers assign existing shipments to verified carriers.","Carrier tracking uses controlled state transitions and exception recovery.","Public tracking exposes safe timeline information and delivery confirmation."]},
  {id:"trade",title:"Trade Passport and cross-border operations",summary:"Trade records support export readiness without claiming regulatory authority.",points:["Vendors declare exporter details, target markets, product groups and Incoterms.","Readiness scoring reflects profile, certification and document completeness.","Trade officers approve, reject or request additional information.","Cross-border shipments record origin, destination, HS codes and customs status.","Trade documents remain private and every decision creates an audit event."]},
  {id:"standards",title:"Standards, packaging and certification",summary:"Destination rules are maintained as structured, source-backed registry records.",points:["Standards are filtered by product category and country.","Packaging rules cover materials, labels, handling and weight limits.","Certification rules identify authority, mandatory status and validity.","Verified quality centres publish services and accreditations.","Sellers apply against owned products; trade staff control review and testing status.","Registry administrators should use only authoritative sources."]},
  {id:"api",title:"Merchant API and webhooks",summary:"Approved vendors can integrate ERP, POS, warehouse and logistics systems.",points:["Create sandbox or live API credentials and copy the key once.","Available scopes: products read, inventory read/write, orders read and webhook management.","Version 1 endpoints live under /api/v1/merchant.","Credentials are hashed, rate-limited, vendor-scoped and revocable.","Webhook deliveries include HMAC signatures, event IDs, attempt state and response logs.","The Developer Portal contains endpoint and verification examples."]},
  {id:"admin",title:"Administration and intelligence",summary:"Administrative centres separate sensitive operational responsibilities.",points:["User & Seller Accounts is the Super Admin-only unified directory for Appwrite users, contacts, account state, verification, seller/store status, registration dates and active administrative roles.","The directory supports search by name, email, phone, store or merchant ID and filtering by account type.","The Super Admin assigns or revokes operational roles by registered email from Admin Team.","Order Fulfilment Managers use the separate /operations centre and cannot access Super Admin configuration or unrelated administration.","Orders & Delivery shows payment capture, complete buyer contact and shipping details, purchased products, quantities, identifiers and vendor-order progress in one operational view.","Delivery records include recipient and account phone numbers, both street lines, city, state or region, postal code, country and the stored address identifier.","Payment records include provider, status, amount, payment number, creation and capture time, and internal identifier.","Sensitive buyer and delivery details are restricted to authenticated Super Admins and appointed Order Fulfilment Managers.","Unpaid orders cannot enter fulfilment; paid orders move through processing, warehouse picking and packing, carrier dispatch and confirmed delivery.","Dispatch requires a carrier and tracking number and creates the customer-visible shipment timeline.","Vendor, carrier, business-buyer, catalogue and certification review.","Warehouse, logistics, finance, settlements, returns and disputes.","Analytics for orders, vendors, products, disputes and reviews.","Demand forecasts, recommendation read models, fraud signals and background jobs.","Redis and external search remain deferred until measured demand requires them."]},
  {id:"deployment",title:"Deployment and operations",summary:"PAC-SM is designed for Coolify and a self-hosted Appwrite installation.",points:["Public catalogue enrichment uses batched Appwrite queries with bounded retry to prevent transient connection failures during regional refreshes.","Set APP_BASE_URL to the public HTTPS marketplace origin; application redirects and payment callback origins use it instead of the container's internal 0.0.0.0 address.","Set Appwrite endpoint, project, database and bucket identifiers as Coolify variables.","Use one limited APPWRITE_API_KEY runtime secret for authentication administration, documents and files.","For Appwrite 1.8.1 the runtime scopes are sessions.write, users.read, users.write, databases.read, databases.write, documents.read, documents.write, files.read and files.write.","Keep the full-scope provisioning key outside the application runtime and use it only for schema and runtime-key provisioning.","On Coolify, supply APPWRITE_API_KEY as a locked runtime secret instead of a local key-file path.","Set PAYSTACK_SECRET_KEY only on the Coolify server to activate Paystack; configure its callback/webhook against the public HTTPS domain before production acceptance tests.","Complete PAPSS onboarding and implement the issued connector specification before enabling PAPSS capture.","Register production and development platform hosts in Appwrite.","Configure SMTP for verification and password recovery.","Use HTTPS in production and preserve trusted proxy country headers.","Run typecheck, lint, domain tests, production build and Appwrite provisioning before release."]}
] as const;
