import Link from "next/link";
import { requireSuperAdmin } from "@/src/modules/authorization/server/require-super-admin";
import { ADMIN_ROLE_INFO,ADMIN_ROLES } from "@/src/modules/authorization/domain/admin-roles";
import { listAdminMembers,listRegisteredUsersForAdminSelection } from "@/src/modules/authorization/server/admin-team";
import { AdminPrivilegeAssignment } from "./admin-privilege-assignment";

export const dynamic="force-dynamic";

export default async function AdminTeamPage({searchParams}:{searchParams:Promise<{assigned?:string;revoked?:string;error?:string}>}){
  await requireSuperAdmin();
  const[members,registeredUsers,query]=await Promise.all([listAdminMembers(),listRegisteredUsersForAdminSelection(),searchParams]),activeCount=members.documents.filter(member=>member.status==="active").length,assignableCount=registeredUsers.filter(user=>user.status&&!user.protected).length,roles=ADMIN_ROLES.map(role=>({id:role,name:ADMIN_ROLE_INFO[role].name,description:ADMIN_ROLE_INFO[role].description}));
  return <main className="admin-detail"><header><div><p className="kicker">ACCESS CONTROL</p><h1>Administrative team and privileges</h1><p>Select an existing PAC-SM account, then grant several operational privileges in one action.</p>{query.assigned&&<p className="success-note">{query.assigned} privilege{query.assigned==="1"?"":"s"} assigned.</p>}{query.revoked&&<p className="success-note">Privilege revoked.</p>}{query.error==="roles"&&<p className="form-error">Select at least one administrative privilege.</p>}{query.error==="not_found"&&<p className="form-error">The selected Appwrite account no longer exists. Refresh the directory and choose another account.</p>}{query.error==="disabled"&&<p className="form-error">Disabled accounts cannot receive administrative privileges.</p>}{query.error==="superadmin"&&<p className="form-error">Super Administrator privileges cannot be changed from Admin Team.</p>}{query.error==="scope"&&<p className="form-error">The Appwrite runtime key cannot manage users. Enable users.read and users.write on the single Coolify APPWRITE_API_KEY.</p>}{query.error==="assignment"&&<p className="form-error">Appwrite could not save one or more selected privileges. Please retry or check the application log for the exact backend response.</p>}</div><Link href="/admin">Admin overview</Link></header><section className="admin-role-summary"><article><span>REGISTERED ACCOUNTS</span><strong>{registeredUsers.length}</strong></article><article><span>ASSIGNABLE ACCOUNTS</span><strong>{assignableCount}</strong></article><article><span>AVAILABLE PRIVILEGES</span><strong>{ADMIN_ROLES.length}</strong></article><article><span>ACTIVE ASSIGNMENTS</span><strong>{activeCount}</strong></article></section><section className="catalogue-create admin-role-create"><h2>Assign multiple privileges</h2><p>Search the live Appwrite user directory and choose the registered email that should receive access.</p><AdminPrivilegeAssignment users={registeredUsers} roles={roles}/><p>Privileges are cumulative and can be revoked individually below. Disabled accounts and the protected Super Administrator account cannot be selected.</p></section><section className="review-table"><div className="review-row review-head"><span>Email</span><span>Privilege</span><span>Status</span><span>Action</span></div>{members.documents.map(member=><div className="review-row" key={member.$id}><span>{String(member.email)}</span><strong>{ADMIN_ROLE_INFO[String(member.role) as keyof typeof ADMIN_ROLE_INFO]?.name??String(member.role)}</strong><span>{String(member.status)}</span>{member.status==="active"?<form action={`/api/admin/team/${member.$id}/revoke`} method="post"><button>Revoke this privilege</button></form>:<span>{member.revokedAt?new Date(String(member.revokedAt)).toLocaleDateString("en-GB"):"—"}</span>}</div>)}</section></main>
}
