import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { requireAcademyLearner } from "@/src/modules/academy/server/access";
import { getAcademyDashboard,isAcademyModuleUnlocked } from "@/src/modules/academy/server/repository";
import { ACADEMY_MODULES,findAcademyModule } from "@/src/modules/academy/domain/curriculum";
import { findAcademyLessonContent } from "@/src/modules/academy/domain/lesson-content";

export const dynamic="force-dynamic";

export default async function AcademyModulePage({params,searchParams}:{params:Promise<{moduleId:string}>;searchParams:Promise<{completed?:string;error?:string}>}){
  const user=await requireAcademyLearner(),[{moduleId},query]=await Promise.all([params,searchParams]),module=findAcademyModule(moduleId);
  if(!module)notFound();
  const dashboard=await getAcademyDashboard(user.$id);
  if(!dashboard.enrollment)redirect("/academy");
  if(!isAcademyModuleUnlocked(module.id,dashboard.completedLessonIds,dashboard.passedModuleIds))redirect("/academy");
  const moduleIndex=ACADEMY_MODULES.findIndex(item=>item.id===module.id),previous=ACADEMY_MODULES[moduleIndex-1],next=ACADEMY_MODULES[moduleIndex+1],moduleComplete=module.lessons.every(lesson=>dashboard.completedLessonIds.has(lesson.id)),assessmentPassed=dashboard.passedModuleIds.has(module.id);
  return <main className="academy-shell academy-module-page">
    <nav className="academy-nav"><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><div><Link href="/academy">Academy dashboard</Link><Link href="/account">My account</Link></div></nav>
    <header className="academy-module-hero"><div><p className="kicker">MODULE {module.number} · {module.durationHours} HOURS</p><h1>{module.title}</h1><p>{module.purpose}</p></div><strong>{module.lessons.filter(lesson=>dashboard.completedLessonIds.has(lesson.id)).length}/{module.lessons.length}<span>lessons complete</span></strong></header>
    {query.completed&&<p className="academy-success">Lesson completed and your Academy record was updated.</p>}{query.error&&<p className="form-error">The lesson could not be completed. Finish lessons and modules in sequence.</p>}
    <section className="academy-lessons">{module.lessons.map((lesson,index)=>{const completed=dashboard.completedLessonIds.has(lesson.id),available=module.lessons.slice(0,index).every(item=>dashboard.completedLessonIds.has(item.id)),content=findAcademyLessonContent(lesson.id);return <article className={completed?"completed":available?"available":"pending"} key={lesson.id}><div className="academy-lesson-index">{completed?"✓":index+1}</div><div><span>{completed?"COMPLETED":available?"READY TO LEARN":"COMPLETE THE PREVIOUS LESSON"}</span><h2>{lesson.title}</h2><p className="academy-lesson-summary">{lesson.summary}</p>{available&&content?<div className="academy-reading"><div className="academy-reading-lead"><b>Lesson reading</b><p>{content.introduction}</p></div><section className="academy-objectives"><h3>What you will learn</h3><ul>{content.objectives.map(objective=><li key={objective}>{objective}</li>)}</ul></section>{content.sections.map(section=><section className="academy-reading-section" key={section.heading}><h3>{section.heading}</h3>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{section.points&&<ul>{section.points.map(point=><li key={point}>{point}</li>)}</ul>}{section.example&&<aside className="academy-example"><strong>{section.example.title}</strong><p>{section.example.body}</p></aside>}</section>)}<section className="academy-takeaways"><h3>Key takeaways</h3><ul>{content.keyTakeaways.map(item=><li key={item}>{item}</li>)}</ul></section><section className="academy-reflection"><h3>Pause and reflect</h3><ol>{content.reflection.map(item=><li key={item}>{item}</li>)}</ol></section></div>:available?<p className="academy-content-notice">The full lesson reading is being prepared. This lesson cannot be completed yet.</p>:null}<aside className="academy-practical"><strong>Practical application</strong><p>{lesson.activity}</p></aside>{available&&!completed&&content&&<form action="/api/academy/progress" method="post"><input type="hidden" name="moduleId" value={module.id}/><input type="hidden" name="lessonId" value={lesson.id}/><button>Mark lesson complete</button></form>}</div></article>})}</section>
    {moduleComplete&&<section className="academy-assessment-gate"><div><span>PROTECTED MODULE ASSESSMENT</span><h2>{assessmentPassed?"Assessment passed":"Your reading is complete"}</h2><p>{assessmentPassed?"Your result is recorded. The next module is now available.":"Complete the timed assessment with a score of 70% or higher to unlock the next module."}</p></div><Link href={`/academy/assessments/${module.id}`}>{assessmentPassed?"View result":"Take assessment"} →</Link></section>}
    <footer className="academy-module-navigation">{previous?<Link href={`/academy/modules/${previous.id}`}>← Previous module</Link>:<span/>}{next&&isAcademyModuleUnlocked(next.id,dashboard.completedLessonIds,dashboard.passedModuleIds)?<Link href={`/academy/modules/${next.id}`}>Next module →</Link>:<Link href="/academy">Return to dashboard →</Link>}</footer>
  </main>
}
