import "server-only";
import { ID, Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
const databaseId = () => env().APPWRITE_DATABASE_ID;
const db = () => createAppwriteDatabaseClient().databases;
export const listWarehouses = (vendorId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "warehouses", queries: [Query.equal("vendorId", vendorId), Query.limit(5000)] });
export const listOffers = (vendorId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "seller_offers", queries: [Query.equal("vendorId", vendorId), Query.limit(5000)] });
export const listBalances = (vendorId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "inventory_balances", queries: [Query.equal("vendorId", vendorId), Query.limit(5000)] });
export const listMovements = (vendorId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "inventory_movements", queries: [Query.equal("vendorId", vendorId), Query.orderDesc("occurredAt"), Query.limit(500)] });
export async function createWarehouse(vendorId: string, name: string, countryCode: string, address: string) { return db().createDocument({ databaseId: databaseId(), collectionId: "warehouses", documentId: ID.unique(), permissions: [], data: { vendorId, name, countryCode, address, status: "active" } }); }
export async function ensureMainStockLocation(vendorId: string) {
  const databases = db(), existing = await listWarehouses(vendorId);
  const preferred = existing.documents.find(item => item.warehouseType === "seller_default" && item.status === "active") ?? existing.documents.find(item => item.status === "active");
  if (preferred) return preferred;
  const stores = await databases.listDocuments({ databaseId: databaseId(), collectionId: "stores", queries: [Query.equal("vendorId", vendorId), Query.limit(1)] }), store = stores.documents[0];
  try { return await databases.createDocument({ databaseId: databaseId(), collectionId: "warehouses", documentId: vendorId, permissions: [], data: { vendorId, name: "Main stock location", countryCode: String(store?.countryCode ?? "NG"), address: "Primary seller stock location", warehouseType: "seller_default", status: "active" } }); }
  catch (error) { if (typeof error === "object" && error && "code" in error && error.code === 409) return databases.getDocument({ databaseId: databaseId(), collectionId: "warehouses", documentId: vendorId }); throw error; }
}
export async function listProductsForOffers(productIds: string[]) { if (!productIds.length) return { documents: [] }; const unique = [...new Set(productIds)]; return db().listDocuments({ databaseId: databaseId(), collectionId: "products", queries: [Query.equal("$id", unique), Query.limit(Math.min(5000, unique.length))] }); }
export async function receiveStock(input: { vendorId: string; warehouseId: string; offerId: string; quantity: number; actorUserId: string }) { const databases = db(); if (!Number.isSafeInteger(input.quantity) || input.quantity < 1) throw new Error("Invalid quantity"); const transaction = await databases.createTransaction({ ttl: 120 }); try { const [warehouse, offer, balances] = await Promise.all([databases.getDocument({databaseId:databaseId(),collectionId:"warehouses",documentId:input.warehouseId,transactionId:transaction.$id}),databases.getDocument({databaseId:databaseId(),collectionId:"seller_offers",documentId:input.offerId,transactionId:transaction.$id}),databases.listDocuments({databaseId:databaseId(),collectionId:"inventory_balances",queries:[Query.equal("offerId",input.offerId),Query.equal("warehouseId",input.warehouseId),Query.limit(1)],transactionId:transaction.$id})]); if (warehouse.vendorId !== input.vendorId || offer.vendorId !== input.vendorId) throw new Error("Invalid tenant-scoped inventory target"); const balance=balances.documents[0]; if(balance) await databases.incrementDocumentAttribute({databaseId:databaseId(),collectionId:"inventory_balances",documentId:balance.$id,attribute:"onHand",value:input.quantity,transactionId:transaction.$id}); else await databases.createDocument({ databaseId: databaseId(), collectionId: "inventory_balances", documentId: ID.unique(), permissions: [], transactionId:transaction.$id, data: { vendorId: input.vendorId, warehouseId: input.warehouseId, offerId: input.offerId, onHand: input.quantity, reserved: 0, incoming: 0, damaged: 0, version: 1, reorderPoint:0 } }); await databases.createDocument({ databaseId: databaseId(), collectionId: "inventory_movements", documentId: ID.unique(), permissions: [], transactionId:transaction.$id, data: { vendorId: input.vendorId, warehouseId: input.warehouseId, offerId: input.offerId, type: "stock_received", quantity: input.quantity, actorUserId: input.actorUserId, occurredAt: new Date().toISOString() } }); await databases.updateTransaction({transactionId:transaction.$id,commit:true}); } catch(error){await databases.updateTransaction({transactionId:transaction.$id,rollback:true}).catch(()=>undefined);throw error} }

export async function setReorderPoint(vendorId:string,balanceId:string,reorderPoint:number,actorUserId:string){if(!Number.isSafeInteger(reorderPoint)||reorderPoint<0)throw new Error("Invalid reorder point");const databases=db(),balance=await databases.getDocument({databaseId:databaseId(),collectionId:"inventory_balances",documentId:balanceId});if(String(balance.vendorId)!==vendorId)throw new Error("Inventory not owned");await databases.updateDocument({databaseId:databaseId(),collectionId:"inventory_balances",documentId:balanceId,data:{reorderPoint}});await databases.createDocument({databaseId:databaseId(),collectionId:"audit_logs",documentId:ID.unique(),permissions:[],data:{actorUserId,action:"inventory.reorder_point",entityType:"inventory_balance",entityId:balanceId,metadata:JSON.stringify({reorderPoint}),occurredAt:new Date().toISOString()}})}
