import "server-only";
import { ID, Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
const databaseId = () => env().APPWRITE_DATABASE_ID;
const db = () => createAppwriteDatabaseClient().databases;
export const listWarehouses = (vendorId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "warehouses", queries: [Query.equal("vendorId", vendorId), Query.limit(100)] });
export const listOffers = (vendorId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "seller_offers", queries: [Query.equal("vendorId", vendorId), Query.limit(100)] });
export const listBalances = (vendorId: string) => db().listDocuments({ databaseId: databaseId(), collectionId: "inventory_balances", queries: [Query.equal("vendorId", vendorId), Query.limit(100)] });
export async function createWarehouse(vendorId: string, name: string, countryCode: string, address: string) { return db().createDocument({ databaseId: databaseId(), collectionId: "warehouses", documentId: ID.unique(), permissions: [], data: { vendorId, name, countryCode, address, status: "active" } }); }
export async function receiveStock(input: { vendorId: string; warehouseId: string; offerId: string; quantity: number; actorUserId: string }) { const databases = db(); const [warehouses, offers, balances] = await Promise.all([listWarehouses(input.vendorId), listOffers(input.vendorId), listBalances(input.vendorId)]); if (!warehouses.documents.some((item) => item.$id === input.warehouseId) || !offers.documents.some((item) => item.$id === input.offerId)) throw new Error("Invalid tenant-scoped inventory target"); const balance = balances.documents.find((item) => item.warehouseId === input.warehouseId && item.offerId === input.offerId); if (balance) await databases.updateDocument({ databaseId: databaseId(), collectionId: "inventory_balances", documentId: balance.$id, data: { onHand: Number(balance.onHand) + input.quantity, version: Number(balance.version) + 1 } }); else await databases.createDocument({ databaseId: databaseId(), collectionId: "inventory_balances", documentId: ID.unique(), permissions: [], data: { vendorId: input.vendorId, warehouseId: input.warehouseId, offerId: input.offerId, onHand: input.quantity, reserved: 0, incoming: 0, damaged: 0, version: 1 } }); await databases.createDocument({ databaseId: databaseId(), collectionId: "inventory_movements", documentId: ID.unique(), permissions: [], data: { vendorId: input.vendorId, warehouseId: input.warehouseId, offerId: input.offerId, type: "stock_received", quantity: input.quantity, actorUserId: input.actorUserId, occurredAt: new Date().toISOString() } }); }
