import "server-only";
import { ID, Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
const databaseId = () => env().APPWRITE_DATABASE_ID;
const db = () => createAppwriteDatabaseClient().databases;
export async function getCart(userId: string) { const databases = db(); try { const cart = await databases.getDocument({ databaseId: databaseId(), collectionId: "carts", documentId: userId }); const items = await databases.listDocuments({ databaseId: databaseId(), collectionId: "cart_items", queries: [Query.equal("cartId", cart.$id), Query.limit(100)] }); return { cart, items: items.documents }; } catch (error) { if (typeof error === "object" && error && "code" in error && error.code === 404) return { cart: null, items: [] }; throw error; } }
export async function addToCart(userId: string, offerId: string, requestedQuantity: number) { const databases = db(); const offer = await databases.getDocument({ databaseId: databaseId(), collectionId: "seller_offers", documentId: offerId }); if (offer.status !== "approved") throw new Error("Offer unavailable"); const [product, vendor, balances] = await Promise.all([databases.getDocument({ databaseId: databaseId(), collectionId: "products", documentId: String(offer.productId) }), databases.getDocument({ databaseId: databaseId(), collectionId: "vendors", documentId: String(offer.vendorId) }), databases.listDocuments({ databaseId: databaseId(), collectionId: "inventory_balances", queries: [Query.equal("offerId", offerId), Query.limit(100)] })]); if (product.status !== "approved" || !["approved", "active"].includes(String(vendor.status))) throw new Error("Offer unavailable"); const available = balances.documents.reduce((sum, item) => sum + Number(item.onHand) - Number(item.reserved) - Number(item.damaged), 0); const current = await getCart(userId); const existing = current.items.find((item) => item.offerId === offerId); const quantity = Number(existing?.quantity ?? 0) + requestedQuantity; if (quantity < Number(offer.minimumOrderQuantity) || quantity > available || (offer.maximumOrderQuantity && quantity > Number(offer.maximumOrderQuantity))) throw new Error("Quantity unavailable"); if (!current.cart) await databases.createDocument({ databaseId: databaseId(), collectionId: "carts", documentId: userId, permissions: [], data: { userId, status: "active", updatedAt: new Date().toISOString() } }); else await databases.updateDocument({ databaseId: databaseId(), collectionId: "carts", documentId: userId, data: { updatedAt: new Date().toISOString() } }); const data = { cartId: userId, userId, vendorId: offer.vendorId, productId: product.$id, ...(offer.variantId ? { variantId: offer.variantId } : {}), offerId, quantity, unitPriceMinor: offer.retailPriceMinor, currency: offer.currency, productName: product.name, sellerSku: offer.sellerSku, fulfilmentMethod: offer.fulfilmentMethod, updatedAt: new Date().toISOString() }; if (existing) await databases.updateDocument({ databaseId: databaseId(), collectionId: "cart_items", documentId: existing.$id, data }); else await databases.createDocument({ databaseId: databaseId(), collectionId: "cart_items", documentId: ID.unique(), permissions: [], data }); }
export async function removeCartItem(userId: string, itemId: string) { const databases = db(); const item = await databases.getDocument({ databaseId: databaseId(), collectionId: "cart_items", documentId: itemId }); if (item.userId !== userId) throw new Error("Forbidden"); await databases.deleteDocument({ databaseId: databaseId(), collectionId: "cart_items", documentId: itemId }); }
