import "server-only";
import {ID,Query,type Models} from "node-appwrite";
import {createAppwriteAuthClient,createAppwriteDatabaseClient} from "@/src/integrations/appwrite/server";
import {env} from "@/src/shared/config/env";
import {isSuperAdmin} from "@/src/modules/authorization/domain/super-admin";

type User=Models.User<Models.Preferences>;
type Dependency={collection:string;attribute:string;label:string};
export type AccountLifecycleReview={user:User;sessions:number;blockers:Array<{label:string;count:number}>;canDelete:boolean};
const retainedDependencies:Dependency[]=[
  {collection:"vendors",attribute:"ownerUserId",label:"seller or vendor application"},{collection:"admin_members",attribute:"userId",label:"administrative assignment"},
  {collection:"orders",attribute:"customerUserId",label:"customer order"},{collection:"payments",attribute:"customerUserId",label:"payment record"},{collection:"return_requests",attribute:"customerUserId",label:"return request"},{collection:"refunds",attribute:"customerUserId",label:"refund record"},{collection:"disputes",attribute:"customerUserId",label:"dispute record"},
  {collection:"business_buyers",attribute:"userId",label:"business-buyer profile"},{collection:"price_negotiations",attribute:"buyerUserId",label:"wholesale negotiation"},{collection:"purchase_orders",attribute:"buyerUserId",label:"purchase order"},{collection:"proforma_invoices",attribute:"buyerUserId",label:"proforma invoice"},{collection:"rfqs",attribute:"buyerUserId",label:"procurement request"},{collection:"quotations",attribute:"buyerUserId",label:"procurement quotation"},
  {collection:"offtaker_applications",attribute:"ownerUserId",label:"off-taker application"},{collection:"carrier_applications",attribute:"ownerUserId",label:"carrier application"},{collection:"carriers",attribute:"ownerUserId",label:"carrier account"},
  {collection:"academy_enrollments",attribute:"userId",label:"Academy enrolment"},{collection:"academy_attempts",attribute:"userId",label:"Academy assessment record"},{collection:"academy_projects",attribute:"userId",label:"Academy project"},{collection:"academy_certificates",attribute:"userId",label:"Academy certificate"},{collection:"fraud_signals",attribute:"userId",label:"risk or fraud review"}
];
const removableData:Dependency[]=[
  {collection:"cart_items",attribute:"userId",label:"cart item"},{collection:"carts",attribute:"userId",label:"cart"},{collection:"customer_addresses",attribute:"userId",label:"address"},{collection:"customer_profiles",attribute:"userId",label:"customer profile"},{collection:"profiles",attribute:"userId",label:"profile"},{collection:"wishlists",attribute:"userId",label:"wishlist"},{collection:"notifications",attribute:"userId",label:"notification"}
];
const database=()=>createAppwriteDatabaseClient().databases,databaseId=()=>env().APPWRITE_DATABASE_ID;
async function countDependency(userId:string,item:Dependency){const result=await database().listDocuments({databaseId:databaseId(),collectionId:item.collection,queries:[Query.equal(item.attribute,userId),Query.limit(1)]});return result.total;}
async function audit(actorUserId:string,action:string,user:User,reason:string,extra:Record<string,unknown>={}){await database().createDocument({databaseId:databaseId(),collectionId:"audit_logs",documentId:ID.unique(),permissions:[],data:{actorUserId,action,entityType:"user",entityId:user.$id,metadata:JSON.stringify({email:user.email,reason,...extra}),occurredAt:new Date().toISOString()}})}
export async function reviewAccountLifecycle(userId:string):Promise<AccountLifecycleReview>{const {users}=createAppwriteAuthClient(),user=await users.get({userId}),[sessions,...counts]=await Promise.all([users.listSessions({userId,total:true}),...retainedDependencies.map(item=>countDependency(userId,item))]),blockers=retainedDependencies.flatMap((item,index)=>counts[index]>0?[{label:item.label,count:counts[index]}]:[]);if(isSuperAdmin(user.labels))blockers.unshift({label:"protected Super Administrator account",count:1});else if(user.labels.length)blockers.unshift({label:"Appwrite account privilege label",count:user.labels.length});return{user,sessions:sessions.total,blockers,canDelete:blockers.length===0};}
export async function performAccountLifecycleAction(input:{targetUserId:string;actorUserId:string;action:"suspend"|"reactivate"|"revoke_sessions"|"delete";reason:string;confirmation:string}){const review=await reviewAccountLifecycle(input.targetUserId),{users}=createAppwriteAuthClient(),reason=input.reason.trim();if(isSuperAdmin(review.user.labels))throw new Error("PROTECTED_ACCOUNT");if(reason.length<10)throw new Error("REASON_REQUIRED");if(input.action==="suspend"){await users.updateStatus({userId:review.user.$id,status:false});await users.deleteSessions({userId:review.user.$id});await audit(input.actorUserId,"account.suspended",review.user,reason);return}if(input.action==="reactivate"){await users.updateStatus({userId:review.user.$id,status:true});await audit(input.actorUserId,"account.reactivated",review.user,reason);return}if(input.action==="revoke_sessions"){await users.deleteSessions({userId:review.user.$id});await audit(input.actorUserId,"account.sessions_revoked",review.user,reason,{sessions:review.sessions});return}if(input.confirmation!==`DELETE ${review.user.email}`)throw new Error("CONFIRMATION_REQUIRED");if(!review.canDelete)throw new Error("DEPENDENCIES_EXIST");await audit(input.actorUserId,"account.deletion_started",review.user,reason);for(const item of removableData){const result=await database().listDocuments({databaseId:databaseId(),collectionId:item.collection,queries:[Query.equal(item.attribute,review.user.$id),Query.limit(5000)]});for(const document of result.documents)await database().deleteDocument({databaseId:databaseId(),collectionId:item.collection,documentId:document.$id})}await users.deleteSessions({userId:review.user.$id});await users.delete({userId:review.user.$id});await audit(input.actorUserId,"account.deleted",review.user,reason).catch(error=>console.error("Deleted account completion audit failed",error));}
