import "server-only";import{ID,Query}from"node-appwrite";import{createAppwriteDatabaseClient}from"@/src/integrations/appwrite/server";import{env}from"@/src/shared/config/env";import{resolveWholesalePrice}from"@/src/modules/wholesale/domain/pricing";
const db=()=>createAppwriteDatabaseClient().databases,id=()=>env().APPWRITE_DATABASE_ID;
export const findBusinessBuyer=(userId:string)=>db().listDocuments({databaseId:id(),collectionId:"business_buyers",queries:[Query.equal("userId",userId),Query.limit(1)]}).then(r=>r.documents[0]??null);
export const listBusinessBuyers=()=>db().listDocuments({databaseId:id(),collectionId:"business_buyers",queries:[Query.orderDesc("createdAt"),Query.limit(100)]});
export async function registerBusinessBuyer(input:{userId:string;organizationName:string;registrationNumber:string;countryCode:string;buyerType:string}){await db().createDocument({databaseId:id(),collectionId:"business_buyers",documentId:ID.unique(),permissions:[],data:{...input,organizationName:input.organizationName.trim(),registrationNumber:input.registrationNumber.trim(),countryCode:input.countryCode.toUpperCase(),status:"pending_review",createdAt:new Date().toISOString()}})}
export async function reviewBusinessBuyer(buyerId:string,approve:boolean,actorUserId:string){await db().updateDocument({databaseId:id(),collectionId:"business_buyers",documentId:buyerId,data:{status:approve?"approved":"rejected",reviewedAt:new Date().toISOString(),reviewedBy:actorUserId}})}
export const listWholesaleOffers=()=>db().listDocuments({databaseId:id(),collectionId:"seller_offers",queries:[Query.equal("status","approved"),Query.greaterThan("minimumOrderQuantity",1),Query.limit(100)]});
export const listPriceTiers=(offerId:string)=>db().listDocuments({databaseId:id(),collectionId:"offer_price_tiers",queries:[Query.equal("offerId",offerId),Query.orderAsc("minimumQuantity"),Query.limit(100)]});
export async function addPriceTier(input:{vendorId:string;offerId:string;minimumQuantity:number;maximumQuantity?:number;unitPriceMinor:number}){const offer=await db().getDocument({databaseId:id(),collectionId:"seller_offers",documentId:input.offerId});if(offer.vendorId!==input.vendorId||input.minimumQuantity<Number(offer.minimumOrderQuantity)||input.unitPriceMinor<1)throw new Error("Invalid tier");await db().createDocument({databaseId:id(),collectionId:"offer_price_tiers",documentId:ID.unique(),permissions:[],data:{...input,currency:offer.currency,createdAt:new Date().toISOString()}})}
export const listBuyerPurchaseOrders=(userId:string)=>db().listDocuments({databaseId:id(),collectionId:"purchase_orders",queries:[Query.equal("buyerUserId",userId),Query.orderDesc("createdAt"),Query.limit(100)]});
export const listVendorPurchaseOrders=(vendorId:string)=>db().listDocuments({databaseId:id(),collectionId:"purchase_orders",queries:[Query.equal("vendorId",vendorId),Query.orderDesc("createdAt"),Query.limit(100)]});
export async function createPurchaseOrder(input:{userId:string;offerId:string;quantity:number}){const [buyer,offer]=await Promise.all([findBusinessBuyer(input.userId),db().getDocument({databaseId:id(),collectionId:"seller_offers",documentId:input.offerId})]);if(!buyer||buyer.status!=="approved"||offer.status!=="approved"||input.quantity<Number(offer.minimumOrderQuantity)||!Number.isInteger(input.quantity))throw new Error("Wholesale order not allowed");const [product,tiers]=await Promise.all([db().getDocument({databaseId:id(),collectionId:"products",documentId:String(offer.productId)}),listPriceTiers(offer.$id)]),unitPriceMinor=resolveWholesalePrice(input.quantity,Number(offer.wholesalePriceMinor??offer.retailPriceMinor),tiers.documents.map(t=>({minimumQuantity:Number(t.minimumQuantity),maximumQuantity:t.maximumQuantity?Number(t.maximumQuantity):undefined,unitPriceMinor:Number(t.unitPriceMinor)}))),poId=ID.unique(),now=new Date().toISOString(),totalMinor=unitPriceMinor*input.quantity;await db().createDocument({databaseId:id(),collectionId:"purchase_orders",documentId:poId,permissions:[],data:{purchaseOrderNumber:`PAC-PO-${new Date().getUTCFullYear()}-${poId.slice(-10).toUpperCase()}`,buyerUserId:input.userId,businessBuyerId:buyer.$id,vendorId:offer.vendorId,status:"submitted",currency:offer.currency,totalMinor,createdAt:now,submittedAt:now}});await db().createDocument({databaseId:id(),collectionId:"purchase_order_items",documentId:ID.unique(),permissions:[],data:{purchaseOrderId:poId,productId:offer.productId,offerId:offer.$id,productName:product.name,quantity:input.quantity,unitPriceMinor,lineTotalMinor:totalMinor,currency:offer.currency}});return poId}
export async function acceptPurchaseOrder(vendorId:string,poId:string){const po=await db().getDocument({databaseId:id(),collectionId:"purchase_orders",documentId:poId});if(po.vendorId!==vendorId||po.status!=="submitted")throw new Error("Purchase order not found");const now=new Date().toISOString(),invoiceId=ID.unique();await db().updateDocument({databaseId:id(),collectionId:"purchase_orders",documentId:poId,data:{status:"accepted",acceptedAt:now}});await db().createDocument({databaseId:id(),collectionId:"proforma_invoices",documentId:invoiceId,permissions:[],data:{invoiceNumber:`PAC-PFI-${new Date().getUTCFullYear()}-${invoiceId.slice(-10).toUpperCase()}`,purchaseOrderId:poId,buyerUserId:po.buyerUserId,vendorId,totalMinor:po.totalMinor,currency:po.currency,status:"issued",issuedAt:now,expiresAt:new Date(Date.now()+604800000).toISOString()}})}
