import nextEnv from "@next/env";
import { readFileSync } from "node:fs";
import { Client, Compression, Databases, IndexType, Storage } from "node-appwrite";
import { ACADEMY_COURSE,ACADEMY_MODULES } from "../src/modules/academy/domain/curriculum";
import { findAcademyLessonContent } from "../src/modules/academy/domain/lesson-content";

nextEnv.loadEnvConfig(process.cwd());

function required(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`${name} is required`);
  return value;
}

function provisioningKey(): string {
  const direct = process.env.APPWRITE_PROVISIONING_KEY?.trim();
  if (direct) return direct;
  const file = required("APPWRITE_PROVISIONING_KEY_FILE");
  const secret = readFileSync(file, "utf8").trim();
  if (!secret) throw new Error("Appwrite provisioning-key file is empty");
  return secret;
}

const client = new Client()
  .setEndpoint(required("APPWRITE_ENDPOINT"))
  .setProject(required("APPWRITE_PROJECT_ID"))
  .setKey(provisioningKey());

const storage = new Storage(client);
const databases = new Databases(client);
const databaseId = required("APPWRITE_DATABASE_ID");

type Attribute = { key: string; type: "string" | "integer" | "datetime"; size?: number; required?: boolean; array?: boolean; encrypt?: boolean };
type Index = { key: string; type: "key" | "unique"; attributes: string[] };
const s = (key: string, size: number, required = false): Attribute => ({ key, type: "string", size, required });
const dt = (key: string, required = false): Attribute => ({ key, type: "datetime", required });
const i = (key: string, required = false): Attribute => ({ key, type: "integer", required });
const secret = (key: string, size: number): Attribute => ({ key, type: "string", size: Math.max(150, size), required: true, encrypt: true });
const idx = (key: string, type: "key" | "unique", attributes: string[]): Index => ({ key, type, attributes });

const collections: { id: string; name: string; attributes: Attribute[]; indexes: Index[] }[] = [
  { id: "support_channels", name: "Customer Support Channels", attributes: [s("label",120,true),s("whatsappNumber",24,true),s("prefilledMessage",500),s("status",24,true),i("sortOrder",true),s("createdBy",36,true),dt("createdAt",true),dt("updatedAt",true)], indexes: [idx("support_number_unique","unique",["whatsappNumber"]),idx("support_status_order_idx","key",["status","sortOrder"])] },
  { id: "profiles", name: "User Profiles", attributes: [s("userId", 36, true), s("email", 320, true), s("fullName", 180, true), s("phone", 40), s("countryCode", 2, true)], indexes: [idx("user_unique", "unique", ["userId"]), idx("email_idx", "key", ["email"])] },
  { id: "businesses", name: "Businesses", attributes: [s("ownerUserId", 36, true), s("legalName", 180, true), s("tradingName", 180), s("registrationNumber", 100, true), s("taxId", 100), s("countryCode", 2, true), s("businessType", 60, true), s("address", 1000, true), s("status", 32, true)], indexes: [idx("business_owner_idx", "key", ["ownerUserId"]), idx("registration_idx", "key", ["registrationNumber"])] },
  { id: "vendors", name: "Vendor Applications", attributes: [s("ownerUserId", 36, true), s("businessId", 36, true), s("merchantId", 40), s("status", 32, true), dt("submittedAt", true), dt("reviewedAt"), s("reviewedBy", 36), s("reviewNotes", 2000)], indexes: [idx("vendor_owner_unique", "unique", ["ownerUserId"]), idx("vendor_status_idx", "key", ["status"]), idx("merchant_unique", "unique", ["merchantId"])] },
  { id: "vendor_documents", name: "Vendor KYC Documents", attributes: [s("vendorId", 36, true), s("ownerUserId", 36, true), s("documentType", 60, true), s("bucketId", 36, true), s("fileId", 36, true), s("filename", 255, true), s("mimeType", 100, true), i("sizeBytes", true), s("status", 32, true)], indexes: [idx("document_vendor_idx", "key", ["vendorId"]), idx("document_file_unique", "unique", ["fileId"])] },
  { id: "vendor_compliance", name: "Vendor Compliance Profiles", attributes: [s("vendorId", 36, true), s("ownerUserId", 36, true), s("vendorType", 60, true), s("operationalAddress", 1000, true), { ...s("directors", 200, true), array: true }, { ...s("beneficialOwners", 200, true), array: true }, s("bankName", 180, true), s("bankAccountName", 180, true), secret("bankAccountNumber", 100), s("bankCountryCode", 2, true), s("swiftCode", 20), s("exporterNumber", 100), s("complianceStatus", 32, true)], indexes: [idx("compliance_vendor_unique", "unique", ["vendorId"]), idx("compliance_owner_idx", "key", ["ownerUserId"])] },
  { id: "stores", name: "Vendor Stores", attributes: [s("vendorId", 36, true), s("ownerUserId", 36, true), s("name", 180, true), s("slug", 100, true), s("countryCode", 2, true), s("currency", 3, true), s("status", 32, true), s("themePrimary", 7), s("themeAccent", 7), s("logoFileId", 36), s("logoAltText", 180), dt("brandingUpdatedAt")], indexes: [idx("store_vendor_unique", "unique", ["vendorId"]), idx("store_slug_unique", "unique", ["slug"])] },
  { id: "vendor_review_events", name: "Vendor Review History", attributes: [s("vendorId", 36, true), s("action", 40, true), s("actorUserId", 36, true), s("notes", 2000), dt("occurredAt", true)], indexes: [idx("review_vendor_idx", "key", ["vendorId"])] },
  { id: "audit_logs", name: "Audit Logs", attributes: [s("actorUserId", 36, true), s("action", 100, true), s("entityType", 60, true), s("entityId", 36, true), s("metadata", 10000), dt("occurredAt", true)], indexes: [idx("audit_entity_idx", "key", ["entityType", "entityId"]), idx("audit_actor_idx", "key", ["actorUserId"])] }
  ,{ id: "categories", name: "Catalogue Categories", attributes: [s("name", 120, true), s("slug", 120, true), s("parentId", 36), s("status", 24, true)], indexes: [idx("category_slug_unique", "unique", ["slug"]), idx("category_status_idx", "key", ["status"])] }
  ,{ id: "brands", name: "Catalogue Brands", attributes: [s("name", 120, true), s("slug", 120, true), s("status", 24, true)], indexes: [idx("brand_slug_unique", "unique", ["slug"])] }
  ,{ id: "products", name: "Canonical Products", attributes: [s("submittedByVendorId", 36, true), s("name", 240, true), s("slug", 240, true), s("description", 5000, true), s("categoryId", 36, true), s("brandName", 120), s("manufacturer", 180), s("countryOfOrigin", 2, true), s("model", 120), s("gtin", 32), s("specifications", 10000), s("status", 32, true), dt("submittedAt", true), s("reviewedBy", 36), dt("reviewedAt")], indexes: [idx("product_slug_unique", "unique", ["slug"]), idx("product_vendor_idx", "key", ["submittedByVendorId"]), idx("product_status_idx", "key", ["status"]), idx("product_category_idx", "key", ["categoryId"])] }
  ,{ id: "product_media", name: "Product Media", attributes: [s("productId", 36, true), s("vendorId", 36, true), s("bucketId", 36, true), s("fileId", 36, true), s("filename", 255, true), s("mimeType", 100, true), i("sizeBytes", true), s("altText", 180, true), i("sortOrder", true), s("isPrimary", 5, true), s("status", 24, true), dt("uploadedAt", true), dt("reviewedAt"), s("reviewedBy", 36), s("reviewNotes", 1000)], indexes: [idx("media_product_idx", "key", ["productId"]), idx("media_product_status_idx", "key", ["productId", "status"]), idx("media_product_sort_idx", "key", ["productId", "sortOrder"]), idx("media_vendor_idx", "key", ["vendorId"]), idx("media_file_unique", "unique", ["fileId"])] }
  ,{ id: "product_variants", name: "Product Variants", attributes: [s("productId", 36, true), s("name", 180, true), s("sku", 100, true), s("barcode", 64), s("attributes", 5000, true), i("weightGrams"), s("status", 24, true)], indexes: [idx("variant_product_idx", "key", ["productId"]), idx("variant_sku_unique", "unique", ["sku"])] }
  ,{ id: "seller_offers", name: "Seller Offers", attributes: [s("vendorId", 36, true), s("productId", 36, true), s("variantId", 36), s("sellerSku", 100, true), i("retailPriceMinor", true), i("wholesalePriceMinor"), i("promotionalPriceMinor"), s("currency", 3, true), i("minimumOrderQuantity", true), i("maximumOrderQuantity"), s("fulfilmentMethod", 40, true), i("processingDays", true), s("status", 32, true), dt("submittedAt", true)], indexes: [idx("offer_vendor_idx", "key", ["vendorId"]), idx("offer_product_idx", "key", ["productId"]), idx("offer_sku_vendor_unique", "unique", ["vendorId", "sellerSku"]), idx("offer_status_idx", "key", ["status"])] }
  ,{ id: "warehouses", name: "Vendor Warehouses", attributes: [s("vendorId", 36, true), s("name", 180, true), s("countryCode", 2, true), s("address", 1000, true), s("warehouseType", 32), s("operatorUserId", 36), s("status", 24, true)], indexes: [idx("warehouse_vendor_idx", "key", ["vendorId"]), idx("warehouse_type_idx", "key", ["warehouseType"])] }
  ,{ id: "inventory_balances", name: "Inventory Balances", attributes: [s("vendorId", 36, true), s("warehouseId", 36, true), s("offerId", 36, true), i("onHand", true), i("reserved", true), i("incoming", true), i("damaged", true), i("version", true)], indexes: [idx("inventory_vendor_idx", "key", ["vendorId"]), idx("inventory_offer_warehouse_unique", "unique", ["offerId", "warehouseId"])] }
  ,{ id: "inventory_movements", name: "Inventory Movements", attributes: [s("vendorId", 36, true), s("warehouseId", 36, true), s("offerId", 36, true), s("type", 40, true), i("quantity", true), s("referenceType", 40), s("referenceId", 36), s("actorUserId", 36, true), dt("occurredAt", true)], indexes: [idx("movement_offer_idx", "key", ["offerId"]), idx("movement_vendor_idx", "key", ["vendorId"])] }
  ,{ id: "customer_profiles", name: "Customer Profiles", attributes: [s("userId", 36, true), s("fullName", 180, true), s("phone", 40), s("countryCode", 2, true), dt("updatedAt", true)], indexes: [idx("customer_user_unique", "unique", ["userId"])] }
  ,{ id: "customer_addresses", name: "Customer Addresses", attributes: [s("userId", 36, true), s("label", 60, true), s("recipientName", 180, true), s("phone", 40, true), s("line1", 240, true), s("line2", 240), s("city", 120, true), s("region", 120, true), s("postalCode", 30), s("countryCode", 2, true), s("status", 24, true)], indexes: [idx("address_user_idx", "key", ["userId"])] }
  ,{ id: "carts", name: "Customer Carts", attributes: [s("userId", 36, true), s("status", 24, true), dt("updatedAt", true)], indexes: [idx("cart_user_unique", "unique", ["userId"])] }
  ,{ id: "cart_items", name: "Cart Items", attributes: [s("cartId", 36, true), s("userId", 36, true), s("vendorId", 36, true), s("productId", 36, true), s("variantId", 36), s("offerId", 36, true), s("negotiationId", 36), s("purchaseOrderId", 36), i("quantity", true), i("unitPriceMinor", true), s("currency", 3, true), s("productName", 240, true), s("sellerSku", 100, true), s("fulfilmentMethod", 40, true), dt("updatedAt", true)], indexes: [idx("cart_item_cart_idx", "key", ["cartId"]), idx("cart_item_user_idx", "key", ["userId"]), idx("cart_offer_unique", "unique", ["cartId", "offerId"]), idx("cart_negotiation_idx", "key", ["negotiationId"]), idx("cart_purchase_order_idx", "key", ["purchaseOrderId"])] }
  ,{ id: "orders", name: "Customer Orders", attributes: [s("orderNumber", 40, true), s("customerUserId", 36, true), s("addressId", 36, true), s("currency", 3, true), i("subtotalMinor", true), i("totalMinor", true), s("status", 32, true), dt("createdAt", true)], indexes: [idx("order_number_unique", "unique", ["orderNumber"]), idx("order_customer_idx", "key", ["customerUserId"]), idx("order_status_idx", "key", ["status"])] }
  ,{ id: "vendor_orders", name: "Vendor Orders", attributes: [s("orderId", 36, true), s("vendorId", 36, true), s("vendorOrderNumber", 44, true), s("currency", 3, true), i("subtotalMinor", true), s("status", 32, true), dt("createdAt", true)], indexes: [idx("vendor_order_number_unique", "unique", ["vendorOrderNumber"]), idx("vendor_order_parent_idx", "key", ["orderId"]), idx("vendor_order_vendor_idx", "key", ["vendorId"])] }
  ,{ id: "order_items", name: "Order Items", attributes: [s("orderId", 36, true), s("vendorOrderId", 36, true), s("vendorId", 36, true), s("productId", 36, true), s("variantId", 36), s("offerId", 36, true), s("negotiationId", 36), s("purchaseOrderId", 36), s("productName", 240, true), s("sellerSku", 100, true), i("quantity", true), i("unitPriceMinor", true), i("lineTotalMinor", true), s("currency", 3, true)], indexes: [idx("order_item_order_idx", "key", ["orderId"]), idx("order_item_vendor_order_idx", "key", ["vendorOrderId"]), idx("order_item_vendor_idx", "key", ["vendorId"]), idx("order_item_negotiation_idx", "key", ["negotiationId"]), idx("order_item_purchase_order_idx", "key", ["purchaseOrderId"])] }
  ,{ id: "order_events", name: "Order Events", attributes: [s("orderId", 36, true), s("vendorOrderId", 36), s("eventType", 60, true), s("actorUserId", 36, true), s("metadata", 5000), dt("occurredAt", true)], indexes: [idx("order_event_order_idx", "key", ["orderId"]), idx("order_event_vendor_idx", "key", ["vendorOrderId"])] }
  ,{ id: "inventory_reservations", name: "Inventory Reservations", attributes: [s("orderId", 36, true), s("vendorId", 36, true), s("offerId", 36, true), s("warehouseId", 36, true), i("quantity", true), s("status", 24, true), dt("expiresAt", true), dt("createdAt", true)], indexes: [idx("reservation_order_idx", "key", ["orderId"]), idx("reservation_offer_idx", "key", ["offerId"]), idx("reservation_status_idx", "key", ["status"])] }
  ,{ id: "payments", name: "Customer Payments", attributes: [s("paymentNumber", 44, true), s("orderId", 36, true), s("customerUserId", 36, true), s("provider", 40, true), s("idempotencyKey", 80, true), i("amountMinor", true), s("currency", 3, true), s("status", 24, true), dt("createdAt", true), dt("capturedAt")], indexes: [idx("payment_number_unique", "unique", ["paymentNumber"]), idx("payment_order_unique", "unique", ["orderId"]), idx("payment_idempotency_unique", "unique", ["idempotencyKey"]), idx("payment_customer_idx", "key", ["customerUserId"])] }
  ,{ id: "shipments", name: "Order Shipments", attributes: [s("orderId", 36, true), s("vendorOrderId", 36, true), s("vendorId", 36, true), s("carrier", 120, true), s("trackingNumber", 120, true), s("trackingUrl", 1000), s("status", 32, true), dt("dispatchedAt", true), dt("deliveredAt"), dt("updatedAt", true)], indexes: [idx("shipment_vendor_order_unique", "unique", ["vendorOrderId"]), idx("shipment_order_idx", "key", ["orderId"]), idx("shipment_vendor_idx", "key", ["vendorId"]), idx("shipment_tracking_idx", "key", ["trackingNumber"])] }
  ,{ id: "return_requests", name: "Customer Return Requests", attributes: [s("orderId", 36, true), s("vendorOrderId", 36, true), s("customerUserId", 36, true), s("vendorId", 36, true), s("reason", 1000, true), s("status", 32, true), dt("requestedAt", true), dt("reviewedAt"), s("reviewNotes", 1000)], indexes: [idx("return_order_idx", "key", ["orderId"]), idx("return_vendor_order_unique", "unique", ["vendorOrderId"]), idx("return_customer_idx", "key", ["customerUserId"]), idx("return_vendor_idx", "key", ["vendorId"])] }
  ,{ id: "commission_rules", name: "Marketplace Commission Rules", attributes: [s("name", 120, true), i("rateBasisPoints", true), s("status", 24, true), dt("effectiveFrom", true), dt("createdAt", true)], indexes: [idx("commission_status_idx", "key", ["status"])] }
  ,{ id: "journal_entries", name: "Financial Journal Entries", attributes: [s("referenceType", 40, true), s("referenceId", 36, true), s("description", 500, true), s("currency", 3, true), s("status", 24, true), dt("postedAt", true)], indexes: [idx("journal_reference_unique", "unique", ["referenceType", "referenceId"]), idx("journal_posted_idx", "key", ["postedAt"])] }
  ,{ id: "journal_lines", name: "Financial Journal Lines", attributes: [s("journalEntryId", 36, true), s("accountCode", 80, true), s("vendorId", 36), s("direction", 6, true), i("amountMinor", true), s("currency", 3, true)], indexes: [idx("journal_line_entry_idx", "key", ["journalEntryId"]), idx("journal_line_vendor_idx", "key", ["vendorId"]), idx("journal_line_account_idx", "key", ["accountCode"])] }
  ,{ id: "refunds", name: "Customer Refunds", attributes: [s("refundNumber", 44, true), s("returnRequestId", 36, true), s("orderId", 36, true), s("vendorOrderId", 36, true), s("customerUserId", 36, true), s("vendorId", 36, true), i("amountMinor", true), s("currency", 3, true), s("status", 24, true), s("provider", 40, true), dt("createdAt", true), dt("processedAt")], indexes: [idx("refund_number_unique", "unique", ["refundNumber"]), idx("refund_return_unique", "unique", ["returnRequestId"]), idx("refund_order_idx", "key", ["orderId"]), idx("refund_vendor_idx", "key", ["vendorId"])] }
  ,{ id: "settlements", name: "Vendor Settlements", attributes: [s("settlementNumber", 44, true), s("vendorId", 36, true), i("amountMinor", true), s("currency", 3, true), s("status", 24, true), s("provider", 40, true), s("providerReference", 120), s("createdBy", 36, true), dt("createdAt", true), dt("processedAt")], indexes: [idx("settlement_number_unique", "unique", ["settlementNumber"]), idx("settlement_vendor_idx", "key", ["vendorId"]), idx("settlement_status_idx", "key", ["status"]), idx("settlement_created_idx", "key", ["createdAt"])] }
  ,{ id: "withdrawal_requests", name: "Seller Withdrawal Requests", attributes: [s("requestNumber", 48, true), s("vendorId", 36, true), s("sellerUserId", 36, true), i("amountMinor", true), s("currency", 3, true), s("status", 24, true), s("payoutAccount", 500, true), s("sellerNote", 1000), s("reviewNote", 1000), s("reviewedBy", 36), s("settlementId", 36), dt("requestedAt", true), dt("reviewedAt"), dt("paidAt")], indexes: [idx("withdrawal_number_unique", "unique", ["requestNumber"]), idx("withdrawal_vendor_idx", "key", ["vendorId"]), idx("withdrawal_status_idx", "key", ["status"]), idx("withdrawal_requested_idx", "key", ["requestedAt"])] }
  ,{ id: "wishlists", name: "Customer Wishlists", attributes: [s("userId", 36, true), s("productId", 36, true), dt("createdAt", true)], indexes: [idx("wishlist_user_product_unique", "unique", ["userId", "productId"]), idx("wishlist_user_idx", "key", ["userId"]), idx("wishlist_product_idx", "key", ["productId"])] }
  ,{ id: "product_reviews", name: "Verified Product Reviews", attributes: [s("userId", 36, true), s("productId", 36, true), s("orderItemId", 36, true), i("rating", true), s("title", 160, true), s("body", 2000, true), s("status", 24, true), dt("createdAt", true)], indexes: [idx("review_user_product_unique", "unique", ["userId", "productId"]), idx("review_product_idx", "key", ["productId"]), idx("review_status_idx", "key", ["status"])] }
  ,{ id: "disputes", name: "Customer Disputes", attributes: [s("disputeNumber", 44, true), s("orderId", 36, true), s("vendorOrderId", 36, true), s("customerUserId", 36, true), s("vendorId", 36, true), s("category", 60, true), s("description", 2000, true), s("status", 32, true), s("resolution", 2000), dt("createdAt", true), dt("updatedAt", true)], indexes: [idx("dispute_number_unique", "unique", ["disputeNumber"]), idx("dispute_customer_idx", "key", ["customerUserId"]), idx("dispute_vendor_idx", "key", ["vendorId"]), idx("dispute_status_idx", "key", ["status"]), idx("dispute_vendor_order_unique", "unique", ["vendorOrderId"])] }
  ,{ id: "dispute_events", name: "Dispute Timeline", attributes: [s("disputeId", 36, true), s("actorUserId", 36, true), s("eventType", 40, true), s("message", 2000), dt("occurredAt", true)], indexes: [idx("dispute_event_dispute_idx", "key", ["disputeId"])] }
  ,{ id: "coupons", name: "Marketplace Coupons", attributes: [s("code", 40, true), s("discountType", 20, true), i("value", true), i("minimumOrderMinor", true), i("maximumDiscountMinor"), i("maximumUses", true), i("uses", true), s("status", 24, true), dt("startsAt", true), dt("endsAt", true), dt("createdAt", true)], indexes: [idx("coupon_code_unique", "unique", ["code"]), idx("coupon_status_idx", "key", ["status"])] }
  ,{ id: "coupon_redemptions", name: "Coupon Redemptions", attributes: [s("couponId", 36, true), s("code", 40, true), s("userId", 36, true), s("orderId", 36, true), i("discountMinor", true), dt("redeemedAt", true)], indexes: [idx("coupon_user_unique", "unique", ["couponId", "userId"]), idx("coupon_order_unique", "unique", ["orderId"]), idx("coupon_redemption_user_idx", "key", ["userId"])] }
  ,{ id: "notifications", name: "In-App Notifications", attributes: [s("userId", 36, true), s("type", 40, true), s("title", 180, true), s("body", 1000, true), s("href", 500), dt("readAt"), dt("createdAt", true)], indexes: [idx("notification_user_idx", "key", ["userId"]), idx("notification_user_created_idx", "key", ["userId", "createdAt"])] }
  ,{ id: "conversations", name: "Order Conversations", attributes: [s("orderId", 36, true), s("vendorOrderId", 36, true), s("customerUserId", 36, true), s("vendorId", 36, true), s("status", 24, true), dt("updatedAt", true)], indexes: [idx("conversation_vendor_order_unique", "unique", ["vendorOrderId"]), idx("conversation_customer_idx", "key", ["customerUserId"]), idx("conversation_vendor_idx", "key", ["vendorId"])] }
  ,{ id: "messages", name: "Order Messages", attributes: [s("conversationId", 36, true), s("senderUserId", 36, true), s("senderRole", 20, true), s("body", 2000, true), dt("createdAt", true)], indexes: [idx("message_conversation_idx", "key", ["conversationId"]), idx("message_created_idx", "key", ["createdAt"])] }
  ,{ id: "business_buyers", name: "Wholesale Business Buyers", attributes: [s("userId", 36, true), s("organizationName", 180, true), s("registrationNumber", 100, true), s("countryCode", 2, true), s("buyerType", 60, true), s("status", 32, true), dt("createdAt", true), dt("reviewedAt"), s("reviewedBy", 36)], indexes: [idx("business_buyer_user_unique", "unique", ["userId"]), idx("business_buyer_status_idx", "key", ["status"])] }
  ,{ id: "offer_price_tiers", name: "Wholesale Price Tiers", attributes: [s("offerId", 36, true), s("vendorId", 36, true), i("minimumQuantity", true), i("maximumQuantity"), i("unitPriceMinor", true), s("currency", 3, true), dt("createdAt", true)], indexes: [idx("tier_offer_min_unique", "unique", ["offerId", "minimumQuantity"]), idx("tier_vendor_idx", "key", ["vendorId"]), idx("tier_offer_idx", "key", ["offerId"])] }
  ,{ id: "negotiation_settings", name: "Wholesale Negotiation Settings", attributes: [s("offerId", 36, true), s("vendorId", 36, true), s("enabled", 8, true), i("minimumQuantity", true), i("floorUnitPriceMinor"), i("maximumDiscountBasisPoints"), i("expiryHours", true), s("allowCounteroffers", 8, true), dt("updatedAt", true)], indexes: [idx("negotiation_setting_offer_unique", "unique", ["offerId"]), idx("negotiation_setting_vendor_idx", "key", ["vendorId"])] }
  ,{ id: "price_negotiations", name: "Wholesale Price Negotiations", attributes: [s("negotiationNumber", 48, true), s("buyerUserId", 36, true), s("businessBuyerId", 36, true), s("vendorId", 36, true), s("sellerUserId", 36, true), s("offerId", 36, true), s("productId", 36, true), s("productName", 240, true), i("regularUnitPriceMinor", true), i("currentUnitPriceMinor", true), i("quantity", true), i("deliveryChargeMinor"), s("currency", 3, true), s("deliveryCountryCode", 2, true), dt("requestedDeliveryAt"), s("status", 32, true), s("actionRequiredBy", 12), dt("expiresAt", true), dt("acceptedAt"), dt("usedAt"), s("orderId", 36), dt("createdAt", true), dt("updatedAt", true)], indexes: [idx("negotiation_number_unique", "unique", ["negotiationNumber"]), idx("negotiation_buyer_idx", "key", ["buyerUserId"]), idx("negotiation_vendor_idx", "key", ["vendorId"]), idx("negotiation_status_idx", "key", ["status"]), idx("negotiation_offer_idx", "key", ["offerId"])] }
  ,{ id: "negotiation_offers", name: "Wholesale Negotiation Offers", attributes: [s("negotiationId", 36, true), i("sequence", true), s("proposedBy", 12, true), s("actorUserId", 36, true), i("unitPriceMinor", true), i("quantity", true), i("deliveryChargeMinor"), s("currency", 3, true), s("message", 2000), dt("validUntil", true), dt("createdAt", true)], indexes: [idx("negotiation_offer_thread_idx", "key", ["negotiationId"]), idx("negotiation_offer_sequence_unique", "unique", ["negotiationId", "sequence"])] }
  ,{ id: "negotiation_events", name: "Wholesale Negotiation Events", attributes: [s("negotiationId", 36, true), s("actorUserId", 36, true), s("actorRole", 12, true), s("eventType", 40, true), s("message", 2000), dt("occurredAt", true)], indexes: [idx("negotiation_event_thread_idx", "key", ["negotiationId"]), idx("negotiation_event_time_idx", "key", ["occurredAt"])] }
  ,{ id: "purchase_orders", name: "Wholesale Purchase Orders", attributes: [s("purchaseOrderNumber", 44, true), s("buyerUserId", 36, true), s("businessBuyerId", 36, true), s("vendorId", 36, true), s("sourceType", 24), s("sourceId", 36), s("orderId", 36), s("status", 32, true), s("currency", 3, true), i("totalMinor", true), dt("createdAt", true), dt("submittedAt", true), dt("acceptedAt"), dt("convertedAt")], indexes: [idx("po_number_unique", "unique", ["purchaseOrderNumber"]), idx("po_buyer_idx", "key", ["buyerUserId"]), idx("po_vendor_idx", "key", ["vendorId"]), idx("po_status_idx", "key", ["status"]), idx("po_source_idx", "key", ["sourceType", "sourceId"]), idx("po_order_idx", "key", ["orderId"])] }
  ,{ id: "purchase_order_items", name: "Wholesale Purchase Order Items", attributes: [s("purchaseOrderId", 36, true), s("productId", 36, true), s("offerId", 36, true), s("productName", 240, true), i("quantity", true), i("unitPriceMinor", true), i("lineTotalMinor", true), s("currency", 3, true)], indexes: [idx("po_item_order_idx", "key", ["purchaseOrderId"]), idx("po_item_offer_idx", "key", ["offerId"])] }
  ,{ id: "proforma_invoices", name: "Wholesale Proforma Invoices", attributes: [s("invoiceNumber", 44, true), s("purchaseOrderId", 36, true), s("buyerUserId", 36, true), s("vendorId", 36, true), i("totalMinor", true), s("currency", 3, true), s("status", 24, true), dt("issuedAt", true), dt("expiresAt", true)], indexes: [idx("proforma_number_unique", "unique", ["invoiceNumber"]), idx("proforma_po_unique", "unique", ["purchaseOrderId"]), idx("proforma_buyer_idx", "key", ["buyerUserId"]), idx("proforma_vendor_idx", "key", ["vendorId"])] }
  ,{ id: "rfqs", name: "Procurement Requests for Quotation", attributes: [s("rfqNumber", 44, true), s("buyerUserId", 36, true), s("businessBuyerId", 36, true), s("title", 240, true), s("description", 5000, true), s("categoryId", 36, true), i("quantity", true), s("unit", 40, true), s("deliveryCountryCode", 2, true), s("currency", 3, true), s("status", 32, true), dt("quotationDeadline", true), dt("createdAt", true), dt("awardedAt")], indexes: [idx("rfq_number_unique", "unique", ["rfqNumber"]), idx("rfq_buyer_idx", "key", ["buyerUserId"]), idx("rfq_category_idx", "key", ["categoryId"]), idx("rfq_status_idx", "key", ["status"])] }
  ,{ id: "rfq_invitations", name: "RFQ Supplier Invitations", attributes: [s("rfqId", 36, true), s("vendorId", 36, true), s("status", 24, true), dt("invitedAt", true), dt("respondedAt")], indexes: [idx("rfq_invite_unique", "unique", ["rfqId", "vendorId"]), idx("rfq_invite_vendor_idx", "key", ["vendorId"]), idx("rfq_invite_rfq_idx", "key", ["rfqId"])] }
  ,{ id: "quotations", name: "Supplier Quotations", attributes: [s("quotationNumber", 44, true), s("rfqId", 36, true), s("vendorId", 36, true), s("buyerUserId", 36, true), i("quantity", true), i("unitPriceMinor", true), i("totalMinor", true), s("currency", 3, true), i("leadTimeDays", true), s("terms", 3000, true), s("status", 32, true), dt("submittedAt", true), dt("updatedAt", true)], indexes: [idx("quotation_number_unique", "unique", ["quotationNumber"]), idx("quotation_rfq_vendor_unique", "unique", ["rfqId", "vendorId"]), idx("quotation_rfq_idx", "key", ["rfqId"]), idx("quotation_vendor_idx", "key", ["vendorId"]), idx("quotation_buyer_idx", "key", ["buyerUserId"])] }
  ,{ id: "quotation_events", name: "Quotation Negotiation History", attributes: [s("quotationId", 36, true), s("actorUserId", 36, true), s("eventType", 40, true), s("message", 2000), dt("occurredAt", true)], indexes: [idx("quotation_event_quote_idx", "key", ["quotationId"])] }
  ,{ id: "warehouse_locations", name: "Warehouse Bin Locations", attributes: [s("warehouseId", 36, true), s("code", 60, true), s("locationType", 32, true), i("capacityUnits"), s("status", 24, true), dt("createdAt", true)], indexes: [idx("location_warehouse_code_unique", "unique", ["warehouseId", "code"]), idx("location_warehouse_idx", "key", ["warehouseId"])] }
  ,{ id: "warehouse_location_stocks", name: "Bin-Level Inventory", attributes: [s("warehouseId", 36, true), s("locationId", 36, true), s("vendorId", 36, true), s("offerId", 36, true), i("quantity", true), i("reserved", true), dt("updatedAt", true)], indexes: [idx("location_stock_unique", "unique", ["locationId", "offerId"]), idx("location_stock_warehouse_idx", "key", ["warehouseId"]), idx("location_stock_vendor_idx", "key", ["vendorId"]), idx("location_stock_offer_idx", "key", ["offerId"])] }
  ,{ id: "inbound_shipments", name: "Warehouse Inbound Shipments", attributes: [s("inboundNumber", 44, true), s("vendorId", 36, true), s("warehouseId", 36, true), s("reference", 120), s("status", 32, true), dt("expectedAt", true), dt("createdAt", true), dt("receivedAt")], indexes: [idx("inbound_number_unique", "unique", ["inboundNumber"]), idx("inbound_vendor_idx", "key", ["vendorId"]), idx("inbound_warehouse_idx", "key", ["warehouseId"]), idx("inbound_status_idx", "key", ["status"])] }
  ,{ id: "inbound_items", name: "Warehouse Inbound Items", attributes: [s("inboundShipmentId", 36, true), s("vendorId", 36, true), s("offerId", 36, true), i("expectedQuantity", true), i("receivedQuantity", true), i("putawayQuantity", true), s("status", 32, true)], indexes: [idx("inbound_item_shipment_idx", "key", ["inboundShipmentId"]), idx("inbound_item_offer_idx", "key", ["offerId"])] }
  ,{ id: "pick_tasks", name: "Warehouse Pick Tasks", attributes: [s("pickNumber", 44, true), s("vendorOrderId", 36, true), s("orderId", 36, true), s("vendorId", 36, true), s("warehouseId", 36, true), s("locationId", 36), s("offerId", 36, true), i("quantity", true), s("status", 24, true), s("assignedTo", 36), dt("createdAt", true), dt("pickedAt")], indexes: [idx("pick_number_unique", "unique", ["pickNumber"]), idx("pick_vendor_order_idx", "key", ["vendorOrderId"]), idx("pick_warehouse_idx", "key", ["warehouseId"]), idx("pick_status_idx", "key", ["status"])] }
  ,{ id: "fulfilment_packages", name: "Warehouse Fulfilment Packages", attributes: [s("packageNumber", 44, true), s("vendorOrderId", 36, true), s("orderId", 36, true), s("vendorId", 36, true), s("warehouseId", 36, true), i("itemCount", true), i("weightGrams"), s("status", 24, true), dt("packedAt", true), s("packedBy", 36, true)], indexes: [idx("package_number_unique", "unique", ["packageNumber"]), idx("package_vendor_order_unique", "unique", ["vendorOrderId"]), idx("package_warehouse_idx", "key", ["warehouseId"])] }
  ,{ id: "trade_passports", name: "Digital Trade Passports", attributes: [s("vendorId", 36, true), s("ownerUserId", 36, true), s("passportNumber", 44, true), s("exporterNumber", 100), { ...s("targetCountries", 2, true), array: true }, { ...s("productCategories", 120, true), array: true }, s("incoterms", 40, true), s("transportModes", 120, true), i("readinessScore", true), s("status", 32, true), dt("submittedAt", true), dt("reviewedAt"), s("reviewedBy", 36), s("reviewNotes", 2000)], indexes: [idx("trade_passport_vendor_unique", "unique", ["vendorId"]), idx("trade_passport_number_unique", "unique", ["passportNumber"]), idx("trade_passport_status_idx", "key", ["status"])] }
  ,{ id: "trade_certifications", name: "Trade Certifications and Inspections", attributes: [s("vendorId", 36, true), s("ownerUserId", 36, true), s("certificationType", 100, true), s("certificateNumber", 120, true), s("issuingAuthority", 180, true), s("countryCode", 2, true), dt("issuedAt", true), dt("expiresAt"), s("status", 32, true), dt("createdAt", true)], indexes: [idx("trade_cert_vendor_idx", "key", ["vendorId"]), idx("trade_cert_number_idx", "key", ["certificateNumber"]), idx("trade_cert_status_idx", "key", ["status"])] }
  ,{ id: "trade_documents", name: "Private Trade Documents", attributes: [s("vendorId", 36, true), s("ownerUserId", 36, true), s("documentType", 80, true), s("referenceNumber", 120), s("bucketId", 36, true), s("fileId", 36, true), s("filename", 255, true), s("mimeType", 100, true), i("sizeBytes", true), s("status", 32, true), dt("uploadedAt", true), dt("reviewedAt"), s("reviewedBy", 36)], indexes: [idx("trade_document_vendor_idx", "key", ["vendorId"]), idx("trade_document_file_unique", "unique", ["fileId"]), idx("trade_document_status_idx", "key", ["status"])] }
  ,{ id: "cross_border_shipments", name: "Cross-border Trade Shipments", attributes: [s("shipmentNumber", 44, true), s("vendorId", 36, true), s("orderId", 36), s("originCountryCode", 2, true), s("destinationCountryCode", 2, true), s("hsCodes", 500, true), s("incoterm", 10, true), s("customsReference", 120), s("customsStatus", 32, true), s("status", 32, true), dt("createdAt", true), dt("clearedAt")], indexes: [idx("trade_shipment_number_unique", "unique", ["shipmentNumber"]), idx("trade_shipment_vendor_idx", "key", ["vendorId"]), idx("trade_shipment_status_idx", "key", ["status"]), idx("trade_customs_status_idx", "key", ["customsStatus"])] }
  ,{ id: "trade_events", name: "Trade Compliance Audit Events", attributes: [s("vendorId", 36, true), s("entityType", 60, true), s("entityId", 36, true), s("eventType", 60, true), s("actorUserId", 36, true), s("notes", 2000), dt("occurredAt", true)], indexes: [idx("trade_event_vendor_idx", "key", ["vendorId"]), idx("trade_event_entity_idx", "key", ["entityType", "entityId"])] }
  ,{ id: "export_product_profiles", name: "Export Product Profiles", attributes: [s("vendorId",36,true),s("productId",36,true),s("categoryId",36,true),s("originCountry",2,true),s("targetCountries",2000,true),s("structuredAttributes",10000,true),s("status",32,true),dt("updatedAt",true)], indexes:[idx("export_profile_product_unique","unique",["productId"]),idx("export_profile_vendor_idx","key",["vendorId"]),idx("export_profile_status_idx","key",["status"])]}
  ,{ id: "product_hs_classifications", name: "Product HS Classifications", attributes: [s("vendorId",36,true),s("productId",36,true),s("hs6",6,true),s("nomenclatureVersion",20,true),i("confidencePercent",true),s("reasoning",3000,true),s("alternatives",1500),s("questions",1500),s("attributesUsed",3000),s("status",40,true),s("modelVersion",100),dt("classifiedAt",true),s("reviewedBy",36),dt("reviewedAt")], indexes:[idx("hs_product_idx","key",["productId"]),idx("hs_vendor_idx","key",["vendorId"]),idx("hs_code_idx","key",["hs6"]),idx("hs_status_idx","key",["status"])]}
  ,{ id: "regulatory_sources", name: "Regulatory Sources", attributes: [s("authority",180,true),s("jurisdiction",20,true),s("title",240,true),s("sourceUrl",1000,true),s("sourceLevel",20,true),dt("effectiveFrom",true),dt("effectiveTo"),dt("lastVerifiedAt",true),dt("nextReviewAt",true),s("version",80,true),s("status",24,true)], indexes:[idx("reg_source_jurisdiction_idx","key",["jurisdiction"]),idx("reg_source_status_idx","key",["status"])]}
  ,{ id: "regulatory_rules", name: "Versioned Regulatory Rules", attributes: [s("sourceId",36,true),s("ruleCode",100,true),s("title",240,true),s("originCountry",2),s("destinationCountry",2,true),s("hsPrefix",6),s("categoryId",36),s("requirementCode",100,true),s("requirementType",60,true),s("legalStatus",32,true),s("conditions",5000),s("guidance",3000,true),i("priority",true),s("version",80,true),dt("effectiveFrom",true),dt("effectiveTo"),s("status",24,true)], indexes:[idx("reg_rule_code_version_unique","unique",["ruleCode","version"]),idx("reg_rule_destination_idx","key",["destinationCountry"]),idx("reg_rule_requirement_idx","key",["requirementCode"]),idx("reg_rule_status_idx","key",["status"])]}
  ,{ id: "compliance_evidence", name: "Export Compliance Evidence", attributes: [s("vendorId",36,true),s("documentId",36,true),s("requirementCode",100,true),s("documentNumber",120),s("issuer",180,true),s("countryCode",2,true),dt("issuedAt"),dt("expiresAt"),s("productsCovered",5000,true),s("hsCodesCovered",2000),s("status",32,true),dt("createdAt",true),s("verifiedBy",36),dt("verifiedAt")], indexes:[idx("evidence_vendor_idx","key",["vendorId"]),idx("evidence_requirement_idx","key",["requirementCode"]),idx("evidence_status_idx","key",["status"])]}
  ,{ id: "compliance_assessments", name: "Destination Compliance Assessments", attributes: [s("vendorId",36,true),s("productId",36,true),s("classificationId",36,true),s("originCountry",2,true),s("destinationCountry",2,true),i("readinessScore",true),s("status",32,true),s("ruleVersions",5000,true),dt("assessedAt",true)], indexes:[idx("assessment_product_destination_idx","key",["productId","destinationCountry"]),idx("assessment_vendor_idx","key",["vendorId"]),idx("assessment_status_idx","key",["status"])]}
  ,{ id: "compliance_findings", name: "Compliance Assessment Findings", attributes: [s("assessmentId",36,true),s("ruleId",36,true),s("requirementCode",100,true),s("title",240,true),s("legalStatus",32,true),s("evidenceState",32,true),s("status",32,true)], indexes:[idx("finding_assessment_idx","key",["assessmentId"]),idx("finding_requirement_idx","key",["requirementCode"])]}
  ,{ id: "api_credentials", name: "Merchant API Credentials", attributes: [s("vendorId", 36, true), s("name", 120, true), s("keyPrefix", 24, true), s("keyHash", 128, true), { ...s("scopes", 80, true), array: true }, s("environment", 16, true), s("status", 24, true), i("rateLimitPerMinute", true), dt("createdAt", true), dt("lastUsedAt"), dt("revokedAt")], indexes: [idx("api_credential_prefix_unique", "unique", ["keyPrefix"]), idx("api_credential_vendor_idx", "key", ["vendorId"]), idx("api_credential_status_idx", "key", ["status"])] }
  ,{ id: "api_usage", name: "Merchant API Usage", attributes: [s("credentialId", 36, true), s("vendorId", 36, true), s("route", 240, true), s("method", 10, true), i("statusCode", true), dt("occurredAt", true)], indexes: [idx("api_usage_credential_idx", "key", ["credentialId"]), idx("api_usage_vendor_idx", "key", ["vendorId"]), idx("api_usage_time_idx", "key", ["occurredAt"])] }
  ,{ id: "webhook_endpoints", name: "Merchant Webhook Endpoints", attributes: [s("vendorId", 36, true), s("url", 1000, true), secret("signingSecret", 160), { ...s("events", 80, true), array: true }, s("status", 24, true), dt("createdAt", true), dt("updatedAt", true)], indexes: [idx("webhook_vendor_idx", "key", ["vendorId"]), idx("webhook_status_idx", "key", ["status"])] }
  ,{ id: "webhook_deliveries", name: "Webhook Delivery Log", attributes: [s("endpointId", 36, true), s("vendorId", 36, true), s("eventId", 36, true), s("eventType", 80, true), s("payload", 10000, true), i("attempt", true), s("status", 24, true), i("responseCode"), s("responseBody", 2000), dt("createdAt", true), dt("deliveredAt"), dt("nextAttemptAt")], indexes: [idx("webhook_delivery_endpoint_idx", "key", ["endpointId"]), idx("webhook_delivery_vendor_idx", "key", ["vendorId"]), idx("webhook_delivery_status_idx", "key", ["status"]), idx("webhook_event_idx", "key", ["eventId"])] }
  ,{ id: "enterprise_connectors", name: "ERP POS and Logistics Connectors", attributes: [s("vendorId", 36, true), s("connectorType", 40, true), s("provider", 80, true), s("displayName", 120, true), s("configuration", 5000, true), s("status", 24, true), dt("createdAt", true), dt("updatedAt", true)], indexes: [idx("connector_vendor_idx", "key", ["vendorId"]), idx("connector_type_idx", "key", ["connectorType"]), idx("connector_status_idx", "key", ["status"])] }
  ,{ id: "analytics_events", name: "Marketplace Analytics Events", attributes: [s("eventType", 80, true), s("actorUserId", 36), s("vendorId", 36), s("entityType", 60), s("entityId", 36), s("countryCode", 2), i("valueMinor"), s("currency", 3), s("properties", 5000), dt("occurredAt", true)], indexes: [idx("analytics_event_type_idx", "key", ["eventType"]), idx("analytics_event_vendor_idx", "key", ["vendorId"]), idx("analytics_event_time_idx", "key", ["occurredAt"])] }
  ,{ id: "fraud_signals", name: "Marketplace Fraud Signals", attributes: [s("signalType", 80, true), s("severity", 16, true), s("entityType", 60, true), s("entityId", 36, true), s("userId", 36), s("vendorId", 36), i("riskScore", true), s("reasons", 3000, true), s("status", 24, true), dt("detectedAt", true), dt("reviewedAt"), s("reviewedBy", 36)], indexes: [idx("fraud_severity_idx", "key", ["severity"]), idx("fraud_status_idx", "key", ["status"]), idx("fraud_entity_idx", "key", ["entityType", "entityId"]), idx("fraud_user_idx", "key", ["userId"])] }
  ,{ id: "demand_forecasts", name: "Product Demand Forecasts", attributes: [s("productId", 36, true), s("vendorId", 36, true), i("units30Days", true), i("forecastUnits30Days", true), i("confidencePercent", true), s("trend", 16, true), dt("generatedAt", true)], indexes: [idx("forecast_product_unique", "unique", ["productId", "vendorId"]), idx("forecast_vendor_idx", "key", ["vendorId"]), idx("forecast_generated_idx", "key", ["generatedAt"])] }
  ,{ id: "product_recommendations", name: "Product Recommendation Read Model", attributes: [s("productId", 36, true), s("recommendedProductId", 36, true), s("strategy", 40, true), i("score", true), dt("generatedAt", true)], indexes: [idx("recommendation_pair_unique", "unique", ["productId", "recommendedProductId", "strategy"]), idx("recommendation_product_idx", "key", ["productId"]), idx("recommendation_score_idx", "key", ["score"])] }
  ,{ id: "background_jobs", name: "Operational Background Jobs", attributes: [s("jobType", 80, true), s("status", 24, true), s("payload", 5000), i("attempts", true), i("maxAttempts", true), s("lastError", 2000), dt("createdAt", true), dt("startedAt"), dt("completedAt"), dt("nextAttemptAt")], indexes: [idx("job_status_idx", "key", ["status"]), idx("job_type_idx", "key", ["jobType"]), idx("job_next_attempt_idx", "key", ["nextAttemptAt"])] }
  ,{ id: "system_metrics", name: "System Operational Metrics", attributes: [s("metricName", 120, true), i("value", true), s("unit", 40, true), s("dimensions", 2000), dt("recordedAt", true)], indexes: [idx("metric_name_idx", "key", ["metricName"]), idx("metric_time_idx", "key", ["recordedAt"])] }
  ,{ id: "carrier_applications", name: "Carrier Applications", attributes: [s("ownerUserId", 36, true), s("legalName", 180, true), s("tradingName", 180), s("registrationNumber", 100, true), s("taxId", 100), s("countryCode", 2, true), s("contactEmail", 320, true), s("contactPhone", 40, true), s("transportModes", 200, true), { ...s("serviceCountries", 2, true), array: true }, s("fleetDescription", 2000, true), s("insurancePolicyNumber", 120, true), s("status", 32, true), dt("submittedAt", true), dt("reviewedAt"), s("reviewedBy", 36), s("reviewNotes", 2000)], indexes: [idx("carrier_application_owner_unique", "unique", ["ownerUserId"]), idx("carrier_application_status_idx", "key", ["status"]), idx("carrier_application_registration_idx", "key", ["registrationNumber"])] }
  ,{ id: "carrier_documents", name: "Private Carrier Documents", attributes: [s("applicationId", 36, true), s("ownerUserId", 36, true), s("documentType", 80, true), s("bucketId", 36, true), s("fileId", 36, true), s("filename", 255, true), s("mimeType", 100, true), i("sizeBytes", true), s("status", 24, true), dt("uploadedAt", true)], indexes: [idx("carrier_document_application_idx", "key", ["applicationId"]), idx("carrier_document_file_unique", "unique", ["fileId"])] }
  ,{ id: "carriers", name: "Verified Logistics Carriers", attributes: [s("applicationId", 36, true), s("ownerUserId", 36, true), s("carrierNumber", 44, true), s("legalName", 180, true), s("tradingName", 180), s("countryCode", 2, true), s("transportModes", 200, true), { ...s("serviceCountries", 2, true), array: true }, s("rating", 12, true), i("completedShipments", true), s("status", 24, true), dt("activatedAt", true)], indexes: [idx("carrier_application_unique", "unique", ["applicationId"]), idx("carrier_owner_unique", "unique", ["ownerUserId"]), idx("carrier_number_unique", "unique", ["carrierNumber"]), idx("carrier_status_idx", "key", ["status"])] }
  ,{ id: "carrier_rates", name: "Carrier Service Rates", attributes: [s("carrierId", 36, true), s("serviceName", 120, true), s("transportMode", 40, true), s("originCountryCode", 2, true), s("destinationCountryCode", 2, true), i("baseRateMinor", true), i("perKgRateMinor", true), s("currency", 3, true), i("estimatedDays", true), s("status", 24, true), dt("createdAt", true)], indexes: [idx("carrier_rate_carrier_idx", "key", ["carrierId"]), idx("carrier_rate_corridor_idx", "key", ["originCountryCode", "destinationCountryCode"]), idx("carrier_rate_status_idx", "key", ["status"])] }
  ,{ id: "shipment_assignments", name: "Carrier Shipment Assignments", attributes: [s("shipmentId", 36, true), s("carrierId", 36, true), s("assignmentNumber", 44, true), s("status", 32, true), i("agreedRateMinor", true), s("currency", 3, true), s("pickupAddress", 1000, true), s("deliveryAddress", 1000, true), dt("pickupAt"), dt("assignedAt", true), dt("acceptedAt"), dt("completedAt")], indexes: [idx("shipment_assignment_shipment_unique", "unique", ["shipmentId"]), idx("shipment_assignment_carrier_idx", "key", ["carrierId"]), idx("shipment_assignment_status_idx", "key", ["status"]), idx("shipment_assignment_number_unique", "unique", ["assignmentNumber"])] }
  ,{ id: "shipment_tracking_events", name: "Shipment Tracking Timeline", attributes: [s("shipmentId", 36, true), s("assignmentId", 36), s("status", 40, true), s("location", 240), s("message", 1000, true), s("actorUserId", 36, true), dt("occurredAt", true)], indexes: [idx("tracking_shipment_idx", "key", ["shipmentId"]), idx("tracking_assignment_idx", "key", ["assignmentId"]), idx("tracking_time_idx", "key", ["occurredAt"])] }
  ,{ id: "proofs_of_delivery", name: "Shipment Proofs of Delivery", attributes: [s("shipmentId", 36, true), s("assignmentId", 36, true), s("recipientName", 180, true), s("deliveryCode", 40), s("bucketId", 36), s("fileId", 36), s("notes", 1000), dt("deliveredAt", true), s("confirmedBy", 36, true)], indexes: [idx("pod_shipment_unique", "unique", ["shipmentId"]), idx("pod_assignment_unique", "unique", ["assignmentId"])] }
  ,{ id: "product_standards", name: "Product Standards Registry", attributes: [s("standardCode", 80, true), s("title", 240, true), s("categoryId", 36, true), s("countryCode", 2, true), s("authority", 180, true), s("summary", 3000, true), s("requirements", 10000, true), s("sourceUrl", 1000), s("status", 24, true), dt("effectiveAt", true), dt("updatedAt", true)], indexes: [idx("standard_code_country_unique", "unique", ["standardCode", "countryCode"]), idx("standard_category_idx", "key", ["categoryId"]), idx("standard_country_idx", "key", ["countryCode"]), idx("standard_status_idx", "key", ["status"])] }
  ,{ id: "packaging_requirements", name: "Packaging and Labelling Requirements", attributes: [s("title", 240, true), s("categoryId", 36, true), s("destinationCountryCode", 2, true), s("packagingType", 100, true), s("materials", 1000, true), s("labellingRules", 5000, true), s("handlingRules", 3000), i("maximumWeightGrams"), s("status", 24, true), dt("updatedAt", true)], indexes: [idx("packaging_category_idx", "key", ["categoryId"]), idx("packaging_country_idx", "key", ["destinationCountryCode"]), idx("packaging_status_idx", "key", ["status"])] }
  ,{ id: "certification_requirements", name: "Certification Requirements Registry", attributes: [s("certificationType", 120, true), s("title", 240, true), s("categoryId", 36, true), s("destinationCountryCode", 2, true), s("authority", 180, true), s("mandatory", 8, true), i("validityMonths"), s("guidance", 5000, true), s("applicationUrl", 1000), s("status", 24, true), dt("updatedAt", true)], indexes: [idx("cert_requirement_category_idx", "key", ["categoryId"]), idx("cert_requirement_country_idx", "key", ["destinationCountryCode"]), idx("cert_requirement_status_idx", "key", ["status"])] }
  ,{ id: "quality_centres", name: "Accredited Quality Centres", attributes: [s("name", 240, true), s("countryCode", 2, true), s("city", 120, true), s("address", 1000, true), { ...s("services", 160, true), array: true }, { ...s("accreditations", 160, true), array: true }, s("contactEmail", 320), s("contactPhone", 40), s("website", 1000), s("status", 24, true), dt("verifiedAt", true)], indexes: [idx("quality_centre_country_idx", "key", ["countryCode"]), idx("quality_centre_status_idx", "key", ["status"])] }
  ,{ id: "certification_applications", name: "Seller Certification Applications", attributes: [s("applicationNumber", 44, true), s("vendorId", 36, true), s("ownerUserId", 36, true), s("productId", 36, true), s("requirementId", 36, true), s("qualityCentreId", 36), s("notes", 3000), s("status", 32, true), dt("submittedAt", true), dt("reviewedAt"), s("reviewedBy", 36), s("reviewNotes", 2000)], indexes: [idx("cert_application_number_unique", "unique", ["applicationNumber"]), idx("cert_application_vendor_idx", "key", ["vendorId"]), idx("cert_application_product_idx", "key", ["productId"]), idx("cert_application_status_idx", "key", ["status"])] }
  ,{ id: "certification_application_events", name: "Certification Application Timeline", attributes: [s("applicationId", 36, true), s("eventType", 60, true), s("actorUserId", 36, true), s("notes", 2000), dt("occurredAt", true)], indexes: [idx("cert_event_application_idx", "key", ["applicationId"]), idx("cert_event_time_idx", "key", ["occurredAt"])] }
  ,{ id: "admin_members", name: "Platform Administrative Members", attributes: [s("userId", 36, true), s("email", 320, true), s("role", 36, true), s("status", 24, true), s("assignedBy", 36, true), dt("assignedAt", true), dt("revokedAt")], indexes: [idx("admin_member_user_role_unique", "unique", ["userId", "role"]), idx("admin_member_email_idx", "key", ["email"]), idx("admin_member_role_idx", "key", ["role"]), idx("admin_member_status_idx", "key", ["status"])] }
  ,{ id: "admin_notifications", name: "Administrative Operations Notifications", attributes: [s("recipientUserId",36,true),s("eventType",80,true),s("priority",16,true),s("title",180,true),s("body",1000,true),s("entityType",60,true),s("entityId",36,true),s("href",500,true),s("dedupeKey",180,true),s("status",16,true),dt("createdAt",true),dt("readAt"),dt("acknowledgedAt")], indexes:[idx("admin_notification_dedupe_unique","unique",["dedupeKey"]),idx("admin_notification_recipient_idx","key",["recipientUserId"]),idx("admin_notice_recipient_status_idx","key",["recipientUserId","status"]),idx("admin_notification_created_idx","key",["createdAt"])]}
  ,{ id: "admin_notification_preferences", name: "Administrative Notification Preferences", attributes:[s("userId",36,true),s("soundEnabled",8,true),dt("updatedAt",true)], indexes:[idx("admin_notification_pref_user_unique","unique",["userId"])]}
  ,{ id: "reconciliation_snapshots", name: "Daily Operations Reconciliation", attributes:[s("snapshotDate",10,true),s("status",24,true),s("metrics",10000,true),i("exceptionCount",true),s("generatedBy",36,true),dt("generatedAt",true)], indexes:[idx("reconciliation_date_unique","unique",["snapshotDate"]),idx("reconciliation_generated_idx","key",["generatedAt"])]}
  ,{ id: "reconciliation_exceptions", name: "Operations Reconciliation Exceptions", attributes:[s("snapshotId",36,true),s("ruleCode",80,true),s("severity",16,true),s("entityType",60,true),s("entityId",36,true),s("description",1000,true),s("assignedRole",36,true),s("status",24,true),dt("createdAt",true),dt("resolvedAt"),s("resolvedBy",36),s("resolution",2000)], indexes:[idx("reconciliation_exception_unique","unique",["snapshotId","ruleCode","entityId"]),idx("recon_exception_snapshot_idx","key",["snapshotId"]),idx("reconciliation_exception_status_idx","key",["status"]),idx("reconciliation_exception_role_idx","key",["assignedRole"])]}
  ,{ id:"academy_courses",name:"Academy Courses",attributes:[s("slug",120,true),s("title",240,true),s("version",24,true),s("description",3000,true),i("estimatedHours",true),i("passMark",true),s("status",24,true),dt("publishedAt"),dt("updatedAt",true)],indexes:[idx("academy_course_slug_version","unique",["slug","version"]),idx("academy_course_status_idx","key",["status"])]}
  ,{ id:"academy_modules",name:"Academy Modules",attributes:[s("courseId",36,true),s("moduleCode",16,true),s("title",240,true),i("sequence",true),i("durationMinutes",true),s("purpose",3000,true),s("status",24,true)],indexes:[idx("academy_module_course_code","unique",["courseId","moduleCode"]),idx("academy_module_course_seq","key",["courseId","sequence"])]}
  ,{ id:"academy_lessons",name:"Academy Lessons",attributes:[s("courseId",36,true),s("moduleId",36,true),s("lessonCode",24,true),s("title",240,true),s("summary",3000,true),s("activity",3000,true),i("sequence",true),s("status",24,true)],indexes:[idx("academy_lesson_module_code","unique",["moduleId","lessonCode"]),idx("academy_lesson_module_seq","key",["moduleId","sequence"])]}
  ,{ id:"academy_lesson_content",name:"Academy Long-form Lesson Content",attributes:[s("lessonId",36,true),s("courseVersion",24,true),s("contentJson",7000,true),s("status",24,true),dt("updatedAt",true)],indexes:[idx("academy_lesson_content_unique","unique",["lessonId","courseVersion"])]}
  ,{ id:"academy_enrollments",name:"Academy Enrollments",attributes:[s("userId",36,true),s("courseId",36,true),s("courseVersion",24,true),s("cohortId",36),s("status",32,true),i("progressPercent",true),dt("enrolledAt",true),dt("lastActivityAt",true),dt("completedAt")],indexes:[idx("academy_enrollment_unique","unique",["userId","courseId"]),idx("academy_enrollment_user_idx","key",["userId"]),idx("academy_enrollment_status_idx","key",["status"])]}
  ,{ id:"academy_lesson_progress",name:"Academy Lesson Progress",attributes:[s("enrollmentId",36,true),s("userId",36,true),s("moduleId",36,true),s("lessonId",36,true),s("status",24,true),dt("startedAt",true),dt("lastViewedAt",true),dt("completedAt")],indexes:[idx("academy_progress_unique","unique",["enrollmentId","lessonId"]),idx("academy_progress_enrollment_idx","key",["enrollmentId"]),idx("academy_progress_user_idx","key",["userId"])]}
  ,{ id:"academy_assessments",name:"Academy Assessments",attributes:[s("courseId",36,true),s("moduleId",36),s("title",240,true),s("assessmentType",32,true),i("passMark",true),i("timeLimitMinutes"),i("maxAttempts",true),s("status",24,true)],indexes:[idx("academy_assessment_course_idx","key",["courseId"]),idx("academy_assessment_module_idx","key",["moduleId"])]}
  ,{ id:"academy_questions",name:"Protected Academy Question Bank",attributes:[s("assessmentId",36,true),s("moduleId",36),s("questionType",32,true),s("prompt",3000,true),s("options",5000),secret("answerKey",1000),s("explanation",3000),i("marks",true),s("status",24,true)],indexes:[idx("academy_question_assessment_idx","key",["assessmentId"]),idx("academy_question_module_idx","key",["moduleId"])]}
  ,{ id:"academy_attempts",name:"Academy Assessment Attempts",attributes:[s("assessmentId",36,true),s("enrollmentId",36,true),s("userId",36,true),i("attemptNumber",true),s("status",24,true),i("scorePercent"),i("earnedMarks"),i("availableMarks"),dt("startedAt",true),dt("expiresAt"),dt("submittedAt"),dt("gradedAt"),s("gradedBy",36)],indexes:[idx("academy_attempt_enrollment_idx","key",["enrollmentId"]),idx("academy_attempt_user_idx","key",["userId"]),idx("academy_attempt_status_idx","key",["status"])]}
  ,{ id:"academy_responses",name:"Academy Assessment Responses",attributes:[s("attemptId",36,true),s("questionId",36,true),s("response",5000,true),s("status",24,true),i("awardedMarks"),s("feedback",3000)],indexes:[idx("academy_response_unique","unique",["attemptId","questionId"]),idx("academy_response_attempt_idx","key",["attemptId"])]}
  ,{ id:"academy_projects",name:"Academy Export Projects",attributes:[s("enrollmentId",36,true),s("userId",36,true),s("title",240,true),s("productName",240,true),s("originCountry",2,true),s("targetMarket",2),s("status",32,true),i("scorePercent"),dt("createdAt",true),dt("updatedAt",true),dt("submittedAt")],indexes:[idx("academy_project_enrollment_unique","unique",["enrollmentId"]),idx("academy_project_status_idx","key",["status"])]}
  ,{ id:"academy_project_milestones",name:"Academy Project Milestones",attributes:[s("projectId",36,true),s("milestoneCode",32,true),s("title",240,true),i("sequence",true),s("content",10000),s("status",24,true),s("feedback",5000),i("score"),dt("submittedAt"),dt("reviewedAt"),s("reviewedBy",36)],indexes:[idx("academy_milestone_unique","unique",["projectId","milestoneCode"]),idx("academy_milestone_status_idx","key",["status"])]}
  ,{ id:"academy_certificates",name:"Academy Certificates",attributes:[s("certificateNumber",64,true),s("enrollmentId",36,true),s("userId",36,true),s("courseId",36,true),s("courseVersion",24,true),s("learnerName",180,true),s("status",24,true),s("verificationCode",80,true),dt("issuedAt",true),dt("revokedAt")],indexes:[idx("academy_certificate_number_unique","unique",["certificateNumber"]),idx("academy_certificate_verify_unique","unique",["verificationCode"]),idx("academy_certificate_user_idx","key",["userId"])]}
  ,{ id:"academy_announcements",name:"Academy Announcements",attributes:[s("courseId",36,true),s("cohortId",36),s("title",240,true),s("body",5000,true),s("status",24,true),s("createdBy",36,true),dt("createdAt",true),dt("publishedAt")],indexes:[idx("academy_announcement_course_idx","key",["courseId"]),idx("academy_announcement_status_idx","key",["status"])]}
  ,{ id: "offtaker_applications", name: "Off-taker Applications", attributes: [s("ownerUserId",36,true),s("legalName",180,true),s("registrationNumber",100,true),s("taxId",100),s("countryCode",2,true),s("address",1000,true),s("industry",120,true),s("buyerType",80,true),s("contactName",180,true),s("contactEmail",320,true),s("contactPhone",40,true),s("productCategories",2000,true),s("expectedVolume",500,true),s("buyingFrequency",80,true),s("sourcingCountries",500),s("currency",3,true),s("deliveryLocations",2000,true),s("paymentTerms",2000,true),s("status",32,true),s("verificationLevel",32,true),dt("submittedAt",true),dt("reviewedAt"),s("reviewedBy",36),s("reviewNotes",2000)], indexes: [idx("offtaker_owner_unique","unique",["ownerUserId"]),idx("offtaker_status_idx","key",["status"]),idx("offtaker_registration_idx","key",["registrationNumber"])]}
  ,{ id: "offtaker_requirements", name: "Off-take Requirements", attributes: [s("offtakerId",36,true),s("ownerUserId",36,true),s("title",240,true),s("productName",240,true),s("specifications",5000,true),i("quantity",true),s("unit",40,true),s("frequency",80,true),i("targetPriceMinor"),s("currency",3,true),s("deliveryDestination",1000,true),s("packagingRequirements",3000),s("certificationRequirements",3000),s("originRestrictions",1000),dt("applicationDeadline",true),s("paymentTerms",2000,true),i("contractDurationMonths",true),s("status",32,true),dt("createdAt",true)], indexes:[idx("offtake_req_offtaker_idx","key",["offtakerId"]),idx("offtake_req_status_idx","key",["status"]),idx("offtake_req_deadline_idx","key",["applicationDeadline"])]}
  ,{ id: "offtake_proposals", name: "Off-take Supplier Proposals", attributes: [s("requirementId",36,true),s("vendorId",36,true),i("quantity",true),i("unitPriceMinor",true),s("currency",3,true),i("leadTimeDays",true),s("certifications",3000),s("terms",5000,true),s("status",32,true),dt("submittedAt",true)], indexes:[idx("offtake_proposal_unique","unique",["requirementId","vendorId"]),idx("offtake_proposal_req_idx","key",["requirementId"]),idx("offtake_proposal_vendor_idx","key",["vendorId"])]}
  ,{ id: "offtake_awards", name: "Off-take Multi-supplier Awards", attributes: [s("requirementId",36,true),s("proposalId",36,true),s("vendorId",36,true),i("quantity",true),i("amountMinor",true),s("currency",3,true),s("status",32,true),dt("awardedAt",true)], indexes:[idx("offtake_award_proposal_unique","unique",["proposalId"]),idx("offtake_award_req_idx","key",["requirementId"]),idx("offtake_award_vendor_idx","key",["vendorId"])]}
  ,{ id: "offtake_agreements", name: "Off-take Supply Agreements", attributes: [s("offtakerId",36,true),s("requirementId",36,true),s("agreementNumber",44,true),s("paymentModel",40,true),i("totalQuantity",true),i("totalMinor",true),s("currency",3,true),s("terms",10000,true),s("status",32,true),dt("startsAt",true),dt("endsAt",true),dt("createdAt",true)], indexes:[idx("offtake_agreement_number_unique","unique",["agreementNumber"]),idx("offtake_agreement_offtaker_idx","key",["offtakerId"]),idx("offtake_agreement_req_unique","unique",["requirementId"])]}
  ,{ id: "offtake_schedules", name: "Off-take Scheduled Purchase Orders", attributes: [s("scheduleNumber",44,true),s("agreementId",36,true),s("awardId",36,true),s("vendorId",36,true),i("quantity",true),dt("dueAt",true),s("destination",1000,true),s("status",32,true),dt("deliveredAt")], indexes:[idx("offtake_schedule_number_unique","unique",["scheduleNumber"]),idx("offtake_schedule_agreement_idx","key",["agreementId"]),idx("offtake_schedule_vendor_idx","key",["vendorId"]),idx("offtake_schedule_status_idx","key",["status"])]}
  ,{ id: "offtake_inspections", name: "Off-take Inspections", attributes: [s("scheduleId",36,true),s("result",32,true),i("acceptedQuantity",true),s("notes",3000,true),s("inspectedBy",36,true),dt("inspectedAt",true)], indexes:[idx("offtake_inspection_schedule_unique","unique",["scheduleId"]),idx("offtake_inspection_result_idx","key",["result"])]}
  ,{ id: "offtake_payment_milestones", name: "Off-take Payment Milestones", attributes: [s("agreementId",36,true),s("scheduleId",36),s("milestoneType",40,true),i("amountMinor",true),s("currency",3,true),s("status",32,true),dt("dueAt",true),dt("paidAt")], indexes:[idx("offtake_payment_agreement_idx","key",["agreementId"]),idx("offtake_payment_status_idx","key",["status"])]}
  ,{ id: "offtake_disputes", name: "Off-take Disputes", attributes: [s("agreementId",36,true),s("scheduleId",36),s("raisedByUserId",36,true),s("category",80,true),s("description",3000,true),s("status",32,true),s("resolution",3000),dt("createdAt",true),dt("updatedAt",true)], indexes:[idx("offtake_dispute_agreement_idx","key",["agreementId"]),idx("offtake_dispute_status_idx","key",["status"])]}
];

try {
  await databases.get({ databaseId });
  process.stdout.write(`verified ${databaseId}\n`);
} catch (error) {
  if (typeof error !== "object" || error === null || !("code" in error) || error.code !== 404) throw error;
  await databases.create({ databaseId, name: "PAC-SM Core", enabled: true });
  process.stdout.write(`created ${databaseId}\n`);
}

const collectionPrefix = process.env.APPWRITE_COLLECTION_PREFIX?.trim();
for (const collection of collections.filter((item) => !collectionPrefix || item.id.startsWith(collectionPrefix))) {
  let live;
  try {
    live = await databases.getCollection({ databaseId, collectionId: collection.id });
    process.stdout.write(`verified ${collection.id}\n`);
  } catch (error) {
    if (typeof error !== "object" || error === null || !("code" in error) || error.code !== 404) throw error;
    live = await databases.createCollection({ databaseId, collectionId: collection.id, name: collection.name, permissions: [], documentSecurity: false, enabled: true });
    process.stdout.write(`created ${collection.id}\n`);
  }
  const existingAttributes = new Set(live.attributes.map((attribute) => attribute.key));
  for (const attribute of collection.attributes.filter((item) => !existingAttributes.has(item.key))) {
    const common = { databaseId, collectionId: collection.id, key: attribute.key, required: attribute.required ?? false, array: attribute.array ?? false };
    if (attribute.type === "string") await databases.createStringAttribute({ ...common, size: attribute.size!, encrypt: attribute.encrypt ?? false });
    else if (attribute.type === "integer") await databases.createIntegerAttribute(common);
    else await databases.createDatetimeAttribute(common);
    for (let attempt = 0; attempt < 30; attempt++) {
      await new Promise((resolve) => setTimeout(resolve, 500));
      const current = await databases.getAttribute({ databaseId, collectionId: collection.id, key: attribute.key }) as { status?: string };
      if (current.status === "available") break;
      if (current.status === "failed") throw new Error(`Attribute ${collection.id}.${attribute.key} failed`);
    }
    process.stdout.write(`created ${collection.id}.${attribute.key}\n`);
  }
  const refreshed = await databases.getCollection({ databaseId, collectionId: collection.id });
  const existingIndexes = new Set(refreshed.indexes.map((index) => index.key));
  for (const index of collection.indexes.filter((item) => !existingIndexes.has(item.key))) {
    await databases.createIndex({ databaseId, collectionId: collection.id, key: index.key, type: index.type === "unique" ? IndexType.Unique : IndexType.Key, attributes: index.attributes });
    process.stdout.write(`created ${collection.id}.${index.key}\n`);
  }
}

if(!collectionPrefix||collectionPrefix.startsWith("academy_")){
  const updatedAt=new Date().toISOString();
  await databases.upsertDocument({databaseId,collectionId:"academy_courses",documentId:ACADEMY_COURSE.id,permissions:[],data:{slug:ACADEMY_COURSE.slug,title:ACADEMY_COURSE.title,version:ACADEMY_COURSE.version,description:"A practical continental trade programme that moves learners from export fundamentals through market entry, compliance, logistics, finance and buyer acquisition.",estimatedHours:ACADEMY_COURSE.estimatedHours,passMark:ACADEMY_COURSE.passMark,status:"published",publishedAt:updatedAt,updatedAt}});
  for(const module of ACADEMY_MODULES){await databases.upsertDocument({databaseId,collectionId:"academy_modules",documentId:module.id,permissions:[],data:{courseId:ACADEMY_COURSE.id,moduleCode:module.id,title:module.title,sequence:module.number,durationMinutes:module.durationHours*60,purpose:module.purpose,status:"published"}});for(const [index,lesson] of module.lessons.entries()){const content=findAcademyLessonContent(lesson.id);if(!content)throw new Error(`Missing Academy reading for ${lesson.id}`);await databases.upsertDocument({databaseId,collectionId:"academy_lessons",documentId:lesson.id,permissions:[],data:{courseId:ACADEMY_COURSE.id,moduleId:module.id,lessonCode:lesson.id,title:lesson.title,summary:lesson.summary,activity:lesson.activity,sequence:index+1,status:"published"}});await databases.upsertDocument({databaseId,collectionId:"academy_lesson_content",documentId:`${lesson.id}-v1`,permissions:[],data:{lessonId:lesson.id,courseVersion:ACADEMY_COURSE.version,contentJson:JSON.stringify(content),status:"published",updatedAt}})}}
  for(const module of ACADEMY_MODULES){const id=`assessment-${module.id}`;await databases.upsertDocument({databaseId,collectionId:"academy_assessments",documentId:id,permissions:[],data:{courseId:ACADEMY_COURSE.id,moduleId:module.id,title:`Module ${module.number}: ${module.title}`,assessmentType:"module_mcq",passMark:ACADEMY_COURSE.passMark,timeLimitMinutes:30,maxAttempts:3,status:"published"}})}
  process.stdout.write("seeded PAC-SM Trade & Export Academy curriculum v1.0\n");
}

const buckets = [
  {
    bucketId: required("APPWRITE_PRODUCT_MEDIA_BUCKET_ID"),
    name: "PAC-SM Product Media",
    permissions: [],
    fileSecurity: true,
    enabled: true,
    maximumFileSize: 10 * 1024 * 1024,
    allowedFileExtensions: ["jpg", "jpeg", "png", "webp"],
    compression: Compression.None,
    encryption: true,
    antivirus: true,
    transformations: true
  },
  {
    bucketId: required("APPWRITE_KYC_BUCKET_ID"),
    name: "PAC-SM Private KYC",
    permissions: [],
    fileSecurity: true,
    enabled: true,
    maximumFileSize: 20 * 1024 * 1024,
    allowedFileExtensions: ["pdf", "jpg", "jpeg", "png"],
    compression: Compression.None,
    encryption: true,
    antivirus: true,
    transformations: false
  }
];

for (const bucket of buckets) {
  try {
    await storage.getBucket({ bucketId: bucket.bucketId });
    process.stdout.write(`verified ${bucket.bucketId}\n`);
  } catch (error) {
    if (typeof error !== "object" || error === null || !("code" in error) || error.code !== 404) throw error;
    await storage.createBucket(bucket);
    process.stdout.write(`created ${bucket.bucketId}\n`);
  }
}

for (const category of [
  { id: "agriculture", name: "Agriculture & Food" }, { id: "electronics", name: "Electronics" },
  { id: "fashion", name: "Fashion & Textiles" }, { id: "home", name: "Home & Living" },
  { id: "industrial", name: "Industrial Supplies" }, { id: "health", name: "Health & Beauty" }
]) {
  await databases.upsertDocument({ databaseId, collectionId: "categories", documentId: category.id, permissions: [], data: { name: category.name, slug: category.id, status: "active" } });
}
process.stdout.write("seeded baseline categories\n");

await databases.upsertDocument({ databaseId, collectionId: "warehouses", documentId: "pacsm-lagos-fc", permissions: [], data: { vendorId: "pacsm-platform", name: "PAC-SM Lagos Fulfilment Centre", countryCode: "NG", address: "Lagos Commerce and Logistics District", warehouseType: "platform_fulfilment", status: "active" } });
for (const code of ["RECEIVING-01", "A-01-01", "A-01-02", "B-01-01", "PACKING-01"]) await databases.upsertDocument({ databaseId, collectionId: "warehouse_locations", documentId: `lagos-${code.toLowerCase()}`, permissions: [], data: { warehouseId: "pacsm-lagos-fc", code, locationType: code.startsWith("RECEIVING") ? "receiving" : code.startsWith("PACKING") ? "packing" : "storage", capacityUnits: 10000, status: "active", createdAt: new Date().toISOString() } });
process.stdout.write("seeded PAC-SM fulfilment centre locations\n");

const commissionRules = await databases.listDocuments({ databaseId, collectionId: "commission_rules", queries: [] });
if (!commissionRules.total) {
  const now = new Date().toISOString();
  await databases.createDocument({ databaseId, collectionId: "commission_rules", documentId: "default-marketplace", permissions: [], data: { name: "Default marketplace commission", rateBasisPoints: 1000, status: "active", effectiveFrom: now, createdAt: now } });
  process.stdout.write("seeded default commission rule\n");
}
