import "server-only";
import { ID, Query } from "node-appwrite";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
import { calculateDiscount } from "@/src/modules/promotions/domain/discount";
const databaseId = () => env().APPWRITE_DATABASE_ID;
const db = () => createAppwriteDatabaseClient().databases;
export const listCoupons = () => db().listDocuments({ databaseId: databaseId(), collectionId: "coupons", queries: [Query.orderDesc("createdAt"), Query.limit(100)] });
export async function createCoupon(input: { code: string; discountType: "percentage" | "fixed"; value: number; minimumOrderMinor: number; maximumDiscountMinor?: number; maximumUses: number; startsAt: string; endsAt: string }) { if (!/^[A-Z0-9_-]{3,40}$/.test(input.code) || input.value < 1 || input.maximumUses < 1 || new Date(input.endsAt) <= new Date(input.startsAt)) throw new Error("Invalid coupon"); await db().createDocument({ databaseId: databaseId(), collectionId: "coupons", documentId: ID.unique(), permissions: [], data: { ...input, code: input.code.toUpperCase(), uses: 0, status: "active", createdAt: new Date().toISOString() } }); }
export async function validateCoupon(databases: ReturnType<typeof db>, transactionId: string, userId: string, code: string, subtotalMinor: number) { if (!code.trim()) return null; const normalized = code.trim().toUpperCase(), now = new Date(); const result = await databases.listDocuments({ databaseId: databaseId(), collectionId: "coupons", queries: [Query.equal("code", normalized), Query.equal("status", "active"), Query.limit(1)], transactionId }), coupon = result.documents[0]; if (!coupon || new Date(String(coupon.startsAt)) > now || new Date(String(coupon.endsAt)) < now || Number(coupon.uses) >= Number(coupon.maximumUses) || subtotalMinor < Number(coupon.minimumOrderMinor)) throw new Error("Coupon is not valid"); const used = await databases.listDocuments({ databaseId: databaseId(), collectionId: "coupon_redemptions", queries: [Query.equal("couponId", coupon.$id), Query.equal("userId", userId), Query.limit(1)], transactionId }); if (used.documents.length) throw new Error("Coupon already used"); const discountMinor = calculateDiscount({ subtotalMinor, discountType: String(coupon.discountType) as "percentage" | "fixed", value: Number(coupon.value), maximumDiscountMinor: coupon.maximumDiscountMinor ? Number(coupon.maximumDiscountMinor) : undefined }); return { coupon, discountMinor }; }
