import Link from "next/link";
import { redirect } from "next/navigation";
import { Query } from "node-appwrite";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { findVendorByOwner } from "@/src/modules/vendors/server/repository";
import { listVendorPurchaseOrders } from "@/src/modules/wholesale/server/repository";
import { getNegotiationSettings, listVendorNegotiations } from "@/src/modules/wholesale/server/negotiations";
import { createAppwriteDatabaseClient } from "@/src/integrations/appwrite/server";
import { env } from "@/src/shared/config/env";
export const dynamic = "force-dynamic";
const money = (v: number, c: string) => new Intl.NumberFormat("en-NG", { style: "currency", currency: c }).format(v / 100);
export default async function SellerWholesale() {
  const user = await getCurrentAppwriteUser(); if (!user) redirect("/login?returnTo=/seller/wholesale");
  const vendor = await findVendorByOwner(user.$id); if (!vendor) redirect("/vendor/register");
  const database = createAppwriteDatabaseClient().databases, databaseId = env().APPWRITE_DATABASE_ID;
  const [offers, orders, negotiations] = await Promise.all([database.listDocuments({ databaseId, collectionId: "seller_offers", queries: [Query.equal("vendorId", vendor.$id), Query.greaterThan("minimumOrderQuantity", 1), Query.limit(100)] }), listVendorPurchaseOrders(vendor.$id), listVendorNegotiations(vendor.$id)]);
  const settings = await Promise.all(offers.documents.map(offer => getNegotiationSettings(offer.$id)));
  return <main className="seller-shell"><nav><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><Link href="/seller">Seller Centre</Link></nav><header><div><p className="kicker">WHOLESALE OPERATIONS</p><h1>Pricing, negotiation and purchase orders</h1></div></header>
    <section className="cart-vendor"><h2>Negotiation controls by offer</h2>{offers.documents.map((offer, index) => <details key={offer.$id}><summary>{String(offer.sellerSku)} · MOQ {String(offer.minimumOrderQuantity)} · {money(Number(offer.wholesalePriceMinor ?? offer.retailPriceMinor), String(offer.currency))}</summary><form className="stack-form" action="/api/seller/wholesale/negotiation-settings" method="post"><input type="hidden" name="offerId" value={offer.$id}/><label>Negotiation<select name="enabled" defaultValue={String(settings[index]?.enabled ?? "true")}><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label>Minimum negotiable quantity<input name="minimumQuantity" type="number" min={Number(offer.minimumOrderQuantity)} defaultValue={Number(settings[index]?.minimumQuantity ?? offer.minimumOrderQuantity)} required/></label><label>Confidential floor unit price<input name="floorUnitPrice" type="number" min="0.01" step="0.01" defaultValue={settings[index]?.floorUnitPriceMinor ? Number(settings[index].floorUnitPriceMinor) / 100 : undefined}/></label><label>Maximum discount percent<input name="maximumDiscountPercent" type="number" min="0" max="99" step="0.01" defaultValue={settings[index]?.maximumDiscountBasisPoints ? Number(settings[index].maximumDiscountBasisPoints) / 100 : undefined}/></label><label>Offer expiry hours<input name="expiryHours" type="number" min="1" max="168" defaultValue={Number(settings[index]?.expiryHours ?? 48)} required/></label><label>Counteroffers<select name="allowCounteroffers" defaultValue={String(settings[index]?.allowCounteroffers ?? "true")}><option value="true">Allowed</option><option value="false">Disabled</option></select></label><button>Save negotiation controls</button></form></details>)}</section>
    <section className="review-table"><h2>Price negotiation inbox</h2><div className="review-row review-head"><span>Reference</span><span>Product</span><span>Status</span><span>Action</span></div>{negotiations.documents.map(n => <div className="review-row" key={n.$id}><span>{String(n.negotiationNumber)}</span><strong>{String(n.productName)}</strong><span>{String(n.status).replaceAll("_", " ")}</span><Link href={`/seller/wholesale/negotiations/${n.$id}`}>Review →</Link></div>)}</section>
    <section className="review-table"><h2>Price tiers</h2>{offers.documents.map(o => <div className="review-row" key={o.$id}><span>{String(o.sellerSku)}</span><span>MOQ {String(o.minimumOrderQuantity)}</span><form action="/api/seller/wholesale/tiers" method="post"><input type="hidden" name="offerId" value={o.$id}/><input name="minimumQuantity" type="number" min={Number(o.minimumOrderQuantity)} placeholder="Min qty" required/><input name="unitPrice" type="number" min="1" placeholder="Unit price" required/><button>Add tier</button></form><span>{money(Number(o.wholesalePriceMinor ?? o.retailPriceMinor), String(o.currency))}</span></div>)}</section>
    <section className="review-table"><h2>Purchase orders</h2>{orders.documents.map(po => <div className="review-row" key={po.$id}><span>{String(po.purchaseOrderNumber)}</span><strong>{String(po.status)}</strong><span>{money(Number(po.totalMinor), String(po.currency))}</span>{po.status === "submitted" ? <form action={`/api/seller/wholesale/purchase-orders/${po.$id}/accept`} method="post"><button>Accept & issue proforma</button></form> : <span/>}</div>)}</section>
  </main>;
}
