import { z } from "zod";
import type { ConnectionResult, SupplierCategory, SupplierConnector, SupplierCredentials, SupplierProductDetail, SupplierProductSearch, SupplierWarehouseStock } from "../../domain/connector";

const CJ_BASE_URL = "https://developers.cjdropshipping.com/api2.0/v1";
const tokenResponse = z.object({ code: z.number(), result: z.boolean(), message: z.string(), requestId: z.string().optional(), data: z.object({ openId: z.union([z.string(), z.number()]).optional(), accessToken: z.string().min(1), accessTokenExpiryDate: z.string().min(1), refreshToken: z.string().min(1), refreshTokenExpiryDate: z.string().min(1) }).nullable() });
async function post(path: string, body: unknown) { const response = await fetch(`${CJ_BASE_URL}${path}`, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(body), signal: AbortSignal.timeout(15_000), cache: "no-store" }); if (!response.ok) throw new Error(`CJ connection returned HTTP ${response.status}`); return tokenResponse.parse(await response.json()); }
type JsonRecord = Record<string, unknown>;
const record = (value: unknown): JsonRecord => value && typeof value === "object" && !Array.isArray(value) ? value as JsonRecord : {};
const textValue = (...values: unknown[]) => String(values.find(value => typeof value === "string" && value.trim()) ?? "");
const imageUrl = (value: unknown) => { try { const url=new URL(String(value??"")); return url.protocol==="https:"&&(/(^|\.)cjdropshipping\.com$/i.test(url.hostname)||/(^|\.)cjdropshipping\.cn$/i.test(url.hostname))?url.toString():""; } catch { return ""; } };
const numberValue = (...values: unknown[]) => { const value = Number(values.find(item => item !== undefined && item !== null && item !== "")); return Number.isFinite(value) ? value : undefined; };
const moneyMinor = (value: unknown) => { const first = String(value ?? "").split("-")[0], amount = Number(first); return Number.isFinite(amount) ? Math.round(amount * 100) : undefined; };
async function cjGet(credentials: SupplierCredentials, path: string, params: Record<string,string|number|undefined> = {}) { if (!credentials.accessToken) throw new Error("CJ access token is unavailable"); const url = new URL(`${CJ_BASE_URL}${path}`); for (const [key,value] of Object.entries(params)) if (value !== undefined && value !== "") url.searchParams.set(key,String(value)); const response = await fetch(url,{headers:{Accept:"application/json","CJ-Access-Token":credentials.accessToken},signal:AbortSignal.timeout(20_000),cache:"no-store"}); if(!response.ok)throw new Error(`CJ catalogue returned HTTP ${response.status}`); const payload=record(await response.json()); if(payload.result===false||Number(payload.code)!==200)throw new Error(`CJ catalogue request failed${payload.requestId?` (${payload.requestId})`:""}`); return payload.data; }
function flattenCategories(data: unknown): SupplierCategory[] { const output: SupplierCategory[]=[]; for(const firstValue of Array.isArray(data)?data:[]){const first=record(firstValue),firstName=textValue(first.categoryFirstName,first.name); for(const secondValue of Array.isArray(first.categoryFirstList)?first.categoryFirstList:[]){const second=record(secondValue),secondName=textValue(second.categorySecondName,second.name); for(const thirdValue of Array.isArray(second.categorySecondList)?second.categorySecondList:[]){const third=record(thirdValue),id=textValue(third.categoryId,third.id),name=textValue(third.categoryName,third.name); if(id&&name)output.push({id,name,path:[firstName,secondName,name].filter(Boolean).join(" › "),level:3});}}} return output; }
function normalizeStock(data: unknown): SupplierWarehouseStock[]{return (Array.isArray(data)?data:[]).map(value=>{const item=record(value);return{warehouseId:textValue(item.areaId,item.id,item.countryCode)||"unknown",warehouseName:textValue(item.areaEn,item.name,item.countryCode)||"CJ warehouse",countryCode:textValue(item.countryCode)||"--",available:numberValue(item.totalInventoryNum,item.storageNum,item.cjInventoryNum,item.inventory)??0,...(numberValue(item.cjInventoryNum)!==undefined?{cjInventory:numberValue(item.cjInventoryNum)}:{}),...(numberValue(item.factoryInventoryNum)!==undefined?{factoryInventory:numberValue(item.factoryInventoryNum)}:{})}});}
const success = (data: z.infer<typeof tokenResponse>, credentials: SupplierCredentials): { result: ConnectionResult; credentials: SupplierCredentials } => { if (!data.result || !data.data) throw new Error(`CJ rejected the connection${data.requestId ? ` (${data.requestId})` : ""}`); const openId = data.data.openId === undefined ? credentials.openId : String(data.data.openId); if (!openId) throw new Error("CJ authentication did not return an account identifier"); const next = { ...credentials, openId, accessToken: data.data.accessToken, refreshToken: data.data.refreshToken, accessTokenExpiresAt: new Date(data.data.accessTokenExpiryDate).toISOString(), refreshTokenExpiresAt: new Date(data.data.refreshTokenExpiryDate).toISOString() }; return { credentials: next, result: { ok: true, provider: "cj", externalAccountId: next.openId, tokenExpiresAt: next.accessTokenExpiresAt, message: "CJ API 2.0 connection verified", ...(data.requestId ? { requestId: data.requestId } : {}) } }; };

export class CJConnector implements SupplierConnector {
  readonly provider = "cj";
  readonly supportedFulfilmentTypes = ["global_direct", "global_wholesale", "global_sourcing"] as const;
  async authenticate(credentials: SupplierCredentials) { if (!credentials.apiKey.trim()) throw new Error("CJ API key is required"); return success(await post("/authentication/getAccessToken", { apiKey: credentials.apiKey.trim() }), credentials); }
  async testConnection(credentials: SupplierCredentials) { const expiry = credentials.accessTokenExpiresAt ? Date.parse(credentials.accessTokenExpiresAt) : 0; if (credentials.accessToken && expiry > Date.now() + 300_000) return { credentials, result: { ok: true, provider: "cj", externalAccountId: credentials.openId, tokenExpiresAt: credentials.accessTokenExpiresAt, message: "Stored CJ access token is valid" } }; if (credentials.refreshToken && (!credentials.refreshTokenExpiresAt || Date.parse(credentials.refreshTokenExpiresAt) > Date.now())) return success(await post("/authentication/refreshAccessToken", { refreshToken: credentials.refreshToken }), credentials); return this.authenticate(credentials); }
  async listCategories(credentials: SupplierCredentials){return flattenCategories(await cjGet(credentials,"/product/getCategory"));}
  async searchProducts(credentials: SupplierCredentials,input:{keyword?:string;categoryId?:string;countryCode?:string;page:number;pageSize:number}):Promise<SupplierProductSearch>{const data=record(await cjGet(credentials,"/product/listV2",{page:input.page,size:input.pageSize,keyWord:input.keyword,categoryId:input.categoryId,countryCode:input.countryCode})),content=Array.isArray(data.content)?data.content:[],raw=content.flatMap(value=>{const item=record(value);return Array.isArray(item.productList)?item.productList:[item]});return{products:raw.map(value=>{const item=record(value);return{externalProductId:textValue(item.id,item.pid),title:textValue(item.nameEn,item.productNameEn,item.nameen)||"Untitled CJ product",sku:textValue(item.sku,item.spu,item.productSku),imageUrl:imageUrl(item.bigImage??item.bigimg??item.productImage),currency:"USD",minimumCostMinor:moneyMinor(item.sellPrice??item.sellprice??item.nowPrice),categoryName:textValue(item.categoryName,item.categoryname),countryCode:textValue(item.countryCode),inventory:numberValue(item.totalInventory,item.inventory)}}).filter(item=>item.externalProductId),total:numberValue(data.totalRecords,data.total)??raw.length,page:input.page,pageSize:input.pageSize};}
  async getProduct(credentials:SupplierCredentials,externalProductId:string):Promise<SupplierProductDetail>{const raw=record(await cjGet(credentials,"/product/query",{pid:externalProductId,features:"enable_video"})),item=record(raw.product??raw),variantsRaw=Array.isArray(item.variants)?item.variants:Array.isArray(item.variantList)?item.variantList:[],variants=variantsRaw.map(value=>{const variant=record(value);return{id:textValue(variant.vid,variant.id),sku:textValue(variant.variantSku,variant.sku),name:textValue(variant.variantNameEn,variant.variantKey,variant.variantName)||"Default",imageUrl:imageUrl(variant.variantImage),costMinor:moneyMinor(variant.variantSellPrice??variant.variantPrice),weightGrams:numberValue(variant.variantWeight),lengthMm:numberValue(variant.variantLength),widthMm:numberValue(variant.variantWidth),heightMm:numberValue(variant.variantHeight),stock:[] as SupplierWarehouseStock[]}});for(const variant of variants.slice(0,10))if(variant.id)try{variant.stock=normalizeStock(await cjGet(credentials,"/product/stock/queryByVid",{vid:variant.id}));}catch{/* Keep the variant visible if granular stock is rate-limited or unavailable. */}const images=[imageUrl(item.bigImage),...(Array.isArray(item.productImageSet)?item.productImageSet.map(imageUrl):[])].filter((value,index,array)=>value&&array.indexOf(value)===index);return{externalProductId:textValue(item.pid,item.id)||externalProductId,title:textValue(item.productNameEn,item.nameEn)||"Untitled CJ product",sku:textValue(item.productSku,item.sku),description:textValue(item.description),categoryId:textValue(item.categoryId),categoryName:textValue(item.categoryName),imageUrl:images[0],images,currency:"USD",minimumCostMinor:moneyMinor(item.sellPrice),weightGrams:numberValue(item.productWeight),unit:textValue(item.productUnit),variants};}
}
