import { z } from "zod";
import type { ConnectionResult, SupplierConnector, SupplierCredentials } from "../../domain/connector";

const CJ_BASE_URL = "https://developers.cjdropshipping.com/api2.0/v1";
const tokenResponse = z.object({ code: z.number(), result: z.boolean(), message: z.string(), requestId: z.string().optional(), data: z.object({ openId: z.union([z.string(), z.number()]).optional(), accessToken: z.string().min(1), accessTokenExpiryDate: z.string().min(1), refreshToken: z.string().min(1), refreshTokenExpiryDate: z.string().min(1) }).nullable() });
async function post(path: string, body: unknown) { const response = await fetch(`${CJ_BASE_URL}${path}`, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(body), signal: AbortSignal.timeout(15_000), cache: "no-store" }); if (!response.ok) throw new Error(`CJ connection returned HTTP ${response.status}`); return tokenResponse.parse(await response.json()); }
const success = (data: z.infer<typeof tokenResponse>, credentials: SupplierCredentials): { result: ConnectionResult; credentials: SupplierCredentials } => { if (!data.result || !data.data) throw new Error(`CJ rejected the connection${data.requestId ? ` (${data.requestId})` : ""}`); const openId = data.data.openId === undefined ? credentials.openId : String(data.data.openId); if (!openId) throw new Error("CJ authentication did not return an account identifier"); const next = { ...credentials, openId, accessToken: data.data.accessToken, refreshToken: data.data.refreshToken, accessTokenExpiresAt: new Date(data.data.accessTokenExpiryDate).toISOString(), refreshTokenExpiresAt: new Date(data.data.refreshTokenExpiryDate).toISOString() }; return { credentials: next, result: { ok: true, provider: "cj", externalAccountId: next.openId, tokenExpiresAt: next.accessTokenExpiresAt, message: "CJ API 2.0 connection verified", ...(data.requestId ? { requestId: data.requestId } : {}) } }; };

export class CJConnector implements SupplierConnector {
  readonly provider = "cj";
  readonly supportedFulfilmentTypes = ["global_direct", "global_wholesale", "global_sourcing"] as const;
  async authenticate(credentials: SupplierCredentials) { if (!credentials.apiKey.trim()) throw new Error("CJ API key is required"); return success(await post("/authentication/getAccessToken", { apiKey: credentials.apiKey.trim() }), credentials); }
  async testConnection(credentials: SupplierCredentials) { const expiry = credentials.accessTokenExpiresAt ? Date.parse(credentials.accessTokenExpiresAt) : 0; if (credentials.accessToken && expiry > Date.now() + 300_000) return { credentials, result: { ok: true, provider: "cj", externalAccountId: credentials.openId, tokenExpiresAt: credentials.accessTokenExpiresAt, message: "Stored CJ access token is valid" } }; if (credentials.refreshToken && (!credentials.refreshTokenExpiresAt || Date.parse(credentials.refreshTokenExpiresAt) > Date.now())) return success(await post("/authentication/refreshAccessToken", { refreshToken: credentials.refreshToken }), credentials); return this.authenticate(credentials); }
}
