import Link from "next/link";
import { notFound } from "next/navigation";
import { getPublicProduct } from "@/src/modules/catalogue/server/repository";
import { listProductReviews } from "@/src/modules/engagement/server/reviews";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { getCurrencyDisplay } from "@/src/modules/localization/server/currency";
import { ProductImage } from "@/src/modules/catalogue/ui/product-image";

export const dynamic = "force-dynamic";

export default async function ProductPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ reviewed?: string; reviewError?: string; saved?: string }> }) {
  const [{ slug }, query, user, pricing] = await Promise.all([params, searchParams, getCurrentAppwriteUser(), getCurrencyDisplay()]);
  const data = await getPublicProduct(slug); if (!data) notFound();
  const reviews = await listProductReviews(data.product.$id), average = reviews.documents.length ? reviews.documents.reduce((sum, review) => sum + Number(review.rating), 0) / reviews.documents.length : 0;
  const primaryOffer = [...data.offers].sort((a, b) => Number(a.offer.retailPriceMinor) - Number(b.offer.retailPriceMinor))[0];

  return <main className="retail-marketplace retail-product-page">
    <header className="retail-header"><div className="retail-header-main"><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><form className="retail-search" action="/products" method="get"><input type="hidden" name="market" value="retail"/><input name="q" aria-label="Search retail marketplace" placeholder="Search products, brands and categories"/><button>⌕ <span>Search</span></button></form><nav><Link href="/account"><span>◎</span><small>My account</small></Link><Link href="/wishlist"><span>♡</span><small>Wishlist</small></Link><Link href="/cart"><span>🛒</span><small>Cart</small></Link></nav></div><nav className="retail-channel-nav"><Link className="active" href="/products?market=retail">Retail marketplace</Link><Link href="/products?market=wholesale">Wholesale catalogue</Link><Link href="/pac-sm-products">PAC-SM Products</Link><Link href="/vendor/register">Sell on PAC-SM</Link><Link href="/orders">Track orders</Link></nav></header>
    <nav className="retail-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/products?market=retail">Retail marketplace</Link><span>›</span><strong>{String(data.product.name)}</strong></nav>
    <section className="retail-detail-grid"><div className="retail-detail-gallery"><ProductImage media={data.media[0]} productName={String(data.product.name)} className="retail-detail-image"/>{data.media.length > 1 && <div className="retail-detail-thumbs">{data.media.map(media => <ProductImage key={media.$id} media={media} productName={String(data.product.name)} className="retail-detail-thumb"/>)}</div>}<div className="retail-gallery-note"><span>⌕</span>Approved product imagery</div></div>
      <article className="retail-detail-copy"><span className="retail-detail-brand">{String(data.product.brandName ?? "VERIFIED MARKETPLACE PRODUCT")}</span><h1>{String(data.product.name)}</h1><div className="retail-detail-rating"><b>{reviews.total ? `${average.toFixed(1)} ★` : "New"}</b><span>{reviews.total ? `${reviews.total} verified review${reviews.total === 1 ? "" : "s"}` : "Be the first verified buyer to review"}</span></div><p className="retail-detail-description">{String(data.product.description)}</p><dl><div><dt>Origin</dt><dd>{String(data.product.countryOfOrigin)}</dd></div><div><dt>Model</dt><dd>{String(data.product.model ?? "Standard")}</dd></div><div><dt>Seller options</dt><dd>{data.offers.length}</dd></div><div><dt>Buyer protection</dt><dd>Included</dd></div></dl>{user ? <form className="retail-wishlist" action="/api/wishlist" method="post"><input type="hidden" name="productId" value={data.product.$id}/><input type="hidden" name="returnTo" value={`/products/${slug}?saved=1`}/><button type="submit">♡ Save to wishlist</button></form> : <Link className="retail-signin-save" href={`/login?returnTo=/products/${slug}`}>Sign in to save this product</Link>}{query.saved && <p className="success-note">Saved to your wishlist.</p>}</article>
      {primaryOffer && <aside className="retail-buy-box"><span>BEST AVAILABLE OFFER</span><strong>{pricing.format(Number(primaryOffer.offer.retailPriceMinor), String(primaryOffer.offer.currency))}</strong><p>{primaryOffer.available > 0 ? <><b>In stock</b> · {primaryOffer.available} available</> : "Currently unavailable"}</p><div><small>Sold by</small><Link href={`/store/${String(primaryOffer.store.slug)}`}>{String(primaryOffer.store.name)} →</Link></div><ul><li>Protected marketplace checkout</li><li>Tracked fulfilment and delivery</li><li>Eligible return and dispute support</li></ul><form method="post" action="/api/cart/items"><input type="hidden" name="offerId" value={primaryOffer.offer.$id}/><input type="hidden" name="productSlug" value={slug}/><label>Quantity<input name="quantity" type="number" min={Number(primaryOffer.offer.minimumOrderQuantity)} max={primaryOffer.available} defaultValue={Number(primaryOffer.offer.minimumOrderQuantity)}/></label><button disabled={primaryOffer.available < Number(primaryOffer.offer.minimumOrderQuantity)}>Add to cart</button></form><Link className="retail-view-cart" href="/cart">View cart</Link></aside>}
    </section>
    <section className="retail-detail-trust"><article><span>✓</span><div><strong>Verified listing</strong><small>Catalogue moderated by PAC-SM</small></div></article><article><span>▣</span><div><strong>Delivery visibility</strong><small>Track order fulfilment milestones</small></div></article><article><span>↺</span><div><strong>Purchase support</strong><small>Structured returns and disputes</small></div></article></section>
    <section className="retail-offer-section"><div className="retail-section-heading"><span>COMPARE SELLERS</span><h2>Available marketplace offers</h2><p>Prices displayed in {pricing.currency}. Select the offer that fits your quantity and fulfilment needs.</p></div><div className="retail-offer-table">{data.offers.map(({ offer, store, available }, index) => <article key={offer.$id}><div className="retail-offer-rank">{index === 0 ? "BEST PRICE" : `OPTION ${index + 1}`}</div><div><strong>{String(store.name)}</strong><Link href={`/store/${String(store.slug)}`}>Verified store →</Link></div><div><small>Buying format</small><span>{Number(offer.minimumOrderQuantity) > 1 ? `Wholesale · MOQ ${String(offer.minimumOrderQuantity)}` : "Retail · Single units"}</span></div><div><small>Stock</small><span className={available > 0 ? "in-stock" : "out-stock"}>{available > 0 ? `${available} available` : "Out of stock"}</span></div><strong>{pricing.format(Number(offer.retailPriceMinor), String(offer.currency))}</strong><form method="post" action="/api/cart/items"><input type="hidden" name="offerId" value={offer.$id}/><input type="hidden" name="productSlug" value={slug}/><input aria-label={`Quantity from ${String(store.name)}`} name="quantity" type="number" min={Number(offer.minimumOrderQuantity)} max={available} defaultValue={Number(offer.minimumOrderQuantity)}/><button disabled={available < Number(offer.minimumOrderQuantity)}>Add to cart</button></form></article>)}</div></section>
    <section className="retail-review-section"><div className="retail-section-heading"><span>BUYER FEEDBACK</span><h2>Verified-purchase reviews</h2><p>Reviews can only be published after an eligible delivered purchase.</p></div>{query.reviewed && <p className="success-note">Review published.</p>}{query.reviewError && <p className="form-error">A delivered purchase is required, and each product can only be reviewed once.</p>}<div className="retail-reviews">{reviews.documents.length ? reviews.documents.map(review => <article key={review.$id}><b>{"★".repeat(Number(review.rating))}</b><h3>{String(review.title)}</h3><p>{String(review.body)}</p><small>Verified purchase</small></article>) : <article className="retail-no-reviews"><h3>No reviews yet</h3><p>Verified buyers can share their experience after delivery.</p></article>}</div>{user ? <details className="retail-review-form"><summary>Write a verified-purchase review</summary><form className="stack-form" action="/api/reviews" method="post"><input type="hidden" name="productId" value={data.product.$id}/><input type="hidden" name="slug" value={slug}/><label>Rating<select name="rating" required><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Average</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select></label><label>Title<input name="title" required minLength={3} maxLength={160}/></label><label>Review<textarea name="body" required minLength={10} maxLength={2000}/></label><button>Publish verified review</button></form></details> : <Link className="retail-review-signin" href={`/login?returnTo=/products/${slug}`}>Sign in to review a delivered purchase</Link>}</section>
  </main>;
}
