import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getPublicProduct } from "@/src/modules/catalogue/server/repository";
import { listProductReviews } from "@/src/modules/engagement/server/reviews";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { getCurrencyDisplay } from "@/src/modules/localization/server/currency";
import { ProductGallery } from "@/src/modules/catalogue/ui/product-gallery";
import { JsonLd } from "@/src/shared/seo/json-ld";
import { getProgramsForOffers } from "@/src/modules/catalogue/server/product-programs";
import { preorderIsOpen } from "@/src/modules/catalogue/domain/product-program";
import { purchaseQuantityLimits } from "@/src/modules/cart/domain/purchase-quantity";
import { PurchaseQuantityForm } from "@/src/modules/cart/ui/purchase-quantity-form";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params, data = await getPublicProduct(slug);
  if (!data) return { title: "Product not found", robots: { index: false, follow: false } };
  const name = String(data.product.name), description = String(data.product.description).slice(0, 160), image = data.media[0] ? `/api/catalogue/media/${data.media[0].$id}` : "/og.png";
  return { title: name, description, alternates: { canonical: `/products/${slug}` }, openGraph: { title: name, description, url: `/products/${slug}`, type: "website", images: [{ url: image, alt: String(data.media[0]?.altText ?? name) }] }, twitter: { card: "summary_large_image", title: name, description, images: [image] } };
}

export default async function ProductPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ reviewed?: string; reviewError?: string; saved?: string; cartError?: string }> }) {
  const [{ slug }, query, user, pricing] = await Promise.all([params, searchParams, getCurrentAppwriteUser(), getCurrencyDisplay()]);
  const data = await getPublicProduct(slug); if (!data) notFound();
  const [reviews, programByOffer] = await Promise.all([listProductReviews(data.product.$id), getProgramsForOffers(data.offers.map(row => row.offer.$id))]), average = reviews.documents.length ? reviews.documents.reduce((sum, review) => sum + Number(review.rating), 0) / reviews.documents.length : 0;
  const primaryOffer = [...data.offers].sort((a, b) => {
    const aLimits = purchaseQuantityLimits({ available: a.available, minimumOrderQuantity: Number(a.offer.minimumOrderQuantity), maximumOrderQuantity: a.offer.maximumOrderQuantity == null ? null : Number(a.offer.maximumOrderQuantity) });
    const bLimits = purchaseQuantityLimits({ available: b.available, minimumOrderQuantity: Number(b.offer.minimumOrderQuantity), maximumOrderQuantity: b.offer.maximumOrderQuantity == null ? null : Number(b.offer.maximumOrderQuantity) });
    return Number(bLimits.purchasable) - Number(aLimits.purchasable) || Number(a.offer.retailPriceMinor) - Number(b.offer.retailPriceMinor);
  })[0];

  const origin = process.env.APP_BASE_URL ?? "http://localhost:3000", productUrl = `${origin}/products/${slug}`;
  const productSchema = { "@context": "https://schema.org", "@type": "Product", "@id": `${productUrl}#product`, name: String(data.product.name), description: String(data.product.description), url: productUrl, image: data.media.map(item => `${origin}/api/catalogue/media/${item.$id}`), sku: String(data.variants[0]?.sku ?? data.product.model ?? data.product.$id), ...(data.product.brandName ? { brand: { "@type": "Brand", name: String(data.product.brandName) } } : {}), countryOfOrigin: String(data.product.countryOfOrigin), offers: data.offers.map(({ offer, store, available }) => ({ "@type": "Offer", url: productUrl, priceCurrency: String(offer.currency), price: (Number(offer.retailPriceMinor) / 100).toFixed(2), availability: available > 0 ? "https://schema.org/InStock" : "https://schema.org/OutOfStock", itemCondition: "https://schema.org/NewCondition", seller: { "@type": "Organization", name: String(store.name), url: `${origin}/store/${String(store.slug)}` } })), ...(reviews.total ? { aggregateRating: { "@type": "AggregateRating", ratingValue: Number(average.toFixed(1)), reviewCount: reviews.total } } : {}) };
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: origin }, { "@type": "ListItem", position: 2, name: "Retail marketplace", item: `${origin}/products?market=retail` }, { "@type": "ListItem", position: 3, name: String(data.product.name), item: productUrl }] };

  return <><JsonLd data={[productSchema, breadcrumbSchema]}/><main className="retail-marketplace retail-product-page">
    <header className="retail-header"><div className="retail-header-main"><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><form className="retail-search" action="/products" method="get"><input type="hidden" name="market" value="retail"/><input name="q" aria-label="Search retail marketplace" placeholder="Search products, brands and categories"/><button>⌕ <span>Search</span></button></form><nav><Link href="/account"><span>◎</span><small>My account</small></Link><Link href="/wishlist"><span>♡</span><small>Wishlist</small></Link><Link href="/cart"><span>🛒</span><small>Cart</small></Link></nav></div><nav className="retail-channel-nav"><Link className="active" href="/products?market=retail">Retail marketplace</Link><Link href="/products?market=wholesale">Wholesale catalogue</Link><Link href="/pac-sm-products">PAC-SM Products</Link><Link href="/vendor/register">Sell on PAC-SM</Link><Link href="/orders">Track orders</Link></nav></header>
    <nav className="retail-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/products?market=retail">Retail marketplace</Link><span>›</span><strong>{String(data.product.name)}</strong></nav>
    <section className="retail-detail-grid"><div className="retail-detail-gallery"><ProductGallery media={data.media.map(item=>({id:item.$id,altText:String(item.altText||data.product.name)}))} productName={String(data.product.name)}/><div className="retail-gallery-note"><span>⌕</span>Choose a thumbnail to display it above · select the large photo to enlarge</div></div>
      <article className="retail-detail-copy"><span className="retail-detail-brand">{String(data.product.brandName ?? "VERIFIED MARKETPLACE PRODUCT")}</span><h1>{String(data.product.name)}</h1><div className="retail-detail-rating"><b>{reviews.total ? `${average.toFixed(1)} ★` : "New"}</b><span>{reviews.total ? `${reviews.total} verified review${reviews.total === 1 ? "" : "s"}` : "Be the first verified buyer to review"}</span></div><p className="retail-detail-description">{String(data.product.description)}</p><dl><div><dt>Origin</dt><dd>{String(data.product.countryOfOrigin)}</dd></div><div><dt>Model</dt><dd>{String(data.product.model ?? "Standard")}</dd></div><div><dt>Seller options</dt><dd>{data.offers.length}</dd></div><div><dt>Buyer protection</dt><dd>Included</dd></div></dl>{user ? <form className="retail-wishlist" action="/api/wishlist" method="post"><input type="hidden" name="productId" value={data.product.$id}/><input type="hidden" name="returnTo" value={`/products/${slug}?saved=1`}/><button type="submit">♡ Save to wishlist</button></form> : <Link className="retail-signin-save" href={`/login?returnTo=/products/${slug}`}>Sign in to save this product</Link>}{query.saved && <p className="success-note">Saved to your wishlist.</p>}</article>
      {primaryOffer && (() => { const limits = purchaseQuantityLimits({ available: primaryOffer.available, minimumOrderQuantity: Number(primaryOffer.offer.minimumOrderQuantity), maximumOrderQuantity: primaryOffer.offer.maximumOrderQuantity == null ? null : Number(primaryOffer.offer.maximumOrderQuantity) }); return <aside className="retail-buy-box"><span>BEST AVAILABLE OFFER</span><strong>{pricing.format(Number(primaryOffer.offer.retailPriceMinor), String(primaryOffer.offer.currency))}</strong><p>{limits.purchasable ? <><b>In stock</b> · {limits.maximum} available to order</> : "No confirmed stock · use pre-order below"}</p><div><small>Sold by</small><Link href={`/store/${String(primaryOffer.store.slug)}`}>{String(primaryOffer.store.name)} →</Link></div><ul><li>Protected marketplace checkout</li><li>Tracked fulfilment and delivery</li><li>Eligible return and dispute support</li></ul><PurchaseQuantityForm offerId={primaryOffer.offer.$id} productSlug={slug} minimum={limits.minimum} maximum={limits.maximum}/><Link className="retail-view-cart" href="/cart">View cart</Link></aside>; })()}
    </section>
    <section className="retail-detail-trust"><article><span>✓</span><div><strong>Verified listing</strong><small>Catalogue moderated by PAC-SM</small></div></article><article><span>▣</span><div><strong>Delivery visibility</strong><small>Track order fulfilment milestones</small></div></article><article><span>↺</span><div><strong>Purchase support</strong><small>Structured returns and disputes</small></div></article></section>
    {query.cartError && <p className="form-error program-order-error">{query.cartError === "standard" ? "This standard purchase could not be added. Check confirmed stock, the seller's quantity limits, and whether the same quantity is already in your cart." : "The selected programme could not be added. Check its current window, capacity, minimum quantity and required branding brief."}</p>}
    {data.offers.some(row => Number(row.offer.minimumOrderQuantity) === 1) && <section className="product-program-section" id="preorder"><div className="retail-section-heading"><span>PRE-ORDER THIS PRODUCT</span><h2>Order ahead from any retail seller</h2><p>Use published seller terms when available; otherwise PAC-SM applies a protected default window based on the offer processing time.</p></div><div className="product-program-grid">{data.offers.filter(row => Number(row.offer.minimumOrderQuantity) === 1).map(({ offer, store }) => { const program = programByOffer.get(offer.$id), configured = Boolean(program?.preorderEnabled), open = configured ? preorderIsOpen(program!) : true, left = configured ? Math.max(0, Number(program!.preorderCapacity) - Number(program!.preorderReserved)) : Number(offer.maximumOrderQuantity ?? 10000), dispatchLabel = configured ? new Date(String(program!.estimatedDispatchAt)).toLocaleDateString("en-GB") : `At least ${Math.max(7, Number(offer.processingDays))} days after payment`; return <article key={`${offer.$id}-preorder`}><span>PRE-ORDER · {String(store.name)}</span><h3>Reserve your units now</h3><p>{configured ? `${left} units remain in this seller allocation.` : "Pre-order is available under PAC-SM standard retail terms."}</p><strong>Estimated dispatch: {dispatchLabel}</strong><form method="post" action="/api/cart/items"><input type="hidden" name="offerId" value={offer.$id}/><input type="hidden" name="productSlug" value={slug}/><input type="hidden" name="purchaseType" value="preorder"/><label>Quantity<input name="quantity" type="number" min="1" max={left} defaultValue="1" required/></label><button disabled={!open}>Pre-order now</button></form></article>; })}</div></section>}
    <section className="retail-offer-section"><div className="retail-section-heading"><span>COMPARE SELLERS</span><h2>Available marketplace offers</h2><p>Prices displayed in {pricing.currency}. Select the offer that fits your quantity and fulfilment needs.</p></div><div className="retail-offer-table">{data.offers.map(({ offer, store, available }, index) => { const limits = purchaseQuantityLimits({ available, minimumOrderQuantity: Number(offer.minimumOrderQuantity), maximumOrderQuantity: offer.maximumOrderQuantity == null ? null : Number(offer.maximumOrderQuantity) }); return <article key={offer.$id}><div className="retail-offer-rank">{index === 0 ? "BEST PRICE" : `OPTION ${index + 1}`}</div><div><strong>{String(store.name)}</strong><Link href={`/store/${String(store.slug)}`}>Verified store →</Link></div><div><small>Buying format</small><span>{Number(offer.minimumOrderQuantity) > 1 ? `Wholesale · MOQ ${String(offer.minimumOrderQuantity)}` : "Retail · Single units"}</span></div><div><small>Stock</small><span className={limits.purchasable ? "in-stock" : "out-stock"}>{limits.purchasable ? `${limits.maximum} available to order` : "Pre-order only"}</span></div><strong>{pricing.format(Number(offer.retailPriceMinor), String(offer.currency))}</strong><PurchaseQuantityForm compact offerId={offer.$id} productSlug={slug} minimum={limits.minimum} maximum={limits.maximum}/></article>; })}</div></section>
    <section className="retail-review-section"><div className="retail-section-heading"><span>BUYER FEEDBACK</span><h2>Verified-purchase reviews</h2><p>Reviews can only be published after an eligible delivered purchase.</p></div>{query.reviewed && <p className="success-note">Review published.</p>}{query.reviewError && <p className="form-error">A delivered purchase is required, and each product can only be reviewed once.</p>}<div className="retail-reviews">{reviews.documents.length ? reviews.documents.map(review => <article key={review.$id}><b>{"★".repeat(Number(review.rating))}</b><h3>{String(review.title)}</h3><p>{String(review.body)}</p><small>Verified purchase</small></article>) : <article className="retail-no-reviews"><h3>No reviews yet</h3><p>Verified buyers can share their experience after delivery.</p></article>}</div>{user ? <details className="retail-review-form"><summary>Write a verified-purchase review</summary><form className="stack-form" action="/api/reviews" method="post"><input type="hidden" name="productId" value={data.product.$id}/><input type="hidden" name="slug" value={slug}/><label>Rating<select name="rating" required><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Average</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select></label><label>Title<input name="title" required minLength={3} maxLength={160}/></label><label>Review<textarea name="body" required minLength={10} maxLength={2000}/></label><button>Publish verified review</button></form></details> : <Link className="retail-review-signin" href={`/login?returnTo=/products/${slug}`}>Sign in to review a delivered purchase</Link>}</section>
  </main></>;
}
