import Link from "next/link";
import { listCategories, listPublicProductsFiltered } from "@/src/modules/catalogue/server/repository";
import { getCurrencyDisplay } from "@/src/modules/localization/server/currency";
import { ProductImage } from "@/src/modules/catalogue/ui/product-image";

export const dynamic = "force-dynamic";
type CatalogueQuery = { q?: string; category?: string; market?: string; sort?: string; availability?: string };

export default async function ProductsPage({ searchParams }: { searchParams: Promise<CatalogueQuery> }) {
  const filters = await searchParams;
  const [products, categories, pricing] = await Promise.all([listPublicProductsFiltered(filters), listCategories(), getCurrencyDisplay()]);
  const retailMode = filters.market !== "wholesale", activeCategory = categories.documents.find(category => category.$id === filters.category);
  const queryString = (next: CatalogueQuery) => { const values = { ...filters, ...next }; return `?${new URLSearchParams(Object.entries(values).filter(([, value]) => value) as [string, string][]).toString()}`; };

  return <main className="retail-marketplace">
    <header className="retail-header"><div className="retail-header-main"><Link className="brand" href="/"><span>PAC</span><b>SM</b></Link><form className="retail-search" action="/products" method="get"><input type="hidden" name="market" value={filters.market ?? "retail"}/><input name="q" defaultValue={filters.q} aria-label="Search retail marketplace" placeholder="Search products, brands and categories"/><button aria-label="Search marketplace">⌕ <span>Search</span></button></form><nav aria-label="Retail account links"><Link href="/account"><span>◎</span><small>My account</small></Link><Link href="/wishlist"><span>♡</span><small>Wishlist</small></Link><Link href="/cart"><span>🛒</span><small>Cart</small></Link></nav></div><nav className="retail-channel-nav" aria-label="Marketplace channels"><Link className={retailMode ? "active" : ""} href="/products?market=retail">Retail marketplace</Link><Link className={!retailMode ? "active" : ""} href="/products?market=wholesale">Wholesale catalogue</Link><Link href="/pac-sm-products">PAC-SM Products</Link><Link href="/vendor/register">Sell on PAC-SM</Link><Link href="/orders">Track orders</Link></nav></header>
    <section className="retail-hero"><div><p className="retail-eyebrow">{retailMode ? "PAN-AFRICAN RETAIL" : "COMMERCIAL SOURCING"}</p><h1>{retailMode ? "Trusted products. Delivered across Africa." : "Verified supply for growing businesses."}</h1><p>Shop approved products from verified sellers with protected checkout, transparent stock and continental delivery support.</p></div><aside><strong>{products.length}</strong><span>products matching your selection</span><small>Prices shown in {pricing.currency}</small></aside></section>
    <section className="retail-benefits" aria-label="Marketplace benefits"><article><span>✓</span><div><strong>Verified sellers</strong><small>KYB-reviewed marketplace stores</small></div></article><article><span>⌁</span><div><strong>Protected checkout</strong><small>Secure payment and order records</small></div></article><article><span>▣</span><div><strong>Tracked delivery</strong><small>Fulfilment visibility from order to door</small></div></article><article><span>↺</span><div><strong>Buyer support</strong><small>Returns and dispute workflows</small></div></article></section>
    <nav className="retail-category-strip" aria-label="Shop by category"><Link className={!filters.category ? "active" : ""} href={queryString({ category: "" })}><span>✦</span>All products</Link>{categories.documents.slice(0, 10).map((category, index) => <Link className={filters.category === category.$id ? "active" : ""} href={queryString({ category: category.$id })} key={category.$id}><span>{["🌾","🥫","👗","🧴","🏠","💻","🥤","🧺","🛠","📦"][index]}</span>{String(category.name)}</Link>)}</nav>
    <div className="retail-catalogue-layout"><aside className="retail-filter-panel"><div><p>SHOPPING FILTERS</p><Link href={filters.market === "wholesale" ? "/products?market=wholesale" : "/products?market=retail"}>Clear all</Link></div><form action="/products" method="get"><label>Search<input name="q" defaultValue={filters.q} placeholder="What are you looking for?"/></label><label>Category<select name="category" defaultValue={filters.category ?? ""}><option value="">All categories</option>{categories.documents.map(category => <option value={category.$id} key={category.$id}>{String(category.name)}</option>)}</select></label><label>Buying format<select name="market" defaultValue={filters.market ?? "retail"}><option value="retail">Retail products</option><option value="wholesale">Wholesale products</option><option value="">All marketplace products</option></select></label><label>Availability<select name="availability" defaultValue={filters.availability ?? ""}><option value="">All stock states</option><option value="in_stock">In stock now</option></select></label><button>Apply filters</button></form><div className="retail-help-card"><span>NEED HELP?</span><strong>Buying across borders?</strong><p>Review delivery, payment and buyer-protection guidance before checkout.</p><Link href="/faq">Visit Help Centre →</Link></div></aside>
      <section className="retail-results"><div className="retail-results-bar"><div><p>{activeCategory ? String(activeCategory.name) : retailMode ? "Retail products" : "Wholesale products"}</p><span>{products.length} result{products.length === 1 ? "" : "s"}{filters.q ? ` for “${filters.q}”` : ""}</span></div><form action="/products" method="get"><input type="hidden" name="q" value={filters.q ?? ""}/><input type="hidden" name="category" value={filters.category ?? ""}/><input type="hidden" name="market" value={filters.market ?? "retail"}/><input type="hidden" name="availability" value={filters.availability ?? ""}/><label>Sort by<select name="sort" defaultValue={filters.sort ?? "featured"}><option value="featured">Featured</option><option value="price_low">Price: low to high</option><option value="price_high">Price: high to low</option><option value="name">Product name</option></select></label><button>Sort</button></form></div>
        {products.length ? <div className="retail-product-grid">{products.map((item, index) => <article className="retail-product-card" key={item.product.$id}><Link className="retail-product-media" href={`/products/${String(item.product.slug)}`}><ProductImage media={item.media} productName={String(item.product.name)} className="retail-product-image"/><span className="retail-card-badge">{Number(item.offer.minimumOrderQuantity) > 1 ? `MOQ ${String(item.offer.minimumOrderQuantity)}` : index < 4 ? "FEATURED" : "RETAIL"}</span>{item.available > 0 && item.available < 10 && <small className="retail-low-stock">Only {item.available} left</small>}</Link><div className="retail-product-copy"><span>{String(item.product.brandName ?? "Verified marketplace seller")}</span><Link href={`/products/${String(item.product.slug)}`}><h2>{String(item.product.name)}</h2></Link><div className="retail-rating" aria-label="Verified marketplace offer"><b>★★★★★</b><small>Verified offer</small></div><strong className="retail-price">{pricing.format(Number(item.offer.retailPriceMinor), String(item.offer.currency))}</strong><p>{item.available > 0 ? "In stock · Ready to order" : "Currently unavailable"}</p><Link className={`retail-card-cta ${item.available < 1 ? "disabled" : ""}`} href={`/products/${String(item.product.slug)}`}>{item.available > 0 ? "View product" : "View details"}<span>→</span></Link></div></article>)}</div> : <div className="retail-empty"><span>⌕</span><h2>No products matched these filters</h2><p>Try a broader search, another category, or clear the current filters.</p><Link href="/products?market=retail">Browse all retail products</Link></div>}
      </section></div>
  </main>;
}
