import Link from "next/link";
import { requireSuperAdmin } from "@/src/modules/authorization/server/require-super-admin";
import { listCategories, listModerationProducts } from "@/src/modules/catalogue/server/repository";
import { listModerationMedia } from "@/src/modules/catalogue/server/media";
import { ProductImage } from "@/src/modules/catalogue/ui/product-image";

export const dynamic = "force-dynamic";

export default async function CatalogueModeration({ searchParams }: { searchParams: Promise<{ created?: string; updated?: string; media?: string; error?: string }> }) {
  await requireSuperAdmin();
  const [products, categories, media, query] = await Promise.all([listModerationProducts(), listCategories(), listModerationMedia(), searchParams]);
  const mediaByProduct = new Map<string, typeof media.documents>();
  for (const item of media.documents) { const key = String(item.productId), rows = mediaByProduct.get(key) ?? []; rows.push(item); mediaByProduct.set(key, rows); }
  return <main className="admin-detail"><header><div><p className="kicker">CATALOGUE OPERATIONS</p><h1>Product management</h1><p>{products.total} products · {media.total} images in Appwrite</p>{query.created && <p className="success-note">Product added.</p>}{query.updated && <p className="success-note">Catalogue updated.</p>}{query.media === "updated" && <p className="success-note">Image moderation updated.</p>}{query.error && <p className="form-error">The catalogue operation failed.</p>}</div><Link href="/admin">Back to overview</Link></header>
    <section className="catalogue-create"><h2>Add marketplace product</h2><form className="stack-form" method="post" action="/api/admin/catalogue"><label>Name<input name="name" required minLength={3} maxLength={240}/></label><label>Description<textarea name="description" required minLength={20} maxLength={5000}/></label><label>Category<select name="categoryId" required>{categories.documents.map(category => <option value={category.$id} key={category.$id}>{String(category.name)}</option>)}</select></label><label>Market<select name="marketType" required><option value="retail">Retail</option><option value="wholesale">Wholesale</option></select></label><label>Price (NGN)<input name="price" type="number" min="1" step="0.01" required/></label><label>Opening stock<input name="stock" type="number" min="0" step="1" required/></label><button type="submit">Add approved product</button></form></section>
    <section className="review-table">{products.documents.length ? products.documents.map(product => { let market = "vendor"; try { market = String(JSON.parse(String(product.specifications)).market ?? market); } catch {} const productMedia = mediaByProduct.get(product.$id) ?? [], isLive = product.status === "approved"; return <article className="catalogue-review" key={product.$id}><div><span>{String(product.status).replaceAll("_", " ")} · {market}</span><h2>{String(product.name)}</h2><p>{String(product.description)}</p><small>{String(product.countryOfOrigin)} · {String(product.brandName ?? "Unbranded")}</small><div className="admin-media-grid">{productMedia.map(item => <article key={item.$id}><ProductImage media={item} productName={String(product.name)} className="admin-media-thumb"/><div><strong>{String(item.status)}{String(item.isPrimary) === "true" ? " · primary" : ""}</strong><small>{String(item.altText)}</small><form action={`/api/admin/catalogue/media/${item.$id}/review`} method="post"><input name="notes" placeholder="Moderation notes" maxLength={1000}/><div>{item.status !== "approved" && <button name="action" value="approve">Restore image</button>}{item.status !== "rejected" && <button className="danger" name="action" value="reject">Reject image</button>}{item.status === "approved" && String(item.isPrimary) !== "true" && <button name="action" value="set_primary">Make primary</button>}</div></form></div></article>)}</div>{!productMedia.length && <p className="catalogue-media-warning">No product images uploaded.</p>}</div><div className="catalogue-controls"><form method="post" action={`/api/admin/catalogue/${product.$id}/manage`}><label>Change product name<input name="name" defaultValue={String(product.name)} required minLength={3}/></label><button name="action" value="rename">Save name</button><button name="action" value="delete" className="danger">Delete product</button></form><form method="post" action={`/api/admin/catalogue/${product.$id}/review`}><label>Moderation reason<textarea name="notes" required/></label><div>{isLive ? <><button name="action" value="request_changes">Request changes</button><button name="action" value="take_down" className="danger">Take product down</button></> : <><button name="action" value="restore">Restore product</button><button name="action" value="reject" className="danger">Reject listing</button></>}</div></form></div></article>; }) : <p className="empty-state">No products have been published.</p>}</section>
  </main>;
}
