import Link from "next/link";
import { redirect } from "next/navigation";
import { Query } from "node-appwrite";
import { CommerceModuleHeader, CommerceModuleHero } from "@/app/components/commerce-module-header";
import { getCurrentAppwriteUser } from "@/src/modules/auth/server/session";
import { findOfftaker, listAgreements, listProposals, listRequirements } from "@/src/modules/offtake/server/repository";
export const dynamic = "force-dynamic";

export default async function Page({ searchParams }: { searchParams: Promise<{ submitted?: string; created?: string; awarded?: string }> }) {
  const user = await getCurrentAppwriteUser(); if (!user) redirect("/login?returnTo=/offtakers");
  const offtaker = await findOfftaker(user.$id); if (!offtaker) redirect("/offtakers/register");
  const [requirements, agreements, query] = await Promise.all([listRequirements([Query.equal("offtakerId", offtaker.$id)]), listAgreements(offtaker.$id), searchParams]);
  const proposals = (await Promise.all(requirements.documents.map(requirement => listProposals(requirement.$id)))).flatMap(result => result.documents);
  return <main className="commerce-module"><CommerceModuleHeader current="offtakers" utility={{ href: "/orders", label: "Orders" }}/><CommerceModuleHero eyebrow="CORPORATE OFF-TAKER CENTRE" title={String(offtaker.legalName)} description="Publish recurring demand, receive verified supplier proposals and build auditable multi-supplier supply agreements." metric={requirements.total} metricLabel="active and historical demand requirements"><div className="module-status-line"><span>{String(offtaker.verificationLevel).replaceAll("_"," ")}</span><span>{String(offtaker.status)}</span><span>{agreements.total} agreements</span></div></CommerceModuleHero>
    <div className="module-body">{(query.submitted || query.created || query.awarded) && <p className="module-success">The off-taker operation was completed successfully.</p>}<section className="module-feature-strip"><article><span>01</span><div><strong>Publish demand</strong><small>Volume, quality and delivery terms</small></div></article><article><span>02</span><div><strong>Compare suppliers</strong><small>Verified commercial proposals</small></div></article><article><span>03</span><div><strong>Award capacity</strong><small>One or several qualified vendors</small></div></article><article><span>04</span><div><strong>Manage supply</strong><small>Schedules, inspection and milestones</small></div></article></section>
      {offtaker.status === "approved" && <section className="module-panel"><div className="module-panel-heading"><div><span>NEW MARKET DEMAND</span><h2>Publish an off-take requirement</h2><p>Define the complete commercial, quality and delivery expectation for potential suppliers.</p></div></div><form action="/api/offtakers/requirements" method="post"><label>Requirement title<input name="title" required/></label><label>Product<input name="productName" required/></label><label>Quantity<input name="quantity" type="number" min="1" required/></label><label>Unit<input name="unit" required/></label><label>Frequency<input name="frequency" required/></label><label>Target unit price<input name="targetPrice" type="number" step=".01"/></label><label>Currency<input name="currency" defaultValue={String(offtaker.currency)} required/></label><label>Contract months<input name="contractDurationMonths" type="number" min="1" required/></label><label>Proposal deadline<input name="applicationDeadline" type="datetime-local" required/></label><label>Origin restrictions<input name="originRestrictions"/></label><label>Specifications<textarea name="specifications" required/></label><label>Delivery destination<textarea name="deliveryDestination" required/></label><label>Packaging requirements<textarea name="packagingRequirements"/></label><label>Certification requirements<textarea name="certificationRequirements"/></label><label>Payment terms<textarea name="paymentTerms" required/></label><button>Publish requirement</button></form></section>}
      <section className="module-panel"><div className="module-panel-heading"><div><span>SUPPLIER RESPONSE</span><h2>Requirements and proposals</h2><p>Review demand status and award verified supplier capacity.</p></div></div>{requirements.total ? <div className="module-data-list">{requirements.documents.map(requirement => { const matches = proposals.filter(proposal => proposal.requirementId === requirement.$id); return <article className="module-data-card" key={requirement.$id}><div><span>{String(requirement.status)}</span><h3>{String(requirement.title)}</h3><p>{String(requirement.quantity)} {String(requirement.unit)} · {String(requirement.deliveryDestination)}</p><small>{matches.length} supplier proposal{matches.length === 1 ? "" : "s"}</small></div><div>{matches.length ? matches.map(proposal => <form action={`/api/offtakers/proposals/${proposal.$id}/award`} method="post" key={proposal.$id}><p>Vendor {String(proposal.vendorId)} · {String(proposal.quantity)} units · {String(proposal.currency)} {(Number(proposal.unitPriceMinor)/100).toLocaleString()}</p><label>Award quantity<input name="quantity" type="number" min="1" max={Number(proposal.quantity)} required/></label><label>Payment model<select name="paymentModel"><option value="advance">Advance</option><option value="deposit_balance">Deposit + balance</option><option value="escrow">Escrow</option><option value="after_inspection">After inspection</option></select></label><button>Award supplier</button></form>) : <div className="module-empty"><strong>Awaiting proposals</strong><span>Verified suppliers can respond while the requirement is open.</span></div>}</div></article>; })}</div> : <div className="module-empty"><strong>No requirements published</strong><span>Create your first structured off-take demand above.</span></div>}</section>
      <section className="module-panel"><div className="module-panel-heading"><div><span>CONTRACT PORTFOLIO</span><h2>Supply agreements</h2><p>Commercial agreements created from awarded supplier proposals.</p></div></div>{agreements.total ? <div className="module-table"><div className="module-table-row head"><span>Agreement</span><span>Status</span><span>Payment model</span><span>Value</span></div>{agreements.documents.map(agreement => <div className="module-table-row" key={agreement.$id}><span>{String(agreement.agreementNumber)}</span><strong>{String(agreement.status)}</strong><span>{String(agreement.paymentModel).replaceAll("_"," ")}</span><span>{String(agreement.currency)} {(Number(agreement.totalMinor)/100).toLocaleString()}</span></div>)}</div> : <div className="module-empty"><strong>No supply agreements yet</strong><span>Awarded proposals will create supplier-specific agreements here.</span></div>}</section>
    </div></main>;
}
